### PR TITLE
dual-funding -> use tx-abort now

### PR DESCRIPTION
**Pull request by niftynei**
Built on #5670. Starts at `fa30d80d5ad1151f5374e72158038f02b46dc33b`

Kind of a fun one. We've got a fancy new message (tx-abort) which will signal we're ending a channel open negotiation. 

What's fun about this is that now when we abort/end an open channel negotiation (v2s only), we don't disconnect from the peer. Instead the subdaemon for the open dies. If the peer retries, we restart the daemon.

What's nice about this is that we now keep the connection open for any other channels that we may or may not currently have with the peer we're talking to.

### CODE REVIEW

**Comment by rustyrussell** [comment]
OK, #5670 merged, so I'm rebasing this on master...

**Comment by rustyrussell** [comment]
Ack dc5b69286a950b60ebf37cc013242f1a58d8a919

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5767/commits/dc5b69286a950b60ebf37cc013242f1a58d8a919

**Comment by rustyrussell** [comment]
Fix test flake and a local mocks build error on latest master.

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/c787bba8c8cfbad872955acfa877ea0d6add62e2

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5767/commits/c787bba8c8cfbad872955acfa877ea0d6add62e2

**Pull request merged**
