### PR TITLE
Regtest fee control

### PR DESCRIPTION
**Pull request by rustyrussell**
Got a report from @gijswijs that we were sending 0 update_fee on regtest; I've seen this complaint before, but this time we fixed it.

Also, @t-bast wanted to override regtest fees: we used to have a dev option which we removed in favor of direct control, I think that was probably overzealous (it's far easier that writing a bcli replacement!).  Of course we recommend this be in the regtest-specific config!

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4629/commits/62396846a5cc1a3cf3cd9898cdac27015024d1b6

**Comment by t-bast** [comment]
Thanks, that sounds perfect for the tests I'm doing.

**Comment by cdecker** [comment]
ACK 62396846a5cc1a3cf3cd9898cdac27015024d1b6

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/e55363ba6903aecd2d3c2daef28d5b666683e6c7

Rebased and fixed (and commented!) code which makes sure we don't reduce, if we're trying to increase and max says were too high already.

**Pull request merged**
