### PR TITLE
[docs] Add documentation for dev-forget-channel

### PR DESCRIPTION
**Pull request by bitkarrot**
Hi, 

First attempt at the docs for the above command.  I did run `make doc-all` and the markdown was generated correctly, but not sure about the *.requests.json. 

@ShahanaFarooqui 

Issue reference: 
https://github.com/ElementsProject/lightning/issues/6923

### CODE REVIEW

**Comment by bitkarrot** [comment]
@ShahanaFarooqui  I am failing to rebase this and I have run out of battery ( power outage here for next 24 hrs). 

Apologies if i messed up the branch in my attempts to rebase and fix the merges

**Comment by ShahanaFarooqui** [comment]
@bitkarrot, Thank you for the PR, I will re-base and review this PR once the PR #6995 is merged.

**Comment by ShahanaFarooqui** [comment]
@bitkarrot I re-based the PR on master and cleaned up multiple #empty `doc/makefile` update commits. 

There were some more updates required after PR #6995 merge:
- Merged request and schema jsons into single lightning-dev-forget-channel.json
- Deleted lightning-dev-forget-channel.7.md file because it is fully generated by script now.

I did add below details in the json schema too:
- Edited required array according to the command
- Types and description of request and response params
- Added errors list returned by the command

Please check and let me know if you need more explanation.

**Review by ShahanaFarooqui — APPROVED** [review]

**Comment by bitkarrot** [comment]
Thanks @ShahanaFarooqui !

**Pull request merged**
