### PR TITLE
Added spent option to listfunds

### LINKED ISSUE #4291: Add spent funds to the `listfunds` method
There are a number of cases that require having access to earlier
owned funds, such as computing the fee for the transactions we sent
from a plugin or app. In order to do that we can add a simple
`spent=true` flag (semantically: "include spent outputs as well as
unspent ones in the `outputs` array) to the `listfunds` method.

This is a good first issue, and should be limited to:

 - Adding the new parameter to the JSON-RPC method
 - Adjusting the call to `wallet_get_utxos` in the handler function
   `json_listfunds` to use `OUTPUT_STATE_ANY` as third argument if the
   parameter is set to `true`.
   
This was first brought up by @hosiawak in #4289

### PR DESCRIPTION
**Pull request by hosiawak**
Added a `spent` option (a boolean) to `listfunds` which adds spent outputs to the `outputs` if set to true.

I didn't see any `test_listfunds` Python test so I thought I'd write one but then I couldn't figure out how to actually run these Python tests after reading `HACKING.md` :) 

* **blackbox tests** - These tests setup a mini-regtest environment and test
  lightningd as a whole.  They can be run individually:

  `PYTHONPATH=contrib/pylightning:contrib/pyln-client:contrib/pyln-testing:contrib/pyln-proto py.test -v tests/`

What's `py.test` ?

I checked `travis.yml` to see how it does that and it sets up bitcoind and elements and it's Linux specific but I'm using a Mac. If anyone knows how to run `tests/test_misc.py` on a Mac and could share this info with me I'd appreciate it.

Fixes #4291

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
On some distros you can install a `pytest` package and that is invoked as `pytest`, so just use `pytest`.  Depends on your Python setup though.  You may need to install it separately.

**Review by ZmnSCPxj — APPROVED** [review]
Code mostly okay.  Would appreciate a test though.

**Comment by hosiawak** [comment]
@ZmnSCPxj I'm not a C or Python coder for the most part so thanks for the hint, helps me navigate these unknown waters. 

I managed to add the `listfunds` test and run it.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4296/commits/fe101e82728ceebae3b7ba020a8ad9df9f217bf7

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4296/commits/f31a27e865c3e8888dcd6eea932c5b35dc9e0d80

**Pull request merged**
