### PR TITLE
keysend: Add `maxfee` to keysend for consistency with pay

### LINKED ISSUE #7227: grpc api: Same fee limit handling for keysend and pay
### Issue 
The handling of fee limits is inconsistent on different api endpoints.
The lightning-pay api endpoint exposes maxfee, maxfeepercent and exemptfee fee as parameters. (https://docs.corelightning.org/reference/lightning-pay)
The lightning-keysend api enpoint only exposes maxfeepercent and exemptfee. (https://docs.corelightning.org/reference/lightning-keysend)

Please add maxfee to lightning-keysend to simplify and unify api handling.

### PR DESCRIPTION
**Pull request by s373nZ**
# Add `maxfee` to keysend for consistency with pay

## Description
Adds `maxfee` parameter to keysend with similar functionality of that of pay. Needed to achieve more consistent behavior across API endpoints.

## Related Issues
- Closes #7227

## Changes Made
- [x] **Feature**: Adds `maxfee` parameter to keysend with similar functionality of that of pay.
- [x] **Bug Fix**: Fixed a minor typo in keysend documentation comments.
- [x] **Refactor**: Any code improvements or refactoring done without changing the functionality.

## Checklist
Ensure the following tasks are completed before submitting the PR:

- [x] Changelog has been added in relevant commit/s.
- [X] Tests have been added or updated to cover the changes.
    - Added a test for plugin parameter format.
    - Added a test in `test_pay.py` to test parameter validation, keysend over route exceeding `maxfee`, and keysend w/ `maxfee` set.
- [x] Documentation has been updated as needed.
- [x] Any relevant comments or `TODOs` have been addressed or removed.

## Additional Notes
- I initially added the parameter directly after the `exemptfee` param, but realized order must be important for scripts. Regardless, I've added to the end of documented parameters for backward compatibility, yet there is a "hidden" `dev_use_shadow` param appearing only in the `cli` documentation which it appears before.

### CODE REVIEW

**Comment by s373nZ** [comment]
TODO:
- Research more about `keysend` and the c implementation to be more sure changes are accurate.
- There doesn't seem to be explicitly tests in the `pay` plugin for `maxfee` functionality to emulate, but determine whether this feature needs automated testing.

**Comment by s373nZ** [comment]
Added tests and fixed some of the logic for default values of the other parameters.

The `maxfee` handling logic is more or less a duplication of that found in the pay plugin. Perhaps this could be abstracted and shared? Will look into a little further, but I wonder where the appropriate place for that would be...

**Comment by s373nZ** [comment]
Sacrificed two semicolons to the flake8 gods.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/7653/commits/fdd60db630329a95d5ff3c90185913efc6687db2

**Pull request merged**
