### PR TITLE
No accidental wumbo

### PR DESCRIPTION
**Pull request by rustyrussell**
With some cleanups along the way...

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2095/commits/548834f5d68068d75856be38891eb033729a0212

**Comment by rustyrussell** [comment]
Simple rebase...

**Comment by cdecker** [comment]
Re-rebase and fixup due to missing header.

**Comment by rustyrussell** [comment]
I think we both force pushed the same fix :)

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/debb31669b4f8f565780f3331294718f00445f51

**Pull request merged**
