### PR TITLE
Part 1: offers cleanups

### PR DESCRIPTION
**Pull request by rustyrussell**
In updating and enhancing bolt12 to be a production-quality implementation, I found these miscellaneous nits which needed fixing.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7454/commits/a8eaedc284d978f68028973de4815f8de83f710c

**Review by niftynei — APPROVED** [review]
ACK a8eaedc284d978f68028973de4815f8de83f710c

Nice set of tidy-ing up!

**Comment by rustyrussell** [comment]
Trivial rebase on master, for flake fix.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7454/commits/1fb6cb35018b6a25a8c7aee3fb0cb5f8f42b13f7

**Pull request merged**
