### PR TITLE
openingd/openingd.c: Fix a mild deviation from BOLT#2.

### LINKED ISSUE #3815: shutdown_scriptpubkey behavior seems to not follow the bolt
### Issue and Steps to Reproduce

I've been trying to open the channel with [rust-lightning](https://github.com/rust-bitcoin/rust-lightning) in regtest docker-compose.
([Here's docker-compose file if you are interested](https://github.com/joemphilips/NRustLightning/blob/payment_integration_tests/tests/NRustLightning.Server.Tests/docker-compose.yml))

When I tried to open channel from c-lightning to rust-lightning, rl returns a following error message.
```
They sent error channel 28e53e353b543cd6da141d5c6ca4d9d82f6a526d1f41b6f24e2671c095439f93: Peer is signaling upfront_shutdown but we don't get any script. Use 0-length script to opt-out
```
> note that "They" refers to c-lightning and "we" is rust-lightning.

It seems obvious from the error message that c-lightning is not setting TLV field(shutdown_scriptpubkey) in open_channel.
BOLT 02 states following, so it seems this is a bug in c-lightning.
```
* if both nodes advertised the option_upfront_shutdown_script feature:
  * MUST include upfront_shutdown_script with either a valid shutdown_scriptpubkey as required by shutdown scriptpubkey, or a zero-length shutdown_scriptpubkey (ie. 0x0000).
```

To reproduce, run following.
```
git clone --recursive https://github.com/joemphilips/NRustLightning
git checkout payment_integration_tests
cd tests/NRustLightning.Server.Tests
docker-compose build && dotnet test --filter="FullyQualifiedName~CanOpenCloseChannels"
```

### `getinfo` output
```
{
   "id": "024236460ad239baa1ad169aab65dfcc566d5e6ddfab5349d5b7fcfeb75c22a69d",
   "alias": "SOMBERBEAM-7981f4c",
   "color": "024236",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "192.168.176.5",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "192.168.176.5",
         "port": 9735
      }
   ],
   "version": "7981f4c",
   "blockheight": 442,
   "network": "regtest",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/root/.lightning/regtest"
}
```

I tried both in v0.8.2.1 and master. This is a response when I used master build.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #3815

Changelog-Fixed: Fixed a deviation from BOLT#2: if both nodes advertised `option_upfront_shutdown_script` feature: MUST include ... a zero-length `shutdown_scriptpubkey`.

@joemphilips can you check if this fixes #3815?

### CODE REVIEW

**Comment by joemphilips** [comment]
Yep. It fixes. @ZmnSCPxj

**Comment by ZmnSCPxj** [comment]
Thank you for the confirmation @joemphilips .  Just waiting on Travis and ACKs.

**Comment by ZmnSCPxj** [comment]
Rebased on top of master.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/3816/commits/629fb482d509be932610b8414ee5ef5ee221ee84

**Comment by ZmnSCPxj** [comment]
github somehow lost all the checks, weird.

Anyway:

* ACK by cdecker
* travis-ci OK
* no squash commits
* Changelog entry provided.

**Pull request merged**
