### PR TITLE
Added build for oss-fuzz [Draft]

### PR DESCRIPTION
**Pull request by AdamKorcz**
I have been working on making Lightnings fuzzers run on OSS-fuzz's infrastructure, and I am hereby committing the build that allows for that.

If there is interest in integrating with oss-fuzz, I will be happy to setup the integrationg on the oss-fuzz side, as I have all the build files for the part ready.

Integration will allow Google to run the fuzzers continuously and notify maintainers when bugs are found. It is offered free of charge  for open source projects with an implied expectation that bugs are fixed, so that the resources spent on fuzzing Lightning are put to good use.

To integrate, at least one maintainer email is needed for bug reports. This can be shared here or when the integration application is set up.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@cdecker Thank you very much. For the record, I have not abandoned this PR. This PR was put on hold due to https://github.com/ElementsProject/lightning/issues/4229 and I am still working on the integration on the OSS-fuzz side.

**Comment by cdecker** [comment]
> @cdecker Thank you very much. For the record, I have not abandoned this PR. This PR was put on hold due to #4229 and I am still working on the integration which needs a bit of work due to recent updates on the OSS-fuzz side.

Don't worry @AdamKorcz, just trying to address the backlog of PRs, there's no hurry :-) Mind if I mark this as draft?

**Comment by AdamKorcz** [comment]
@cdecker Thanks. Yeah, marking it as draft would be lovely, thank you.

**Comment by rustyrussell** [comment]
I've closed this: if someone wants to revisit, please open a new PR!

**Pull request closed without merging**
