### PR TITLE
doc(README.md): fix typo about supported installation options

### PR DESCRIPTION
**Pull request by dancer1325**
## Description
* fix a typo about the number of supported installation options

## How to review?
* ONLY 3 are enumerated before

## Checklist
Before submitting the PR, ensure the following tasks are completed. If an item is not applicable to your PR, please mark it as checked:

- [ ] The changelog has been updated in the relevant commit(s) according to the [guidelines](https://docs.corelightning.org/docs/coding-style-guidelines#changelog-entries-in-commit-messages).
- [ ] Tests have been added or modified to reflect the changes.
- [x] Documentation has been reviewed and updated as needed.
- [ ] Related issues have been listed and linked, including any that this PR closes.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK db1d503ed4e40edff178d49e622c7455c834dda9

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Ah ok now we have also the changelog check in the CI

```
Run base_ref="master"
Error: 'Changelog' entry is missing in all commits
Error: Process completed with exit code 1.
```

probably you need in your commit body a `Changelog-None`

**Comment by dancer1325** [comment]
Hi @vincenzopalazzo adjusted. Could you review?

**Review by vincenzopalazzo — APPROVED** [review]
ACK fe3ecc0c0c927debe59348cefd7450e88212c61e

**Pull request merged**
