### PR TITLE
doc-schema: make address field in getinfo response required

### PR DESCRIPTION
**Pull request by RCasatta**
~~Since it is always returned even if empty~~ this was false, see https://github.com/ElementsProject/lightning/pull/5904#issuecomment-1386475617 , there are cases where address field is not returned, but since there are also cases where is returned empty the issue remains. 

alternative to #5902 
Closes #5902 
Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
Following the discussion on #5902 it feels like this breaks fewer things. Apologies for suggesting #5902 first :_0

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5904/commits/8da5c7fd676d9e8d6b5fb5b139441fdf37ae61c4

I preferer this, but I do not have the big picture of the problem

**Comment by rustyrussell** [comment]
But the code shows this is trivially untrue?

```
	/* Add network info */
	if (cmd->ld->listen) {
		/* These are the addresses we're announcing */
		count_announceable = tal_count(cmd->ld->announceable);
		json_array_start(response, "address");
```

So, run with --offline, and you'll see no `address`.

**Comment by RCasatta** [comment]
> But the code shows this is trivially untrue?

Right, so I updated this to add an empty address array even if `--offline` is set

**Comment by RCasatta** [comment]
> but I do not have the big picture of the problem

The reason I am doing this is that If the field is optional and I have a getinfo json A with the address field empty, 
if I do `json A -> grpc -> json B` the B json will not match A because it will skip serializing an empty optional field.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5904/commits/2dc70b50dc93d0ccea71cc75ded02b7081e360f4

**Comment by rustyrussell** [comment]
Trivial rebase for conflict.

Ack https://github.com/ElementsProject/lightning/commit/297b5e4ead9c3b9042da92f806fab340975d0cae

**Comment by rustyrussell** [comment]
Trivial rebase for man page checksum conflict.

Ack 58566cbf7ef51adb22d9ba1db8a9139bdda7d3d6

**Pull request merged**
