### PR TITLE
gossipd: fix listnodes crash on non existing id

### LINKED ISSUE #2634: Crash: gossip WIRE_GOSSIP_GETNODES_REQUEST
### Issue and Steps to Reproduce
- Affected reversion: 12f703eb (master)
- Not (yet) affected revision: b7279e91 (bug introduced in between)
- Reproducabiltiy: 100%
- Network: main

When `getnodes()` is called (i.e. via summary plugin), the daemon crashes with some `tal` bounds checks immediately with stacktrace, see blow. I attached my [gossip_store.zip](https://github.com/ElementsProject/lightning/files/3175367/gossip_store.zip), since I cannot reproduce the issue on testnet. 

### `getinfo` output
```
   "id" : "02a2c53bc475cb92e4ab2f38a5bca56df695034ce90ad78c2f47c05911e3f79e41",
   "alias" : "schmoock.net",
   "color" : "00ddff",
   "num_peers" : 21,
   "num_pending_channels" : 0,
   "num_active_channels" : 20,
   "num_inactive_channels" : 1,
   "address" : [
      {
         "type" : "ipv4",
         "address" : "46.4.92.21",
         "port" : 9735
      },
      {
         "type" : "ipv6",
         "address" : "2a01:4f8:141:47::2",
         "port" : 9735
      }
   ],
   "binding" : [
      {
         "type" : "ipv6",
         "address" : "::",
         "port" : 9735
      },
      {
         "type" : "ipv4",
         "address" : "0.0.0.0",
         "port" : 9735
      }
   ],
   "version" : "v0.7.0-331-g12f703e",
   "blockheight" : 575926,
   "network" : "bitcoin",
   "msatoshi_fees_collected" : 2502492,
   "fees_collected_msat" : "2502492msat"
```

### Stacktrace
```
2019-05-14T00:18:41.496Z lightning_gossipd(6574): FATAL SIGNAL (version v0.7.0-331-g12f703e)
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: common/daemon.c:45 (send_backtrace) 0x56279d18782f
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: common/status.c:194 (status_failed) 0x56279d18c725
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: common/subdaemon.c:25 (status_backtrace_exit) 0x56279d18c97c
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: common/daemon.c:56 (crashdump) 0x56279d187888
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0x7f7668eba8af
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0x7f7668eba82f
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0x7f7668ea5671
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/tal/tal.c:93 (call_error) 0x56279d1b9143
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/tal/tal.c:165 (check_bounds) 0x56279d1b930b
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/tal/tal.c:173 (to_tal_hdr) 0x56279d1b9332
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/tal/tal.c:186 (to_tal_hdr_or_null) 0x56279d1b93cb
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/tal/tal.c:632 (tal_bytelen) 0x56279d1ba2b3
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: gossipd/gossipd.c:2239 (getnodes) 0x56279d18300c
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: gossipd/gossipd.c:2851 (recv_req) 0x56279d1848e3
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: common/daemon_conn.c:31 (handle_read) 0x56279d187ce3
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x56279d1aaabd
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x56279d1ab63a
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x56279d1ab678
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x56279d1ad6cd
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: gossipd/gossipd.c:2973 (main) 0x56279d184c0d
2019-05-14T00:18:41.496Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0x7f7668ea6ce2
2019-05-14T00:18:41.497Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0x56279d17083d
2019-05-14T00:18:41.497Z lightning_gossipd(6574): backtrace: (null):0 ((null)) 0xfffffffffffffff
```

[gossip_store.zip](https://github.com/ElementsProject/lightning/files/3175367/gossip_store.zip)

### PR DESCRIPTION
**Pull request by darosior**
Fixes #2634.

### CODE REVIEW

**Comment by m-schmoock** [comment]
Thx, now it looks good, lets wait for Jenkins...

**Comment by m-schmoock** [comment]
I think we need to check for `node_arr` instead of `nodes`. Also we need an else case, as `towire_gossip_getnodes_reply` would behave indeterminate when called with an uninitilaized pointer.

**Comment by m-schmoock** [comment]
@cdecker @rustyrussell maybe your input is needed here...

**Comment by darosior** [comment]
> I think we need to check for `node_arr` instead of `nodes`. Also we need an else case, as `towire_gossip_getnodes_reply` would behave indeterminate when called with an uninitilaized pointer.

You are right about checking `node_arr` only instead of both `node_arr` and `nodes`, but for the else case I don't see why it would be needed since `towire_gossip_getnodes_reply` takes `nodes` as parameter, which is initialized to NULL.

**Comment by m-schmoock** [comment]
ACK d3ccb7a

**Comment by m-schmoock** [comment]
@cdecker @rustyrussell

This fix resolves the issue #2634 . Sucessfully tested on my mainnet master node.

**Pull request merged**
