### PR TITLE
Readthedocs and markdown manpages

### LINKED ISSUE #2918: Integrate the man-pages into the generated docs webpage
We have quite a wealth of man-pages that we make extensive use when calling `lightning-cli help [command]` on the command-line, but it'd be nice to serve that info also in the [generated doc](https://lightning.readthedocs.org).

I could not find a way to convert our current `asciidoc` format to a format understood by readthedocs / sphinx, which internally uses sphinx, but I found a way to generate man-pages from restructuredtext, so maybe we should just port the sources of the man-pages over?

rst seems like a more supported format (and one whose compiler doesn't attempt to drag in the entire latex distribution on CI).

### PR DESCRIPTION
**Pull request by darosior**
As per https://github.com/ElementsProject/lightning/pull/2928#issuecomment-519828918, fixes #2918.

This completely moves on from asciidoc to Markdown for manpages thanks to a [tweaked version of a Python Markdown->Roff converter](https://github.com/darosior/mrkd). That way, manpages can be completely written in Markdown, displayed in readthedocs, and converted to Roff.

There are still some little things to be fixed with final Roff manpages (WIP) but I wanted to get some feedbacks (for example, is the huge number of insertions/deletions due to file creation/deletion/regeneration a problem ?). Here is a sample of a Markdown manpage : https://gist.github.com/darosior/48bfdf65017ad4a10811be5f00adc32d .

Closes #2928

### CODE REVIEW

**Comment by rustyrussell** [comment]
Yeah, happy with this.  I grabbed asciidoc because I'd used it before for man pages; happy to change to any sane format, like another markdown.

Would be tempted to split into one commit which replaced the .txt with .md files, and another which replaced the generated man pages.  But that's a minor issue, to help review.  Someone has to read all the man pages though...

**Comment by darosior** [comment]
> Would be tempted to split into one commit which replaced the .txt with .md files, and another which replaced the generated man pages. But that's a minor issue, to help review.

It's already what's done ? 547b0c03faf8a2bdb6e07b40a615b8a226cac998 for txt replacement by md and eb09276acad875a502963a0e8899b1384b1f155e for manpage replacement

> Someone has to read all the man pages though...

I've read most of them yesterday and will finish today once I've fix some typos

**Comment by darosior** [comment]
I've fixed the Markdown lists inconsistence at roff generation, regenerated manpages, adapted `check-manpages`, stole @rustyrussell's recipe to update readthedocs pages from #2928, and (more importantly) reviewed all generated md files and manpages.

**Comment by darosior** [comment]
Here is another Markdown manpage sample : https://gist.github.com/darosior/05e6c9da8d2bb0f55b8c15ca217b6499 (took `disconnect` because there are multiple text formatting : code, errors, bold, italic, ..)
And here is the corresponding man :
disco_manpage

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2936/commits/e007a9fe2f0fcdf77d25e9069790d680f556bd4b

**Comment by darosior** [comment]
Rebased to resolve conflicts.

**Comment by cdecker** [comment]
I'm afraid we missed the freeze window by a tiny bit, so we'll merge this directly after the 0.7.2.

**Comment by rustyrussell** [comment]
Rebased, a bit tricky since listforards had been significantly reworked. but we have the whole dev window to fixup :)

Ack https://github.com/ElementsProject/lightning/commit/4b9e3c95a6fe19a908fcd71b331573e14b9ae901

**Comment by darosior** [comment]
Thank you for the rebase! :-)

**Pull request merged**
