### PR TITLE
Update pylightning with current lightningd RPC commands

### PR DESCRIPTION
**Pull request by gdassori**
This PR add all the current lightningd available RPC commands to the LightningRpc object.
Also increase package minor version.

### CODE REVIEW

**Comment by gdassori** [comment]
Not sure if same problem as in pull #799

**Comment by cdecker** [comment]
Unlikely with all tests failing at once :-)

```
    def test_bad_opening(self):
        # l1 asks for a too-long locktime
        l1 = self.node_factory.get_node(options=['--locktime-blocks=100'])
        l2 = self.node_factory.get_node(options=['--max-locktime-blocks=99'])
>       ret = l1.rpc.connect(l2.info['id'], 'localhost', l2.info['port'])
E       TypeError: connect() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by gdassori** [comment]
@cdecker I may update the PR to be compliant with issue #828, but not sure how to design it:
Python is not strictly typed, but I dislike the approach of parsing the type of the first argument and, "if dict", use as "args" for _call. It's very implicit.
Also, in some calls we have two mandatory positional arguments, and this is kinda tricky to handle.

I would instead create another subclass, LightningJsonRpc, which accept dicts on methods.
What do you think about it ?

**Comment by cdecker** [comment]
You can probably get away with having methods with the following signature:

```
def rpcmethod(*args, **kwargs):
```

Then map the positional args to dict values in `kwargs` and pass `kwargs` to `_call`. That way `_call` only needs to know how to handle `dict` based calls, and the logic of mapping positional args to key-value pairs is done in the methods.

**Comment by cdecker** [comment]
I think the rework into `dict`-based calls deserves its own PR :-) Would you like me to push the version 0.0.3 to pypi, or shall I wait for the `dict`-based one and call that one 0.0.3?

**Comment by gdassori** [comment]
I'd say this PR is worth a release on pypi, but since I'm going to make the other PR soon... I'd wait a bit and release the ver 0.0.3 with both enhancements. 
However, as you prefer :-)

**Pull request merged**
