### PR TITLE
Gossmap api improvements

### PR DESCRIPTION
**Pull request by rustyrussell**
These were taken from my renepay branch, but are just surrounding work.

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5596/commits/b86ed678e8d93d4cb2374a5a369ecaa8d7b54c14

**Comment by rustyrussell** [comment]
Trivial rebase only.  I don't understand why rust under CI is giving an internal compiler error; works fine here :(

Ack b86ed678e8d93d4cb2374a5a369ecaa8d7b54c14

**Comment by cdecker** [comment]
> Trivial rebase only. I don't understand why rust under CI is giving an internal compiler error; works fine here :(

Nightly compilers are a bit unstable, we switched over to the stable branch now :-)

**Comment by cdecker** [comment]
Well, seems like `make` is trying to regenerate `hsmd/hsmd_wiregen.h`, likely due to timestamps, but can't because CI now runs without `mako`. We definitely should drop the use of `mako` altogether.

```
Traceback (most recent call last):
2527  File "/work/tools/generate-wire.py", line 27, in <module>
2528    from mako.template import Template
2529ModuleNotFoundError: No module named 'mako'
2530make: *** [Makefile:331: hsmd/hsmd_wiregen.h] Error 1
2531make: *** Waiting for unfinished jobs....
2532wiregen hsmd/hsmd_wiregen.h
2533Traceback (most recent call last):
2534  File "/work/tools/generate-wire.py", line 27, in <module>
2535    from mako.template import Template
2536ModuleNotFoundError: No module named 'mako'
2537make: *** [Makefile:331: hsmd/hsmd_wiregen.h] Error 1
```

**Comment by rustyrussell** [comment]
> Well, seems like make is trying to regenerate hsmd/hsmd_wiregen.h, likely due to timestamps

Well, yeah!  You need it, it's not included, and it require mako?  Are you thinking of mrkd?

Anyway, it's lnprototest python requirements in a knot:

```
The conflict is caused by:
    The user requested grpcio==1.47.0
    grpcio-tools 1.47.0 depends on grpcio>=1.47.0
    pyln-testing 0.11.1 depends on grpcio<2.0.0 and >=1.49.0
```

It's breaking everything RN.

**Pull request merged**
