### PR TITLE
Update CI to Bitcoin Core 24.0.1

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
What is the reason to use this https://github.com/ElementsProject/lightning/pull/5729 ?

I ack if the reason if just to run with new version of bitcoin core, we should make sure that we work with a minimal version of bitcoin core, but I think we use just a minimal API of bitcoin core so that this can have a lower priority?

**Comment by instagibbs** [comment]
Ideally I think the project would have some basic testing around all non-EOL versions of Bitcoin Core https://bitcoincore.org/en/lifecycle/#:~:text=Critical%20security%20issues%20would%20still,to%20a%20later%20major%20version as those are the versions we'd expect people to be running, right?

For now, this PR is demonstrating basic compatibility with releases we expect users to start using soon, even if it ends up not being merged soon.

**Comment by cdecker** [comment]
> I see, another idea also with the @cdecker CI refactoring we could run different version of bitcoin core in the CI

I don't think this is in the scope of that PR, since that is mostly concerned with speeding up CI, and/or conserving precious CI runner minutes. The crunch during the release process was just really too much (release captain having to cancel runs manually and rerun them several times...).

Having multiple `bitcoind` versions under test is orthogonal to that, and we'd probably want to run them outside the critical path for PRs, i.e., on a crontab, once a day to ensure we don't accidentally regress.

**Comment by instagibbs** [comment]
If nothing else happens I'll still be opening these up prior to Core releases to make Core maintainers happy that someone it checking :)

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5813/commits/bed690cd1e73cb63516f67e006bab9f68834bbfd

**Comment by instagibbs** [comment]
Since taproot activated on 0.21.1, I think it's reasonable to expect clients to update to that version? We will need taproot support required if we want to start handing out addresses/generating taproot change

**Comment by vincenzopalazzo** [comment]
I do not see why not merge this, I think we should just rebase on top of the master to adopt the new Ci workflow? @instagibbs

**Comment by cdecker** [comment]
Trying not to make our CI matrix explode again: how about we bundle two versions (HEAD and oldest still supported version). Assuming things don't flip flop too much we should be able to say that all in-between versions are supported.

**Comment by instagibbs** [comment]
@cdecker should catch 99%+ of regressions! sgtm

**Review by vincenzopalazzo — COMMENTED** [review]
Ci failure looks unrelated! and I think the only part missed here is force the CI to use the new bitcoind?

https://github.com/ElementsProject/lightning/blob/master/.github/workflows/ci.yaml#L166

We leave the check inside the CI as future improvment?

**Review by rustyrussell — APPROVED** [review]
Ack 711a3e6abf1af088e917e6e8e8e24f6a4d798c86

**Pull request merged**
