### PR TITLE
Add gitattribute to enforce lf on sh and py files

### PR DESCRIPTION
**Pull request by NicolasDorier**
Not having this change make in a nightmare to code on windows while running on docker.

### CODE REVIEW

**Comment by cdecker** [comment]
Why are `sh` and `py` files special in that regard? I would have expected the same to be true for `c` and `h` files as well.

**Comment by NicolasDorier** [comment]
yeah, it does not really matter for c files actually, but one sec... I force for it as well

**Comment by NicolasDorier** [comment]
well actually .h and .c don't have to be LF, it builds fine.
It does not really matter but given the choice I prefer CR/LF for code files so I am more sure it shows nicely on any editors on windows.

**Comment by NicolasDorier** [comment]
added makefile

**Comment by cdecker** [comment]
Couldn't you also specify `native`, so the newlines get switched to whatever you have locally?

**Comment by NicolasDorier** [comment]
I don't want it to be native. That's the problem.

When I am coding linux stuff, I am checking out from windows but running and compiling on linux through shared drives. Not having LF break the compilation.

**Comment by cdecker** [comment]
ACK 1d1d865

**Comment by rustyrussell** [comment]
The comment says "Declare files that will always have CRLF line endings on checkout."

It then sets those files to have "LF".  Leaving me deeply confused...

Do you mean "Override files which would otherwise be CRLF on windows?"

**Pull request merged**
