### PR TITLE
Preventing lightningd closing when the session ends.

### PR DESCRIPTION
**Pull request by gabridome**
At the moment lightningd doesn't go in background simply adding the "&".
If the server is remote or if, for any other reason the session ends, the program stops without the
user even knowing it. 

Nohup is just a suggestion which works for me. I'm fine with any other procedure. 

It could be useful to useful to mention that the output is appended into nohup.out 
even if there's a message telling that.

### CODE REVIEW

**Comment by cdecker** [comment]
Shouldn't be too hard to implement the double-fork magic to daemonize, shall we go that way?

**Comment by rustyrussell** [comment]
We could use ccan/daemonize, but that's not the problem here I think.  & has been approx equivalent to nohup since the nineties.

I wonder if you're hitting the systemd "I'll kill all your processes when you log out!" in which case daemonize won't help.  @gabridome if I create a fork for you to test, can you see if it helps?

**Comment by gabridome** [comment]
Of course I can test. In the meanwhile I'll do some other check in the next hours

**Comment by gabridome** [comment]
After some test I can say that the end of the program at the closing of the session is rare and depend on how the session is closed (once it was because I closed the session closing directly the window).

The only annoying thing is that the output is always directed to standout if only "&" is added at the end and I could redirect only with `nohup` or

```
lightningd > ~/lightning/lightning.log 2>&1
```

then sending it to the background with crtl+Z and `bg`.

Not a problem for an expert user but a bit confusing for me.

**Comment by rustyrussell** [comment]
Ah, if you ^Z and bg, then the daemon *will* die when you log out.  If you use nohup or &, it won't.

I'll implement --daemon, which should help this.

**Comment by gabridome** [comment]
Yeah!
The -daemon option is perfect IMHO.

Thank you!

Il giorno ven 16 feb 2018 alle ore 00:58 Rusty Russell <
notifications@github.com> ha scritto:

**Pull request closed without merging**
