### PR TITLE
Fix a typo in the description of field `private`

### PR DESCRIPTION
**Pull request by nepet**
Change `False` to `True` in the description of the field `private` for the responses of the following calls:
- `listpeers`
- `listpeerchannels`
- `listclosedchannels`

New description is: "if True, we will not announce this channel"

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Looks like from the Ci it is missing only the `make doc all`

**Comment by nepet** [comment]
@vincenzopalazzo do i have to build the docs locally with `make doc all` and then push them or are they built by the CI?

**Comment by vincenzopalazzo** [comment]
Yeah, correct. You are not building the docs itself but just updating the `.md` file.

Then all the site stuff are done in some magic way that i did not know 😸

**Comment by rustyrussell** [comment]
Trivial rebase and commit of changed man pages.

Ack: ddf02962b

**Pull request merged**
