### PR TITLE
Autoclean gentler

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes: #7753

### CODE REVIEW

**Comment by wtogami** [comment]
Can you auto clean during runtime without disrupting routing?

**Comment by vincenzopalazzo** [comment]
>Can you auto clean during runtime without disrupting routing?

Should not be a problem, why it should disrupting routing? The action of a middle node is just a "witness step", no big operation involved

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7805/commits/7d95004ce86b21c52a71c75ca498cc8892fa25ff

**Comment by vincenzopalazzo** [comment]
@rustyrussell probably a good stacktrace for your timeout debugging

```
test_autoclean passed 1 out of the required 1 times. Success!
test_getroutes_auto_sourcefree passed 1 out of the required 1 times. Success!
test_real_biases failed (1 runs remaining out of 2).
	<class 'Failed'>
	Timeout >1200.0s
	[<TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/_pytest/runner.py:341>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/flaky/flaky_pytest_plugin.py:146>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_hooks.py:513>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_manager.py:120>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_callers.py:182>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_result.py:100>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_callers.py:103>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/_pytest/runner.py:169>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/_pytest/python.py:1792>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_hooks.py:513>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_manager.py:120>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_callers.py:182>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_result.py:100>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pluggy/_callers.py:103>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/_pytest/python.py:194>, <TracebackEntry /home/runner/work/lightning/lightning/tests/test_askrene.py:1188>, <TracebackEntry /home/runner/work/lightning/lightning/contrib/pyln-client/pyln/client/lightning.py:332>, <TracebackEntry /home/runner/work/lightning/lightning/contrib/pyln-testing/pyln/testing/utils.py:735>, <TracebackEntry /home/runner/work/lightning/lightning/contrib/pyln-client/pyln/client/lightning.py:392>, <TracebackEntry /home/runner/work/lightning/lightning/contrib/pyln-client/pyln/client/lightning.py:309>, <TracebackEntry /home/runner/work/lightning/lightning/contrib/pyln-client/pyln/client/lightning.py:278>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pytest_timeout.py:313>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/pytest_timeout.py:498>, <TracebackEntry /home/runner/.cache/pypoetry/virtualenvs/cln-meta-project-AqJ9wMix-py3.8/lib/python3.8/site-packages/_pytest/outcomes.py:198>]
test_real_biases passed 1 out of the required 1 times. Success!
test_plugin_start passed 1 out of the required 1 times. Success!
test_rust_plugin_subscribe_wildcard passed 1 out of the required 1 times. Success!
```

**Comment by rustyrussell** [comment]
Definitely!  And you can test it with autoclean-once...

**Pull request merged**
