### PR TITLE
Add a function to register RPC method which passes down parameter to callback

### PR DESCRIPTION
**Pull request by ffaex**
for cln-plugin crate.

Might be used for something like passing down config parameters to the function, which should be read only once from disk

### CODE REVIEW

**Comment by cdecker** [comment]
Cool idea, so this captures the extra argument in a closure and registers that with the RPC system. Can you share a more concrete example? Might be good to have that in the docs too, in order to convey the rationale behind it.

**Comment by ffaex** [comment]
```rust
#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let network_graph = Arc::new(//read my network graph from disk);
    let state = ();
    if let Some(plugin) = Builder::new(tokio::io::stdin(), tokio::io::stdout())
        .rpcmethod_with_param("altpay", "command to pay with optimized routing", altpay_method, network_graph.clone())
        .start(state)
        .await?
    {
        plugin.join().await 
    } else {
        Ok(())
    }
}
async fn altpay_method(_p: Plugin<()>, _v: serde_json::Value, s: Arc<NetworkGraph>) -> Result<serde_json::Value, Error> {
    let network_graph = s;
    // do stuff with network graph like finding a route and paying it
    // update network graph once in a while
```
This would be a plugin which registers an rpcmethod with lightningd called "altpay".
Like in this example I only would want to read the network graph from disk once

**Comment by cdecker** [comment]
Hm, wouldn't you also be able to make the network graph an attribute on the `State` that `Plugin` gives you access to? That'd also allow you to keep one instance in memory in total, shared among everything that registers a handler, and it could even be deferred using `OnceCell` or similar, and synchronized by wrapping in `Arc<Mutex<MyNetwork>>`.

I guess my question is: what's the advantage of customizing one RPC method with an additional param, if we could also pass it through the `Plugin<State>`?

**Comment by ffaex** [comment]
L

**Comment by ffaex** [comment]
Sorry my bad. Didn't look properly new to rust...

**Comment by ffaex** [comment]
Hey any chance you could give me an example of how one could use the state @cdecker ? I couldn't figure it out.

**Pull request closed without merging**
