### PR TITLE
Increase fd limits (and warn as we approach them)

### PR DESCRIPTION
**Pull request by rustyrussell**
On many systems, the default fd limit is 1024, and we've got users with over 900 channels.  But that's a soft limit, and you can simply ask for an increase!

Also, we should log when we are running low, so people don't have to ask me what to do!

### CODE REVIEW

**Review by cdecker — APPROVED** [review]
ACK adbf9bc7127997a052a940c8ff16f9b3040e9676

**Comment by endothermicdev** [comment]
Added the connecting map to the memleak detection callback in connectd.  Also included a driveby fix for tracepoints memory initialization.

**Comment by rustyrussell** [comment]
Fixing up test assumption that hard limit > soft limit (on CI it seems to be 65536 for both!).

**Comment by endothermicdev** [comment]
This works fine for me locally, but the CI seems unable to raise the fd limit after pytest constrains it.  I noticed if I run pytest as root, it exhibits the same behavior.

**Comment by benthecarman** [comment]
would be nice to test this in docker, kubernetes, and the like to make sure it doesn't have the same constraints

**Comment by rustyrussell** [comment]
> would be nice to test this in docker, kubernetes, and the like to make sure it doesn't have the same constraints

Agreeed.  Meanwhile, this doesn't make it *worse* if we can't increase fd limits, and at least now we'll get a warning if it seems limiting.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7237/commits/71c039ee0e34887ad1720a877dbd616ff1310dc7


Passing the github CI should also give us some clue about the limits in VMs?

**Pull request merged**
