### PR TITLE
msggen: All the changes in one PR

### PR DESCRIPTION
**Pull request by cdecker**
I got really annoyed at the CI for its flakiness, and was not looking
forward to have to do it 20x just to get all these merged, so I'm
doing exactly what I told @daywalker90 not to do, and am bundling the
changes into one large cluster.  This PR just subsumes all the ones
that I have reviewed and would be shepherding through CI anyway.

Closes #7264
Closes #7262
Closes #7263
Closes #7265
Closes #7257 
Closes #7266 
Closes #7267 
Closes #7268 
Closes #7270 
Closes #7271 
Closes #7275

### CODE REVIEW

**Comment by cdecker** [comment]
Dropping #7257 from the bundle as it is running into an type-mixup issue. I'll let @daywalker90 rebase that one.

**Comment by cdecker** [comment]
Dropping #7266 from the bundle as well, since there is a missing `From<ShortChannelId>` trait in the conversion.

**Comment by daywalker90** [comment]
rebased both #7266 and #7257 ! I'll go through the rest to see if they had changes in grpc.py and rebase them, because rebasing those is non-trivial

**Comment by daywalker90** [comment]
found one more: #7267, rest should be fine!

**Comment by cdecker** [comment]
Perfect, thanks @daywalker90, I am letting the current run finish and then I'll push the branch with #7257, #7266 and #7267 re-added. They look good now ^^

**Pull request merged**
