### PR TITLE
doc: Add missing signet to --help and man

### PR DESCRIPTION
**Pull request by jsarenik**
Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4128/commits/821295a8a4f3846d66fc7352e6d1099d569198d5

**Comment by jsarenik** [comment]
@cdecker Hey, sorry I did one change that is only related to ordering. In `--network` the order is `bitcoin, testenet, signet, regtest` and so I moved `--mainnet` in the man page before `--testnet`. If that is OK, should the `--help` options be also moved as in 202f73a62?

**Comment by jsarenik** [comment]
If it is OK, I can squash it. If rather not, I will take out the previous ordering change as well.

**Comment by cdecker** [comment]
Either way works for me :+1:

**Comment by jsarenik** [comment]
@cdecker Thanks for feed-back. Check 8eacc856f

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4128/commits/8eacc856f90cf6608f866b7adf6f5724527a8ab4

**Pull request merged**
