### PR TITLE
bolt12: allow minimal offer

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Make sure that we can fetch the invoice
from an offer without a description

```
E           pyln.client.lightning.RpcError: RPC call failed: method:
offer, payload: {'amount': '2msat'}, error: {'code': -32602, 'message':
'bolt12: Offer does not contain a description: invalid token
\'"lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqyppvggz953rvg9rtxj8lalh43z8epwydjfrmffn3y3p5qz5cywpu09rr4vs"\''}
```

Fixes https://github.com/ElementsProject/lightning/issues/7405
Fixes https://github.com/ElementsProject/lightning/issues/7404

### CODE REVIEW

**Comment by cdecker** [comment]
Adding @rustyrussell as this touches bolt12 semantics.

**Comment by vincenzopalazzo** [comment]
Yep added already Rusty as a reviewer, but still fighting with our generated file 😮‍💨

**Comment by Sjors** [comment]
I can't cleanly cherry-pick this onto `v24.05` so I'm too chicken to test this... :-)

**Comment by vincenzopalazzo** [comment]
>I can't cleanly cherry-pick this onto v24.05 so I'm too chicken to test this... :-)

I will rebase it tomorrow, but with this you can not parse a phoenix invoice anyway, probably you can just parse a ldk invoice, there is a missing feature that we must support before

**Comment by rustyrussell** [comment]
Rebased on master...

**Pull request merged**
