### PR TITLE
Reckless update

### PR DESCRIPTION
**Pull request by endothermicdev**
Removes an extraneous web request, and unnecessary config rewrites. Adds an installer class to support resolution/installation of dependencies and specification of necessary binaries for additional languages.

Based on #6110

Changelog-Changed: Added support for node.js plugin installation via reckless

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
@endothermicdev The code has mostly been executed really well and I enjoyed testing it. Looking forward to use it soon in applications. Below are my testing results:

- Works well with symlink and the file both.
- "if LIGHTNING_CLI_CALL is None" did throw an error for me.
        Changing the check to "if LIGHTNING_CLI_CALL == [None]" fixed the issue and found the cli.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" search "c-lightning-rest"
        Error: Unable to locate source for plugin c-lightning-rest. Should add case sensitive message?
- source rm/source rem/source remove/source add: These commands do not throw any error/info message if called without params.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source add https://github.com/Ride-The-Lightning/c-lightning-REST
        Can we add a success message or return a list of sources once successful?
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source remove "https://github.com/Ride-The-Lightning/c-lightning-REST"
	Error: File "/home/shahana/workspace/lightning/tools/reckless", line 208, in obtain_config
		assert isinstance(config_path, str)
		AssertionError
	Remove is not working for all sources.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source add dummy
	Didn't throw any error but didn't add dummy in the sources list as well
- Call enable before install: tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" enable c-lightning-REST
	File "/home/shahana/workspace/lightning/tools/reckless", line 350, in __init__
		raise Exception(f"Could not find a reckless directory for {name}")
	Exception: Could not find a reckless directory for c-lightning-REST
- Should `npm install` be executed with `--omit=dev` option.
- <Popen: returncode: None args: ['npm', 'install']> shows "dependencies installed successfully" message but <Popen: returncode: None args: ['pip', 'install', '-e', '.']>
shows "error encountered installing dependencies"
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" -v install donations
        Error: No file/folder found for package cln-plugins-donations
- I was unable to install the c-lightning-REST plugin without commenting plugin test code from line 532 till 545. Install works as expected after that.
- Should `universal_newlines` be changed to `text` as it is deprecated since Python 3.7.

Please note that I spent most of my time on testing the plugin rather than reviewing the code as @cdecker will do it much better than me :).

**Review by ShahanaFarooqui — COMMENTED** [review]
@endothermicdev The code has mostly been executed really well and I enjoyed testing it. Looking forward to use it soon in applications. Below are my testing results:

- Works well with symlink and the file both.
- "if LIGHTNING_CLI_CALL is None" did throw an error for me.
        Changing the check to "if LIGHTNING_CLI_CALL == [None]" fixed the issue and found the cli.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" search "c-lightning-rest"
        Error: Unable to locate source for plugin c-lightning-rest. Should add case sensitive message?
- source rm/source rem/source remove/source add: These commands do not throw any error/info message if called without params.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source add https://github.com/Ride-The-Lightning/c-lightning-REST
        Can we add a success message or return a list of sources once successful?
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source remove "https://github.com/Ride-The-Lightning/c-lightning-REST"
	Error: File "/home/shahana/workspace/lightning/tools/reckless", line 208, in obtain_config
		assert isinstance(config_path, str)
		AssertionError
	Remove is not working for all sources.
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" source add dummy
	Didn't throw any error but didn't add dummy in the sources list as well
- Call enable before install: tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" enable c-lightning-REST
	File "/home/shahana/workspace/lightning/tools/reckless", line 350, in __init__
		raise Exception(f"Could not find a reckless directory for {name}")
	Exception: Could not find a reckless directory for c-lightning-REST
- Should `npm install` be executed with `--omit=dev` option.
- <Popen: returncode: None args: ['npm', 'install']> shows "dependencies installed successfully" message but <Popen: returncode: None args: ['pip', 'install', '-e', '.']>
shows "error encountered installing dependencies"
- tools/reckless -l "/.../.lightning" -c "/.../.lightning/config" --network "testnet" -v install donations
        Error: No file/folder found for package cln-plugins-donations
- I was unable to install the c-lightning-REST plugin without commenting plugin test code from line 532 till 545. Install works as expected after that.
- Should `universal_newlines` be changed to `text` as it is deprecated since Python 3.7.

Please note that I spent most of my time on testing the plugin rather than reviewing the code as @cdecker will do it much better than me :).

**Comment by endothermicdev** [comment]
Did some cleanup and addressed several of these points @ShahanaFarooqui.  I'll take another look at some of the failure responses (though these often only show up with the verbose flag.)

"pip install -e ." installs from the pyproject.toml file, which I believe is generally geared toward developer usage (i.e., poetry install.)  I debated whether I should include this method at all as it's only a fallback when a requirements.txt is missing.  It works sometimes, but it less reliable outside of a separate virtual environment.  Maybe it's best to not include this? Alternatively it could provide a warning and prompt the user to ask the developer for a requirement.txt.

**Comment by ShahanaFarooqui** [comment]
ACK https://github.com/ElementsProject/lightning/commit/67012ae70ea803bdf428655d59cd97f43ad00fc7

**Comment by ShahanaFarooqui** [comment]
Changelog-Changed: Added support for node.js plugin installation via reckless

ACK https://github.com/ElementsProject/lightning/commit/9daa6cb73fd604b04926e2c278938f169b368b18

**Pull request merged**
