### PR TITLE
docs: standardise notifications schema

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
Notifications schema was introduced in the last release (commit 932396e2b3c7eda1532fe128117c6295dd46bf6b) by @ErikDeSmedt. The last release also had a huge documentation update with PR #6995. 

This PR is modifying the notifications schema definitions and json schema according to our latest documentation standard.

Changelog-None.

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
@ErikDeSmedt You are not showing up in my reviewers list. Please review the PR.

**Review by Zoiediez — APPROVED** [review]

**Review by Zoiediez — APPROVED** [review]

**Comment by ShahanaFarooqui** [comment]
@ErikDeSmedt Can you please ACK the PR if everything is okay?

**Comment by ShahanaFarooqui** [comment]
ACK b55434b51669e0eef34d71e8c6a767d8e961d8e4

**Comment by rustyrussell** [comment]
Trivial rebase for genfile conflict.

**Pull request merged**
