### PR TITLE
what if we just didn't use poetry install

### PR DESCRIPTION
**Pull request by niftynei**
What if we use pip install for our builds? Just a thought.

Changelog-None

### CODE REVIEW

**Comment by wtogami** [comment]
yes please

**Comment by cdecker** [comment]
That should be much less of a problem, if we generate the `requirements.txt` from `pyproject.toml` it will specify exact versions, cutting down on the combinatorial issue that we were having before on CI.

So poetry for dependency definition and resolution, and pip + requirements.txt to avoid having to configure poetry and others. This sounds like a good idea, and we could go one step further and check the `requirements.txt` file in, and treat it as a lock file that if generated and can be checked for changes in CI

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5589/commits/ae2bedfb097b753c2479ec9572e90eb2754f6b7d

**Review by rustyrussell — APPROVED** [review]
Ack ae2bedfb097b753c2479ec9572e90eb2754f6b7d

poetry is for devs, pip is for users.

**Pull request merged**
