### PR TITLE
doc/TOR.md: Add missing instructions to add user to Tor group.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Changelog-None

Fixes: #4208

### CODE REVIEW

**Comment by cdecker** [comment]
Good catch. I think the instructions could be a bit more specific as to what `lightningd` requires access to (the cookie in `/run/tor/control.authcookie`) and the instructions could make use of that file to determine the tor group, rather than having them search through the list of all the system's groups.

This will return the group ID of the user directly:

```
stat -c "%G" /run/tor/control.authcookie
```

Finally, re-logging in is only required if the daemon is run manually in an already loaded shell, and starting from an init system will most likely not require it.

**Comment by ZmnSCPxj** [comment]
Well, in theory the authcookie file could be somewhere *else*, is my problem.  I suppose qualifying it with "usually" is sufficient.

**Comment by ZmnSCPxj** [comment]
Added about `/run/tor/control.authcookie`, rebased on master.

**Review by m-schmoock — APPROVED** [review]
Yep this info was missing. I also discovered that for my system (arch linux) the `/etc/tor/torrc` config option  `DataDirectoryGroupReadable 1` was required when using cln with tor. Maybe you want to add this to the `TOR.md`.

Otherwise I did get following stacktraces when starting `lighningd --daemon`:

```
lightning_connectd: Could not open Tor cookie file '/var/lib/tor/control_auth_cookie': Permission denied (version v0.9.1-329-g23ab1c5)
0x555e1fc5564b send_backtrace
	common/daemon.c:38
0x555e1fc5fb31 status_failed
	common/status.c:206
0x555e1fc511c6 negotiate_auth
	connectd/tor_autoservice.c:269
0x555e1fc51566 tor_fixed_service
	connectd/tor_autoservice.c:359
0x555e1fc4beaa setup_listeners
	connectd/connectd.c:1213
0x555e1fc4c199 connect_init
	connectd/connectd.c:1296
0x555e1fc4d403 recv_req
	connectd/connectd.c:1597
0x555e1fc55b54 handle_read
	common/daemon_conn.c:31
0x555e1fc8bf64 next_plan
	ccan/ccan/io/io.c:59
0x555e1fc8caeb do_plan
	ccan/ccan/io/io.c:407
0x555e1fc8cb29 io_ready
	ccan/ccan/io/io.c:417
0x555e1fc8ece8 io_loop
	ccan/ccan/io/poll.c:445
0x555e1fc4d63b main
	connectd/connectd.c:1679
0x7f5482dd0151 ???
	???:0
0x555e1fc46e7d ???
	???:0
0xffffffffffffffff ???
	???:0
lightningd: connectd failed (exit status 242), exiting.
```

**Comment by ZmnSCPxj** [comment]
Added suggestion from @m-schmoock

**Comment by m-schmoock** [comment]
ACK b5b270b

**Pull request merged**
