### PR TITLE
v0.7.2.1: Nakamoto's Pre-approval by US Congress

### PR DESCRIPTION
**Pull request by rustyrussell**
(Last-minute build fixes, all Rusty's fault!)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
please fix https://github.com/ElementsProject/lightning/issues/2968 before

**Comment by NicolasDorier** [comment]
Also merging this one https://github.com/ElementsProject/lightning/pull/2966 would be nice. I think arm32 is broken without it.

**Comment by rustyrussell** [comment]
> Also merging this one #2966 would be nice. I think docker arm32 is broken without it.

Done, as it's unlikely to make it worse, and we're delayed anyway.

**Comment by rustyrussell** [comment]
> please fix #2968 before. I can't roll out the new version, as it break my test suite consistently.

Thanks!  I've delayed release.

Erk, if we'd released on time, we'd have missed this.  "Fortunately" I committed a build issue in rc2, and so we delayed release to fix that.

Just FYI: we now release -rc1 on the 10th of every second month.  That's a great time to test the release for upstream project like yours.  If we get no new bug reports in 3 working days, we feel free to tag the final one...

**Comment by NicolasDorier** [comment]
@rustyrussell thanks will keep in mind. It is the first time I see c-lightning failing my tests after an update, so I took for granted that non-rc are bug free. :p

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2971/commits/545d0c640a7478277eed334ac6e84da41489a5d7

**Comment by NicolasDorier** [comment]
Tested after 8b85380 and it seems the problem I reported is fixed.

**Pull request merged**
