### PR TITLE
msggen: Enable ListPeerChannels RPC

### PR DESCRIPTION
**Pull request by TonyGiorgio**
Partially resolves some problems https://github.com/ElementsProject/lightning/issues/6186

The channels inside of `ListPeers` has been deprecated yet the thing that deprecates it (`ListPeerChannels`) is inaccessible, this PR enables that and fixes invalid characters in the schema as identified by https://github.com/ElementsProject/lightning/pull/6203#issuecomment-1522289346

Let me know if I did anything incorrect. It was a painful undocumented and manual process to generate all of this rust code with python code that reads from a schema file.

Perhaps moving to proto files and common proto tools will fix all of this manual, tedious, and error prone process.

Changelog-None

### CODE REVIEW

**Comment by 2Fast2BCn** [comment]
You converted ChannelType.names from an `enum` into a `string` right?
Or am I reading this incorrectly?
I kinda would prefer if it was an enum to keep it in-line with the existing code.
Just tried replacing `/` with `_` from `static_remotekey/even` etc and keep the `enum` but that is not working unfortunately.

**Comment by TonyGiorgio** [comment]
> You converted ChannelType.names from an enum into a string right?

Yeah, I believe so. I was following the lead of `ListPeers.peers[].channels[].features[]` which also does that.

**Comment by 2Fast2BCn** [comment]
So you did it correctly and I tried to fix something that was already string rather then enum to start with.
So to keep it consistent I should actually NOT use an enum.
Thanks will revert this in my PR.
Was it still needed to replace the `/` into `_` even with string rather then enum?

**Comment by TonyGiorgio** [comment]
> So you did it correctly and I tried to fix something that was already string rather then enum to start with. So to keep it consistent I should actually NOT use an enum. Thanks will revert this in my PR. Was it still needed to replace the `/` into `_` even with string rather then enum?

Yeah I noticed that all the rust code was generated with `/` in the name which is invalid, then I looked to see where else that was the case and it was just these two files. So not standard or a mistake, so I decided to just fix it in the schema. Afterwards, rust package was being created successfully but was still getting proto errors when running `make` and it pointed to those enums still so I added all the similar exceptions that `listpeers` had.

I will say, I do not know if that was the correct approach, but I have tested it locally on a rust project and it works, though I'm only looking for a few specific fields, I didn't specifically test those enums.

**Comment by TonyGiorgio** [comment]
Is there any specific error? I can take a look and see about adding it on my PR and testing it.

**Comment by 2Fast2BCn** [comment]
> Yeah I noticed that all the rust code was generated with `/` in the name which is invalid, then I looked to see where else that was the case and it was just these two files. So not standard or it was a mistake, so I decided to just fix it in the schema. Afterwards, rust package was being created successfully but was still getting proto errors when running `make` and it pointed to those enums still so I added all the similar exceptions that `listpeers` had.

I created PR https://github.com/ElementsProject/lightning/pull/6202 to fix the rust code generation but since it's defined as a string now that is not needed anymore.

**Comment by 2Fast2BCn** [comment]
> Is there any specific error? I can take a look and see about adding it on my PR and testing it.

Alternatively you could checkout my branch and see if it works for you. Maybe I'm not correctly rebuilding everything.

**Comment by cdecker** [comment]
Ok, I'm finally back on keyboard, sorry for the delay. I went and reworked the PR:

 - Not renaming the feature names, rather normalizing them during conversion. Just renaming them is technically a breaking change that'd impact any existing applications using it.
 - I have some overrides in place, since `listpeers` was also omitting a couple of fields. This is temporary until we have time to complete the mapping. This also means that the conversions for grpc responses -> jsonrpc responses don't really work since the conversion is lossy.
 - I added a test to ensure that we actually get a valid grpc result.

I'll address the `ListClosedChannels` call in #6210

**Comment by 2Fast2BCn** [comment]
PR https://github.com/ElementsProject/lightning/pull/6212 was on top of this PR.
I closed https://github.com/ElementsProject/lightning/pull/6210 as it's code is also part of PR https://github.com/ElementsProject/lightning/pull/6212

I also had a PR with channel types as part of primitives but maybe it's easier for you to start from scratch.

FYI: I also moved some stuff around in the decode.schema.json files because `"PROPRETY_NAME": {},` was causing problems when it was in the top part of the file.

**Comment by cdecker** [comment]
Yep, I just pushed #6222 and will rebuild #6212 on top of this PR next. So we'll end up with all the methods you required.

As for the `channel_type` I'll add them back in asap, but to get things going it's a bit easier to just override them with a `None`.

**Review by rustyrussell — APPROVED** [review]
Ack 69ac0627807764f673bc8bf54560d0036bc6956e

**Comment by rustyrussell** [comment]
Annoyingly, this needs `Changelog-Added: GRPC: `ListPeerChannels` support.  Though @ShahanaFarooqui could add that manually for the release...

**Comment by cdecker** [comment]
Since I'm touching the last PR anyway to get the generated files in order I'll add a changelog added line for all three PRs so we don't pollute the changelog too much :-)

**Comment by rustyrussell** [comment]
Merged successor

**Pull request closed without merging**
