### PR TITLE
rs: Bump crates and update `bitcoin` dependency

### PR DESCRIPTION
**Pull request by cdecker**
The Fedi project is asking for a new version, and hoping that we switch to `bitcoin==0.30.1` to reduce their dependencies. Why not :-)

Fixes https://github.com/ElementsProject/lightning/issues/6735

Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
Trivial Rebase

ACK https://github.com/ElementsProject/lightning/pull/6726/commits/0ca2849c8ba3cf64e14875117f63dc8ef98963ea

This build on my system, lets see if the CI is happy BTW

**Comment by cdecker** [comment]
Since I was at it I also added a fix for #6735

**Comment by daywalker90** [comment]
cln-rpc and cln-plugin 0.1.6 are already published

**Comment by kilrau** [comment]
> Since I was at it I also added a fix for #6735

:pray:

**Comment by nepet** [comment]
The Pre-build checks are still complaining about a mismatch in the compiled proto stubs and I don't understand why. CI uses `grpcio_tools=1.59.0` and my local poetry shell also uses `grpcio_tools=1.59.0` to compile the proto files and a local run of `make check-gen-updated` seems to be fine with the compiled stubs from 520cbbcd892373579195c6ff7f50650cb49b6151

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6726/commits/6802a44d24b92dbcc920a5e71de20b3e461b8476

**Pull request merged**
