### PR TITLE
Adding Travis-CI configuration

### PR DESCRIPTION
**Pull request by cdecker**
Added simple travis-ci configuration that will build and test branches and pull requests.

Travis CI will probably blacklist us, due to the `bitcoind` dependency, but I had the ban lifted after talking to their support and explaining what we do, I can coordinate with them to do the same here :-)

### CODE REVIEW

**Comment by cdecker** [comment]
This is currently a bit flaky, due to some dependencies not installing correctly.

**Comment by cdecker** [comment]
@rustyrussell this should work now :)

The trick was the restart of a node that accepted a connection, may result in a timeout when waiting for the opening node to reopen the connection.

This currently does not call `make check-source` since `make check-source-bolt` will fail since there is no connection between the source and the version of the spec that it checks against. Maybe we should have the lightning-rfc repo as a submodule?

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> @rustyrussell this should work now :)
>
> The trick was the restart of a node that accepted a connection, may result in a timeout when waiting for the opening node to reopen the connection.
>
> This currently does not call `make check-source` since `make check-source-bolt` will fail since there is no connection between the source and the version of the spec that it checks against. Maybe we should have the lightning-rfc repo as a submodule?

Well, we should fix that requirement: check-source-bolt should be a NOOP
if there's no spec.

Then we should make travis check it out, I think.

Cheers,
Rusty.

**Comment by cdecker** [comment]
The problem is not so much checking out the spec repo as well, it's that there is no link between what version of the spec to check against for this precise version of the lightning repo. For example master on rustyrussell/lightning-rfc@9f18acec2653206d5f91d63267ccb437aac41b54 is out of sync with master on ElementsProject/lightning@c2d71497ff1238b84c53e09eb9fb8c120d00a705, either because the spec changed, the implementation changed or both. Either way `check-source` returns 

```
daemon/peer.c:2542:mismatch:    /* BOLT #2:
Closest match: A node MUST send an `init` message immediately immediately after it has validated the `authenticate` message. A node MUST set the `ack` field in the `init` message to the the sum of previously-processed messages of types `open...[_commit_sig`, `updat]
make: *** [check-source-bolt] Error 1
```

(see rustyrussell/lightning-rfc/pull/10 for a fix)

Adding the spec repo as a submodule actually also commits which commit of the spec we are checking against, so this would not be an issue anymore.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Adding the spec repo as a submodule actually also commits which commit of the spec we are checking against, so this would not be an issue anymore.

Except we're switching to a different spec, so we'll always have this
problem.

check-source should really check against the latest spec, so I'm not
sure what to do about this...

Cheers,
Rusty.

**Comment by cdecker** [comment]
Problem is that we probably want to change the spec and the implementation in sync when making changes. If the two are not in sync then we get failing builds on perfectly reasonable PRs and commits, which is worse than having no CI at all IMHO.

Unless you have a strong objection, I'll merge the submodule in as well.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> Problem is that we probably want to change the spec and the implementation in sync when making changes. If the two are not in sync then we get failing builds on perfectly reasonable PRs and commits, which is worse than having no CI at all IMHO.
>
> Unless you have a strong objection, I'll merge the submodule in as well.

True, if we're developing on a branch there's no good solution, since
either master or our branch will fail.

But submodules don't work either :(  They're not within git, so you
can't have a different submodule for one branch...

So we need to do it manually: simplest is a Makefile var which says what
version of the ../lightning-rfc to use, which can be adjusted
per-branch.

Meanwhile, "check-source" passes fine if ../lightning-rfc doesn't exist,
AFAICT.

Cheers,
Rusty.

**Pull request merged**
