### PR TITLE
Return both style addresses (and eventually, more?) from newaddr

### PR DESCRIPTION
**Pull request by rustyrussell**

### CODE REVIEW

**Comment by rustyrussell** [comment]
We may squeeze this in after rc1, given it's fairly simple and Shesek asked for it, but I don't want to hold up rc1 just for this...

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2391/commits/7972ec12a5a1de37d1316ea2a35609f1795f63d8

**Comment by rustyrussell** [comment]
This will have to wait, as I missed it for rc2.  Marking for 0.7.1

**Comment by cdecker** [comment]
Rebased on top of #2430 since we switched over to a new era :wink: 
ACK https://github.com/ElementsProject/lightning/pull/2391/commits/e0862f59d03b7ff5120d8358e70fc45f599c8e47

**Comment by rustyrussell** [comment]
Re-rebased :)

Ack https://github.com/ElementsProject/lightning/pull/2391/commits/f9f9e1b4bfd3bcc2111f5658c6eef11e93afbb37

**Pull request merged**
