### PR TITLE
Support P2SH

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: https://github.com/ElementsProject/lightning/issues/410

### CODE REVIEW

**Comment by cdecker** [comment]
Looking good so far @ZmnSCPxj, the build failure for commit e93b6dc808d11df7fa1c0821ef583c045994d430 comes from `bitcoin_address p2pkh_destination` not being used. It's a bit hidden due to the folding I added some time ago to the travis output. I should probably remove it again.

```
wallet/walletrpc.c:117:25: error: unused variable 'p2pkh_destination' [-Werror=unused-variable]
  struct bitcoin_address p2pkh_destination;
                         ^
cc1: all warnings being treated as errors
```

**Comment by ZmnSCPxj** [comment]
Largely complete, but still requires a test for P2SH.  Removed WIP tag.

I am considering, to copy `test_withdraw` in `test_lightningd.py`, but modify the below:

    -        waddr = l1.bitcoin.rpc.getnewaddress()
    +        p2pkh_addr = l1.bitcoin.rpc.getnewaddress()
    +        waddr = l1.bitcoin.rpc.addwitnessaddress(p2pkh_addr)

Which should generate a `waddr` that is a P2SH-P2WPKH.

**Comment by ZmnSCPxj** [comment]
The `addwitnessaddress` is not supported in the Travis: https://travis-ci.org/ElementsProject/lightning/jobs/314465277#L3636

I will have to find another way, to generate this P2SH.

**Comment by ZmnSCPxj** [comment]
`addmultisigaddress` also does not work: https://travis-ci.org/ElementsProject/lightning/jobs/314475609#L3636

Or possibly I have massively misunderstood how Python interacts with bitcoind, in which case, I need more help, regarding how to test P2SH withdrawal from `test_lightningd.py`.

**Comment by rustyrussell** [comment]
You could just use lightningd to generate a p2sh, and send funds to itself?  Or the other lightningd?

The other option is to use a throwaway hardcoded privkey, for which you know the p2sh address, but I think using lightningd's newaddr is simplest...

**Comment by ZmnSCPxj** [comment]
Ah, I suppose that is indeed better.  I shall try to see how to check this "correct receive".

**Comment by ZmnSCPxj** [comment]
Initial run looks promising: https://travis-ci.org/ElementsProject/lightning/jobs/314589056#L3583

**Comment by ZmnSCPxj** [comment]
Seems OK with new `test_withdraw_p2sh`.

**Comment by ZmnSCPxj** [comment]
@rustyrussell , is there anything in particular more I need to do to get this merged?

**Comment by rustyrussell** [comment]
Sorry, was swamped with other lightning things.  Merged now, thanks!!

**Pull request merged**
