### PR TITLE
new line for default value, makes it more visable

### PR DESCRIPTION
**Pull request by LightningHelper**
See here #4670

Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
LTGM https://github.com/ElementsProject/lightning/pull/4682/commits/e634916608ff1291e27e443fc53660f8f8d2989a

I think you are missing only a make doc-all command, also just make should be fine.

**Comment by LightningHelper** [comment]
Thanks @vincenzopalazzo 
I am not sure what:

> I think you are missing only a make doc-all command, also just make should be fine.

This means

**Comment by vincenzopalazzo** [comment]
I'm so sorry to be not clear @LightningHelper.

The documentation contained in the `lightning-commandname.md` file are "compiled" in a file lightning-`commandname.7`.somethings, the second file is autogenerated by the command `make doc-all` .

So, if you run the command `make doc-all` you will have a new file called `lightning-close.7`, and you need to include also it in the PR.

I hope I clarify the problem 😄

**Comment by LightningHelper** [comment]
Go it, thanks!!
I actually do not compile it, but I'll start, it will take me some time.

**Comment by cdecker** [comment]
Amended with missing `make doc-all` call.

ACK https://github.com/ElementsProject/lightning/pull/4682/commits/285d6b3375a57a5d3b12e34da6aee24d02cb78c4

**Pull request merged**
