### PR TITLE
Missing changelog entries

### PR DESCRIPTION
**Pull request by rustyrussell**
We all need to add this to our mental checklist of PR review I think...

### CODE REVIEW

**Comment by niftynei** [comment]
cool, lgtm. ACK 3eabbd779be8783854cc1584a242dd0222ce2994

**Comment by jb55** [comment]
ack ac85728d64ffdf2f9a88a5382e6017307672e692

**Comment by rustyrussell** [comment]
@cdecker Why didn't ackbot trigger on @niftynei msg?  Upper case?  Other things on line?  For future reference...

**Comment by cdecker** [comment]
> @cdecker Why didn't ackbot trigger on @niftynei msg? Upper case? Other things on line? For future reference...

Yep, tha ACK needs to be on a separate line, otherwise I might be triggering on unrelated content.

**Pull request merged**
