### PR TITLE
Fixed assertion in pay plugin

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Hi all,

I don't know if this type of PR is welcome, if no, I'm so sorry.

This PR includes the fix discussed on PR #3855. This fix was tested with the use case described inside the issue and worked.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
It is acceptable of course.

You need a `Changelog` entry.  Since this fixes a bug that does not exist in previous version, it would be `Changelog-None`.  Just add to commit message (use `git commit --amend` to edit the commit message) then push `--force` to your branch.

You also probably want to add the text "Fixes: #3855" to the commit message and the original comment you put above, so that merging this change auto-closes #3855

I have a test to tickle this bug.

**Comment by ZmnSCPxj** [comment]
Hi @vincenzopalazzo I have a branch with the proposed fixes to your commit message, as well as the test, which I have confirmed catches this bug and also confirms the fix is working. https://github.com/ZmnSCPxj/lightning/commit/1e62ac0e20496be1f8a8bdc2646ca0af5e4356df

Will push into this PR.

**Comment by ZmnSCPxj** [comment]
Force pushed.  Let us leave to @cdecker for review.

**Comment by vincenzopalazzo** [comment]
Hi @ZmnSCPxj 

Thanks and sorry if I missed the test. In addition, Should I add the message that you suggest in the message below?

>You need a Changelog entry. Since this fixes a bug that does not exist in previous version, it would be Changelog-None. Just add to commit message (use git commit --amend to edit the commit message) then push --force to your branch.

**Comment by ZmnSCPxj** [comment]
Already added when I force-pushed into your PR.  Moar tests == better as well.

**Comment by cdecker** [comment]
Excellent work @vincenzopalazzo and @ZmnSCPxj, this is very much appreciated, but I could hit myself for not thinking of this myself :-)

Anyway, this works greate and I'll ACK it as soon as CI reports that it is working :+1:

**Comment by ZmnSCPxj** [comment]
CI seems to catch another bug, where we somehow trigger the paymod system to split the payment into tiny, tiny, tiny parts and then things start collapsing due to the load of handling lots of tiny tiny parts.

**Comment by ZmnSCPxj** [comment]
I suggest adding a reset of some kind to `paymod`, where after we split too many times into tiny tiny pieces, we just clear the entire payment tree, erase our memory of excluded channels and nodes, and retry with the parent payment.

**Comment by cdecker** [comment]
Having a split limiter is definitely a good idea, though we already have that indirectly via the fee and cltv budgets that get split into smaller and smaller pieces.

I think it's probably best not to automatically retry, since that would most likely lead down the same path. Rather we should optimize the first tree in such a way that any retry of the root would be superfluous anyway. There's just loads of parameters we can tweak here, and we're just getting started :-)

**Comment by cdecker** [comment]
Rusty and I are working on fixing those other issues, reported by testers, and fix up the CI runs btw, so I'll rebase this PR on top of those so we can make sure this works as expected (which I'm pretty sure looking at the change anyway)

**Comment by ZmnSCPxj** [comment]
Suggest cherry-picking this on top of #3857 and then closing this then, seems we need a bit more tests and so on for `paymod`.

**Comment by cdecker** [comment]
Will do :+1:

**Comment by cdecker** [comment]
Cherry-picked on top of #3857 as suggested

**Pull request closed without merging**
