### PR TITLE
schema: add missing option_will_fund for listnodes

### PR DESCRIPTION
**Pull request by daywalker90**
Ok ok i did not adhere to the writing-json-schemas.md guideline for conditional fields but it just didn't want to work when i tried.
This is me learning json schemas and msggen so bear with me please. I'll plan on doing as much as i can if this works out :)

Note that i also made `address` in `addresses` no longer optional since there is no scenario where it is on >23.08

fixes: #7185

### CODE REVIEW

**Comment by daywalker90** [comment]
So my removing of all `allOf`'s was affecting the documentation. So i reintroduced it for `last_timestamp`

**Comment by daywalker90** [comment]
apparently i broke a test that i don't yet understand

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7210/commits/ca556b061cbe0439810cf918fa3d7ee392a3357a

**Comment by daywalker90** [comment]
I think i found a big fix for msggen that makes this obsolete

**Pull request closed without merging**
