### PR TITLE
Ping request type

### PR DESCRIPTION
**Pull request by litch**
The rust cln_rpc rust project `PingRequest` message does not work, since it asks for an f64.  The model.rs file is generated from `doc/schemas/ping.request.json`, where I have changed "number" type to "u16".

Changelog-None

### CODE REVIEW

**Comment by litch** [comment]
Ugh, I am not sure why that prototest hash thing is in there.  Will take a look with fresh eyes.

**Comment by cdecker** [comment]
No worries, it just means that `make check-gen-updated` detected a file that was not checked in after being regenerated. To fix just run that command and commit all modified files. I did that for you in this case to check if that's the only thing that fails (which I'm confident it is since the change is great ^^)

**Comment by cdecker** [comment]
I also squashed the submodule refresh and its revert so just the effective changes remain :-)

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5887/commits/951fa9ac3bc4efde1417bb2c3b6ced7929077e87

**Comment by litch** [comment]
Thank you @cdecker !

**Pull request merged**
