### PR TITLE
Add litecoin testnet support

### PR DESCRIPTION
**Pull request by lvaccaro**
Add "litecoin-testnet" chainparam with litecoin testnet genesis blockhash, port and options.

### CODE REVIEW

**Comment by windsok** [comment]
possibly for testing bitcoin testnet <-> litecoin testnet atomic swaps?

**Comment by laanwj** [comment]
Or could be useful for testing lightning-to-lightning exchange sites such as http://zigzag.bitlum.io .

**Comment by windsok** [comment]
If anyone would like to help test this, I have a c-lightning node up and running on litecoin-testnet.

You can connect to my node, and try to open a channel:
033849da551ed69aff710a2c7f2978b421faeb88437405b6bcb135a6e0d19bb103 35.224.94.81:9735

To get up and running on litecoin testnet you need to:
* Compile litecoind from the 0.15 branch - https://github.com/litecoin-project/litecoin/tree/0.15
* Fully sync litecoind on testnet4
* Compile c-lightning with this branch rebased on master (or use my version which is up to date with  master as of this comment - https://github.com/windsok/lightning/tree/litecoin-testnet)
* Run lightningd with --network=litecoin-testnet

**Comment by windsok** [comment]
Looks like someone tried to open a channel with me:

`{
  "peers": [
    {
      "id": "0397929954bd36a05a19f6007a73b0a5dddd4bc295b161e528da1d50ea6fb8010b",
      "connected": false,
      "channels": [
        {
          "state": "CHANNELD_AWAITING_LOCKIN",
          "funding_txid": "a43f256a2e553b63d7b2ecea8809f56ad6d72ce9c4deb2582fe1cf0d85882971",
          "msatoshi_to_us": 0,
          "msatoshi_total": 500000000,
          "dust_limit_satoshis": 546,
          "max_htlc_value_in_flight_msat": 18446744073709552000,
          "channel_reserve_satoshis": 0,
          "htlc_minimum_msat": 0,
          "to_self_delay": 6,
          "max_accepted_htlcs": 483
        }
      ]
    }
  ]
}`

However, I don't see the funding tx in the mempool or any block (using http://explorer.litecointools.com/ to check).

I'm seeing this error repeated over and over in the lightningd log:
`lightningd(21822): Broadcasting tx 02000000000101712988850dcfe12f58b2dec4e92cd7d66af50988eaecb2d7633b552e6a253fa40000000000b674998001405d0700000000001600146c67e73747ba8dcd54110467bbebad267f346644040048304502210095c8437336b50a6fa3945474a63bd0632562cedd17d8ee4dc42020427a9db8360220131f36bc44ef47856915d36a39375e7afb98fb06dea25a744bf683c0242020670147304402205defd8a012d00d9a77570083f695c90b44ad44d78365103d8164fe62d758c3490220373a0e64c3ef902e82dec407b59d168153e1b5c53fead13fba5d747e1e4bc04a0147522102a0e17c5822fa80d1e5909e5b397cd2b205f697dbade24e60c7eded05c735d78b21032d99fcf34aa552fcd99396e79a6b9f9541fe66ce5a3a0e5ea7656c73d668c3cb52ae42584e20: 25 error code: -25
error message:
Missing inputs`

**Pull request merged**
