### PR TITLE
pyln: check if msat replacement works on events

### PR DESCRIPTION
**Pull request by m-schmoock**
Modifies `Plugin()` constructor to tell it that it also should replace msat fields on notifications.

### CODE REVIEW

**Comment by SimonVrouwe** [comment]
What do you mean with
> '_msat' fields are not replaced

is this related to the great 'msat' purge?

**Comment by m-schmoock** [comment]
@SimonVrouwe 

I mean that the corresponding JSON payload fields (when key ends with `_msat`) are not replaced by the pyln-client wrapper by a `Millosatoshi()` object as they are normally replaced on the fly for normal requests.

This incorrect behaviour only seem to happen on event notifications.

**Comment by m-schmoock** [comment]
@cdecker 
I did a quick fix https://github.com/ElementsProject/lightning/pull/5798/commits/898086be2686165a72b68ad1adf9c4332a6687b9 
How should we address this cleanly?

**Comment by cdecker** [comment]
I briefly mentioned this on discord, so I'll relay that message here:

> I've been thinking about this a bit more, and I think we may need a more principled approach here. pyln by default keeps everything as a python dict matching the JSON structure, BUT we have the msat conversion which jumps out of nowhere.
>
> I'd love for a layering, i.e., keep a low level version of the client that keeps the raw JSON, without any object conversion, and then layer an object layer in top in which we use native python objects generated from the schemas for all messages, not making msat the weird one in the API. The latter gets us more idiomatic code with native property access, and helpers that we can build on top, code completion would work and mypy can do static analysis that we don't get things wrong.
>
> Thinking of pydantic to go from JSON to native python objects btw

However that is more of a longer term solution, that needs brainstorming. I think in order to address this issue specifically we can use something that is already at the top of every plugin:


```python
from pyln.client import Plugin
plugin = Plugin()
```

The solution here could be to add a new argument to the `Plugin` constructor, such as `notification_parse_msat=False`, with `False` as the default value. We then build out the layered solution for a longer term API that we can maintain and should maximize developer ergonomics. We then start warning users about the upcoming deprecation if they use the `notification_parse_msat=False`, after which we wait 2 releases (6 months, normal deprecation cycle), and we remove the parsing from the `JSON -> dict` layer, and use it in the `JSON -> dict -> obj` layer where it makes more sense to have python objects representing an API message.

**Comment by m-schmoock** [comment]
@cdecker Updated the PR...  like this?

Keep in mind with previous versions of pyln this was not an issue and notification `_msat` fields have been replaced in the past correctly, otherwise the plugins that use notifications wouldn't have been build like the way they are now failing. Or is this now only happening because of the msat purge and/or `--deprecated-apis` is now making it behave differently?

I'm not sure if this patch is any help. I still need to go through all plugins and make them compatible by not relying on msat replacement (at least on notifications). Otherwise I need pyln version checks and do both, which is even more ugly.

**Comment by cdecker** [comment]
Excellent, that should work fine, and give devs quite the choice on what to do. We haven't changed anything in the notification delivery and parsing afaik, so it it likely the `--deprecated-apis` hiding the breaking change from the msat purge.

**Comment by m-schmoock** [comment]
> so it is likely the `--deprecated-apis` hiding the breaking change from the msat purge.

Yes that is indeed correct!
I just checked that, when a (plugin) test is run per default it has `--allow-deprecated-apis=False` which makes cln have the `_msat` fields be a plain number. But when operating out in the wild (likely having `--allow-deprecated-apis=True`) it makes `_msat` fields be a string for example `0.1234msat` which crashes, as those strings have never been converted to a `Millisatoshi` on the fly when it comes to event notifications and python cannot do arithmetic operations on a number and a string.

**Comment by rustyrussell** [comment]
I am closing this, since we now output these msat fields as raw integers, which are basically completely compatible with Millisatoshi class.

**Pull request closed without merging**
