### PR TITLE
bitcoind: Relax the check of `initialblockdownload` for compat of spruned

### LINKED ISSUE #3143: lightningd no longer starts when using spruned instead of bitcoind.
When running latest spruned (0.0.10) and latest lightningd (f019dc3d710eb37f42c18962685dbc31ca3e5ba6), lightningd exits soon after startup with this error:

```
$ lightningd 
Invalid 'initialblockdownload' field in getblockchaininfo '{
  "chain": "main",
  "warning": "spruned 0.0.10, emulating bitcoind v0.16",
  "blocks": 598500,
  "headers": 598500,
  "bestblockhash": "00000000000000000002957e1186941dffe9f1c9460c7e93351040aefca8800b",
  "difficulty": 0,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000000000",
  "mediantime": 1570562099,
  "verificationprogress": 0,
  "pruned": false
}
```

An [issue](https://github.com/gdassori/spruned/issues/103) was filed in spruned repo Aug 13 and has received no comments.  Also, latest commit in spruned repo is May 17.   Maybe no longer maintained?

Still, it would be nice to remain compatible.  How necessary is this initialblockdownload field?  Can it safely be ignored if not present?

note this is blocking testing/verification in #2779.

### PR DESCRIPTION
**Pull request by trueptolemy**
Fixed #3143 
TBH, the better way is to let `spruned` add this field.
But it seems that project hasn't update for these months.
Could we make some compromises on that `initialblockdownload` field?

Don't ask for `initialblockdownload` make us can't know if we finishes IBD.
But the check 'headers != blocks', to a certain extent, can help us handle the problem.

### CODE REVIEW

**Comment by trueptolemy** [comment]
Wow, thank you @darosior ! :-)

**Comment by niftynei** [comment]
Since this is a `spruned` error, it's better to get the fix into spruned rather than coding their bug fixes into c-lightning.

**Comment by gdassori** [comment]
Hi, main spruned developer here, thnx for using it.
I agree this is a spruned issue and not a c-lightning one: it's spruned that must comply the bitcoind API.
I wouldn't fix c-lightning for that.
(.. but spruned instead, PR accepted in the repo, I'm quite off the project right now).

**Comment by trueptolemy** [comment]
@gdassori Thank you for your looking at here. :-) 
In favor of https://github.com/gdassori/spruned/pull/106 close this PR.

**Pull request closed without merging**
