### PR TITLE
Onion v2 deprecation

### PR DESCRIPTION
**Pull request by darosior**
This prevents user from setting or connecting to v2 hidden services. This is behind `deprecated_apis` but since they are going to break in a month and a half on the Tor backend we should probably break before?

I still need to update the doc and i wonder if we shoudl do anything about the `node_announcement`.

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
utACK 293a7f84b56ccbd39f8dae6e146647412f896c0d

**Comment by rustyrussell** [comment]
Second commit simply needs:

```
Changelog-Deprecated: lightningd: `enable-autotor-v2-mode` option and v2 Tor addresses.  Use v3.  See https://blog.torproject.org/v2-deprecation-timeline.
```

**Comment by darosior** [comment]
Done, and also updated the doc. `doc/TOR.md` is not really clear so it's really best effort here :/

**Review by rustyrussell — APPROVED** [review]
Ack d9434eaa0d0fc75d01d8c11f49ad05e53af847ad

**Comment by rustyrussell** [comment]
YA trivial rebase for conflicts on generated files

**Pull request merged**
