### PR TITLE
plugins/libplugin-pay.c: Make presplitter less aggressive in general.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Changelog-Changed: pay: Limit presplitting to a smaller number of HTLCs.

EDIT:

Closes #3951

I prefer #3951 over this one.

### CODE REVIEW

**Comment by cdecker** [comment]
Looking at the number of reports of people sening 1'000'000+ satoshis I'm coming around to the idea of changing the presplitter. I still think that there is value in clamping to common shared values, instead of outright clamping to a constant that'd then allow reversing the split.

What do you think about splitting to `2^p * 10,000` where `p` is the smallest power for which the result is above the total amount of the payment and `p % 4 == 0`. Seems weird I know, but this would result in at most 16 parts, and all payments in the range of `[2^(p-4) * 10,000; 2^p * 10,000]` would result in the same amount side per part better hiding the initial amount.

The added advantage is that with the adaptive splitter splitting the amount in half, the post-adaptive splitter amount would then re-align with a lower class of presplits as well.

I think ranges of 1x - 16x are large enough to provide some obfuscation, while not overwhelming channels like our current simple presplitter does. I'm not sure whether keeping the 10,000 coefficient is a good choice or whether we should go powers of two all the way in order to have the presplitter sizes mix with the adaptive splitter sizes, but we can certainly discuss that :-)

**Comment by ZmnSCPxj** [comment]
I would suggest that powers of two would work better.  Maybe the lowest bin could be 8,388,608 msat (2^23) and the next higher bin is 2^27 then 2^31 .  This mixes well with the 2^32 wumbo limit we still currently have, and 8,388,608 is just slightly smaller than your initial 10,000,000 msats bin.

**Comment by ZmnSCPxj** [comment]
Ultimately, the  cost of each HTLC is determined ultimately by onchain fees.  Even `max-concurrent-htlcs` is just a proxy of the cost of each HTLC, as noted by @whitslack in https://github.com/ElementsProject/lightning/pull/3936#issuecomment-673654383 .  So it might do us better to dynamically select a higher starting bin size (fewer splits) if onchain fees are currently high.  Some of the logs from @thestick613 show that some of the errors are not due to `max-concurrent-htlcs` but because of the HTLC addition fee, so any assumptions about `max-concurrent-htlcs` may be invalidated in a high-fee climate.

Another thing to consider would be to do splits in a fibonacci sequence rather than powers of two.  So you might want to initially split by some fibonacci index, and adaptive splitter splits by fibonacci.  This might work better with the expected distribution that there will be some number of channels with high capacity while a majority are low-capacity.  Unless I am now betraying the fact that I am completely not a mathist and spouting nonsense at this point.

**Comment by whitslack** [comment]
> So it might do us better to dynamically select a higher starting bin size (fewer splits) if onchain fees are currently high.

If you do that, then you also need to dynamically scale (down) `max-concurrent-htlcs` if the HTLC fee rate is high. Otherwise, I'm just going to continue setting the minimum allowed `max-concurrent-htlcs` to try to minimize my monetary losses due to malicious/buggy nodes that stop responding with HTLCs in flight.

**Comment by whitslack** [comment]
Seems like it might be more useful to cap the amount of fees that must be paid to unilaterally close a channel rather than capping the number of HTLCs that may concurrently be in flight through each channel.

**Comment by ZmnSCPxj** [comment]
> Seems like it might be more useful to cap the amount of fees that must be paid to unilaterally close a channel rather than capping the number of HTLCs that may concurrently be in flight through each channel.

True, though seems a bit OT here in `pay`-land.  An issue is what happens if there already are HTLCs in-flight, and then a fee spike occurs?  We cannot simply drop an HTLC, so we would just have to prevent future HTLCs but we cannot remove current ones.  Thus it will be at best a soft limit (which might be acceptable).  Further, we can easily set a number-of-HTLCs limit to the peer (because it is already existant in the spec), but adding a limit to the fees would require a spec change; if we are at the limit already and the peer wants to add a new HTLCs, the best we can do is to accept it (thus temporarily going over the limit) and either immediately succeed it (if we are the payee AND it completes an MPP or is a single-part payment)  or just fail it ASAP.

**Pull request closed without merging**
