### PR TITLE
make: add ctags target

### PR DESCRIPTION
**Pull request by jb55**
For us vim users :)

Signed-off-by: William Casarin <jb55@jb55.com>

### CODE REVIEW

**Comment by cdecker** [comment]
Congrats @jb55 on grabbing PR #5000 😉

**Comment by jb55** [comment]
@cdecker oh dang sorry it was so lame lol

**Comment by cdecker** [comment]
No problem, I was waiting for someone to claim it. Next stop: PR #9000 🚀⚡

**Review by rustyrussell — APPROVED** [review]
Ack ed4e8622ac6a33d987f3ded8a21e412b92aa296c

**Pull request merged**
