### PR TITLE
Make human help human friendly

### PR DESCRIPTION
**Pull request by abitfan**
HELLO FELLOW HUMANS!

THE FOLLOWING DISPLAY IS MORE READABLE FOR US HUMANS
PERHAPS DUE TO THE RESSEMBLENCE TO bitcoin-cli help OUTPUT.
CHECK IT OUT!

### CODE REVIEW

**Comment by m-schmoock** [comment]
Capslock is totally uncool. Makes things less humanly readable ;)

**Comment by darosior** [comment]
What is the rationale ? Without line break the help is far less readable..

**Comment by abitfan** [comment]
Generally when one issues help is looking to locate a command (and only after that
the description is of interest).
As it is it wastes a lot of screen space making even more difficult to navigate.
It may be just a matter of personal taste but I even think listing just the 
commands the same way as bitcoin-cli help is preferred for efficiency.

**Comment by rustyrussell** [comment]
Well, if we just printed the synopsis and not a description, it might be OK, but this is a pig's salad.

Though now I look at it, we should put the extra '\n' *before* the section headings, not after!

**Pull request closed without merging**
