### PR TITLE
grpc: generate composite fields

### PR DESCRIPTION
**Pull request by JssDWt**
The grpc api is missing some fields, because composite fields weren't generated. This PR adds this functionality.

Notes:
- I had to update the `tonic` version, because it treated some fields as optional, while they weren't.
- One oddity: The `GrpcConverterGenerator` converts the typename for a pb to camel case (instead of snake case) to reflect the actual struct name. I wasn't sure how else to handle that.
- Please check whether I regenerated all the necessary files.

I didn't get the tests running on my machine yet, so letting the CI do that for me for now.

Changelog-None

### CODE REVIEW

**Comment by JssDWt** [comment]
CI cannot find `protoc`. Is that my fault?

**Comment by cdecker** [comment]
Thanks @JssDWt I took the liberty and split out the dependency updates into #5820 and will rebase this PR on top of that once we get that merged.

**Comment by cdecker** [comment]
Found at least one issue with the generated composites, most likely just not being mapped in the conversion script:

```
error[E0277]: the trait bound `std::option::Option<pb::ConnectAddress>: From<cln_rpc::model::ConnectAddress>` is not satisfied
   --> cln-grpc/src/convert.rs:393:22
    |
393 |             address: c.address.into(),
    |                      ^^^^^^^^^ ---- required by a bound introduced by this call
    |                      |
    |                      the trait `From<cln_rpc::model::ConnectAddress>` is not implemented for `std::option::Option<pb::ConnectAddress>`
    |
    = help: the following other types implement trait `From<T>`:
              <std::option::Option<&'a T> as From<&'a std::option::Option<T>>>
              <std::option::Option<&'a mut T> as From<&'a mut std::option::Option<T>>>
              <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing::span::EnteredSpan>>
              <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing::span::Span>>
              <std::option::Option<&'a tracing_core::span::Id> as From<&'a tracing_core::span::Current>>
              <std::option::Option<&'static tracing_core::metadata::Metadata<'static>> as From<&'a tracing_core::span::Current>>
              <std::option::Option<T> as From<T>>
              <std::option::Option<tracing_core::metadata::Level> as From<tracing_core::metadata::LevelFilter>>
            and 6 others
    = note: required for `cln_rpc::model::ConnectAddress` to implement `Into<std::option::Option<pb::ConnectAddress>>`

error[E0277]: the trait bound `SendonionFirst_hop: From<std::option::Option<SendonionFirstHop>>` is not satisfied
    --> cln-grpc/src/convert.rs:1364:24
     |
1364 |             first_hop: c.first_hop.into(),
     |                        ^^^^^^^^^^^ ---- required by a bound introduced by this call
     |                        |
     |                        the trait `From<std::option::Option<SendonionFirstHop>>` is not implemented for `SendonionFirst_hop`
     |
     = note: required for `std::option::Option<SendonionFirstHop>` to implement `Into<SendonionFirst_hop>`

For more information about this error, try `rustc --explain E0277`.
```

I'll give it a try as soon as I have some time :-)

**Comment by JssDWt** [comment]
@cdecker Odd! That's the reason I updated the tonic version before. I thought that fixed it. Putting back the versions as in my original PR doesn't appear to work either now.

Those fields are optional in the .proto file, while they're supposed to be required.

**Comment by JssDWt** [comment]
Updated `grpc.py` to also convert composites in the `GrpcUnconverterGenerator`

(doesn't fix the required/optional problem in the .proto, but was another issue)

**Comment by JssDWt** [comment]
OK it turns out all proto3 fields are optional. There is no longer a difference between optional and required fields.

That means mapping towards a grpc composite type will always be an optional type and mapping from a grpc composite type will always come from an optional type.

Fixed it in the latest force push.

Please review @cdecker

**Comment by JssDWt** [comment]
Removed trailing whitespaces

**Comment by cdecker** [comment]
> OK it turns out all proto3 fields are optional. There is no longer a difference between optional and required fields.
> 
> That means mapping towards a grpc composite type will always be an optional type and mapping from a grpc composite type will always come from an optional type.
> 
> Fixed it in the latest force push.
> 
> Please review @cdecker  

Haven't looked at the code yet, but one minor thing: optional is being reintroduced in proto3, due to better semantics. With everything optional it is not possible to distinguish a missing fields from one that is set but has the default value. This nullability is important in some languages (C member vs pointer, Rust member vs optional member, etc). So whenever the schema doesn't mention the field in the required list we annotate with the `optional` keyword as it is the most expressive variant.

**Comment by JssDWt** [comment]
Rebased and regenerate the pyln testing files

**Comment by JssDWt** [comment]
> Haven't looked at the code yet, but one minor thing: optional is being reintroduced in proto3, due to better semantics. With everything optional it is not possible to distinguish a missing fields from one that is set but has the default value. This nullability is important in some languages (C member vs pointer, Rust member vs optional member, etc). So whenever the schema doesn't mention the field in the required list we annotate with the `optional` keyword as it is the most expressive variant.

@cdecker I think this only applies for basic types (numeric, string, bytes, and enums) https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md?plain=1#L103

**Comment by cdecker** [comment]
Right, I keep forgetting the different handling between primitives and messages, good catch 👍

**Comment by JssDWt** [comment]
I don't know what I'm doing with the pyln/testing files that have changed.
I tried regenerating them and adding them to the commit, but the import for `primitives_pb2` is generated differently.

It was `from . import primitives_pb2 as primitives__pb2`

When I generate it becomes `import primitives_pb2 as primitives__pb2` and that doesn't work.

So I removed those files again.

**Comment by cdecker** [comment]
I just regenerated the files by removing them altogether and then making them again :-)

ACK https://github.com/ElementsProject/lightning/pull/5801/commits/29e12d095ad4d0fcba8241537aafc7ad2adaebcf

**Comment by JssDWt** [comment]
ACK https://github.com/ElementsProject/lightning/commit/29e12d095ad4d0fcba8241537aafc7ad2adaebcf

**Comment by JssDWt** [comment]
I tested getting the channel alias in the ListPeers call btw. Works!

**Pull request merged**
