### PR TITLE
typo: information is an uncountable mass noun

### PR DESCRIPTION
**Pull request by jsarenik**
See https://en.wikipedia.org/wiki/Information

In libplugin.c also the word "details" was added (without removing
the 'information').

Changelog-None

Discussion welcome.

FYI: @darosior

Nice discussion of the topic is at [Englishforums](https://www.englishforums.com/English/InformationOrInformations/gzdmw/post.htm)

### CODE REVIEW

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/b8583401dec2dc38f6b4c9e26f1e1d58255eff84

**Comment by rustyrussell** [comment]
CI fail is interesting (unrelated ofc). @niftynei ?

test_v2_rbf_multi:
[logs_286.zip](https://github.com/ElementsProject/lightning/files/6138271/logs_286.zip)

```
lightningd-1: 2021-03-14T09:25:28.690Z DEBUG   022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-dualopend-chan#1: peer_in WIRE_TX_SIGNATURES
lightningd-2: 2021-03-14T09:25:28.691Z DEBUG   0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-dualopend-chan#1: peer_in WIRE_TX_SIGNATURES
lightningd-2: 2021-03-14T09:25:28.692Z DEBUG   0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-chan#1: Broadcasting funding tx 6a8c0c59ffd12835e3e5acce6139a1bf400d4a22bf2f72d96450c734cc8486d5 for channel 252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7. 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-2: 2021-03-14T09:25:28.692Z DEBUG   lightningd: sendrawtransaction: 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-2: 2021-03-14T09:25:28.692Z INFO    0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518-chan#1: State changed from DUALOPEND_AWAITING_LOCKIN to DUALOPEND_AWAITING_LOCKIN
lightningd-2: 2021-03-14T09:25:28.694Z DEBUG   plugin-spenderp: mfc ??: `openchannel_peer_sigs` no pending dest found for channel_id UNKNOWN TYPE channel_id
lightningd-1: 2021-03-14T09:25:28.695Z DEBUG   022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: Broadcasting funding tx 6a8c0c59ffd12835e3e5acce6139a1bf400d4a22bf2f72d96450c734cc8486d5 for channel 252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7. 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-1: 2021-03-14T09:25:28.695Z DEBUG   lightningd: sendrawtransaction: 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-1: 2021-03-14T09:25:28.696Z INFO    022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: State changed from DUALOPEND_AWAITING_LOCKIN to DUALOPEND_AWAITING_LOCKIN
lightningd-1: 2021-03-14T09:25:28.699Z DEBUG   plugin-spenderp: mfc ??: `openchannel_peer_sigs` no pending dest found for channel_id UNKNOWN TYPE channel_id
lightningd-1: 2021-03-14T09:25:28.699Z DEBUG   022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-dualopend-chan#1: peer_out WIRE_TX_SIGNATURES
lightningd-1: 2021-03-14T09:25:28.699Z DEBUG   022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: Broadcasting funding tx 6a8c0c59ffd12835e3e5acce6139a1bf400d4a22bf2f72d96450c734cc8486d5 for channel 252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7. 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-1: 2021-03-14T09:25:28.700Z DEBUG   lightningd: sendrawtransaction: 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000
lightningd-1: 2021-03-14T09:25:28.700Z INFO    022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: State changed from DUALOPEND_AWAITING_LOCKIN to DUALOPEND_AWAITING_LOCKIN
lightningd-2: 2021-03-14T09:25:28.716Z DEBUG   plugin-bcli: sendrawtx exit 0 (bitcoin-cli -regtest -datadir=/tmp/ltests-ntu2dev5/test_v2_rbf_multi_1/lightning-2/ -rpcport=33681 -rpcuser=... -rpcpassword=... sendrawtransaction 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000)
lightningd-1: 2021-03-14T09:25:28.727Z DEBUG   plugin-bcli: sendrawtx exit 0 (bitcoin-cli -regtest -datadir=/tmp/ltests-ntu2dev5/test_v2_rbf_multi_1/lightning-1/ -rpcport=33535 -rpcuser=... -rpcpassword=... sendrawtransaction 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000)
lightningd-1: 2021-03-14T09:25:28.728Z DEBUG   wallet: Owning output 1 17570045sat (SEGWIT) txid 6a8c0c59ffd12835e3e5acce6139a1bf400d4a22bf2f72d96450c734cc8486d5
lightningd-1: 2021-03-14T09:25:28.742Z DEBUG   plugin-bcli: sendrawtx exit 27 (bitcoin-cli -regtest -datadir=/tmp/ltests-ntu2dev5/test_v2_rbf_multi_1/lightning-1/ -rpcport=33535 -rpcuser=... -rpcpassword=... sendrawtransaction 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000) error code: -27\nerror message:\nTransaction already in block chain
lightningd-1: 2021-03-14T09:25:28.743Z **BROKEN** 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: No outstanding command for channel 252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7, funding sent was success? 0
lightningd-1: 2021-03-14T09:25:28.743Z UNUSUAL 022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59-chan#1: Error broadcasting funding tx: error code: -27\nerror message:\nTransaction already in block chain. Unsent tx discarded 02000000000101080af3ee29fbf90f0119d219ed548dcb8031f08a0d85f45ecb9f33a56a2a4bbd0100000000fdffffff02400d0300000000002200205b8cd3b914cf67cdd8fa6273c930353dd36476734fbd962102c2df53b90880cdfd180c01000000001600147d08d997dfa9cde39f86863aaf0f82e32cc30c830247304402204ace7ee517f9bf853a583643462513b01e848a15f3b4c6fc20d1d7c0ab9c4e3e0220533ce22ab5e54659e1e0784a6687e76495cfc9c3dd98e93b2c18f592f91b8aa3012103d745445c9362665f22e0d96e9e766f273f3260dea39c8a76bfa05dd2684ddccf66000000.
```

**Review by darosior — APPROVED** [review]
ACK b8583401dec2dc38f6b4c9e26f1e1d58255eff84

Thanks! The french 'information' can be conjugated so i tend to often make this mistake :)

**Comment by niftynei** [comment]
> CI fail is interesting (unrelated ofc). @niftynei ?

Racy bug here. If a node calls `openchannel_signed` at the same time that they receive the `tx_signatures` message from the peer, there's a loop through `dualopend` on our sending of the tx-sigs side that makes it possible we'll call the broadcast code twice. On return, the broadcast code resolves the `cmd` that originated with `openchannel_signed`; if we hit the broadcast code twice the second time through we log a warning because no `cmd` was found on termination. Whoops.

**Pull request merged**
