### PR TITLE
Hacking update

### PR DESCRIPTION
**Pull request by rustyrussell**
This needs more fleshing out, but I'd really like guidance from @ZmnSCPxj  and @practicalswift who've had the experience of diving in recently.

What have I missed?  I think it's probably way too short...

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Rather than punting on the description of `take`, maybe describe it instead?

> `take()` marks a pointer as to be consumed (i.e. freed automatically before return) by a called function. It can safely accept `NULL` pointers. Functions whose prototype in headers has the macro `TAKES` can have the specific argument as a `take()` call.

You might want to mention that one daemon specifically uses non async io to simplify state transitions.

**Comment by rustyrussell** [comment]
Done... @ZmnSCPxj @practicalswift @jb55 any other suggestions?

I plan on adding much more detailed description to the main file of each daemon, too, but this is just a kind of overview on where to start looking.

**Comment by ZmnSCPxj** [comment]
`tal` and `take`are different enough from typical C manual management that they should be described, but the HACKING.md file gives good enough pointers to those. Those are the main gotchas with the code for me.

**Comment by jb55** [comment]
Rusty Russell <notifications@github.com> writes:
> Done... @ZmnSCPxj @practicalswift @jb55 any other suggestions?

Looks good to me, I'll try to think about things for this document as I hack
around. The only other gotcha I've run into is sometimes make clean
doesn't clean well enough. I get into states that I can't seem to
recover from. I've had to nuke the project twice. That's more of a
separate issue instead of something worth documenting though.

**Comment by practicalswift** [comment]
@rustyrussell LGTM! :-)

**Comment by cdecker** [comment]
ACK 27b082e759ed59356c9445b33596b9c14045cd38

**Comment by practicalswift** [comment]
I'll echo @jb55:s comment about the `make clean`-not-as-clean-as-expected gotcha. I think that could be a source of confusion for new contributors.

The source of confusion could be a combination of the following factors:
* The auto-generation of `.c`-files from CSV-files creates `.c`-files not under version controls. Changes to these files are thus invisible to `git diff` despite being changes.
* Quite a lot of files in `.gitignore` that are invisible to `git diff` and `git status`.
* The use of git submodules can be a source of confusion. More specifically I think developers new to git submodules might get confused how to revert back to a clean `master` checkout after touching files in the submodules. (This is not specific to this project.)

**Comment by jb55** [comment]
I put together #538 to automatically configure the coding style for emacs users

**Comment by rustyrussell** [comment]
OK, I've applied for now.

The 'make clean' doesn't clean should be addressed separately: if it happens again, tar (sorry, zip, no tar files on github) up the dir and file a bug?

I've already had to add some extra magic to clean the submodules.  Maybe more is needed?

**Pull request merged**
