### PR TITLE
fix markdown link where text and url are swapped

### PR DESCRIPTION
**Pull request by greggzigler**

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Ack 68b4e4fcf063b6b5502ccdfb6afd1ab19343ebfc

**Comment by greggzigler** [comment]
> Ack [68b4e4f](https://github.com/ElementsProject/lightning/commit/68b4e4fcf063b6b5502ccdfb6afd1ab19343ebfc)

This is my first PR, so I have a couple basic questions:

1) What does it mean when one commit is approved but the other one isn't? Does it mean I should close this PR and create a new one with only the approved changes?

2) Why would the Build fail when I only changed markdown files? And should I (somehow) re-trigger the build?

**Comment by vincenzopalazzo** [comment]
>Why would the Build fail when I only changed markdown files? And should I (somehow) re-trigger the build?

It is just a flaky test that the team is trying to solve step by step, you do not need to worry about that if the failure is unrelated

**Comment by greggzigler** [comment]
> It is just a flaky test that the team is trying to solve step by step, you do not need to worry about that if the failure is unrelated

Great. And what about my other question? Is there something wrong in the first (unapproved) commit?

**Comment by rustyrussell** [comment]
> > Ack [68b4e4f](https://github.com/ElementsProject/lightning/commit/68b4e4fcf063b6b5502ccdfb6afd1ab19343ebfc)
> 
> Thanks! This is my first PR, so I have a couple basic questions:
> 
>     1. What does it mean when one commit is approved but the other one isn't? Does it mean I should close this PR and create a new one with only the approved changes?

Approving the final one implies approval of the previous ones too (git is a blockchain!), so you're good.

Though I may squash them into one commit to apply them.

 

> 
>     2. Why would the Build fail when I only changed markdown files? And should I (somehow) re-trigger the build?

**Pull request merged**
