### PR TITLE
fixup clang error for update-mocks?

### PR DESCRIPTION
**Pull request by niftynei**
test for #3226

pinging @willcl-ark for review

### CODE REVIEW

**Comment by willcl-ark** [comment]
@niftynei This appears to be working well now on MacOS 10.15 with Apple clang version 11.0.3 (clang-1103.0.32.29). Thanks!

[configure.txt](https://github.com/ElementsProject/lightning/files/4704501/configure.txt)
[make.txt](https://github.com/ElementsProject/lightning/files/4704502/make.txt)

**Comment by willcl-ark** [comment]
Not sure what the force push was, but compiles nicely still on 5e8906317733011fe4a4853ea7a7221121b4b9d1. 

I get some `make pytest` errors, but I think I get them on master too, so will open a new issue after a little troubleshooting...

**Comment by niftynei** [comment]
The force push was to update a commit message :t-rex:

**Comment by cdecker** [comment]
Restarted CI since it hit a flake.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/commit/5e8906317733011fe4a4853ea7a7221121b4b9d1

**Pull request merged**
