### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by cdecker**
Includes the @dependabot fixes from #4160 and #4161 as well as some minor cleanups.

### CODE REVIEW

**Comment by jsarenik** [comment]
```diff
diff --git a/contrib/pyln-proto/pyln/proto/primitives.py b/contrib/pyln-proto/pyln/proto/primitives.py
index 1b37f1423..418f52212 100644
--- a/contrib/pyln-proto/pyln/proto/primitives.py
+++ b/contrib/pyln-proto/pyln/proto/primitives.py
@@ -14,6 +14,7 @@ def compactsize_encode(i, w):
     else:
         w.write(struct.pack("!BQ", 0xFF, i))
 
+
 def compactsize_decode(r):
     """Decode an integer from reader `r`
     """
```

**Comment by jsarenik** [comment]
But even with above-mentioned patch, I get another error:

```
$ make check-cppcheck
common/test/run-features.c:185:36: error: Uninitialized variable: f1 [uninitvar]
 for (size_t i = 0; i < ARRAY_SIZE(f1->bits); i++) {
                                   ^
common/test/run-features.c:217:36: error: Uninitialized variable: f [uninitvar]
 for (size_t i = 0; i < ARRAY_SIZE(f->bits); i++) {
                                   ^
make: *** [Makefile:462: check-cppcheck] Error 123
```

Do you use any particular `.cppcheck-suppress`?

**Comment by jsarenik** [comment]
Adding the previously-deleted cppcheck error here again. Now even on latest `cppcheck`. The same. How should one run cppcheck? Or did this find a real error? It is already on `master` branch.

```
$ cppcheck --version
Cppcheck 2.2
$ make check-cppcheck
common/test/run-features.c:185:36: error: Uninitialized variable: f1 [uninitvar]
 for (size_t i = 0; i < ARRAY_SIZE(f1->bits); i++) {
                                   ^
common/test/run-features.c:217:36: error: Uninitialized variable: f [uninitvar]
 for (size_t i = 0; i < ARRAY_SIZE(f->bits); i++) {
                                   ^
make: *** [Makefile:462: check-cppcheck] Error 123
```

**Comment by jsarenik** [comment]
For above-mentioned unrelated `cppcheck` error there is a new issue https://github.com/ElementsProject/lightning/issues/4167

**Comment by cdecker** [comment]
> Adding the previously-deleted cppcheck error here again. Now even on latest `cppcheck`. The same. How should one run cppcheck? Or did this find a real error? It is already on `master` branch.
> 
> ```
> $ cppcheck --version
> Cppcheck 2.2
> $ make check-cppcheck
> common/test/run-features.c:185:36: error: Uninitialized variable: f1 [uninitvar]
>  for (size_t i = 0; i < ARRAY_SIZE(f1->bits); i++) {
>                                    ^
> common/test/run-features.c:217:36: error: Uninitialized variable: f [uninitvar]
>  for (size_t i = 0; i < ARRAY_SIZE(f->bits); i++) {
>                                    ^
> make: *** [Makefile:462: check-cppcheck] Error 123
> ```

I have no idea why it's complaining about this file now, and not before, since I didn't touch that file :-)

**Comment by cdecker** [comment]
Thansk @jsarenik for checking this PR so quickly, I should check for answers more often :-)

I fixed up the python lint you pointed out :+1:

**Comment by jsarenik** [comment]
ACK cd024fbd7

Also tested locally

**Comment by jsarenik** [comment]
Of course https://github.com/ElementsProject/lightning/issues/4167 fails locally. Funny that it does not fail on Travis.

**Pull request merged**
