### PR TITLE
gossipd: catch zombie node when the last channel is a normal close

### PR DESCRIPTION
**Pull request by endothermicdev**
As reported by @vincenzopalazzo, the node_announcement was left in the gossip_store though all channels had been closed and the node deleted from gossmap.  This was caused by a node having zombie channels, but the last channel was closed normally without checking if the node should now get zombie status (which would make the node_announcement invisible to gossmap.)

Changelog-None

### CODE REVIEW

**Comment by rustyrussell** [comment]
This can't be right: if we hit this path, node_announcement would have been deleted?

**Comment by rustyrussell** [comment]
I think this is wrong, but there is a real problem in the "move if predating" logic.  Unfortunately, I don't see how that could have caused this issue:

```diff
diff --git a/gossipd/routing.c b/gossipd/routing.c
index fb54eefe6..a0c6583b2 100644
--- a/gossipd/routing.c
+++ b/gossipd/routing.c
@@ -440,6 +440,10 @@ static bool node_announce_predates_channels(const struct node *node)
 		if (!is_chan_public(c))
 			continue;
 
+		/* Zombies don't count! */
+		if (is_chan_zombie(c))
+			continue;
+
 		if (c->bcast.index < node->bcast.index)
 			return false;
 	}
```

**Comment by rustyrussell** [comment]
OK, so I thought, what if we're accepting a node_announcement when we're not supposed to?  This test looks really weird to me, tried fixing it:

```diff
diff --git a/gossipd/routing.c b/gossipd/routing.c
index fb54eefe6..fc42cff94 100644
--- a/gossipd/routing.c
+++ b/gossipd/routing.c
@@ -1811,9 +1815,7 @@ bool routing_add_node_announcement(struct routing_state *rstate,
 	}
 
 	node = get_node(rstate, &node_id);
-
-	if (node == NULL || (!node_has_broadcastable_channels(node) &&
-	    !is_node_zombie(node))) {
+	if (node == NULL || is_node_zombie(node)) {
 		struct pending_node_announce *pna;
 		/* BOLT #7:
 		 *
```

**Comment by endothermicdev** [comment]
> Unfortunately, I don't see how that could have caused this issue

The node announcement got a zombie flag (the node had at least two zombie channels), then the oldest channel is closed and the node announcement was rewritten.  Rewriting (`force_node_announce_rexmit`) loses the zombie bit(!), so gossmap now sees it despite the only remaining channels being hidden due to zombie status.

That sounds plausible to me.  I think `force_node_announce_rexmit` should respect the existing zombie bit/status.  That way the gossip store remains properly ordered, even if we're only dealing with zombie channel/node messages.  I just overlooked that the node announcement can be rewritten to the store here.

**Comment by endothermicdev** [comment]
Closed in favor of #6013 which eliminates the handling of the zombie node `node_announcement` and keeps a cleaner gossip store.

**Pull request closed without merging**
