### PR TITLE
bugfix: fix uninitialized variable compiler errors

### PR DESCRIPTION
**Pull request by benthecarman**
Was unable to build the project without doing this

### CODE REVIEW

**Comment by benthecarman** [comment]
I am on the most recent version of gcc and still unable to build.  I get errors saying this
```
ccan/ccan/tal/path/path.c: In function ‘path_readlink’:
ccan/ccan/tal/path/path.c:325:6: error: ‘len’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   ret[len] = '\0';
cc1: all warnings being treated as errors
Makefile:586: recipe for target 'ccan-tal-path.o' failed

```

**Comment by rustyrussell** [comment]
What gcc version, what optimization flags, are you using --enable-developer? Was this a clean build?

We are supposed to ignore those warnings when using anything other than -O3 or no optimization at all...

**Comment by benthecarman** [comment]
`gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

I am just pulling the repo and then using `make`

**Comment by rustyrussell** [comment]
> `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
> 
> I am just pulling the repo and then using `make`

Well, you must have run `configure` at some stage, so my guess is you have old warning flags in there.

Try running './configure' again?

**Comment by benthecarman** [comment]
> Try running './configure' again?

Oh wow I am just an idiot, that fixed it. Normally I don't need to do that.

**Pull request closed without merging**
