### PR TITLE
sphinx-doc: Fix small typo

### PR DESCRIPTION
**Pull request by romanz**

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK ae3aefacd54d8291914123d6dee4b05a5f4bc5cd

Nice find! :-)

**Comment by rustyrussell** [comment]
This had me deeply confused until I realized that it's against the sphinx-doc branch, which @cdecker  seems to have created?

**Comment by cdecker** [comment]
Yep, sorry about the confusion, I wanted to make sure this is up to date before including it in the `master` branch, on the other hand not having it in master means that we will never get there. Would you prefer just merging it in and going from there?

**Comment by cdecker** [comment]
Spell checker complaint was addressed in 545745d5e825afb05067b92fc9f715476729ddc0

ACK ae3aefa

**Comment by practicalswift** [comment]
@cdecker I vote for merging `sphinx-doc` in `master` :-)

**Pull request merged**
