### PR TITLE
docs: openchannel_abort correction

### PR DESCRIPTION
**Pull request by king-11**
> [!IMPORTANT]
> Open for merging new PRs until the next PR freeze date is confirmed!

## Checklist
Before submitting the PR, ensure the following tasks are completed. If an item is not applicable to your PR, please mark it as checked:

- [ ] The changelog has been updated in the relevant commit(s) according to the [guidelines](https://docs.corelightning.org/docs/coding-style-guidelines#changelog-entries-in-commit-messages).
- [ ] Tests have been added or modified to reflect the changes.
- [x] Documentation has been reviewed and updated as needed.
- [ ] Related issues have been listed and linked, including any that this PR closes.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7762/commits/d9dd5011b7c9abb02995911ecc6986e2c10214a5

**Comment by vincenzopalazzo** [comment]
Oh wait, we need to add `Changelog-None` inside the commit message like in vls

**Comment by vincenzopalazzo** [comment]
Mh this PR should not be automatically merged, looks like that the disable button in the auto-merge is not working as expected?

I remember that I disable the merge when I noted https://github.com/ElementsProject/lightning/pull/7762#issuecomment-2433295832

**Comment by king-11** [comment]
I think that was too late by the time they triggered the operation I was confused how to change now.

**Comment by vincenzopalazzo** [comment]
>I think that was too late by the time they triggered the operation I was confused how to change now.

In theory the bot should not merge it if the CI fails

**Pull request merged**
