### PR TITLE
Compulsory modern features, and open-by-channel-type APIs

### PR DESCRIPTION
**Pull request by rustyrussell**
I thought we made static_remotekey, gossip_queries and dataloss_protect required already, but we didn't.  However, we still need to handle old channels without static_remotekey, which lead me to finally implement the open-by-channel-type explicit API.

### CODE REVIEW

**Comment by rustyrussell** [comment]
@cdecker this broke the GRPC generation, and I cannot figure out why :(


I note that `channel_types` is missing from GRPC for the existing `listpeerchannels` return; seems patched out (which seems wrong!), but doing the same for Fundchannel does not seem to work.  Here's the error:

```
node.proto:1597:18: "FundchannelChannel_typeNames" is not defined.
make: *** [Makefile:385: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Error 1
```

**Comment by cdecker** [comment]
Ok, so it turns out that `msggen` does not correctly handle arrays of enum values. Since this is the only time we used them, I just overrode it for this type, since it is likely we'll want to reuse the type somewhere else too (`listpeerchannels`, etc), and from that point of view it's very similar to `HtlcState` which is also manually managed.

The longer term solution for this would be to have a protobuf-like IDL that allows us to specify the API as a flat namespace of messages that may nest each other, and then generate the JSON Schema from that. That'd also remove the need for unreadable, context-related, names such as `FundchannelChannel_typeNames` which technically reflects the `jq` path `fundchannel.channel_type.names[]`, and is generated from the full path to be unique.

**Comment by cdecker** [comment]
Fixed a couple of source lints, and added the missing enum, as well as the override.
Please force-pull before making changes, otherwise my changes will get lost :-)

**Comment by rustyrussell** [comment]
Note that this needs https://github.com/rustyrussell/lnprototest/pull/115 so I've changed the upstream for lnprototest temporarily!

**Pull request merged**
