### PR TITLE
msggen: add getlog method

### PR DESCRIPTION
**Pull request by daywalker90**
Based on the fixes from #7215 + #7217 + #7218 and #7230

### CODE REVIEW

**Comment by daywalker90** [comment]
rebased on master

**Review by cdecker — APPROVED** [review]
ACK 4bda2232a3a9a863d7c6ee19795986c7e5030e5c

**Comment by daywalker90** [comment]
rebased on master

**Comment by cdecker** [comment]
Queued up behind #7233

**Pull request closed without merging**
