### PR TITLE
pyln_client: (re-)adds method description to usage via docstring

### PR DESCRIPTION
**Pull request by m-schmoock**
The extended usage information (long_description) has been removed a while ago without proper replacement. ( commit 2ff3e55f0  Date:   Mon Jul 29 17:58:43 2024 -0700 )

# This PR does the following:
 - adds a optional `description` parameter to a plugin method via docstring that will (if set) be appended with a newline following the generated usage argument list.
 - adds method usage to plugin.print_usage()
 - adds a testcase that checks if extended usage information is passed to manifest json and `print_usage`
 
 # Things to think about
 - Maybe we want to add an optional getmanifest json description field and use that instead of internally appending it with newline to the usage

### CODE REVIEW

**Comment by m-schmoock** [comment]
@cdecker Another option would be to reintroduce the `description` as a separate decorator to the method but do the same internal handling (appending to usage and passing to manifest json). Maybe that looks nicer in plugin code

**Comment by rustyrussell** [comment]
We had to fix it quickly for the release, BUT the correct answer is to use the docstring!  We already introspect, so accessing __doc__ is easy (which always exists, but is None for no doc string).

**Comment by m-schmoock** [comment]
> We had to fix it quickly for the release, BUT the correct answer is to use the docstring! We already introspect, so accessing **doc** is easy (which always exists, but is None for no doc string).

Thanks for the clarification. I have been away from the project for a while as you know ;)

I rewrote the PR to use python docstring  __doc__ (if set) as the description.

**Comment by m-schmoock** [comment]
We may want to extend the JSON schema to have the description as a separate field (and not internally concatenated to the usage). What do you think?

**Comment by rustyrussell** [comment]
Trivial rebase!

**Pull request merged**
