### PR TITLE
Dont ignore first scid for sendpay, sendonion

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes: #5504 

@niftynei Note new Changelog entries!!

### CODE REVIEW

**Review by nepet — APPROVED** [review]
Ack a935d2a07891b3f089ad7f9fd7b48db7f2735ff9

**Comment by rustyrussell** [comment]
I reverted the fix to the sendonion request schema, as that broke the rust stuff...

**Comment by nepet** [comment]
Ok, maybe I was too fast before but still, the changes on pay seem good and ci seems to be happy now, so again: Ack 566ef5709d709ca5fee5f30802de1bc09b062585

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5505/commits/566ef5709d709ca5fee5f30802de1bc09b062585

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5505/commits/566ef5709d709ca5fee5f30802de1bc09b062585

**Pull request merged**
