### PR TITLE
doc: channel_state_changed has a timestamp field

### PR DESCRIPTION
**Pull request by tony-voltage**

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
This is hard to keep updated!

ACK https://github.com/ElementsProject/lightning/pull/5877/commits/620e5d09627722bda0c91fe79a33e9041e757a88

**Comment by SimonVrouwe** [comment]
Please indicate this is a documentation change by prepending "doc: " to the title

**Comment by m-schmoock** [comment]
> Please indicate this is a documentation change by prepending "doc: " to the title

@SimonVrouwe I changed the title for you, though I bet you meant the commit message :)

**Comment by m-schmoock** [comment]
... also did that commit message `doc: ...`, seems im able to push into PRs remotes :D

**Comment by m-schmoock** [comment]
ACK e2e0a6a3e69f76e88419cf6e9c7506479333d5e9

**Pull request merged**
