### PR TITLE
CI and flake fixes

### PR DESCRIPTION
**Pull request by rustyrussell**
There are more flakes, but we have enough disparate ones now that *something* randomly failing is the norm.

I'll merge this ASAP so others can rebase,  then open another PR to find more flakes...

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6316/commits/2123a057ac9ad37dfc36f003974bf8238de842f2

**Comment by rustyrussell** [comment]
> ACK [2123a05](https://github.com/ElementsProject/lightning/commit/2123a057ac9ad37dfc36f003974bf8238de842f2)
> 
> For ASan builds, I generally observed that they ran faster than Valgrind in CI. I wonder what's different for `test_feerate_stress`.

I finally looked.  That test takes less than two minutes.  The race is actually in disconnect: if we call disconnect just as the peer is (re) connecting, we hang.  This was from an earlier attempt to fix a race, which we ended up fixing properly.

**Comment by morehouse** [comment]
> I finally looked. That test takes less than two minutes. The race is actually in disconnect: if we call disconnect just as the peer is (re) connecting, we hang. This was from an earlier attempt to fix a race, which we ended up fixing properly.

So it looks like [ceb79ac](https://github.com/ElementsProject/lightning/pull/6316/commits/ceb79acdb9dab55b8ff1aa955ee348e538c0cf72) is the intended fix.  If so, we can probably drop [2123a05](https://github.com/ElementsProject/lightning/pull/6316/commits/2123a057ac9ad37dfc36f003974bf8238de842f2).

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6316/commits/7dfc5345fd9be8a2017f7acf96516b7a4d176f27

**Comment by rustyrussell** [comment]
> > I finally looked. That test takes less than two minutes. The race is actually in disconnect: if we call disconnect just as the peer is (re) connecting, we hang. This was from an earlier attempt to fix a race, which we ended up fixing properly.
> 
> So it looks like [ceb79ac](https://github.com/ElementsProject/lightning/pull/6316/commits/ceb79acdb9dab55b8ff1aa955ee348e538c0cf72) is the intended fix. If so, we can probably drop [2123a05](https://github.com/ElementsProject/lightning/pull/6316/commits/2123a057ac9ad37dfc36f003974bf8238de842f2).

Erk, looks like the "give ASAN longer" part of that commit *is* required, so only a partial revert.

**Pull request merged**
