### PR TITLE
MOAR CHECK POWER!

### PR DESCRIPTION
**Pull request by rustyrussell**
Ok, this lets plugins support `check` on their commands, and also lets `setconfig` support check.  Previously these would always trivially "pass", now they actually check.

autoclean is upgraded to improve setconfig, but the funder stuff would be a good candidate for dynamic settings too....

Someone should open some Good First Issue things to add setconfig to make more variables dynamic!

### CODE REVIEW

**Comment by devrandom** [comment]
> Here's what we have defined for `HsmdDevPreinit` on the VLS side

moving our new fields to TLVs sounds good to me, and I don't feel there's a need to maintain backwards compat.

**Comment by devrandom** [comment]
BTW, I don't think there will be a need for VLS to synchronize the TLVs we understand with CLN, as long as we make sure types IDs are odd.

**Comment by ksedgwic** [comment]
@rustyrussell I think that puts the ball squarely in our court to figure out the TLV parsing, unless I'm missing something we can work with exactly what you have.

**Comment by endothermicdev** [comment]
Any more feedback on the hsm preinit tlvs @ksedgwic? This works on your end?

**Comment by ksedgwic** [comment]
@endothermicdev Apologies for the delay ... hsm preinit tlvs are in good shape on the VLS side

**Pull request merged**
