### PR TITLE
build-release.sh: fix zipfile determinism.

### PR DESCRIPTION
**Pull request by rustyrussell**
Please test by checking out this commit and doing:

    ./tools/build-release.sh --force-version=v0.7.0rc2 --force-mtime=2019-02-23 zipfile

The resulting `release/clightning-v0.7.0rc2.zip` should have sha256sum ~`d5842ca0e3f38ccaf3a16db5ac92af78c3b482bb43a6c57258876c0d666803f9`~

    3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip

### CODE REVIEW

**Comment by cdecker** [comment]
```
$ sha256sum release/clightning-v0.7.0rc2.zip
2a368932dc0f510a698108d210678d6843b5d02bff342db7cd48d02fbe1dbbb9  release/clightning-v0.7.0rc2.zip
```
[clightning-v0.7.0rc2.zip](https://github.com/ElementsProject/lightning/files/2898188/clightning-v0.7.0rc2.zip)

**Comment by rustyrussell** [comment]
Gah, can you attach please so I can debug and/or cry?

**Comment by rustyrussell** [comment]
umask, you old scoundrel!

**Comment by yaraaer** [comment]
Raspbian 9:
$ sha256sum release/clightning-v0.7.0rc2.zip
3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip

**Comment by wythe** [comment]
```
> sha256sum release/clightning-v0.7.0rc2.zip 
3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip
```

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2397/commits/6f124e220bbaea618f0fa2b11910fbe386fbc25d
```
lightning$ sha256sum release/clightning-v0.7.0rc2.zip
3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip
```

**Comment by cdecker** [comment]
```bash
$ sha256sum release/clightning-v0.7.0rc2.zip                                                                                                                                                                                             
3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip
```

**Comment by jb55** [comment]
$ sha256sum release/clightning-v0.7.0rc2.zip
    3885991850576daef7844ef53b265593304f9486c13c8b55db914cb6b33397d4  release/clightning-v0.7.0rc2.zip

awesome!

**Comment by rustyrussell** [comment]
Thank you *so much* for testing this! @jb55 @wythe @yayaaer @cdecker @niftynei

**Pull request merged**
