### PR TITLE
doc: fix wording for fundchannel_complete

### PR DESCRIPTION
**Pull request by meeDamian**
As per https://github.com/ElementsProject/lightning/issues/2983#issuecomment-523354987.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Also better to wait for #2936 also, as that changes the format of the manpages from Asciidoc to Markdown.

**Comment by ZmnSCPxj** [comment]
Hi @meeDamian, can you remake the commit to change the `.md` file now, as well as add verbiage like "This is a low-level command and incorrect usage can lead to permanently unrecoverable irrevocably irreversible loss of funds." or some such.

**Comment by meeDamian** [comment]
Rebased to the new format, and added likely-loss-of-funds notes in both commands.

**Comment by ZmnSCPxj** [comment]
ACK  985e4cb

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2984/commits/985e4cb8be86215f43656e538d732ba2469de6ee

**Pull request merged**
