### PR TITLE
doc: regenerate and update.

### PR DESCRIPTION
**Pull request by rustyrussell**
My node tried to rebuild one of them because it was lagging (I noticed
because mrkd was not installed).

Turns out a few were lagging, and lightning-dev-sendcustommsg.7 was totally
empty!

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
For some unknown reason it's not letting me merge this. I'll kick travis again and see if that changes things.

**Comment by ZmnSCPxj** [comment]
Seems like travis filesystem is unstable, and binaries go missing or suddenly become unexecutable...

**Comment by ZmnSCPxj** [comment]
Well Travis is now passing but "This branch cannot be rebased safely".  Sigh.

**Comment by ZmnSCPxj** [comment]
ACK d7eb8fe

Re-acking

**Pull request merged**
