### PR TITLE
[rc2 bugfix] wallet: correct CSV check in `deep_enough`

### PR DESCRIPTION
**Pull request by darosior**
I tried to fund a channel with all my coins, but one was marked in db as having a CSV (but it's a p2wpkh!!) which made it mistakenly unvailable.

### CODE REVIEW

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
LGTM https://github.com/ElementsProject/lightning/pull/4703/commits/a635f9361df59b28dff153e670908c599f11ea46

The only change that we need is to push in the patch also the autogenerate files.

Good catch 😄

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4703/commits/be779a57f806a0e4f00fcfb3795bae4d9f8f21ae

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4703/commits/be779a57f806a0e4f00fcfb3795bae4d9f8f21ae

**Comment by niftynei** [comment]
fixes #4697

ACK be779a5

**Pull request merged**
