### PR TITLE
Fix BUILD_ASSERT failure in wireaddr_to_sockname

### PR DESCRIPTION
**Pull request by isghe**
Fix BUILD_ASSERT failure on macOS, introduced in https://github.com/ElementsProject/lightning/commit/6b2282fc1dd9f09cf238340d9e1daa9de424b098

Fixes: #1478

### CODE REVIEW

**Comment by isghe** [comment]
@rustyrussell take care, the only relevant commit is the last, there is only one file changed, only the modification of the function `wireaddr_to_sockname`

**Comment by rustyrussell** [comment]
Yep, I'll force-push a rebase, which will make it clearer...

**Comment by rustyrussell** [comment]
Does that work for you?  If so, I'll commit once CI is happy!

Thanks!
Rusty.

**Comment by isghe** [comment]
yes, it sounds ok. thanks :-)

**Comment by isghe** [comment]
Perfect, it's ok :-)

**Comment by ZmnSCPxj** [comment]
ACK 4baae3a67394ed3d4a60e8884d06fe399666b43f

**Pull request merged**
