### PR TITLE
Wait for bitcoind if it's gone backwards, don't abort.

### PR DESCRIPTION
**Pull request by rustyrussell**
@ShahanaFarooqui and I spent about 2-3 hours trying to fix this, but the code was fragile and we kept breaking existing cases.

So instead, I started by reworking the code to make it simple, then I change it.  The result is much neater, and will serve us well for any future changes.

Fixes: https://github.com/ElementsProject/lightning/issues/6924

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Mh What is the main reason that makes https://github.com/ElementsProject/lightning/issues/6924 difficult to implement with the current mainline?

I do this in [folgore](https://github.com/coffee-tools/folgore) all the time by using `last_height` given by the getchaininfo RPC In https://github.com/ElementsProject/lightning/issues/6924 and blocking till the `bitcoind` is not fully sync.

Do you think that we need all this pile of change while we are under `rc`?

**Comment by rustyrussell** [comment]
> Mh What is the main reason that makes #6924 difficult to implement with the current mainline?

The code is ridiculously fragile.  As I said, every time we tried, we broke something else.

> I do this in [folgore](https://github.com/coffee-tools/folgore) all the time by using `last_height` given by the getchaininfo RPC In #6924 and blocking till the `bitcoind` is not fully sync.

That only works because we do not time you out, but it's silly: we should handle this internally.

> Do you think that we need all this pile of change while we are under `rc`?

No, that's why it's set to 24.08 milestone?

**Comment by vincenzopalazzo** [comment]
>That only works because we do not time you out, but it's silly: we should handle this internally.

I agree

>No, that's why it's set to 24.08 milestone?

Ah sorry I read it wrong!

**Comment by ShahanaFarooqui** [comment]
ACK b5b834a37b003b56a1b1028568638d3b859dfd98

**Review by ShahanaFarooqui — APPROVED** [review]
LGTM.

**Pull request merged**
