### PR TITLE
A fuzz target for `libhsmd` message handling and some bugfixes

### PR DESCRIPTION
**Pull request by darosior**
The work on libhsmd in #4497 made it simpler to fuzz the message handling of `hsmd`. This adds a simple target to test that `hsmd` is not going to crash even if sent (smartly malleated) garbage. This uncovered a few missing NULL checks in our fromwire routines.

I'm opening this as draft, and will open another PR for the bugfixes as i spent the last days tracking down a segfault in `wally_tx_from_bytes` and i won't be able to continue.
I was also planning to generate some seeds by (ab)using the functional tests but i couldn't even get to there yet.

### CODE REVIEW

**Comment by cdecker** [comment]
> I'm opening this as draft, and will open another PR for the bugfixes as i spent the last days tracking down a segfault in `wally_tx_from_bytes` and i won't be able to continue.

Currently also looking into this, as it crashes one of my toy examples whenever calling `fundchannel`. I wrote this tiny test to reproduce:

```python
from libhsmd import init as libhsmd_init, handle as libhsmd_handle


def test_fundchannel():
        secret = '9f5a9ba98d7e816eebf496db2ff760dc17a4a2f0ae5a87c37cab4bbf6ee05530'
        network = 'testnet'
        msg = '00130200000001f25c0c5f21c46ed3f1063a9a41a489ed4e6bb2c18ef1998eb6618198b17137f90000000000666a6c8001e985010000000000160014f4d3100ee3828a602cbc47b1d70ac204e3342081f06a98200000012d70736274ff0100520200000001f25c0c5f21c46ed3f1063a9a41a489ed4e6bb2c18ef1998eb6618198b17137f90000000000666a6c8001e985010000000000160014f4d3100ee3828a602cbc47b1d70ac204e3342081f06a98200001012ba086010000000000220020cc2ef6e3d8102826a2167b463a77bfaf5b57c1ec24c52115d3c471320ad475720105475221026ecfe4d4dd089bbadcf19c860580dae91b2752261269c1f770f32f80e80680492102df1c73d6d45af5edac96953e0eaae5677411b46791092b4bef2c59648b83c20c52ae220602df1c73d6d45af5edac96953e0eaae5677411b46791092b4bef2c59648b83c20c0841c77c75000000002206026ecfe4d4dd089bbadcf19c860580dae91b2752261269c1f770f32f80e806804908109206e600000000000002df1c73d6d45af5edac96953e0eaae5677411b46791092b4bef2c59648b83c20c039c7fa80e43780ad63af6df575924b4c9ae3f1ad22f74067c28227fb45817b2e301'

        res = libhsmd_init(secret, network)
        print(res)
        capabilities = 24
        dbid = 1
        node_id = "02312627fdf07fbdd7e5ddb136611bdde9b00d26821d14d94891395452f67af248"
        libhsmd_handle(capabilities, dbid, node_id, msg)
```

Then using `gdb` we can dive into the error:

```
$ gdb python3
> r /home/cdecker/dev/lightning/.direnv/python-3.6.12/bin/pytest test_libhsmd.py

test_libhsmd.py
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3970ea5 in list_del_ (n=<optimized out>, abortstr=<optimized out>) at src/ccan/ccan/list/list.h:327
327     src/ccan/ccan/list/list.h: No such file or directory.
(gdb) bt
#0  0x00007ffff3970ea5 in list_del_ (n=<optimized out>, abortstr=<optimized out>) at src/ccan/ccan/list/list.h:327
#1  tal_steal_ (new_parent=0xce8388, ctx=0xde10c0) at src/ccan/ccan/tal/tal.c:501
#2  0x00007ffff39691bf in pull_wtx (ctx=0xce8388, cursor=0x7fffffff5c68, max=0x7fffffff5c60) at src/bitcoin/tx.c:575
#3  0x00007ffff39695df in pull_bitcoin_tx (ctx=<optimized out>, cursor=0x7fffffff5c68, max=0x7fffffff5c60) at src/bitcoin/tx.c:591
#4  fromwire_bitcoin_tx (ctx=<optimized out>, cursor=0x7fffffff5c68, max=0x7fffffff5c60) at src/bitcoin/tx.c:706
#5  0x00007ffff39defa4 in fromwire_hsmd_sign_remote_commitment_tx (ctx=0xbb7908, p=<optimized out>, tx=0x7fffffff5f50, remote_funding_key=0x7fffffff5ec0, remote_per_commit=<optimized out>, option_static_remotekey=0x7fffffff5ce8) at src/hsmd/hsmd_wiregen.c:881
#6  0x00007ffff39e1f3e in handle_sign_remote_commitment_tx (msg_in=<optimized out>, c=<optimized out>) at src/hsmd/libhsmd.c:1084
#7  hsmd_handle_client_message (ctx=<optimized out>, client=0xcb3068, msg=0xf6e958 "") at src/hsmd/libhsmd.c:1378
#8  0x00007ffff39e317e in handle (cap=24, dbid=1, peer_id=<optimized out>, hexmsg=0xf6d430 "00130200000001f25c0c5f21c46ed3f1063a9a41a489ed4e6bb2c18ef1998eb6618198b17137f90000000000666a6c8001e985010000000000160014f4d3100ee3828a602cbc47b1d70ac204e3342081f06a98200000012d70736274ff01005202000000"...) at src/contrib/libhsmd_python/libhsmd_python.c:62
#9  0x00007ffff397b7cc in _wrap_handle (self=<optimized out>, args=<optimized out>) at src/contrib/libhsmd_python/swig_wrap.c:4145
#10 0x000000000050a9af in ?? ()
#11 0x000000000050c6d4 in _PyEval_EvalFrameDefault ()
...
```

My best guess is that we somehow forgot to initialize one of the magic globals, but the crash location is really weird for that.

**Comment by darosior** [comment]
Yes. I've had similar issues with other fuzz targets in the past, and if debugging this issue would probably unlock them as well. However i went as far as reproducing with dozens of input to `pull_wtx` (using `tal_hex`) and writing unit tests in libwally, with no luck: it passes in libwally and crashes here.

However my crash is slightly different, and crashes in `uint32_from_le_bytes`:
```
==51502==ERROR: AddressSanitizer: SEGV on unknown address 0x610ffff81b27 (pc 0x0000006cb744 bp 0x7ffc0d13c0e0 sp 0x7ffc0d13c0c0 T0)
==51502==The signal is caused by a READ memory access.
    #0 0x6cb743 in uint32_from_le_bytes /home/darosior/projects/lightning/external/x86_64-pc-linux-gnu/libwally-core-build/src/../../../libwally-core/src/script_int.h:32:1
    #1 0x6ca837 in analyze_tx /home/darosior/projects/lightning/external/x86_64-pc-linux-gnu/libwally-core-build/src/../../../libwally-core/src/transaction.c:2380:9
    #2 0x6c706d in tx_from_bytes /home/darosior/projects/lightning/external/x86_64-pc-linux-gnu/libwally-core-build/src/../../../libwally-core/src/transaction.c:2503:9
    #3 0x6c6fda in wally_tx_from_bytes /home/darosior/projects/lightning/external/x86_64-pc-linux-gnu/libwally-core-build/src/../../../libwally-core/src/transaction.c:2662:12
    #4 0x5fc6bf in pull_wtx /home/darosior/projects/lightning/bitcoin/tx.c:571:6
    #5 0x5fc1b8 in pull_bitcoin_tx /home/darosior/projects/lightning/bitcoin/tx.c:591:12
    #6 0x5fd4b7 in fromwire_bitcoin_tx /home/darosior/projects/lightning/bitcoin/tx.c:708:7
    #7 0x61da16 in fromwire_hsmd_sign_penalty_to_us /home/darosior/projects/lightning/hsmd/hsmd_wiregen.c:829:9
    #8 0x60d60c in handle_sign_penalty_to_us /home/darosior/projects/lightning/hsmd/libhsmd.c:1129:7
    #9 0x606d66 in hsmd_handle_client_message /home/darosior/projects/lightning/hsmd/libhsmd.c:1380:10
    #10 0x6ad809 in run /home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg.c:68:2
    #11 0x553b19 in LLVMFuzzerTestOneInput /home/darosior/projects/lightning/tests/fuzz/libfuzz.c:25:2
    #12 0x45de91 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x45de91)
    #13 0x45d6d5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x45d6d5)
    #14 0x45ff97 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x45ff97)
    #15 0x460309 in fuzzer::Fuzzer::Loop(std::Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x460309)
    #16 0x44e478 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x44e478)
    #17 0x4778c2 in main (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x4778c2)
    #18 0x7f30466b7d09 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26d09)
    #19 0x421d19 in _start (/home/darosior/projects/lightning/tests/fuzz/fuzz-libhsmd_handle_msg+0x421d19)
```

Here is a reproduction (using this branch):
```
mkdir repro_seed_dir ; echo "MRkAAAAA//8ADgIJ//////////////////////////////////////////////////////////////8v/wAZ+P8AAAarAAAKBwoBaAAKEAICAgL//////wL///////f//////////////////////////////////////////////////////////////////////y//ABn4/wAABqsAAAoHCgFoAAoQAgICAv//////AgICAgIAAAkQCgAmpQ==" |base64 -d -w0 > repro_seed_dir/crash && make clean && CC=clang ASAN=1 FUZZING=1 DEVELOPER=1 ./configure && make -j16 && ./tests/fuzz/fuzz-libhsmd_handle_msg -runs=1 repro_seed_dir
```

Happy that we are both looking into this now! I had kinda gave up previously :D

**Comment by cdecker** [comment]
Found at least the issue that was causing my problem: `libwally` was not being initialized to use `tal`, and so we'd fail as soon as we'd try to re-parent the allocations libwally did internally once we return the tx. Calling `common_setup()` fixes that:

https://github.com/cdecker/lightning/commit/56a9f8bc0d301413b66850311198d6dd1a9ceddc

**Comment by cdecker** [comment]
Found another issue, that was likely not detected in the fuzz tests: we were using the message instead of the `peer_id` in libhsmd-python as the context to derive secrets from. See https://github.com/ElementsProject/lightning/pull/4543 for the fixes, including the `tal` fix.

**Comment by darosior** [comment]
Just tested on top of #4543 and yep it's unrelated. The fuzz target can't get anywhere far enough to discover other bugs anyways :/ .

**Comment by cdecker** [comment]
@darosior: what's the status of this? Should we try and merge it for 0.10.2, it is marked as a blocker for #4527 which I'd also like to resolve :wink:

**Comment by darosior** [comment]
@cdecker going to resurrect it ASAP [0], i was blocked by some libwally stuff but it's been updated since so i can give it another try!

[0] Porbably not next week but hopefully the week after

**Comment by cdecker** [comment]
> week

No worries, we have plenty of time before the release, just trying to get everything in line ahead of time ^^

**Comment by rustyrussell** [comment]
I've closed this: if someone wants to revisit, please open a new PR!

**Pull request closed without merging**
