### PR TITLE
option_upfront_shutdown_script support

### PR DESCRIPTION
**Pull request by rustyrussell**
First commit is the bugfix from #2578 without which the test hangs

### CODE REVIEW

**Comment by rustyrussell** [comment]
This also triggers the bug fixed by #2577 so will re-run tests after that is merged...

**Comment by cdecker** [comment]
Rebased to address changelog conflicts

**Comment by rustyrussell** [comment]
Nice catch, turns out an unrelated race though.  Will fix separately...

**Comment by rustyrussell** [comment]
Since Christian Acked before, only to remove it because of separate now-fixed issue, I'm going to self-ack:

Ack https://github.com/ElementsProject/lightning/pull/2579/commits/13272fe09b7323f1f39028362f30cd87dbbf484c

**Pull request merged**
