### PR TITLE
ci: use Bitcoin Core 27.1

### PR DESCRIPTION
**Pull request by fanquake**
Changelog-None

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
@rustyrussell Below is the complete list of Bitcoin versions used in the Core Lightning. 

1: Should we update the Bitcoin to it's latest version on the same day of it's release?
2: Should we not be using the same version everywhere? 

```
.github/workflows/macos.yaml: v26.1
.github/workflows/ci.yaml: v26.1
.github/workflows/bsd.yml: v26.1
.github/scripts/setup.sh: v26.1
contrib/docker/scripts/setup.sh: v22.0
contrib/docker/Dockerfile.tester: v22.0
contrib/docker/Dockerfile.builder.fedora: v22.0
contrib/docker/Dockerfile.builder: v0.18.1
Dockerfile: v22.0
```

**Review by vincenzopalazzo — APPROVED** [review]
>1: Should we update the Bitcoin to it's latest version on the same day of it's release?

Yes IMHO our CI should, otherwise we can not find problems before our users

ACK 0aa921f3eb0aabcc00d38f42e82665ed64660f42

P.S: we should keep an eye on execution time of our CI, looks like that the splice one timeouts for some reason after 2h

**Comment by fanquake** [comment]
> contrib/docker/scripts/setup.sh: v22.0
> contrib/docker/Dockerfile.tester: v22.0
> contrib/docker/Dockerfile.builder.fedora: v22.0
> contrib/docker/Dockerfile.builder: v0.18.1
> Dockerfile: v22.0

All of these [versions are end of life](https://bitcoincore.org/en/lifecycle/), and subject to multiple (some yet to be disclosed) CVEs. I wouldn't suggest using them for much at all, and probably not as the basis of production deployments, which it seems is already the case here, or is going to be after #7408? My suggestion would be the upgrade to the latest point release on either the 27.x or 26.x branch, depending on requirements.

**Comment by rustyrussell** [comment]
Yes, we've not really had problems with *old* bitcoind, but we've had problems with new ones.  Let's upgrade more aggressively.

And yes, we should standardize this across all our CI!  I'll apply this meanwhile.

**Pull request merged**
