### PR TITLE
param: renamed files

### PR DESCRIPTION
**Pull request by wythe**
Signed-off-by: Mark Beckwith <wythe@intrig.com>

### CODE REVIEW

**Comment by cdecker** [comment]
What's the rationale behind this rename? It is likely to cause some breakage if people are editing these files in their feature branches.

**Comment by wythe** [comment]
#1695 shortened the function and macro names defined in `param.h`. This filename change is so the names will be consistent.  I saved this for a separate PR because it confused `git diff` when I did it within #1695 (it made the diff too big for `param.h`).

#1682 is a pending PR and has this branch already merged. It is the first actual usage of `param()` in  `lightningd`.  I doubt anyone else even knows about it.  My plan was to rebase #1682 once this was merged.

**Comment by wythe** [comment]
Apologies for not being more descriptive in the commit message. @rustyrussell and I got into a 24-hr rhythm of getting these small changes in daily, but then the weekend came :-)

**Comment by rustyrussell** [comment]
Yeah, sorry @cdecker I pre-acked this when proposed in a previous PR.

Ack e882741d14a2d18a8791198d03c2bfcf3e8b0c84

**Pull request merged**
