### PR TITLE
Litecoin versioning fixup + support for aarch64

### PR DESCRIPTION
**Pull request by 78bash**

### CODE REVIEW

**Comment by 78bash** [comment]
Did travis-ci checks fail because I made 2 pull requests for the same file?

**Comment by cdecker** [comment]
Nope, seems we have a test that hangs somewhere. Could you also parametrize the bitcoin arch with `uname`? There's no point in having it download the amd64 version if we run on a different arch.

Speaking of which, I'm not sure about this, but wouldn't the base `alpine` image always be an amd64 image? Or is docker smart enough to use the host arch and pull the matching images if they exist?

**Comment by cdecker** [comment]
Just saw your other PR #2064, so no need to amend this here, but this PR will need a rebase once #2064 is merged, since there is a merge conflict.

**Comment by 78bash** [comment]
RUN will treat its arguments as cli commands. So `uname -m` will return the arch available on the server. This is the same arch portion for amd64 and aarch64 used in the bitcoin and litecoin tarballs.

**Comment by 78bash** [comment]
Looks like there's also an aarch64 version of Alpine

**Comment by cdecker** [comment]
Superseded by #2071 and #2064

**Pull request closed without merging**
