### PR TITLE
master: Move the gossipd initialization after the other inits

### LINKED ISSUE #1437: Crash on startup
Seconds after starting lightningd, it crashes with this output:
```
lightningd: Fatal signal 11
0x432bcd crashdump
        common/daemon.c:37
0x7f74406a74af ???
        ???:0
0x407a03 get_block_height
        lightningd/chaintopology.c:556
0x409fba peer_start_channeld
        lightningd/channel_control.c:229
0x424e9d peer_connected
        lightningd/peer_control.c:494
0x40bc3c gossip_msg
        lightningd/gossip_control.c:161
0x42cc36 sd_msg_read
        lightningd/subd.c:503
0x42c55d read_fds
        lightningd/subd.c:330
0x465ecf next_plan
        ccan/ccan/io/io.c:59
0x4669a6 do_plan
        ccan/ccan/io/io.c:387
0x4669e4 io_ready
        ccan/ccan/io/io.c:397
0x468550 io_loop
        ccan/ccan/io/poll.c:310
0x40818a setup_topology
        lightningd/chaintopology.c:744
0x4146dc main
        lightningd/lightningd.c:392
0x7f744069282f ???
        ???:0
0x403518 ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightning_channeld: Writing out status 65522: Broken pipe
Segmentation fault (core dumped)
```

I'm synced to 91d149b.

### PR DESCRIPTION
**Pull request by cdecker**
If we start accepting peer connections before we initialized some of the other
parts (mainly the chaintopology) we could end up asking for stuff that isn't
ready yet (blockchain head for example).

Fixes #1437

### CODE REVIEW

**Comment by rustyrussell** [comment]
This revealed a new race, however; activating peer means we tried sending to gossipd before it was ready.

Let's start gossipd, then explicitly tell it to activate.  That also improves parallelism.

**Comment by ZmnSCPxj** [comment]
This is supposed to fix #1437? Yes/No/Maybe?

**Comment by rustyrussell** [comment]
I think so, though @cdecker didn't reference a PR in the original?

**Comment by cdecker** [comment]
> Let's start gossipd, then explicitly tell it to activate. That also improves parallelism.
Ok, shall we defer the sending of `gossipctl_init` or do you prefer adding a new `activate` message that sets up the listeners?

> I think so, though @cdecker didn't reference a PR in the original?
It's a bug I encountered when restarting sleepyark, I didn't get a chance to go through the issue list. I'll edit the OP to include fixes markers.

**Comment by cdecker** [comment]
ACK 3c6a943

**Pull request merged**
