### PR TITLE
The great msat purge

### PR DESCRIPTION
**Pull request by rustyrussell**
@ShahanaFarooqui urged me to complete the msat transition.  This series does that, but some msat fields which were not named correctly leaked in, forcing broader deprecations.

1. All "msat" fields now end in _msat.  This allows e.g. the Python code to turn them into Millisatoshi() class *unconditionally*
2. All "msat" fields will become raw numbers; this happens currently with allow-deprecated-apis=false.  Code should handle both a `"123msat"` JSON string and `123` for the transition.
3. We rename some input arguments similarly for consistency.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Yes, schema should be correct!  We should add tooling on this (that all outgoing msat fields have names _msat, and all _msat field have msat values) though.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/commit/f69780988c8f0e1dd27bc8e76d06cf36dc8052bf

**Comment by rustyrussell** [comment]
Trivial rebase to address conflicts, and update examples in PLUGINS.md.

**Review by ShahanaFarooqui — APPROVED** [review]

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/6132e9f94e5b8a2ba5b9022d7e0c8eac5f09be7a
(In case ackbot is waiting for a separate message, not an edited one?)

**Comment by jsarenik** [comment]
Please do not release a stable version until lightningd/plugins#369 is fixed (here in pyln). Thanks.

**Comment by jsarenik** [comment]
Or rother there in the summary plugin? OK.

**Pull request merged**
