### PR TITLE
common: change default network to mainnet

### LINKED ISSUE #4159: Default network changing in 2020
### Issue and Steps to Reproduce

`lightningd` when run without network selection warns about following:

```
default network changing in 2020
```

### `getinfo` output

```
{
   "id": "029b579174dcece6b2f5712cd33d640d291138ba68467294e2079f16118bd25610",
   "alias": "SOMBERFIRE",
   "color": "029b57",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "2001:470:6f:200:c2f6:bf7c:c6c:bf6b",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.9.1-249-g3b69dce",
   "blockheight": 653356,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/nsm/.lightning/bitcoin",
   "warning_bitcoind_sync": "Bitcoind is not up-to-date with network."
}
```

### PR DESCRIPTION
**Pull request by jsarenik**
Changelog-changed: Default network on both new and old
installs is now bitcoin. The warning "default network
changing in 2020" was removed.

Reverts 36c517bac59521dbf012c1faa29c012cfe48deae (except the comment)
Fixes #4159

### CODE REVIEW

**Comment by jsarenik** [comment]
The whole idea of this patch was changed after feed-back from @rustyrussell . Now it is removing all the logic that would detect if the directory `smells_like_old_testnet`.

**Comment by jsarenik** [comment]
Note: original patch which introduced this smelly thing was 36c517bac and it also brought following include files:

```diff
+#include <sys/stat.h>
+#include <sys/types.h>
+#include <unistd.h>
```

Would it be safe to remove all of these? @rustyrussell

**Comment by cdecker** [comment]
Needs a changelog entry, otherwise excellent :+1:

ACK https://github.com/ElementsProject/lightning/pull/4277/commits/bf19dc6b4729383f85d4bb5e05e83340dd123a26

**Comment by jsarenik** [comment]
@cdecker See the commit itself.  There is currently this changelog entry:

```
Changelog-changed: Default network on both new and old
installs is now bitcoin. The warning "default network
changing in 2020" was removed.
```

**Comment by cdecker** [comment]
I see, @bitcoin-bot must have been slow picking it up and the check was marked as pending. All good to go then.

**Pull request merged**
