### PR TITLE
wait/pagination support for listsendpays, listforwards

### PR DESCRIPTION
**Pull request by rustyrussell**
This expands wait (and pagination) to listsendpays and listforwards.

It does not cover listpays (yet, sorry), so the caller needs to collate the multiple parts (by payment_hash and groupid) to get presentable payment information (which is what the pay plugin does to create `listpays`.

Closes: #6740

### CODE REVIEW

**Comment by rustyrussell** [comment]
Trivial rebase on #6802 for flake fixes.

**Comment by cdecker** [comment]
Rebased on top of `master` due to conflicts in the generated files.

**Comment by rustyrussell** [comment]
Rebased, and wrote tests and documentation (which caused more minor fixes).

**Comment by rustyrussell** [comment]
Rebase and PostgresSQL fix.

**Pull request merged**
