### PR TITLE
ci: use Bitcoin Core 24.1

### PR DESCRIPTION
**Pull request by fanquake**
cc @instagibbs 
Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6264/commits/4a7d35322029b864b16b96858eabfc620ae812fe

**Comment by instagibbs** [comment]
ACK https://github.com/ElementsProject/lightning/pull/6264/commits/4a7d35322029b864b16b96858eabfc620ae812fe

**Comment by cdecker** [comment]
Rebased on top of `master`

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/6264/commits/bf0504a1effe0906288679d2bfdfedfdb729b287

**Pull request merged**
