### PR TITLE
Libbase58 as git submodule

### PR DESCRIPTION
**Pull request by lclc**
This PR adds a git submodule for libbase58, pointing to the last tagged release (0.1.4, same as in the Ubuntu repo), as suggested in the comments by @cdecker in https://github.com/ElementsProject/lightning/issues/64.

Should fix https://github.com/ElementsProject/lightning/issues/64 & make building on various systems easier (atm probably everything that is not Ubuntu) and the dependency version required/supported more clear.

I’m not very familiar with plain make files, so please let me know what I need to do different.

I would also write a cmake build system over Christmas / New Year if you're interested.
A list of some of the advantages of CMake: https://cmake.org/Wiki/Really_Cool_CMake_Features
I especially like the ootb creation of Debian and RPM packages.
Also cross-compiling gets much easier: http://www.vtk.org/Wiki/CMake_Cross_Compiling
It's very easy to read & understand and well documented.
I've already done the same for the Open Transactions library (https://raw.githubusercontent.com/lclc/opentxs/develop/CMakeLists.txt) and the Digital Bitbox hardware wallet code (https://raw.githubusercontent.com/digitalbitbox/mcu/master/CMakeLists.txt).

### CODE REVIEW

**Comment by cdecker** [comment]
CI reports some of the test binaries breaking:

```
valgrind -q --error-exitcode=7 --track-origins=yes --leak-check=full --show-reachable=yes bitcoin/test/run-tx-encode
bitcoin/base58.o: In function `to_base58':
/builds/ElementsProject/lightning/bitcoin/base58.c:31: undefined reference to `b58_sha256_impl'
/builds/ElementsProject/lightning/bitcoin/base58.c:32: undefined reference to `b58check_enc'
bitcoin/base58.o: In function `from_base58':
/builds/ElementsProject/lightning/bitcoin/base58.c:57: undefined reference to `b58_sha256_impl'
/builds/ElementsProject/lightning/bitcoin/base58.c:60: undefined reference to `b58tobin'
/builds/ElementsProject/lightning/bitcoin/base58.c:61: undefined reference to `b58check'
bitcoin/base58.o: In function `key_to_base58':
/builds/ElementsProject/lightning/bitcoin/base58.c:121: undefined reference to `b58check_enc'
bitcoin/base58.o: In function `key_from_base58':
/builds/ElementsProject/lightning/bitcoin/base58.c:132: undefined reference to `b58tobin'
/builds/ElementsProject/lightning/bitcoin/base58.c:133: undefined reference to `b58check'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'daemon/test/run-maxfee' failed
make: *** [daemon/test/run-maxfee] Error 1
```

**Comment by rustyrussell** [comment]
Lucas Betschart <notifications@github.com> writes:
> This PR adds a git submodule for libbase58, pointing to the last tagged release (0.1.4, same as in the Ubuntu repo), as suggested in the comments by @cdecker in https://github.com/ElementsProject/lightning/issues/64.
>
> Should fix https://github.com/ElementsProject/lightning/issues/64 & make building on various systems easier (atm probably everything that is not Ubuntu) and the dependency version required/supported more clear.
>
> I’m not very familiar with plain make files, so please let me know what I need to do different.
>
> I would also write a cmake build system over Christmas / New Year if you're interested.

Please don't, at least for now.  I am happy to maintain the Makefiles
for Unix-like systems, and there are a lot of other things we need to
change if we want to support non-Unix systems.

Your changes were neat, but there were a few twists I had to add;
git submodules are a little tricky.  I've pushed them to:

        https://github.com/ElementsProject/lightning/tree/pr-103

Let's see if that makes the CI happy :)

Thanks!
Rusty.

**Comment by cdecker** [comment]
Finally figured out how to push onto a PR created by another user :wink: 

I took the liberty of pushing the changes by @rustyrussell and me onto your branch @lclc, I'll try to get the CI to accept this. It was complaining about the unit tests. `make full-check` is your friend :wink:

**Comment by lclc** [comment]
Ok great, thanks!

**Comment by cdecker** [comment]
If @rustyrussell is ok with this I'll marge it :smile:

**Pull request closed without merging**
