### PR TITLE
Ancient databases nonstatic unilateral close fix

### PR DESCRIPTION
**Pull request by rustyrussell**
Found when I closed my oldest channel (since I've not seen the peer in several years, AFAICT).

### CODE REVIEW

**Comment by rustyrussell** [comment]
I confirmed that this fixed the problem on my node.

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4831/commits/3fe7838f7876f996c929e6865deafffd41b63c57

P.S: I review the CI action error in different time today, but the error looks unrelated to me.

**Comment by rustyrussell** [comment]
DO NOT SO APPLY THIS BROKE MY NODE!!!!

**Comment by vincenzopalazzo** [comment]
>DO NOT SO APPLY THIS BROKE MY NODE!!!!

Mh, so this is the reason that your node is down all day yesterday. one thing that jumps to my mind, is that this cast is legal to migrate an old table to a new one. But, I have no answer here

**Pull request closed without merging**
