### PR TITLE
msggen: add disableoffer method

### PR DESCRIPTION
**Pull request by daywalker90**
Based on the fixes from #7215 + #7217 + #7218 and #7230

### CODE REVIEW

**Comment by cdecker** [comment]
This needs a rebase on top of `master` and then its good to go.

**Comment by daywalker90** [comment]
rebased on master

**Comment by cdecker** [comment]
Rebased, and resolved a bunch of conflicts. The many tiny PR idea is nice, but just does not work if there are conflicts that rebasing brings in. In order for that to work we'd have to have a way to stack the PRs one on top of the other, which GH does not support at all atm for external contributors.

**Comment by daywalker90** [comment]
😢

**Comment by cdecker** [comment]
Ah no worries, I love your contributions, I'm just revising my own mental model on what the ideal flow would be. No criticism intended :hugs:

**Comment by daywalker90** [comment]
None taken, it was directed at Github. I tried stacking them all on top of each other in the beginning but you indeed still had to rebase with conflicts every time iirc.

**Comment by cdecker** [comment]
Ok, I butchered this PR trying to stack them. I'll reset to your latest version.

**Comment by cdecker** [comment]
Ok, I messed up stacking them, the code was added in #7256, so this is just regenerating the grpc files.

**Pull request merged**
