### PR TITLE
tests: memleak catching a plugin that's still grinding test_sendinvoice

### PR DESCRIPTION
**Pull request by niftynei**
We shutdown before the offers plugin infra has finished grinding for a
shadow route, which results in a memleak error.

If we wait to end the test until the node has finished the route calculations
etc, we can avoid running memleak while it's in the middle of something.

Found in CI run of #2649.

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
ACK ffbb36ab429de50e57b56ef68f44e171f4699b84

**Comment by rustyrussell** [comment]
The commit message is insufficient :(

You need to at least include the backtrace so I can tell what you're fixing!  And so others can google it...

And I can't reproduce it.

**Comment by niftynei** [comment]
There's a backtrace in the commit message with the memleak traces?

https://github.com/ElementsProject/lightning/pull/5095/commits/9e314cd53d3f7fa8f6a84a92e6196fe4d1b47a0c

The logs were pretty big, but my understanding is that the `pay` plugin was in the middle of a shadow_route calculation when the test cleanup happened, which resulted in a flake due to memleak catching still allocated memory in the plugin. By waiting til the shadow_route calculation terminates to cleanup, we avoid the memleak flake.

Since we fixed the memleak detection, I've been seeing a decent number more flakes due to non-terminated RPC calls handlers in plugins being caught in the memleak sweep. This is one of those.

**Comment by rustyrussell** [comment]
I think this weird leak is solved by https://github.com/ElementsProject/lightning/pull/5100

**Pull request closed without merging**
