### PR TITLE
Fixes #5276 by using debian bullseye instead of buster

### LINKED ISSUE #5276: Update Debian buster to bullseye  for docker images
Hi!

I am testing elementsproject/lightningd:v0.11.1 docker image with [rust-teos watchtower plugin](https://github.com/talaia-labs/rust-teos/tree/cln-plugin/watchtower-plugin) but it looks like that a compilation from this rust project cannot be executed with the current debian buster image.
Error:
```
cln-wt-test    | /opt/rust-teos/watchtower-plugin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/rust-teos/watchtower-plugin)
```
I've tested with compiling with rust in debian buster and it won't work but it will on bullseye, so a "simple" (maybe not) upgrade of the CLN docker images to bullseye might fix a lot of issues with plugins. Another good point to upgrade the images is that debian buster will be EOL on 2022-08
### Issue and Steps to Reproduce
1. Compile [rust-teos watchtower plugin](https://github.com/talaia-labs/rust-teos/tree/cln-plugin/watchtower-plugin) with Rust official docker image.
2. Copy the content to lightningd docker image and set it as as plugin
3. Launch lightningd and receive the error mentioned above.

cc @sr-gi 

Thanks for all your work!

### PR DESCRIPTION
**Pull request by Jossec101**
This fixes #5276 

I've tested the upgrade with plugins that requires GLIBC 2.29+ when compiled with Rust and it works, shall I test something more for this PR?

This is is my first contribution here, guidance is very welcome

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
LGTM, looks like the only way to update the library is to update the base docker image, and have error has gone good because unlock the possibility to use rust lib provided in a cool way too!


ACK https://github.com/ElementsProject/lightning/pull/5278/commits/1c618282d19125d603b3b0bae308dc66b3a316a5

Your PRs are fine, the only optional thing is the Changelog-None entry in the commit body!

**Comment by Jossec101** [comment]
I added it as Changelog-Fixed:  Upgrade docker base image from Debian buster to bullseye to work with glibc 2.29+

**Comment by cdecker** [comment]
This needs squashing, and the `Changelog-Fixed` should not be on the first line, rather on the bottom so the commit retains a human-readable commit message.

**Comment by cdecker** [comment]
> @cdecker Squashing done, hope it is ok now.

Perfect 👍 Thank you very much

**Pull request merged**
