### PR TITLE
external/Makefile: Change HOST to MAKE_HOST

### PR DESCRIPTION
**Pull request by jsarenik**
Proposed fix for issue #1231 - FreeBSD (tcsh) build problem due
to HOST environment variable.

### CODE REVIEW

**Comment by jsarenik** [comment]
@ZmnSCPxj thank you for feed-back! I changed it appropriately.

**Comment by ZmnSCPxj** [comment]
ACK af804ef5846eccfbd3195c34f26133a851bc1870

**Comment by jsarenik** [comment]
@ZmnSCPxj `MAKE_HOST` is an internal variable of GNU Make. It may work well for others who use autotools, but did not translate well for `lightning` which is Makefile-only + also submodules which use Autotools themselves

**Comment by jsarenik** [comment]
Ref: #1533

**Pull request merged**
