### PR TITLE
lightningd: encode fallback address in 5 bits

### PR DESCRIPTION
**Pull request by jBarz**
The bolt11 specification requires that the version number of the Fallback on-chain address be 5 bits wide instead of 8 bits.

To test this I:

1. modified my local repo to accept a p2pkh fallback address at the end of the "invoice" command.
2. create an invoice
3. use "decodepay" on the bolt11 string

Before this change, decodepay would fail because it doesn't read the right version number of the address.

If there is another way to test the encoding of the fallback address, please do let me know :-).
If we want to add fallback address to the list of args accepted by the "invoice" command, I could help with that too.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
@jBarz, thank you for the offer, have you seen #542 and #590? The issue with fallback adresses is that applications wrapping c-lightning might want to  use our invoice system exclusively for tracking all incoming payments, so we need to decide how to track onchain incoming payments.

**Comment by jBarz** [comment]
thanks @ZmnSCPxj. 
Can I do this part independently first? Or do we ideally want all 5 points in https://github.com/ElementsProject/lightning/issues/542 to be implemented and merged in together?

> Add an optional "?fallback" argument to invoice RPC command, which if the JSON value true generates a fallback address in the invoice object, and load the bolt11 object appropriately.

**Comment by ZmnSCPxj** [comment]
Yes, it would be better to do this fix first.

**Comment by rustyrussell** [comment]
Hi!  There are test vectors in BOLT 11 https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md and we test these in `tests/test_lightningd.py`.  In particular, we test the following:

* lntb20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfpp3x9et2e20v6pu37c5d9vax37wxq72un98kmzzhznpurw9sgl2v0nklu2g4d0keph5t7tj9tcqd8rexnd07ux4uv2cjvcqwaxgj7v4uwn5wmypjd5n69z2xm3xgksg28nwht7f6zspwp3f9t
* lnbc20m1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqsfpp3qjmp7lwpagxun9pygexvgpjdc4jdj85fr9yq20q82gphp2nflc7jtzrcazrra7wwgzxqc8u7754cdlpfrmccae92qgzqvzq2ps8pqqqqqqpqqqqq9qqqvpeuqafqxu92d8lr6fvg0r5gv0heeeqgcrqlnm6jhphu9y00rrhy4grqszsvpcgpy9qqqqqqgqqqqq7qqzqj9n4evl6mr5aj9f58zp6fyjzup6ywn3x6sk8akg5v4tgn2q8g4fhx05wf6juaxu9760yp46454gpg5mtzgerlzezqcqvjnhjh8z3g2qqdhhwkj
* lnbc20m1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqsfpp3qjmp7lwpagxun9pygexvgpjdc4jdj85fr9yq20q82gphp2nflc7jtzrcazrra7wwgzxqc8u7754cdlpfrmccae92qgzqvzq2ps8pqqqqqqpqqqqq9qqqvpeuqafqxu92d8lr6fvg0r5gv0heeeqgcrqlnm6jhphu9y00rrhy4grqszsvpcgpy9qqqqqqgqqqqq7qqzqj9n4evl6mr5aj9f58zp6fyjzup6ywn3x6sk8akg5v4tgn2q8g4fhx05wf6juaxu9760yp46454gpg5mtzgerlzezqcqvjnhjh8z3g2qqdhhwkj
* lnbc20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfppj3a24vwu6r8ejrss3axul8rxldph2q7z9kmrgvr7xlaqm47apw3d48zm203kzcq357a4ls9al2ea73r8jcceyjtya6fu5wzzpe50zrge6ulk4nvjcpxlekvmxl6qcs9j3tz0469gq5g658y
* lnbc20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfppqw508d6qejxtdg4y5r3zarvary0c5xw7kepvrhrm9s57hejg0p662ur5j5cr03890fa7k2pypgttmh4897d3raaq85a293e9jpuqwl0rnfuwzam7yr8e690nd2ypcq9hlkdwdvycqa0qza8
* lnbc20m1pvjluezhp58yjmdan79s6qqdhdzgynm4zwqd5d7xmw5fk98klysy043l2ahrqspp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqfp4qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3q28j0v3rwgy9pvjnd48ee2pl8xrpxysd5g44td63g6xcjcu003j3qe8878hluqlvl3km8rm92f5stamd3jw763n3hck0ct7p8wwj463cql26ava

Which should test that we parse every kind of currently-valid fallback address successfully?

**Comment by rustyrussell** [comment]
Ah thanks!  I misread this as "decode" and was very confused!

As encode is currently unused, I'm not shocked it's broken. We should code up #542 so we can test your changes (which, BTW, look correct!).  Did you want to do that, or should I do it?  If I do, there might be a week's delay...

**Comment by jBarz** [comment]
thanks @ZmnSCPxj . I made changes as you suggested.

**Comment by ZmnSCPxj** [comment]
ACK 5832a160851214c60ff3910720b8f8be71b44ca8

**Comment by rustyrussell** [comment]
Thanks!  And congratulations on such a nice patch for your first contribution!

**Pull request merged**
