### PR TITLE
Bitcoind is fickle

### PR DESCRIPTION
**Pull request by rustyrussell**

### CODE REVIEW

**Comment by cdecker** [comment]
Reproducibly fails on 32bit:
```Fatal signal 11. 0x80535d8 log_crash
	lightningd/log.c:460
0xf771acaf ???
	???:0
0xf74dc456 ???
	???:0
0x8090dd4 tal_strdup
	ccan/ccan/tal/str/str.c:18
0x804a5bd gather_args
	lightningd/bitcoind.c:47
0x804b634 cmdarr
	lightningd/bitcoind.c:488
0x804b65a wait_for_bitcoind
	lightningd/bitcoind.c:497
0x804cfd0 setup_topology
	lightningd/chaintopology.c:576
0x805240c main
	lightningd/lightningd.c:273
0xf7476636 ???
	???:0
0x804a1b0 ???
	???:0```

I'll try to gather a core dump :-)

**Comment by cdecker** [comment]
It appears we read way past the list of provided args in

```
43              args[n++] = cast_const(char *, cmd);
44              tal_resize(&args, n + 1);
45
46              while ((args[n] = va_arg(ap, char *)) != NULL) {
47                      args[n] = tal_strdup(args, args[n]);
48                      n++;
49                      tal_resize(&args, n + 1);
50              }
```

In the core dump `n=15` this fails, but `n` should never go past 4. This also appears to resize one too many times, i.e., `args[n-1]` is the last initialized element, but `args[n]` is the last element in the array.

**Comment by rustyrussell** [comment]
Yes, it should set args[n] to NULL at the end; it's supposed to be a NULL-terminated array.  But that would fail in execvp, not here.

**Comment by rustyrussell** [comment]
Ah, NULL terminator belongs in *caller*.  Fixed.

**Comment by cdecker** [comment]
Great, that seems to fix it. The CI failure is likely due to a flaky test when running in valgrind, will rerun and merge if it passes :+1:

**Pull request merged**
