### PR TITLE
Fix many cases of undefined behaviour

### PR DESCRIPTION
**Pull request by rustyrussell**
This helps both fuzzing (see #6106 etc), and actually caught a few real errors!

Changelog-None

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Looks like that this need a rebase?

**Comment by rustyrussell** [comment]
Trivial rebase complete

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6117/commits/75ba34ed6c25176884e6e8f7fd122bb3f47683c6

**Review by morehouse — APPROVED** [review]
ACK 75ba34ed6c25176884e6e8f7fd122bb3f47683c6

**Pull request merged**
