### PR TITLE
Fix connect crash

### LINKED ISSUE #1434: Crash in `destroy_reconnecting_peer` from `add_reconnecting_peer`
got some random crashes lately with current master after running it a while without any actions.
seem to crash at the same place.
can't find any specific reason in the normal log

```
2018-04-27T06:02:39.697Z lightning_gossipd(10502): UPDATE WIRE_GOSSIP_GET_TXOUT
2018-04-27T06:02:39.697Z lightning_gossipd(10502): Received channel_announcement for channel 516708:2208:0
2018-04-27T06:02:39.704Z lightning_gossipd(10502): UPDATE WIRE_GOSSIP_GET_TXOUT                                                                                                                              
2018-04-27T06:02:39.704Z lightning_gossipd(10502): Failed connected out for 031d244a60d61936834f290656cdf0ed4b9979260c19b07804bde681819f8e14ca
2018-04-27T06:02:39.705Z lightning_gossipd(10502): ...will try again in 8 seconds
2018-04-27T06:02:39.705Z lightning_gossipd(10502): Received channel_announcement for channel 505516:488:1                                                                                                    
2018-04-27T06:02:39.705Z lightning_gossipd(10502): UPDATE WIRE_GOSSIP_GET_TXOUT
2018-04-27T06:02:39.705Z lightning_gossipd(10502): Failed connected out for 02952cc6b7f92226e490d6354636604a26484a396627c97661c932ffc55042a500
2018-04-27T06:02:39.705Z lightning_gossipd(10502): ...will try again in 8 seconds
2018-04-27T06:02:39.706Z lightning_gossipd(10502): Connected out for 02b11440fc0a82e4489a124623a63e01936bd3dfd60f33ad6f0d7756e922bcdced                                                                     
2018-04-27T06:02:39.706Z lightning_gossipd(10502): Connected out for 028e5a8e86540f703e1f58880d35d1e318a54c27d84ec1edbcde04a78ed4469a1e
```

```
0x415911 crashdump
        common/daemon.c:37
0x7f5e3ad9f4af ???
        ???:0
0x7f5e3ad9f428 ???
        ???:0
0x7f5e3ada1029 ???
        ???:0
0x43ac6b call_error
        ccan/ccan/tal/tal.c:98
0x43ae28 check_bounds
        ccan/ccan/tal/tal.c:170
0x43ae4f to_tal_hdr
        ccan/ccan/tal/tal.c:178
0x43b83a tal_free
        ccan/ccan/tal/tal.c:504
0x42f33b io_close
        ccan/ccan/io/io.c:443
0x403195 destroy_reconnecting_peer
        gossipd/gossip.c:264
0x43afdd notify
        ccan/ccan/tal/tal.c:240
0x43b48e del_tree
        ccan/ccan/tal/tal.c:400
0x43b8c0 tal_free
        ccan/ccan/tal/tal.c:511
0x4031ca add_reconnecting_peer
        gossipd/gossip.c:270
0x403a89 peer_connected
        gossipd/gossip.c:455
0x403c5c peer_init_received
        gossipd/gossip.c:505
0x415104 peer_decrypt_body
        common/cryptomsg.c:158
0x42e6b7 next_plan
        ccan/ccan/io/io.c:59
0x42f18e do_plan
        ccan/ccan/io/io.c:387
0x42f1cc io_ready
        ccan/ccan/io/io.c:397
0x430d38 io_loop
        ccan/ccan/io/poll.c:310
0x409042 main
        gossipd/gossip.c:2390
0x7f5e3ad8a82f ???
        ???:0
0x402a38 ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightningd: lightning_gossipd failed (signal 14), exiting.
```

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes #1434

### CODE REVIEW

**Comment by cdecker** [comment]
I'm acking this now, but it needs a quick squash. Feel free to re-apply my ACK after squashing :wink: 

ACK 8603625

**Comment by ZmnSCPxj** [comment]
ACK 860362513efd75d087367bd3dbeaf9e767948413

**Comment by cdecker** [comment]
Squashed

ACK 2da1758

**Comment by cdecker** [comment]
Travis was complaining about a test failing, had to rebase and add a commit that renames `dev-ping` to `ping`.

**Comment by cdecker** [comment]
Recycling my prior ack

ACK 6e0bcc8

**Pull request merged**
