### PR TITLE
plugins: add grpc-plugin to PLUGINS, so it gets started and installed.

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes: #5162
Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
ACK 9777eb671ff89cbaf18233e0134c381f7cb17830

**Comment by rustyrussell** [comment]
Hmm, now it *is* exiting silently, too soon!  Even caught it under strace, but nothing informative; it's doing an exit(0) *sometimes*.

**Comment by vincenzopalazzo** [comment]
>Hmm, now it is exiting silently, too soon! Even caught it under trace, but nothing informative; it's doing an exit(0) sometimes.

Maybe we shouldn't mark the plugin as important? there is a case where the plugin exit in the normal operation, and if I read correctly the code, this should be the case where we are not setting the `grpc-port` value.

```rust
 let bind_port = match plugin.option("grpc-port") {
        Some(options::Value::Integer(-1)) => {
            log::info!("`grpc-port` option is not configured, exiting.");
            return Ok(());
        }
        Some(options::Value::Integer(i)) => i,
        None => return Err(anyhow!("Missing 'grpc-port' option")),
        Some(o) => return Err(anyhow!("grpc-port is not a valid integer: {:?}", o)),
    };
```

**Comment by instagibbs** [comment]
this patch also seems to fix my inability to run:
```
make -j12 full-check PYTEST_PAR=24 DEVELOPER=1 VALGRIND=0
```
from `HACKING.md`

**Comment by rustyrussell** [comment]
... all builtin plugins are "important".  There's a designated way for them to say they don't want to be started: you return `{"disable": "... reason why I want to be disabled"}` from the JSON init call.

I'm going to cut rc2 today without this, but clearly there will need to be an rc3: we can't *not* install this plugin!

**Comment by vincenzopalazzo** [comment]
>... all builtin plugins are "important". There's a designated way for them to say they don't want to be started: you return {"disable": "... reason why I want to be disabled"} from the JSON init call.

I will try to look into that tomorrow!

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
The actual code skips an `rpc-plugin` example that it is used inside the tests.

In the PR https://github.com/ElementsProject/lightning/pull/5173 I put this addition to the bottom at line 185 again

**Comment by rustyrussell** [comment]
Rebased on master now that cln-grpc is fixed!

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/commit/6d6c6706833a1c84063c18d7666d026839147ac4

**Comment by whitslack** [comment]
@rustyrussell: Question about the Rust build: should these commands…
```
PYTHONPATH=contrib/msggen python3 contrib/msggen/msggen/__main__.py
```
…be completed before Cargo starts compiling Rust code? It appears to my casual eye that `msggen` generates some Rust code, but I often see it running after Cargo has already started. Maybe the Makefiles are missing a dependency somewhere?

**Comment by cdecker** [comment]
> @rustyrussell: Question about the Rust build: should these commands…
> 
> ```
> PYTHONPATH=contrib/msggen python3 contrib/msggen/msggen/__main__.py
> ```
> 
> …be completed before Cargo starts compiling Rust code? It appears to my casual eye that `msggen` generates some Rust code, but I often see it running after Cargo has already started. Maybe the Makefiles are missing a dependency somewhere?

That should indeed be the case, not sure if there's a dependency between make targets missing.

**Pull request merged**
