### PR TITLE
pyln-proto: update coincurve to v20

### PR DESCRIPTION
**Pull request by daywalker90**
Since today the python 3.12 CI on the plugins repo started failing because it could not install a python dependency called `coincurve`. Apparently `coincurve` supports python 3.12 with version 19+. I found it in the `contrib/pyln-proto/pyproject.toml` and updated it to the latest version 20 and ran `poetry update` in the root folder. Version 20 of coincurve is supposed to be compatible  with python 3.8 aswell.

### CODE REVIEW

**Comment by daywalker90** [comment]
The error when running `poetry install`:
```
ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  Traceback (most recent call last):
    File "/home/runner/.local/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/home/runner/.local/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/.local/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
      return _build_backend().build_wheel(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 266, in <module>
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 171, in setup
      ok = dist.parse_command_line()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 476, in parse_command_line
      args = self._parse_command_opts(parser, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 878, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpi4mwiuhf/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 541, in _parse_command_opts
      if not issubclass(cmd_class, Command):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: issubclass() arg 1 must be a class
  

  at ~/.local/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with coincurve (18.0.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "coincurve (==18.0.0)"'.
```

I saw that there are two `requirements.txt` files in `plugins/clnrest` and `plugins/wss-proxy` which contain `coincurve==18.0.0` but i think they are generated. I tried to run `poetry export -f requirements.txt --output requirements.txt` but then coincurve disappeared from one file and i thought i did something wrong @ShahanaFarooqui

**Comment by ShahanaFarooqui** [comment]
@daywalker90 Hi, Thanks for informing me about clnrest's requirements. 

As suggested by @cdecker, I compared `poetry show --tree` results from before/after `cd plugins/clnrest/ && poetry export --output requirements.txt && pip install -r requirements.txt` to check for any significant difference. There is no difference in the tree.

But poetry export removed coincurve & other dependencies from clnrest's requirements.txt. So I updated the PR with those changes.

**Comment by daywalker90** [comment]
@ShahanaFarooqui what about the requirements.txt in wss-proxy?

**Comment by ShahanaFarooqui** [comment]
> @ShahanaFarooqui what about the requirements.txt in wss-proxy?

Confirmed that it was not changed.

**Pull request merged**
