### PR TITLE
make: Add cli/lightning-cli to default make target

### LINKED ISSUE #270: Command make won't build lightning-cli
In the documentation it says the user only has to execute the command "make" to compile the source code. However, this won't build lightning-cli which is later used in the documentation and that's very confusing.To also get lightning-cli I also had to execute the command:

make lightning-cli-all

Please, add that to the documentation.

### PR DESCRIPTION
**Pull request by cdecker**
Closes #270

Reported-by: @sumBTC

### CODE REVIEW

**Comment by rustyrussell** [comment]
Hmm, I've generally been moving stuff out to the sub Makefiles.  In this case, that means 'default: cli/lightning-cli' line in there (this is how the other daemons get built).

**Comment by cdecker** [comment]
Not too familiar with Makefile syntax to be honest, but I noticed that when reordering the `default` rule in the main file with the includes below, the first include will be used for the `default` rule and the one we want is skipped. So I thought these rules do not get composed, instead the files are just literally included and then the first `default` rule gets executed. That's also why `default: $(ALL_PROGRAMS)` doesn't seem to work because `cli/lightning-cli` gets added to that list late.

What's the correct way of doing this?

**Comment by rustyrussell** [comment]
OK, so make syntax is kind of fun.

There are several things here.
1. If A needs B, you say "A: B"
2. If A needs B and C, you can either do "A: B C" or two separate lines: "A: B" and "A: C".  Order here doesn't matter.
3. If you need to tell make *what* to do, *only one* of the dep lines (or an empty one, ie. "A:") has a set of rules underneath it, tab-indented.  If none have it, it tries pattern then built-in rules, otherwise assumes it's a dummy target.
4. Variables are expanded at the point they're used, and there's no warning if a variable is not set (typos beware!).  So you have to set before use.
5. Make defaults to running the first rule in the makefile (in our case, I called it 'default').

So, this is why: "default: $(ALL_PROGRAMS)" doesn't work.  'default' has to appear first in the Makefile, but ALLPROGRAMS isn't set then.  SO we could do 'default: all-programs' and then after including all the other makefiles, 'all-programs: $(ALL_PROGRAMS)'.

I've done the latter...

**Comment by cdecker** [comment]
Oh, I see I was trying to work with lazy binding and didn't get it to work, hence my simple hack, but your fix is much better :wink:

**Pull request merged**
