### PR TITLE
Complete the JSON schemas.

### PR DESCRIPTION
**Pull request by rustyrussell**
Based on #4585, since that cleans up JSON outputs.

This has been a mammoth effort, but it finally works.  So much documentation cleanups, and JSON output fixes in here.

Glad it's finally done!

(If someone wants to write schemas & auto-gen docs for the rpc hooks, go for it!)

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
Look really good Rusty.

ack https://github.com/ElementsProject/lightning/pull/4594/commits/6637b11359b754db7b7a514f768fcf6d31b94d48

This test error proof that the JSON schema works, right? :-)

```
JSON report written to: report.json (69796936 bytes)
===Flaky Test Report===

test_htlc_accepted_hook_direct_restart failed (2 runs remaining out of 3).
	<class 'jsonschema.exceptions.ValidationError'>
	Additional properties are not allowed ('status' was unexpected)
```

**Comment by rustyrussell** [comment]
Yep!  And I fixed the schema!  (Which update the documentation!)

**Comment by rustyrussell** [comment]
Trivial rebase now #4585 is merged.

**Review by cdecker — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/4594/commits/44d53d9c45a31fccf5413da29159f82acfa6ab17

**Pull request merged**
