### PR TITLE
Add htlc rpc call

### PR DESCRIPTION
**Pull request by ffaex**
added "ListHtlcs" in contrib/msggen/msggen/utils/utils.py and
autogenerated with "contrib/msggen/msggen/__main__.py" 

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
Looking good, thanks. Please remove the extra merge commit and we're good to go :+1:

ACK https://github.com/ElementsProject/lightning/pull/6017/commits/fee26a565002c09dd332fe8a1de0b3735fb12af0

**Review by cdecker — APPROVED** [review]

**Comment by ffaex** [comment]
Done!

**Comment by cdecker** [comment]
It seems the schema files are missing, please add them to the same commit as the derived files.

**Comment by rustyrussell** [comment]
> It seems the schema files are missing, please add them to the same commit as the derived files.

The schema files are already in the tree?  Should I merge this @cdecker (after rebase?)

**Comment by cdecker** [comment]
Fixed up the changes, integrated with the option inference for multi-version support, and using `HtlcState` primitive now.

**Pull request merged**
