### PR TITLE
msgdecode tool

### PR DESCRIPTION
**Pull request by rustyrussell**

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Should we also install this (and `bolt11-cli`) in `$(prefix)/bin/`?

Or maybe in `$(pkglibexecdir)` and add hooks to them to `lightning-cli`.... e.g. `lightning-cli bolt11-cli` will  pass its arguments directly to `bolt11-cli` in `$(pkglibexecdir)`, as well as `decodemsg`, without opening an RPC channel to `lightningd` --- basically it just looks up pkglibexecdir for those two "commands".

**Comment by rustyrussell** [comment]
I figure devtools are not for install?  But if they're useful enough they may graduate, I guess.  I don't think we're there yet though.

**Comment by cdecker** [comment]
Very nice, I was hoping to implement this eventually too. Maybe we can change the print format slightly to produce valid JSON? That way we wouldn't lose the nesting, and context of a print would be a bit clearer.

**Comment by rustyrussell** [comment]
Let's add a -J flag later?  For now I don't want to spend more cycles on it.

**Pull request merged**
