### PR TITLE
fix: Fixed raising `TypeError` instead of `ValueError` for invalid types

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
In few places in the codebase, We are raising `ValueError` upon encountering an inappropriate type. It is more appropriate to raise `TypeError` instead of `ValueError` at these places:

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Mh maybe you are right, but maybe this will break a lot of stuff?

Running the CI to see if there are no case where we check for this cases just to make sure that you are not introducing regression :)

**Comment by Sai-Suraj-27** [comment]
> Mh maybe you are right, but maybe this will break a lot of stuff?
> 
> Running the CI to see if there are no case where we check for this cases just to make sure that you are not introducing regression :)

Hey, thanks for the review. I'm not sure how this will break a lot of stuff because I am new to the codebase and don't have that much understanding yet. If possible can you please elaborate, why this might break some stuff?
Thank you.

**Comment by vincenzopalazzo** [comment]
>If possible can you please elaborate, why this might break some stuff?

because our tests check for the exception too, but I think the cases that you want to cover are not used in the test.

But please fix the error inside the CI in this way we can be sure

**Comment by cdecker** [comment]
CI should be able to tell us if/when we break something internally, or in the test-suite, externally I don't believe we have many devs using the library and care about the exception they catch.

That being said we have a lint failing:

```
contrib/pyln-client/pyln/client/plugin.py:953:34: E127 continuation line over-indented for visual indent
contrib/pyln-client/pyln/client/plugin.py:960:34: E127 continuation line over-indented for visual indent
make: *** [Makefile:534: check-python-flake8] Error 1
```

I reported that here, because it often gets drowned by parallel compilation steps continuing, and therefore it can be a bit tricky to find the reason for an aborted test :-)

**Comment by Sai-Suraj-27** [comment]
> CI should be able to tell us if/when we break something internally, or in the test-suite, externally I don't believe we have many devs using the library and care about the exception they catch.
> 
> That being said we have a lint failing:
> 
> ```
> contrib/pyln-client/pyln/client/plugin.py:953:34: E127 continuation line over-indented for visual indent
> contrib/pyln-client/pyln/client/plugin.py:960:34: E127 continuation line over-indented for visual indent
> make: *** [Makefile:534: check-python-flake8] Error 1
> ```
> 
> I reported that here, because it often gets drowned by parallel compilation steps continuing, and therefore it can be a bit tricky to find the reason for an aborted test :-)

Hey, @cdecker. Thanks for pointing out the problem, i think I resolved it. Can you please check now?

**Comment by cdecker** [comment]
Yep, this looks good :+1:, now we just have the "normal flakes" that are up to me to fix :wink:

**Pull request merged**
