### PR TITLE
Reallow no gossip queries

### PR DESCRIPTION
**Pull request by rustyrussell**
LDK in some configurations gets upset.  @bluematt suggested we repurpose this bit slightly to mean "I have no useful gossip".  I've updated the BOLT feature deprecation https://github.com/lightning/bolts/pull/1092

I would like a point release to fix this if possible.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7174/commits/06e850c74e3b9c672386a4415ce6671034b93524

Would be good to keep the ldk use case in mind when we design the gossip 2.0

**Comment by TonyGiorgio** [comment]
Is there still a point release planned for this? Breaks our LDK integration with the release CLN release, which we need to attempt to fix CLN scaling issues we're seeing.

**Comment by vincenzopalazzo** [comment]
cc @cdecker for the point release info

**Comment by cdecker** [comment]
Sorry about the delay, building repro builds now and then releasing this later today 👍

**Pull request merged**
