### PR TITLE
Fix redundant includes. Fix inconsistent LIGHTNING_DIR_FILE_H defines. Add regression test.

### PR DESCRIPTION
**Pull request by practicalswift**
* Fix redundant includes: `foo.c` includes `bar.h`, but `bar.h` is already included in `foo.h`
* Fix inconsistent `LIGHTNING_DIR_FILE_H` defines
* Add regression test

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
ACK 75a7243cc8db8470706d5a08ad16e00b9ccc22d8

**Comment by practicalswift** [comment]
@ZmnSCPxj Pushed improved version. New version uses `git ls-files` and checks all three parts of the guard. Please re-review :-)

**Comment by ZmnSCPxj** [comment]
ACK 980a3d29b3d9b844c9075d21a628e4f7638fdf7d

**Comment by practicalswift** [comment]
Rebased! Please re-review :-)

**Pull request merged**
