### PR TITLE
Use external libraries and neaten release

### PR DESCRIPTION
**Pull request by rustyrussell**
I am working on a simple reproducible build script, at least for ubuntu 18.04 LTS.  These cleanups make things simpler.

### CODE REVIEW

**Comment by cdecker** [comment]
Awesome, this'll make the PPA builds way easier since I don't have to materialze the submodules when creating the tarball anymore.

**Comment by niftynei** [comment]
Travis is complaining about syntax errors, but otherwise lgtm

```
In tools/build-release.sh line 31:
	    echo Known targets: $ALL_TARGETS
                                ^----------^ SC2086: Double quote to prevent globbing and word splitting.
In tools/build-release.sh line 48:
    TARGETS=" $@ "
            ^----^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.

```

**Comment by cdecker** [comment]
concept ACK, pending script fix :wink:

**Comment by rustyrussell** [comment]
Rebased (again)!  Will merge once Travis says OK.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2319/commits/54f7a98fc4bc84aa6e7157c39a88dadfba45493c

**Pull request merged**
