### PR TITLE
msggen: add low level fundchannel methods

### PR DESCRIPTION
**Pull request by daywalker90**
Based on: #7215 + #7217 + #7218 and the fix from #7230

This PR adds the following low level fundchannel methods in msggen:

- `fundchannel_cancel`
- `fundchannel_complete`
- `fundchannel_start`

### CODE REVIEW

**Comment by daywalker90** [comment]
Notice that i changed the `amount` in the json schema to `msat`

**Review by cdecker — CHANGES_REQUESTED** [review]
Just a small issue with the change in denomination in the schema (it's `sat` whenever on-chain is involved, and `msat` otherwise).

**Comment by daywalker90** [comment]
rebased on #7238

**Comment by cdecker** [comment]
This was a clean rebase, I'll merge asap.

**Comment by cdecker** [comment]
Rebased on top of `master`

**Pull request merged**
