### PR TITLE
pyln: Fix an issue with the LightningConnection short-reading

### PR DESCRIPTION
**Pull request by cdecker**
We may end up with a short read, that is not empty, when a message gets fragmented during transport, so we need to loop until we either reach the full size or we have an empty read indicating a dropped connection.

Changelog-None

### CODE REVIEW

**Comment by rustyrussell** [comment]
Ack bdbbf4c558fe9440c98e96a5b88e757827b6a889

**Review by vincenzopalazzo — COMMENTED** [review]
Mh! This could fix lnprototest I think?

**Review by vincenzopalazzo — APPROVED** [review]
This is the error that we got https://github.com/ElementsProject/lightning/issues/5683 and it is in the init connection. 

I think this is the cause, I will try to take a look, but for now let's land it

ACK https://github.com/ElementsProject/lightning/pull/5758/commits/bdbbf4c558fe9440c98e96a5b88e757827b6a889

P.S: is it possible to make a small pre-release of the pyln-proto?

**Comment by cdecker** [comment]
@vincenzopalazzo if you enable logging you should be able to see `pyln.proto.wire.LightningConnection` logging a warning about a short-read (I had a mixup of lengths logged in that message, and it'll expecting to read 18 bytes, when the real expected length was longer).

Otherwise you can cherry-pick this and try testing lnprototest with and without the patch.

**Comment by vincenzopalazzo** [comment]
Thanks @cdecker the solution looks promising and I need just to play with it a little bit.

**Pull request merged**
