### PR TITLE
doc: fix GH/readthedocs rendering of manual pages.

### PR DESCRIPTION
**Pull request by rustyrussell**
They render the comment as if it's in the list.

Old: https://github.com/ElementsProject/lightning/blob/master/doc/lightning-addgossip.7.md#return-value

New: https://github.com/ElementsProject/lightning/blob/a5a2370d36437b323883c125dabcfba02adcfdfc/doc/lightning-addgossip.7.md#return-value

Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/rustyrussell/lightning/commit/a5a2370d36437b323883c125dabcfba02adcfdfc

lovely this autogenated stuff 😸

**Comment by cdecker** [comment]
> ack [rustyrussell@a5a2370](https://github.com/rustyrussell/lightning/commit/a5a2370d36437b323883c125dabcfba02adcfdfc)

@vincenzopalazzo please note that the @bitcoin-bot will only recognize the commit if you either put the simple hash or the URL pointing to the hash in this repository. It does not recognize links to forks and will not recognize actual MD link syntax. These are the formats we do accept:

```
ACK a5a2370d36437b323883c125dabcfba02adcfdfc
ACK https://github.com/ElementsProject/lightning/pull/4759/commits/a5a2370d36437b323883c125dabcfba02adcfdfc
```

**Comment by cdecker** [comment]
Rebased due to conflick with fetchinvoice from master
ACK 138af3f71

**Comment by vincenzopalazzo** [comment]
You have right @cdecker, it looks like that the commit hash in the Github PR page point in the original PR. I think.

Thanks to fix me!

**Pull request merged**
