### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by RvMp**
Someone has a sticky F key :-)

### CODE REVIEW

**Comment by practicalswift** [comment]
"iff" is intentional and not a spelling mistake – see https://en.wikipedia.org/wiki/If_and_only_if

Perhaps it should be expanded from "iff" to "if and only if" to avoid confusion? :-)

**Comment by RvMp** [comment]
... not a native English speaker. Let me fix that :-)

**Comment by RvMp** [comment]
Any chance referrring does also mean something else ;-)

**Comment by practicalswift** [comment]
@RvMp The "referrring" fix looks right. Can't believe I missed that typo! :-)

**Comment by rustyrussell** [comment]
Well, I would have left it as 'iff', but I like the rremoval, so I'll apply it!

Thanks

**Pull request merged**
