### PR TITLE
Configurator cross fix

### PR DESCRIPTION
**Pull request by rustyrussell**
This is my preferred fix for #1090. @icota @arowser @Sjors ?

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Looks OK to me, would ACK, but deferring to the affected users.

**Comment by arowser** [comment]
ACK

**Comment by icota** [comment]
ACK
For reference, to make `qemu-arm` run cross compiled configurator tests without complaining use something like: `CONFIGURATOR_CC="arm-linux-androideabi-clang -static"`

**Comment by Sjors** [comment]
I was able to run `make` on macOS 10.13.3

**Comment by cdecker** [comment]
ACK e9a35f5

**Pull request merged**
