### PR TITLE
Fix sql crash, update test, make it run under CI

### PR DESCRIPTION
**Pull request by rustyrussell**
TIL we do not run openchannel("v2") tests in CI!  Oops.

### CODE REVIEW

**Review by endothermicdev — APPROVED** [review]
ACK df4a7170f68297dbb14cc1126da4a37b5172cf76

**Comment by rustyrussell** [comment]
DF and elements don't mix for now, disabled test under elements.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6046/commits/e133797f543f8f1741836c275cfd2d44a5fa8fa5

**Comment by endothermicdev** [comment]
ACK 2ed5f4c26ecdc72e81747d2789d59f92af3ab531

**Pull request merged**
