### PR TITLE
Add circleci support for building images and pushing to docker when t…

### PR DESCRIPTION
**Pull request by NicolasDorier**
The following environment variable which need to be configured in CircleCI
`DOCKERHUB_REPO` (for example `elementsproject/lightning`)
`DOCKERHUB_USER` (for example `nico`)
`DOCKERHUB_PASS` (for example `hello`)

Every time there is a new tagged release with the format like `v1.2.3`, this pull request should automatically do the following on CircleCI:
* Build a docker image for x64, tag it and push (`elementsproject/lightning:1.2.3-amd64`)
* Build a docker image for arm32v7, tag it and push (`elementsproject/lightning:1.2.3-arm32v7`)
* Build a docker image with `DEVELOPER=1`, tag it and push (`elementsproject/lightning:1.2.3-dev`)
* Build a manifest image, tag it and push (`elementsproject/lightning:1.2.3`)

On top of this, every times there is a commit on any branch, it will attempt to build without publishing. Ensuring you did not break the build process. 

It uses the credentials `nico` and `hello` to connect to dockerhub in this example.

As a result, you can run the image `elementsproject/lightning:1.2.3` on both arm7v32 and amd64.

This is a modified version of what I use for BTCPay, still need to test it to be sure it works properly on this repo.

The use of `docker_layer_caching` make builds way faster, especially when debugging. However this seems to be a [premium feature](https://circleci.com/docs/2.0/docker-layer-caching/). However if my memory is correct, this is still enabled for open source projects. (Though I think that for BTCPay, @kukks contacted them directly... my memory is failing me)

To test it:
* Fork your own (ie `nicolasdorier/lightning`)
* Create an account on circleci and attach it to your project
* In the project settings, configure the environment variable DOCKERHUB_REPO, DOCKERHUB_USER, DOCKERHUB_PASS . (I advise you to create a special account for this)
* Pull this PR
* Create a test tag (ie `v9.9.9`)
* Push to your repo
* Circle CI must run the build.

If you have a bug or need to fix something

* Remove the tag, (`git tag -d v9.9.9`)
* Make your change and commit
* Re-tag (`git tag -a v9.9.9 -m v9.9.9.9`)
* Re-push the tags (`git push nicolasdorier --force --tags`)

# Note to maintainers of this repository

After merging this:
* Create an account on circleci
* Attach to this repo (this will give some rights to [CircleCI to this repo](https://circleci.com/docs/2.0/gh-bb-integration/#overview))
* In the advanced settings (which will be https://circleci.com/gh/ElementsProject/lightning/edit#advanced-settings), turn `Build forked pull requests` to `on`
* Setup DOCKERHUB_REPO, DOCKERHUB_USER, DOCKERHUB_PASS environment variables ([not shared on forked pull requests](https://circleci.com/docs/2.0/oss/))

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Ok I cross checked and this is indeed surprisingly the case.
I am trying to find an alternative.

I will try

1. Create a new GitHub user: e.g. (circleci-builder@example.com) 
2. Grant read-only access to specific repositories to the new user. 
3. Configure CI to use that user

and see if that work

**Comment by NicolasDorier** [comment]
It does not work, CircleCI asks for being admin of the repo.

What about I add the docker build to Travis? We will miss the multi arch image published on docker hub, but at least we can have travis check on the arm and x64 builds.

**Comment by rustyrussell** [comment]
Yes, let's do that then?  Sorry to be a pain...

**Comment by NicolasDorier** [comment]
Not that complicated, that's understandable. I actually thought it was only read-only, and by looking closer to it I saw that. I need to find a long term solution to this problem for all my repo now.

**Comment by rustyrussell** [comment]
So, should I apply this or not?  Unsure whether it's still useful for you?

**Comment by NicolasDorier** [comment]
Not directly useful to me, as I have my own fork of c-lightning with the images built to my own repo.

Though I will still add the Travis support to build the images to make sure you guys do not break the ARM builds by mistake.

**Comment by cdecker** [comment]
Pushing from a public Travis instance is a no-go as well, since it is trivial for a user to create a PR that leaks the configured password in the logs or by pinging a server containing the passwords.

**Comment by NicolasDorier** [comment]
@cdecker the environment variables are not available on a PR build. (At least on CircleCI and Appveyor, I would be surprised if that's not the case with travis)

**Comment by rustyrussell** [comment]
Closing this, since seems like we can't use circle-ci.

**Pull request closed without merging**
