### PR TITLE
listpeerchannels: split conversion into stages

### PR DESCRIPTION
**Pull request by rustyrussell**
This is #5568 split into simple commits.  Hopefully this will not just help with review, but with debugging!

### CODE REVIEW

**Comment by rustyrussell** [comment]
Moving to draft, since https://github.com/ElementsProject/lightning/pull/5825/commits/8f0cdb842842eba697248bb0b2fbd2064dfd41ee is suspicious.

Is it really the case that bookkeeper won't see the payment if it happens just before the node is shutdown? @niftynei

**Review by vincenzopalazzo — COMMENTED** [review]
Sorry for the messy history, I should do a better job with it and make life easier for everybody.

I think the last change that this PR needs is

`rm contrib/pyln-testing/pyln/testing/node_pb2.py` and `make -j$(nproc) check DEVELOPER=1`

this will regenerate the python code that we had, maybe this works also without removing the file?

**Comment by rustyrussell** [comment]
OK, I've further diagnosed the bookkeeper issue.

What happens (once listpeers is faster due to removal of channels[]):

1. Two payments (111 msat and 222 msat) are complete.
2. One payment (4,000,000 msat) is half-complete: l2 sends removal and sig, but stops before l1 reply.  So bookkeeper's notification not called.
3. l1 goes onchain, with that 4M msat HTLC resolved.
4. bookkeeper records this differently.

Before (all settled before unilateral close):

```
DEBUG:root:{
  "id": "pytest:bkpr-listaccountevents#23",
  "result": {
    "events": [
      {
        "account": "wallet",
        "type": "channel",
        "tag": "journal_entry",
        "credit_msat": "0msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "timestamp": 1671162611,
        "is_rebalance": false
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "channel_open",
        "credit_msat": "0msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "39d55b0463a19f49e31e5dca98c5af17721b33383c603d9f535c451590a0e712:1",
        "timestamp": 1671162614,
        "blockheight": 103
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "channel",
        "tag": "invoice",
        "credit_msat": "111msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "payment_id": "edaf67a40f8ca36ae02832ca591cff0d6be6fd05dac28addea5b8359a697e855",
        "part_id": 0,
        "timestamp": 1671162624,
        "description": "JPLcIsLkZ4PIl04gljQh",
        "is_rebalance": false
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "channel",
        "tag": "invoice",
        "credit_msat": "222msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "payment_id": "be8ea4c3d7cc291a76ae865d2feda2a85de28d405b0f1877919aeb0b225f112b",
        "part_id": 0,
        "timestamp": 1671162625,
        "description": "xyGn04WTTt8WM33A2xqJ",
        "is_rebalance": false
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "channel",
        "tag": "invoice",
        "credit_msat": "4000000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "payment_id": "43006c98d17c4d72a81a256e0ce7260d940fde3b5757bcba3a209b7559837053",
        "part_id": 0,
        "timestamp": 1671162627,
        "description": "xohM9goEbViIiTRuzzPl",
        "is_rebalance": false
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "channel_close",
        "credit_msat": "0msat",
        "debit_msat": "4000333msat",
        "currency": "bcrt",
        "outpoint": "39d55b0463a19f49e31e5dca98c5af17721b33383c603d9f535c451590a0e712:1",
        "txid": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186",
        "timestamp": 1671162629,
        "blockheight": 104
      },
      {
        "account": "wallet",
        "origin": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "anchor",
        "credit_msat": "330000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186:0",
        "timestamp": 1671162629,
        "blockheight": 104
      },
      {
        "account": "external",
        "origin": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "anchor",
        "credit_msat": "330000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186:1",
        "timestamp": 1671162629,
        "blockheight": 104
      },
      {
        "account": "wallet",
        "origin": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "deposit",
        "credit_msat": "4000000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186:2",
        "timestamp": 1671162629,
        "blockheight": 104
      },
      {
        "account": "external",
        "origin": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "chain",
        "tag": "to_them",
        "credit_msat": "982975000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186:3",
        "timestamp": 1671162629,
        "blockheight": 104
      },
      {
        "account": "12e7a09015455c539f3d603c38331b7217afc598ca5d1ee3499fa163045bd538",
        "type": "onchain_fee",
        "tag": "onchain_fee",
        "credit_msat": "333msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "timestamp": 1671162629,
        "txid": "2a35b9498dfa9881b5b8e6a5844db6af4f520d7c077d872790c7c4dd7bf8e186"
      }
    ]
  }
}
```

After (one settled by unilateral close):

```
DEBUG:root:{
  "id": "pytest:bkpr-listaccountevents#19",
  "result": {
    "events": [
      {
        "account": "wallet",
        "type": "channel",
        "tag": "journal_entry",
        "credit_msat": "0msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "timestamp": 1671162699,
        "is_rebalance": false
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "channel_open",
        "credit_msat": "0msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "500e5492b6ab78e62c7fdd4e29de39cfb829e41e42b341e0ed12188e3b98e043:0",
        "timestamp": 1671162702,
        "blockheight": 103
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "channel",
        "tag": "invoice",
        "credit_msat": "111msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "payment_id": "2b9320b8d31dc5767a0c9d7302983a1c3d86dbf489cd0f1e92a81ce8206c9fac",
        "part_id": 0,
        "timestamp": 1671162712,
        "description": "ILn6TzJJn6OrB8qinufP",
        "is_rebalance": false
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "channel",
        "tag": "invoice",
        "credit_msat": "222msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "payment_id": "7154be1f3d8f5f19d11fffbb832cbdc4a51b094cda189a9023329db84307b206",
        "part_id": 0,
        "timestamp": 1671162713,
        "description": "b1GyiJYLKeu39Fyi8aRX",
        "is_rebalance": false
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "channel_close",
        "credit_msat": "0msat",
        "debit_msat": "333msat",
        "currency": "bcrt",
        "outpoint": "500e5492b6ab78e62c7fdd4e29de39cfb829e41e42b341e0ed12188e3b98e043:0",
        "txid": "478dd6ba6f98c393bb207e5849c86494443c194c0c94993fd49f05fcf93af2b7",
        "timestamp": 1671162716,
        "blockheight": 104
      },
      {
        "account": "wallet",
        "origin": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "anchor",
        "credit_msat": "330000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "478dd6ba6f98c393bb207e5849c86494443c194c0c94993fd49f05fcf93af2b7:0",
        "timestamp": 1671162716,
        "blockheight": 104
      },
      {
        "account": "external",
        "origin": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "anchor",
        "credit_msat": "330000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "478dd6ba6f98c393bb207e5849c86494443c194c0c94993fd49f05fcf93af2b7:1",
        "timestamp": 1671162716,
        "blockheight": 104
      },
      {
        "account": "wallet",
        "origin": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "deposit",
        "credit_msat": "4000000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "478dd6ba6f98c393bb207e5849c86494443c194c0c94993fd49f05fcf93af2b7:2",
        "timestamp": 1671162716,
        "blockheight": 104
      },
      {
        "account": "external",
        "origin": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "chain",
        "tag": "to_them",
        "credit_msat": "982975000msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "outpoint": "478dd6ba6f98c393bb207e5849c86494443c194c0c94993fd49f05fcf93af2b7:3",
        "timestamp": 1671162716,
        "blockheight": 104
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "channel",
        "tag": "penalty_adj",
        "credit_msat": "3999667msat",
        "debit_msat": "0msat",
        "currency": "bcrt",
        "timestamp": 1671162716,
        "is_rebalance": false
      },
      {
        "account": "43e0983b8e1812ede041b3421ee429b8cf39de294edd7f2ce678abb692540e50",
        "type": "channel",
        "tag": "penalty_adj",
        "credit_msat": "0msat",
        "debit_msat": "3999667msat",
        "currency": "bcrt",
        "timestamp": 1671162716,
        "is_rebalance": false
      }
    ]
  }
}
```

**Comment by rustyrussell** [comment]
I've rebased this onto master; it deprecates the schema and doesn't remove it now.  We don't have deprecations for *parameter* removal, so that still gets removed entirely.

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Looks like the bookkeeper error is hide under the following one

```
=========================== short test summary info ============================
FAILED tests/test_connection.py::test_wumbo_channels - KeyError: 'channels'
============ 1 failed, 499 passed, 54 skipped in 1863.02s (0:31:03) ============
```

I think this is one reason to prioritize this PR and not merge it close to the end of the merge windows, this PR will break many (if not all) others PRs

**Comment by rustyrussell** [comment]
These changes always find things that have changed since I did the initial sweep!  No big deal, I'm re-testing now, rebased on master.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5825/commits/6b4166627b720b7bf5114cb723d29aae7c856746

**Pull request merged**
