### PR TITLE
Fix dockerfiles for arm64 and arm32

### PR DESCRIPTION
**Pull request by NicolasDorier**
Docker images arm32 and arm64 docker images were both broken.

I also moved back from `bookworm` to `bullseye`, as I don't have time to hunt why bookworm didn't work.

### CODE REVIEW

**Comment by rustyrussell** [comment]
These files are new in this release!  Cool that you're using them!  But

1. Does 32 bit even work for you?  It doesn't for @ShahanaFarooqui and we were still trying to figure out the rust issues...
2. Why regress 64 bit from Python 3.11 to 3.9?  It works for us?

Thanks!

**Comment by NicolasDorier** [comment]
I just took noticed that the builder step is using 3.9. As such, the runtime image should do the same to avoid funny behavior.
I don't know why builder step is using 3.9 specifically. It wasn't before.

If that fixed @ShahanaFarooqui problem I will try to bump to bookworm again and test it.

**Comment by NicolasDorier** [comment]
I missed the fact that @ShahanaFarooqui did a change to use `docker buildx` it may be why I have difficulties

**Comment by NicolasDorier** [comment]
So this PR https://github.com/ElementsProject/lightning/pull/6390 made lot's of change in the ARM64 which completely broke image.

It seems the intention was to use `docker buildx` to maintain a single dockerfile rather than several one, but this doesn't work at all.

I don't think I am able to fix those files. In our btcpay fork, I will restore the former docker files.

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier The goal was to fix these scripts to be able to release docker images for most common platforms. 

AFAIK, btcpayserver needs amd64, arm64v8 and arm32v7 images. We can now upload amd64 and arm64v8 images directly on Dockerhub to pull and maintaining the fork will not be required anymore. 

But I am still working on arm32v7 and it is failing with some circular errors related to rust. I will try to fix them before next release. Let us know if that works for you?

**Comment by NicolasDorier** [comment]
We can't rely on the docker hub of this repo. Our fork has some slight changes (https://github.com/btcpayserver/lightning/commit/a22d55afe577a913611255128256cec5614ff63d)

I will revert to using the old docker images on our fork for now and revisit the new one in the next release.

**Pull request closed without merging**
