### PR TITLE
lightningd/io_loop_with_timers.c: Move mainloop to its own source file, have chaintopology use it

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #2687

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Alternate solution for #2687 is to just fudge the fee estimation at the start.

**Comment by ZmnSCPxj** [comment]
Missing a `#include"../io_loop_with_timers.c"` in `lightningd/test/run-find_my_abspath.c`, will fix after several hours.

**Comment by ZmnSCPxj** [comment]
For that matter, why does `struct plugins` have its own `timers`?  Why not just unify it to a single `struct timers`?

**Comment by cdecker** [comment]
> For that matter, why does `struct plugins` have its own `timers`? Why not just unify it to a single `struct timers`?

I did that to better encapsulate the plugins and make sure we have full control over the timers we create (in the same allocation hierarchy).

**Comment by cdecker** [comment]
Am I correct in assuming the issue is that we don't process timers when starting the topology, therefore a failed fee estimate or a failed first block fetch will result in us hanging indefinitely?

**Comment by ZmnSCPxj** [comment]
> Am I correct in assuming the issue is that we don't process timers when starting the topology, therefore a failed fee estimate or a failed first block fetch will result in us hanging indefinitely?

Yes, I believe so.

**Comment by cdecker** [comment]
I took the liberty of add a test that reproduces #2687 first, this way we make sure the fix works and we don't get a regression later :-)

**Comment by cdecker** [comment]
I'll ack @ZmnSCPxj's part and let someone else ack mine :-)

ACK https://github.com/ElementsProject/lightning/pull/2690/commits/cb0b9f7c45760e87099368a4c1928071e44f4774

**Comment by m-schmoock** [comment]
ACK 592db38

Your test 592db38 without the fix properly xfails and demonstates the issue after a timeout of 70 seconds or so. It is also properly fixed by cb0b9f7 .

**Comment by m-schmoock** [comment]
ACK 592db38

Your test 592db38 without the fix properly xfails and demonstates the issue after a timeout of 70 seconds or so. It is also properly fixed by cb0b9f7 . I have some unrelated flakes sometimes okay sometimes not when running locally, but behaves same on master with or without this fix:

 - tests/test_connection.py::test_no_fee_estimate (flaky)
 - tests/test_plugin.py::test_openchannel_hook  (always timeout wait_for ONCHAIN)
 - tests/test_misc.py::test_funding_reorg_private (always timeout wait_for_log "Deleting channel")

**Pull request merged**
