### PR TITLE
bcli: fix compilation on 32-bit platforms.

### PR DESCRIPTION
**Pull request by rustyrussell**
Reported-by: Shahana Farooqui

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
ACK f87d65c35e960c4502fbf1e589c4fc37c5edbac8

**Comment by daywalker90** [comment]
I don't know how i missed these but please use `node_factory.get_unused_port()` instead of `reserve()`, See #7314

**Comment by ShahanaFarooqui** [comment]
The error from b-cli is gone but now I am getting another error on arm32:

```
231.7 plugins/renepay/mods.c: In function 'payment_continue':
231.7 plugins/renepay/mods.c:63:7: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
231.7    63 |       (u64)payment_virtual_program[payment->exec_state++];
231.7       |       ^
231.8 cc1: all warnings being treated as errors
231.9 make: *** [Makefile:301: plugins/renepay/mods.o] Error 1
```

**Comment by ShahanaFarooqui** [comment]
> I don't know how i missed these but please use `node_factory.get_unused_port()` instead of `reserve()`, See #7314

Thanks, changed reserve() to node_factory.get_unused_port().

**Comment by ShahanaFarooqui** [comment]
ACK 1b822669022dd082da53966e0ddb0658868c96d2

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7319/commits/1b822669022dd082da53966e0ddb0658868c96d2

**Pull request merged**
