### PR TITLE
Require nonzero payments

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #686

### CODE REVIEW

**Comment by cdecker** [comment]
LGTM

ACK 6ec24db

**Comment by rustyrussell** [comment]
Not clear this fixes the problem?

Someone could route a zero payment thru us.

And there's nothing wrong with 0 payments in theory.

**Comment by rustyrussell** [comment]
And we shouldn't crash. Sorry, on phone, will look at root cause.

**Comment by cdecker** [comment]
Closing in favor of #694

**Pull request closed without merging**
