### PR TITLE
Remove unused function json_dev_broadcast(...)

### PR DESCRIPTION
**Pull request by practicalswift**
Remove unused function `json_dev_broadcast(...)`.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
Maybe it should be a dev command? @rustyrussell seems to have written this code, so we should call him here.

**Comment by rustyrussell** [comment]
Hmm, a quick look at history says I moved it in 38cc6c2f2137acd2a8766a122d8084d974a01f7a but accidentally deleted the actual command.  Clearly, we never use it, so I'll delete the associated struct field as well.

**Comment by ZmnSCPxj** [comment]
Okay, will ACK when struct field is deleted also.

**Comment by practicalswift** [comment]
Updated! Please re-review :-)

**Comment by ZmnSCPxj** [comment]
ACK fdfe6e5076d8ebfd7f20926b69c3d90e076496fe

**Pull request merged**
