### PR TITLE
sphinx: fix potential data leak.

### PR DESCRIPTION
**Pull request by rustyrussell**
[ Based on #3245 to keep Travis happy: just look at last commit ]

https://github.com/lightningnetwork/lightning-rfc/pull/697
https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-November/002288.html

Reported-by: @roasbeef
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

Changelog-None

### CODE REVIEW

**Comment by niftynei** [comment]
ACK 5a24039

**Comment by cdecker** [comment]
I'd prefer we have a way to turn the random bytes off, or at least produce them in a reproducible way, e.g., usin chacha20 which is already in use elsewhere in the onion.

Otherwise we'll end up without test-vectors.

**Comment by rustyrussell** [comment]
> I'd prefer we have a way to turn the random bytes off, or at least produce them in a reproducible way, e.g., usin chacha20 which is already in use elsewhere in the onion.
> 
> Otherwise we'll end up without test-vectors.

Well, we already have a backdoor to set the session_key for testing, so we'd just need another one.

But you're right: generating it this way is Just Good Practice anyway, so let's do that.  Take II coming.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/3246/commits/d8c386a141beccc67fc9d30de70cf027331de089

**Pull request merged**
