### PR TITLE
splice: minor code cleanups

### PR DESCRIPTION
**Pull request by ddustin**
A few little stylistic things were bugging me when reading through the splice code so I cleaned them up.

ChangeLog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6729/commits/fa99d92f331a3795d6e9885b7696144688dde0a4

**Comment by rustyrussell** [comment]
Trivial rebase on master for CI...

**Comment by rustyrussell** [comment]
Fixed memleak due to tal off NULL....

**Comment by ddustin** [comment]
Thanks for the memory fixes 🙏. Looks like this was triggered by removing the ugly way of explicitly free'ing: https://github.com/ElementsProject/lightning/pull/6729/commits/25f7b718782322250e889cc4bd0a218b182ece69#diff-b1299b24697159a06e7b426c5086c36df8e48db15739a0e301d53a9a21149722L770
```
	/* valgrind complains last_tx is leaked so we explicitly free it
	 * DTODO: investigate this more. */
	for (size_t i = 0; i < tal_count(peer->splice_state->inflights); i++) {
		inflight = peer->splice_state->inflights[i];
		tal_free(inflight->last_tx);
		tal_free(inflight);
	}
```

**Pull request merged**
