### PR TITLE
chaintopology: Protect against underflow when computing first_blocknum.

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #1423

(Hopefully)

Reported-by: @NicolasDorier

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Tested and it fixed my issue.

**Comment by NicolasDorier** [comment]
Just wondering though if it is regtest only issue or if also issue when node is still not synched?

**Comment by NicolasDorier** [comment]
You don't want `first_blocknum` to end up being 0 if mainnet or testnet is not synched/

**Comment by ZmnSCPxj** [comment]
If the bitcoind is reporting its highest blockheight as that low, I do not know what we can do other than to just follow it.

Or possibly respect `when_lightning_became_cool`, but I have not explored `chaintopology` as much; suggest @cdecker for more feedback on what to do if the `lightningd` is started with a brand-new `bitcoind` with very low blockheight.  Would it be fine to move `first_blocknum` to `when_lightning_became_cool`?

**Comment by NicolasDorier** [comment]
@ZmnSCPxj C grammar hitler bot kicked in

**Comment by ZmnSCPxj** [comment]
Fixed grammarbot complaint point, rebase.

**Comment by rustyrussell** [comment]
Ack 0161222c9370246d60c3d06b51bfc2976ed201d4

**Pull request merged**
