### PR TITLE
Makefile: fix some Makefiles in subdirectories for "make clean" to properly remove all object files

### PR DESCRIPTION
**Pull request by siburu**
"make clean" removes all object files listed in $(ALL_OBJS), which is derived from $(ALL_C_SOURCES).
 The following files are missing from $(ALL_C_SOURCES) therefore some object files are not removed by "make clean".

- Files listed in $(LIGHTNINGD_SRC_NOHDR)
- common/status_levels.c

This PR fixes lightningd/Makefile and common/Makefile for adding the above files to $(ALL_C_SOURCES).

And also, this PR fixes some typos in external/Makefile.

Signed-off-by: YOSHIDA Masanori <masanori.yoshida@gmail.com>
Changelog-None

### CODE REVIEW

**Comment by jsarenik** [comment]
Thank you! Tested ACK 1a87869

The diff of `find . -name '*.o'` (after full compile and `make clean`):

```diff
--- before	2020-10-25 12:12:42.975195609 +0100
+++ after	2020-10-25 12:13:43.665676738 +0100
@@ -1,6 +1,5 @@
 $ find . -name '*.o'
 ./common/status_levels.o
-./lightningd/signmessage.o
 ./external/x86_64-linux-gnu/libbacktrace-build/print.o
 ./external/x86_64-linux-gnu/libbacktrace-build/dwarf.o
 ./external/x86_64-linux-gnu/libbacktrace-build/mmapio.o
```

@siburu is `/common/status_levers.o` OK to stay?

**Comment by jsarenik** [comment]
Tested ACK 1a87869f1

**Comment by siburu** [comment]
@jsarenik Thank you for testing!


> is /common/status_levers.o OK to stay?

Oh, `status_levels.c` appears to have been added recently.
The file should be added to $(COMMON_SRC_NOGEN), but it's not yet.

I'll do it with this pull request.

**Comment by jsarenik** [comment]
@siburu here is the full `after` file, just in case also test object files need to be removed:

```
$ find . -name '*.o'
./common/status_levels.o
./external/x86_64-linux-gnu/libbacktrace-build/print.o
./external/x86_64-linux-gnu/libbacktrace-build/dwarf.o
./external/x86_64-linux-gnu/libbacktrace-build/mmapio.o
./external/x86_64-linux-gnu/libbacktrace-build/mmap.o
./external/x86_64-linux-gnu/libbacktrace-build/state.o
./external/x86_64-linux-gnu/libbacktrace-build/elf.o
./external/x86_64-linux-gnu/libbacktrace-build/atomic.o
./external/x86_64-linux-gnu/libbacktrace-build/sort.o
./external/x86_64-linux-gnu/libbacktrace-build/simple.o
./external/x86_64-linux-gnu/libbacktrace-build/backtrace.o
./external/x86_64-linux-gnu/libbacktrace-build/fileline.o
./external/x86_64-linux-gnu/libbacktrace-build/posix.o
./tools/test/gen_test.o
./tools/test/run-test-wire.o
./tools/test/gen_print.o
```

And what about external?

**Comment by siburu** [comment]
@jsarenik Thank you for the good hint!
I found some typos in external/Makefile and fixed them!

> ./common/status_levels.o
Is the file still there?
In my environment (Arch Linux), it's removed correctly with "make clean".

**Comment by siburu** [comment]
@jsarenik
```
./tools/test/gen_test.o
./tools/test/run-test-wire.o
./tools/test/gen_print.o
```

On the latest master branch, `gen_*.c` have been renamed to `*_gen.c`.
See 5e865ce42bbf1c7837e1ade930d6f8cab1d604f1

And on my machine, the above three object files (with `gen_*.o` replaced with `*_gen.o`) are properly removed with "make clean".
Could you please confirm it?

**Comment by jsarenik** [comment]
Checking now…

**Comment by jsarenik** [comment]
All I get now are the object files in `tools/test` directory.

```
$ find . -name '*.o'
./tools/test/gen_test.o
./tools/test/run-test-wire.o
./tools/test/gen_print.o
```

Tested 6f8781e79

**Comment by jsarenik** [comment]
Ah, I just did `git clean -xffd` and trying again.

**Comment by jsarenik** [comment]
All clean now. Tested ACK 6f8781e79

Thank you!!!

**Comment by siburu** [comment]
@jsarenik Thank you!!!

**Comment by cdecker** [comment]
Excellent work @siburu and @jsarenik. By the way the ACK bot is pretty picky in what it'll accept as an ACK (so it doesn't wrongly mark things as ack'd), so for it to pick this up in the future you should use `ACK [commithash]` on a line by itself @jsarenik (it'll also pick up the 6 char short version and the link to commit version).

ACK 6f8781e

**Comment by rustyrussell** [comment]
Thank you so much for chasing these down!

**Pull request merged**
