### PR TITLE
Fix plugin startup crash

### PR DESCRIPTION
**Pull request by rustyrussell**
Thanks to @m-schmoock for the excellent bug report.

Fixes: https://github.com/ElementsProject/lightning/issues/7671

### CODE REVIEW

**Comment by m-schmoock** [comment]
ACK e13d34c

Thanks. Does what its supposed to do.
Now I know it was the backup plugin that crashed with 
```
2024-09-17T06:20:27.651Z UNUSUAL plugin-backup-cli: Killing plugin: Invalid/missing result tok in '{"jsonrpc": "2.0","id": 19,"error": {"code":-4, "message":"Plugin terminated before replying to RPC call."}}'
```

Anyway, the daemon was able to do the database update and the backup plugin came online just normal after that.

The test runs fine on my development machine ( x86_64 ) but I can't run it on the Raspberry ( aarch64 ) likely for unrelated reasons:

```
FAILED tests/test_plugin.py::test_plugin_fail_on_startup - jsonschema.exceptions.ValidationError: 0msat is not of type 'msat
```

**Review by m-schmoock — APPROVED** [review]
ACK e13d34c

Thanks. Does what its supposed to do.
Now I know it was the backup plugin that crashed with 
```
2024-09-17T06:20:27.651Z UNUSUAL plugin-backup-cli: Killing plugin: Invalid/missing result tok in '{"jsonrpc": "2.0","id": 19,"error": {"code":-4, "message":"Plugin terminated before replying to RPC call."}}'
```

Anyway, the daemon was able to do the database update and the backup plugin came online just normal after that.

The test runs fine on my development machine ( x86_64 ) but I can't run it on the Raspberry ( aarch64 ) likely for unrelated reasons:

```
FAILED tests/test_plugin.py::test_plugin_fail_on_startup - jsonschema.exceptions.ValidationError: 0msat is not of type 'msat
```

**Comment by m-schmoock** [comment]
Ah nevermind, found out the issue on my Raspberry. It was using the 23.0.8 pyln-client for some reason and the v24 pyln-testing

**Comment by ShahanaFarooqui** [comment]
ACK e13d34c4b203433d59e89e02a90b49df82fd6b52

**Pull request merged**
