### PR TITLE
Fix the onion tool

### LINKED ISSUE #503: run-sphinx --generate segfaults
`run-sphinx` segfaults when no parameter is given to the `--generate` flag:

```
$ common/test/run-sphinx --generate
Segmentation fault (core dumped)
```

When passing parameters to the `--generate` flag the following output is given:

```
towire_u8 called!
Aborted (core dumped)
```

What is an example of a correct invocation of `run-sphinx --generate …` that will yield non-error output? :-)

### PR DESCRIPTION
**Pull request by cdecker**
It also gave me the opportunity to retest the test vectors in the spec, and against the `lnd` tool.

Fixes #503

### CODE REVIEW

**Comment by practicalswift** [comment]
Excellent! Concept ACK

**Comment by cdecker** [comment]
btw if you want to test if it's working this'll do it:

```
valgrind -q --leak-check=full ./onion --generate 4141414141414141414141414141414141414141414141414141414141414141 \
		4242424242424242424242424242424242424242424242424242424242424242 \
		4343434343434343434343434343434343434343434343434343434343434343 \
		4444444444444444444444444444444444444444444444444444444444444444 \
		4545454545454545454545454545454545454545454545454545454545454545 | tail -n 1 | \
		valgrind -q --leak-check=full ./onion --decode 4141414141414141414141414141414141414141414141414141414141414141 | \
		valgrind -q --leak-check=full ./onion --decode 4242424242424242424242424242424242424242424242424242424242424242 | \
		valgrind -q --leak-check=full ./onion --decode 4343434343434343434343434343434343434343434343434343434343434343 | \
		valgrind -q --leak-check=full ./onion --decode 4444444444444444444444444444444444444444444444444444444444444444 | \
		valgrind -q --leak-check=full ./onion --decode 4545454545454545454545454545454545454545454545454545454545454545
```

It'll spit out the fully decrypted onion, with lots of 0x00-bytes which is what the fillers are before encryption :-)

**Comment by practicalswift** [comment]
@cdecker Seems to work as expected! :-)

What about …

```diff
diff --git a/devtools/onion.c b/devtools/onion.c
index 8ae1366..061261e 100644
--- a/devtools/onion.c
+++ b/devtools/onion.c
@@ -28,7 +28,7 @@ static void do_generate(int argc, char **argv)
                if (secp256k1_ec_pubkey_create(secp256k1_ctx, &path[i].pubkey,
                                               privkeys[i]) != 1)
                        errx(1, "Could not decode pubkey");
-               printf("Node %d pubkey %s\n", i, secp256k1_pubkey_to_hexstr(ctx, &path[i].pubkey));
+               fprintf(stderr, "Node %d pubkey %s\n", i, secp256k1_pubkey_to_hexstr(ctx, &path[i].pubkey));
        }

        for (int i = 0; i < num_hops; i++) {
@@ -38,7 +38,7 @@ static void do_generate(int argc, char **argv)
                       sizeof(hops_data[i].channel_id));
                hops_data[i].amt_forward = i;
                hops_data[i].outgoing_cltv = i;
-               printf("Hopdata %d: %s\n", i, tal_hexstr(NULL, &hops_data[i], sizeof(hops_data[i])));
+               fprintf(stderr, "Hopdata %d: %s\n", i, tal_hexstr(NULL, &hops_data[i], sizeof(hops_data[i])));
        }

        struct onionpacket *res =
```

… to avoid having to `tail -1` when piping? :-)

How does `run-sphinx` relate to `onion`?

**Comment by cdecker** [comment]
Good idea @practicalswift, it's also what the `lnd` tool does.

**Comment by cdecker** [comment]
Translating @practicalswift into an ack that ackbot understands :-)

ACK 02449b0

**Pull request merged**
