### PR TITLE
reckless: simplify installer registration

### PR DESCRIPTION
**Pull request by endothermicdev**
Fixes a bug in installer registration where executable is evaluated before entrypoints and other details are added.

***RECKLESS STDERR***
Traceback (most recent call last):
  File lightning/tools/reckless, line 382, in <module>
    INSTALLERS['nodejs'].add_entrypoint('{name}')
KeyError: 'nodejs'

Reported by @ksedgwic

Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6195/commits/1495c889088d418c46d53e96b67baae9c70050fd

CI looks unrelated

**Comment by ksedgwic** [comment]
This worked for me. Thanks!

**Comment by endothermicdev** [comment]
Added a stderr check to avoid pip as root warning reported by @ksedgwic 
`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

**Comment by ShahanaFarooqui** [comment]
ACK https://github.com/ElementsProject/lightning/pull/6195/commits/96618521f6de1bfdde2b585b527f6e1c3dcf7994

**Pull request merged**
