### PR TITLE
Clean-up some warnings. Initialized some uninitialized variables.

### PR DESCRIPTION
**Pull request by Chirimen-Jako**
### Changed

- Clean-up some warnings.
- Initialize some uninitialized auto variables which value was unstable.

### CODE REVIEW

**Comment by Chirimen-Jako** [comment]
Hi,
Thanks you very much for your reviewing. Sorry to take your precious time.
> initializing things which should not be initialized can cover up real bugs!
I agreed with it. However, I think disable warning is more risky.
I'm not sure there is a variable which should not be initialized in the C/C++ world.
Each of variables should be reviewed one by one and initialized by obviously invalid value in the future in my opinion.

Thanks!

**Comment by ZmnSCPxj** [comment]
> I agreed with it. However, I think disable warning is more risky.
I'm not sure there is a variable which should not be initialized in the C/C++ world.
Off course, I understand performance problem. No need to initialize unused memory, or if it's overwritten by valid value exactly. But some of them are referred in the code context in this case.
Each of variables should be reviewed one by one and initialized by obviously invalid value in the future in my opinion.

We have found `valgrind` to be more reliable in finding *actual* uninitialized memory on both stack and heap.  Indeed, initializing variables to "invalid" values tends to *hide* such uninitialized memory from `valgrind`.

As we run `valgrind` in our CI we prefer to keep variables uninitialized if possible, so that `valgrind` can find such bugs accurately (unlike the compilers, which are often hit-or-miss).

**Comment by Chirimen-Jako** [comment]
Thank you for your kind explanation.
I understood completely. Because I was using `BoundsChecker` (maybe, similar to `valgrind`) decades ago.

**Comment by cdecker** [comment]
This seems to be addressed now by #2884

**Pull request closed without merging**
