### PR TITLE
Improved display of lightning-cli help for humans

### PR DESCRIPTION
**Pull request by wythe**
The display format is now:
<pre>
command1
    description1

command2
    description2

    .
    .
    .
</pre>

### CODE REVIEW

**Comment by Sjors** [comment]
Tried on macOS. Way more readable...

**Comment by ZmnSCPxj** [comment]
I took the liberty of changing the test so that the CI passes.

**Comment by wythe** [comment]
I appreciate the help.  I have CI setup now.

**Comment by cdecker** [comment]
Excellent contribution, I always reverted to the JSON help because that was more readable, but now `-H` became usable :smile: 

ACK 0b82f42

**Pull request merged**
