### PR TITLE
Weekly cleanups

### PR DESCRIPTION
**Pull request by cdecker**
- Moves JSON-RPC setup below the pid-file
 - Fixes the builder with the missing dependencies for a2x which was failing on travis some times.

### CODE REVIEW

**Comment by cdecker** [comment]
Added one more commit that @rustyrussell requested.

**Comment by ZmnSCPxj** [comment]
ACK af98e7d5dee522375b8620559ebaddc4dc9cdd73

**Comment by rustyrussell** [comment]
Suggest splitting pidfile handling instead: better to do everything which could fail *before* we daemonize and can't print to stderr any more...

**Comment by cdecker** [comment]
> Suggest splitting pidfile handling instead: better to do everything which could fail before we daemonize and can't print to stderr any more...

Roger :+1:

**Comment by cdecker** [comment]
ACK eadc570

**Pull request merged**
