### PR TITLE
Notifications over GRPC

### PR DESCRIPTION
**Pull request by ErikDeSmedt**
This PR implements notifications over the `grpc`-interface.

The first commit introduces the json-schema's that are used to serialize notifications.

I've introduced notifications to msggen. This PR also introduces code that allows msggen to generate
   - structs that can deserialize JSON-notifications
   - the `.proto`-file that defines the grpc-interface
   - methods to convert notifications from JSON to protobuf
   - a function grpc-server
   
  I've updated the `grpc-plugin` to ensure it can support notifications.

### CODE REVIEW

**Review by cdecker — APPROVED** [review]

**Comment by ErikDeSmedt** [comment]
I've marked this PR as ready for review.

I am explicitly looking for review on the [choose better when subfield is optional](https://github.com/ElementsProject/lightning/pull/7084/commits/a1b4f8d31512798b1bfdc55877b7b3389b8f4d25) commit.

The proposed change also change generated code for schema's introduced before v24.05.
To my understanding this is safe for `protobuf` as the `optional`-keyword will not affect the wire-format.
For the `cln_rpc`-structs library users will have to update their code. However, the updated code will still work with older versions of Core Lightning.

**Comment by endothermicdev** [comment]
This still had a couple failing tests, but the logs have now expired.  Do you want help getting this PR through CI @ErikDeSmedt?

**Comment by ErikDeSmedt** [comment]
@endothermicdev : I've rebased it on top of master and the tests are mostly successful again. I assume the current failure is a flake.

Let me know if have any question or need help to merge this request

**Comment by cdecker** [comment]
Rebased on top of #7274 for immediate inclusion.

**Pull request merged**
