### PR TITLE
Fix bsd workflow

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
What we are fixing here?

**Comment by gruve-p** [comment]
FreeBSD test workflow has been disabled since one month because it keeps failing. This PR fixes that so the workflow can be re-enabled again.

**Comment by vincenzopalazzo** [comment]
mh! it was disabled because was flaky related to some ssh error, but I leave this review to @cdecker because I have no clue for this freebsd CI part!

**Comment by gruve-p** [comment]
> mh! it was disabled because was flaky related to some ssh error, but I leave this review to @cdecker because I have no clue for this freebsd CI part!

yes this PR fixes that SSH error

**Pull request closed without merging**
