### PR TITLE
Store optimizations: the JSON parts

### PR DESCRIPTION
**Pull request by rustyrussell**
You've reviewed these before, except for the two fixup! commits from your suggestions and the new "
lightning-cli: do pretty-printing" at https://github.com/ElementsProject/lightning/commit/72c4e42ad2bddca37f1f30aa89b0da5abea29fe5.

Otherwise, it's just a rebase, with benchmark numbers added to the commit msgs.

### CODE REVIEW

**Comment by rustyrussell** [comment]
... Trivial rebase to fix include order...

**Comment by SimonVrouwe** [comment]
Have you thought about [stop logging IO when accessing the IO log](https://github.com/ElementsProject/lightning/issues/2467#issuecomment-478238838)?

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2541/commits/d3d741fb2184aa323e047f21f5030cc8567c6178

**Comment by niftynei** [comment]
should we add the new `-R` flag to the Changelog?

**Pull request merged**
