### PR TITLE
contrib/startup_ln.sh updates, new contrib/giantnode.py

### PR DESCRIPTION
**Pull request by rustyrussell**
As promised to @ShahanaFarooqui this gives us the ability to make a giant test node.  There are also some optimizations required for doing it in a sane timeframe (I will create another PR for them!) but meanwhile you can simply download a pre-made one from https://ozlabs.org/~rusty/giantnodes.tar.xz

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
`giantnode.py` isn't passing the python linting.

**Comment by rustyrussell** [comment]
Make shellcheck happy and rebase on master....

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5549/commits/1baaef24b3273a2b545a26608e9368b61df796fc

**Comment by grubles** [comment]
>you can simply download a pre-made one from https://ozlabs.org/~rusty/giantnodes.tar.xz

Is there a corresponding bitcoind data directory for these nodes you can share too?

**Pull request merged**
