### PR TITLE
doc: update decode instruction for emergency.recover

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
Changelog-None

### CODE REVIEW

**Comment by adi2011** [comment]
lgtm!

**Review by nepet — APPROVED** [review]
ACK 2e8b3614a686717948bef46017b246378709872c

**Comment by adi2011** [comment]
ACK `2e8b361`

**Review by adi2011 — CHANGES_REQUESTED** [review]
<path/to/emergency.recover> instead of <emergency.recover-path>?
Similar to how it is described in hsmtool.c

**Review by adi2011 — APPROVED** [review]
ACK

**Review by nepet — APPROVED** [review]
ACK ccf18810f228f10b6dc9364bd12ce53bd7269223

**Pull request merged**
