### PR TITLE
Gossip rework part 3: gossipd now uses gossmap

### PR DESCRIPTION
**Pull request by rustyrussell**
~Based on #6904 ~ Merged into master!

Lots of moving code out of gossipd/routing.c, followed by getting rid of spam and zombie code.

Then we switch everything across to our new "gossmap_manage" API, and clean up.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Tweak to overstrict test change in final commit.

Fuzzer is complaining about leaks, but it seems to be an OpenSSL thing.  This series doesn't contain any fuzz changes, either...

**Comment by cdecker** [comment]
Yeah, I noticed the fuzzer complaining in some other PRs too. We should likely split out the fuzzer into a cron-triggered CI run instead, since at best it can catch newly introduced bugs (but randomized), and at worst it delays a completely unrelated PR just because it tried some other path through the program and hit a latent one.

**Comment by cdecker** [comment]
Rebased on top of `master`.

ACK 23cc4f35b9

**Comment by morehouse** [comment]
@cdecker 

> Yeah, I noticed the fuzzer complaining in some other PRs too. We should likely split out the fuzzer into a cron-triggered CI run instead, since at best it can catch newly introduced bugs (but randomized), and at worst it delays a completely unrelated PR just because it tried some other path through the program and hit a latent one.

This is not how the fuzz regression tests work in CI.  No new fuzzing is done, the fuzz target is only run on the existing inputs in the corpus.  The regression tests really do belong in CI, so they can actually detect regressions.

I haven't looked in detail, but one particular fuzz test seems to be failing due to a new bug in OpenSSL -- perhaps the CI container recently upgraded OpenSSL?  We should really figure out what's going on and fix that, or if necessary disable the particular test that is failing.  Getting rid of all fuzz regression testing in CI (#7029) is not the right solution IMO.

**Comment by rustyrussell** [comment]
> @cdecker
> 
> > Yeah, I noticed the fuzzer complaining in some other PRs too. We should likely split out the fuzzer into a cron-triggered CI run instead, since at best it can catch newly introduced bugs (but randomized), and at worst it delays a completely unrelated PR just because it tried some other path through the program and hit a latent one.
> 
> This is not how the fuzz regression tests work in CI. No new fuzzing is done, the fuzz target is only run on the existing inputs in the corpus. The regression tests really do belong in CI, so they can actually detect regressions.
> 
> I haven't looked in detail, but one particular fuzz test seems to be failing due to a new bug in OpenSSL -- perhaps the CI container recently upgraded OpenSSL? We should really figure out what's going on and fix that, or if necessary disable the particular test that is failing. Getting rid of all fuzz regression testing in CI (#7029) is not the right solution IMO.

I agree, and will create a patch to re-eneable all but this one until it's fixed...

**Comment by cdecker** [comment]
Good point, thanks @morehouse for the additional context, I did not know it was only regression testing, though I could have immagined as much from the Workflow name :-)

The CI and its brittleness have long been a major issue for CLN maintainers, and this is a good example: the first assumption is always that it must be a flake, not that there is something really wrong. Something something signal vs noise :-)

**Comment by morehouse** [comment]
Here's a PR to revert #7029 and avoid the LSan reports:  https://github.com/ElementsProject/lightning/pull/7032

**Pull request merged**
