### PR TITLE
bookkeeper, stop spamming to logs

### PR DESCRIPTION
**Pull request by niftynei**
The bookkeeper is unnecessarily noisy. I can fix her :toolbox:

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
looks like that there is an regression in the tests?

```
txids = [('B', '78ffed98b8d13732dc1b3cbd55b9166d1455e6d1ccb45dc73cecf95d8abe2c93')]
channel_id = '4f50a01658badd2d64e800314c6549664d6c0ce64158c746bfdedc8fb3d435a3'
actual = {'blockheight': 104, 'fees_paid_msat': 5526000msat, 'outputs': [{'account': 'external', 'credit_msat': 330000msat, 'cu...'bcrt', 'debit_msat': 894474000msat, ...}], 'txid': '78ffed98b8d13732dc1b3cbd55b9166d1455e6d1ccb45dc73cecf95d8abe2c93'}
exp = [('wallet', ['deposit'], None, None), ('cid1', ['htlc_timeout'], ['to_wallet'], 'C'), ('external', ['anchor'], None, None), ('wallet', ['anchor', 'ignored'], None, None)]

    def inspect_check_actual(txids, channel_id, actual, exp):
        assert len(actual['outputs']) == len(exp)
        for e in exp:
            # find the event in actual that matches
            found = False
            for a in actual['outputs']:
                if e[0].startswith('cid'):
                    if a['account'] != channel_id:
                        continue
                elif a['account'] != e[0]:
                    continue
    
                if e[1][0] != a['output_tag']:
                    continue
                if e[2]:
                    assert e[2][0] == a['spend_tag']
                    txids.append((e[3], a['spending_txid']))
                else:
>                   assert 'spend_tag' not in a
E                   AssertionError

```

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/6889/commits/62b42ac15e4c1f633659a382bfa65ede1fdbf59f

**Review by rustyrussell — APPROVED** [review]

**Comment by rustyrussell** [comment]
Trivial rebase for fresh CI testing...

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6889/commits/d94b1f35f93d62f4e7802dface7c881bb0724480

**Pull request merged**
