### PR TITLE
Inflights ordering, crashfix 

### LINKED ISSUE #4511: Node crashes on startup, failing RBF in incomplete state
@jsarenik and I got most of the way through an RBF attempt before he desisted, now it's crashing my node. 

We saved the 'inflight' attempt since we got as far as exchanging commitment sigs, but now the "most recent inflight" doesn't match the funding_txid for the channel (sigs should have been exchanged but failed to broadcast..?)

Worth noting that the initial feerate bump wasn't high enough to pass bitcoind's RBF rules, so broadcasting the tx failed. 
Jan decided he didn't want to try again, which is valid. It's entirely a manual process at the moment, could definitely use a nicer/more concise command to bump a channel.

```
2021-05-05T23:09:52.142Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.10.0-130-g929a418-modded)
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: common/daemon.c:44 (send_backtrace) 0x562a27aa874b
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: common/daemon.c:52 (crashdump) 0x562a27aa879b
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6c0fcf
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6c0f47
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6c28b0
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6b2429
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6b24a1
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/channel.c:735 (channel_current_inflight) 0x562a27a341fc
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/channel.c:743 (channel_last_funding_feerate) 0x562a27a3421a
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/peer_control.c:753 (json_add_channel) 0x562a27a69614
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/peer_control.c:1424 (json_add_peer) 0x562a27a6b80e
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/peer_control.c:1457 (json_listpeers) 0x562a27a6b9e0
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/jsonrpc.c:643 (command_exec) 0x562a27a4e63c
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/jsonrpc.c:767 (rpc_command_hook_final) 0x562a27a4ebd2
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/plugin_hook.c:275 (plugin_hook_call_) 0x562a27a7dde0
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/jsonrpc.c:855 (plugin_hook_call_rpc_command) 0x562a27a4ef99
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/jsonrpc.c:942 (parse_request) 0x562a27a4f3e8
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/jsonrpc.c:1033 (read_json) 0x562a27a4f74f
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x562a27b00b47
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x562a27b016c4
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x562a27b01702
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x562a27b038c8
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:24 (io_loop_with_timers) 0x562a27a4c71c
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1111 (main) 0x562a27a524fc
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fe62a6a3b96
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x562a27a2c629
2021-05-05T23:09:52.142Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

Temp patch to fix:

```patch
diff --git a/lightningd/channel.c b/lightningd/channel.c
index 094a66eb3..b60a7ef8f 100644
--- a/lightningd/channel.c
+++ b/lightningd/channel.c
@@ -726,15 +726,10 @@ void channel_fail_forget(struct channel *channel, const char *fmt, ...)
 struct channel_inflight *
 channel_current_inflight(const struct channel *channel)
 {
-       struct channel_inflight *inflight;
        /* The last inflight should always be the one in progress */
-       inflight = list_tail(&channel->inflights,
-                            struct channel_inflight,
-                            list);
-       if (inflight)
-               assert(bitcoin_txid_eq(&channel->funding_txid,
-                                      &inflight->funding->txid));
-       return inflight;
+       return list_tail(&channel->inflights,
+                        struct channel_inflight,
+                        list);
 }
```

### PR DESCRIPTION
**Pull request by niftynei**
Found a number of issues with the RBF path for the v2 channel opens. Namely, we weren't handling the inflight promotion and broadcast correctly if a non-last transaction ended up being mined (which is very likely given how RBF attempts can fail if they don't pass bitcoind's RBF rules for fees).

We weren't ordering channel_inflights, so they get out of order when reloaded from disk, which fails an assert and leads to a crash loop. Resolved by ordering inflights by feerate.

Fixes #4511

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Ack 2a155fb03b77adad5910772a0132069b0889bb78

**Comment by rustyrussell** [comment]
Trivial rebase, and added Changelog-Experimental line.

**Comment by niftynei** [comment]
Two outstanding CI problems; one is fixed in #4541, the other is in `test_hsmtool_secret_decryption`

```
`: Enter hsm_secret password:
Time-out: can't find [re.compile('Confirm hsm_secret password:')] in logs
```

**Comment by niftynei** [comment]
Found some more bugs in the RBF pathways. Here's some tests and fixes. ty @jsarenik for the help in identifying these!

**Comment by jsarenik** [comment]
@niftynei Thank you!

My node is already running `v0.10.0-181-gffdd029` and it automagically did the closing transaction (of the unopened channel which was forgotten by the other side of dualfunding because I mistakenly used the lowest fee and it got mined in the end, already when the other side forgot about it).

It is my pleasure to cause problems that lead to improvements. Thanks again for your care!

**Comment by jsarenik** [comment]
ACK ffdd02920

**Review by rustyrussell — APPROVED** [review]
Ack 2d4f3d0d661f17429b0fa7989127e98c5fd04b6b

Great work!

**Comment by jsarenik** [comment]
@rustyrussell Excuse me, I might have been to fast in ACKing it, see below.

@niftynei now I realized that the transaction the fixed version did is actually not pointing to any address of mine, but rather an other 2of2 multising (guessing from the length of bech32). Where is it going? And where are the 330 sats going?

I will send a link to the TX in question on-request.

**Comment by jsarenik** [comment]
@rustyrussell UPDATE: Everything is OK. Learning on the run, with `jasan --verbose=9`.

And the 330 sats UTXO is called `anchor output` (see https://github.com/lightningnetwork/lightning-rfc/pull/688/files)

**Pull request merged**
