### PR TITLE
Remove unused includes

### PR DESCRIPTION
**Pull request by lclc**

### CODE REVIEW

**Comment by cdecker** [comment]
CI fails with the following warning:

```
cc -Werror -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -g -fstack-protector -I ccan -I secp256k1/include/ -I .    -c -o daemon/lightningd.o daemon/lightningd.c
daemon/lightningd.c: In function 'main':
daemon/lightningd.c:528:2: error: implicit declaration of function 'signal' [-Werror=implicit-function-declaration]
  signal(SIGPIPE, SIG_IGN);
  ^
daemon/lightningd.c:528:9: error: 'SIGPIPE' undeclared (first use in this function)
  signal(SIGPIPE, SIG_IGN);
         ^
daemon/lightningd.c:528:9: note: each undeclared identifier is reported only once for each function it appears in
daemon/lightningd.c:528:18: error: 'SIG_IGN' undeclared (first use in this function)
  signal(SIGPIPE, SIG_IGN);
                  ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'daemon/lightningd.o' failed
make: *** [daemon/lightningd.o] Error 1
```

Seems like at least `signal.h` is still required in `lightningd.c`.

**Comment by lclc** [comment]
Hm strange, it works with clang/OSX.
I've added signal.h back, but seems there are some more of those cases with gcc.
I'll try to get a VM to build it on Linux.

**Comment by cdecker** [comment]
Incidentally, what did you use to detect the unused includes? Might be interessting to report this upstream.

**Comment by lclc** [comment]
I'm using CLions built-in code inspection tools. Not sure if one can export those somehow and integrate them into a CI or so.

Can you make the CI-build report accessible to the public automatically somehow? Maybe upload them to S3/Pastbin with a script after building.

**Comment by cdecker** [comment]
Sadly I can't publish the logs automatically, since they might leak some access tokens. But I can certainly publish them manually. Another variant is to get Travis-CI configured on your fork :-)

**Comment by lclc** [comment]
I'll get a VM with gcc

**Comment by lclc** [comment]
I've tried it now with a fresh Ubuntu 16.04; it builds.
It fails with make check (I guess that's why the CI fails too this time). make check also fails for me using the latest master branch (gcc, 16.04). I assume you already fixed those in https://github.com/ElementsProject/lightning/pull/105 since there the CI doesn't fail. So I'll just wait for that to get merged and then rebase this PR.

**Comment by cdecker** [comment]
Just tried to rebase this onto the newest master. However things have changed so much that I'd rather re-run the tools on the master, than try to fix the rebase. I'll close this issue for now, but feel free to reopen it when it can be applied to the master branch :wink:

**Pull request closed without merging**
