### PR TITLE
msggen: add missing methods for 24.11

### PR DESCRIPTION
**Pull request by daywalker90**
We don't want to fall out of sync again, right?! @rustyrussell @ShahanaFarooqui 

EDIT: reworked the PR to include all the missing rpc commands for 24.11:

- GetEmergencyRecoverData
- EnableOffer
- AskRene-Unreserve
- AskRene-ListLayers
- AskRene-Create-Layer
- AskRene-Remove-Layer
- AskRene-Reserve
- AskRene-Age
- GetRoutes
- AskRene-Disable-Node
- AskRene-Inform-Channel
- AskRene-Create-Channel
- AskRene-Update-Channel
- AskRene-Bias-Channel
- AskRene-ListReservations
- InjectPaymentOnion

Aswell as: 

- Xpay
- ListAddresses
- Bkpr-EditDescriptionByPaymentId
- Bkpr-EditDescriptionByOutpoint
- Dev-Splice
- ExposeSecret

### CODE REVIEW

**Comment by rustyrussell** [comment]
I'm going to defer these because they're still experimental and I want to reserve the right to change them radically!  Maybe by the time we're into next release @Lagrang3 and I will have more confidence?

**Review by cdecker — APPROVED** [review]

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/4968fdb740889ee1529a79a77993a02db3085576

Several other PRS will conflict (damn generated files) so I'll wait a bit before rebasing and merging this

**Comment by daywalker90** [comment]
Want me to do a separate PR for the rest or add them here?

**Comment by rustyrussell** [comment]
> Want me to do a separate PR for the rest or add them here?

All the other API changes are merged now, so go wild!

**Comment by daywalker90** [comment]
Rebased and added missing methods listed in OP, these are now all missing methods that were added since 24.08

**Comment by rustyrussell** [comment]
I had to revert this for rc2, as the rust build broke.  Will try again after rc2...

**Comment by daywalker90** [comment]
I've looked through the CI jobs. It worked a couple of times and then failed in your rc2 PR run. Looking at the logs it looks to me like it still didn't wait "long" enough for the generated files to be there completely.

**Comment by daywalker90** [comment]
It's not enough that the files exist apparently. The generation could still be ongoing and the compiler would use a half finished file and then complain about missing things that are not missing in fully generated files.

**Comment by rustyrussell** [comment]
Hmm... weird!  I'll look deeper...

But there were crashes in rc1 so I want to release rc2 now :(

**Comment by rustyrussell** [comment]
I suspect that MSGGEN_GEN_ALL -> MSGGEN_GENALL change, TBH.  We can depend on both. I'll try.

**Pull request merged**
