### PR TITLE
wire: Fix generated files

### PR DESCRIPTION
**Pull request by jsarenik**
Replacing #4792

### CODE REVIEW

**Comment by jsarenik** [comment]
The failing tests are unrelated to the change in this commit.

**Comment by jsarenik** [comment]
CI tests succeeded on my fork: https://github.com/jsarenik/lightning/actions/runs/1250776208

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4794/commits/c3565c67d0e8d3b2a9c4c5bc38cf7385897f6e6b

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4794/commits/c3565c67d0e8d3b2a9c4c5bc38cf7385897f6e6b

Thanks to making the rebase easyer 😄

**Pull request merged**
