### PR TITLE
update Dockerfile

### PR DESCRIPTION
**Pull request by arowser**
add libevent library, #2111 need this to update docker image.
update bitcoind to last version 0.17.0.1

### CODE REVIEW

**Comment by cdecker** [comment]
Is the developer package needed even if we download a binary release of `bitcoind` and `bitcoin-cli`?

**Comment by arowser** [comment]
@cdecker The libevent-dev packagae is dpendcy by #2111, that add a native bitcoin rpc client,
the lightningd not need bitcoin-cli.

**Comment by cdecker** [comment]
Ok, we'll make this dependent on #2111 then :wink:

**Comment by arowser** [comment]
replaced by #2295

**Pull request closed without merging**
