### PR TITLE
Db code cleanups

### PR DESCRIPTION
**Pull request by rustyrussell**
No code changes, just some cleanups.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6128/commits/2be271d5fa2322119a35fd2fb98bb248eb9f5ba8

**Comment by rustyrussell** [comment]
This broke bookkeeper under postgres it seems? @niftynei ?

**Comment by niftynei** [comment]
Does #6141 fix this?

**Comment by niftynei** [comment]
Also thanks for this, we definitely needed to be reporting errors...

**Comment by rustyrussell** [comment]
> Does #6141 fix this?

I've pulled it in, let's find out!

**Comment by vincenzopalazzo** [comment]
Looks like the io return the wrong reference? this is happening also with lnprototest sometimese

```
--------------------------- Captured stderr teardown ---------------------------
lightningd: lightningd/connect_control.c:734: connectd_activate: Assertion `ret == ld->connectd' failed.
lightningd: FATAL SIGNAL 6 (version 798d3a7-modded)
0x55dc786700ac send_backtrace
	common/daemon.c:33
0x55dc78670158 crashdump
	common/daemon.c:46
0x7f6ff207451f ???
	???:0
0x7f6ff20c8a7c ???
	???:0
0x7f6ff2074475 ???
	???:0
0x7f6ff205a7f2 ???
	???:0
0x7f6ff205a71a ???
	???:0
0x7f6ff206be95 ???
	???:0
0x55dc785f1afe connectd_activate
	lightningd/connect_control.c:734
0x55dc78604df3 main
	lightningd/lightningd.c:1152
0x7f6ff205bd8f ???
	???:0
0x7f6ff205be3f ???
	???:0
0x55dc785d3d34 ???
	???:0
0xffffffffffffffff ???
	???:0
2023-04-03 07:35:24.132 UTC [100292] LOG:  received fast shutdown request
```

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/6128/commits/2f49be0bc209534fd14f3c231b9792c164fd1734 since @niftynei patch fixes it!

**Pull request merged**
