### PR TITLE
Fix CLN service startup failure by trimming trailing spaces in config parameters

### LINKED ISSUE #7132: Minor issue/question: Trailing spaces in Config file parameter make CLN fail to start
### Issue
I recently updated my config file and there were a couple of trailing spaces at the end of the line that I didn't notice.
I didn't need the changes right away so I didn't restart CLN after modifying the config file.
Today I finally had to restart CLN service and it kept failing. I did change Bitcoin to Bitcoin Knots and I thought that could be the reason and it took me awhile before realizing that  the problem wasn't Knots but the change I made to the config file few weeks ago...
When I finally decided to try and run it form the CLI instead than through systemctl I saw this message and I could fixed the issue:

`lightningd: Config file /mnt/md0/C-Lightning/config line 24: autoclean-failedforwards-age=1296000 : '1296000 ' is not a number`

So the question/proposal is: 
wouldn't be better to try and remove any trailing spaces from the parameters when reading the configuration file? Or at least have some warnings showing up in the systemctl status output (if it is even possible) other than a generic failure?

image

### PR DESCRIPTION
**Pull request by maxrantil**
fixes #7132

I would really appreciate some friendly feedback on this, as it is my first PR to the project and I might have misunderstood or missed important details.

~~I did find a similar function `strip_trailing_whitespace` in `plugins/bcli.c`, but from what I understand, having `void trim_trailing_spaces(char *str);` in `ccan` would still be beneficial, right?~~

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Thanks for this, looks good to me

I was wondering if it is possible move this `trim` function inside tal string https://github.com/rustyrussell/ccan/blob/master/ccan/tal/str/str.h

**Comment by maxrantil** [comment]
Pardon me, but I don't fully understand what you mean. Could you elaborate on your suggestion? To my understanding, the `tal` functions you are linking to, @vincenzopalazzo , relate to string functions involving memory allocation. If I were to implement tal_strtrim(), from my experience, those implementations remove spaces from the beginning and end and allocate a new string. Is that what you are aiming for here? The current placement of the function `trim_trailing_spaces()` in `ccan/ccan/str/str.c` made sense to me because it manipulates an already allocated string. 
Like I said at the beginning, I am new here and would appreciate a more thorough explanation if you have time for that.

**Review by endothermicdev — APPROVED** [review]
Nice PR!  It's a neat solution to the problem.  I agree with Vincenzo - so long as a ccan library is being modified, it would be nice to go ahead and trim the leading whitespace too and resize the buffer (which would make this a tal/str operation).  It's not a significant difference in this case, but it could be more useful for the library.  I'm okay with either approach.

**Comment by maxrantil** [comment]
Thanks for the comment @endothermicdev, I'll start doing a strtrim function in tal tomorrow if you both think that is more useful then 👍

**Comment by maxrantil** [comment]
@vincenzopalazzo & @endothermicdev , I've now changed to using `tal_strtrim`, is this what you had in mind?

**Comment by maxrantil** [comment]
@endothermicdev  I am having some issues with tests on my local machine using `tal_resize` like this. I am working on writing a test for it that I will push with the PR. Is there anything in the way I am using it now that you can see is not working directly?

**Comment by maxrantil** [comment]
If someone could have a look at the pytest and tell me if something is wrong in it, that would be appreciated.

**Comment by maxrantil** [comment]
Hi @rustyrussell ,
Thanks for the feedback! I didn't notice the review until now but I will get into it asap.

**Comment by maxrantil** [comment]
@rustyrussell or @endothermicdev , do you find it acceptable  to manipulate a `const char *` with `memmove()` like I do in the trimming func??

**Comment by rustyrussell** [comment]
Given how close we are to rc1, I simply added a commit with various cleanups.  Thanks for this work!

**Comment by maxrantil** [comment]
That's fine @rustyrussell ! I learned some new things from studying your changes.

I'm not sure how to fix the error in the test that is failing now, tho.

**Comment by rustyrussell** [comment]
THose issues were from master, fortunately!

**Comment by maxrantil** [comment]
Is there any chance of getting the sphinx bounty of 100k sats for this? 😊 I can't get Sphinx Chat to work with Core lightning on my umbrel node. Is there another way to get the payout if i am eligible for it?

**Comment by BitcoinJiuJitsu** [comment]
DM sent to @max54302324

**Pull request merged**
