### PR TITLE
build: add a simple nix dev shell

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
I've had these changes on a branch for some time and have been considering preparing a patch and pushing it.

Essentially, this enables any NixOS or Nix package manager user to launch a development shell with all the necessary dependencies. This allows CLN users to contribute, compile, and install CLN. The process can be a bit intricate due to our use of shared libraries. This update might also enhance the OSX build, though I haven't been able to test it currently.

The documentation has been updated as well, as it previously didn't work on a fresh NixOS machine. In the latest commit, I've added myself as the code owner to assist in maintaining this configuration.

This approach differs from https://github.com/ElementsProject/lightning/pull/6650. Their method offers a more intricate Nix configuration that employs Nix to execute the `make` target. While I might be oversimplifying, I believe their approach is excessive for our needs.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Python package are painful also in nix :/

So I fixed a couple of those but I still need to work around this bug https://github.com/nix-community/poetry2nix/issues/413

```
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/lr06kyfn2nzxq718jf5c2mw00kz5ir5f-cryptography-41.0.4-vendor.tar.gz
checking for references to /build/ in /nix/store/lr06kyfn2nzxq718jf5c2mw00kz5ir5f-cryptography-41.0.4-vendor.tar.gz...
patching script interpreter paths in /nix/store/lr06kyfn2nzxq718jf5c2mw00kz5ir5f-cryptography-41.0.4-vendor.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/3gh7z3si4jh5y5x9fwcfg5mk19fqwrvx-cryptography-41.0.4-vendor.tar.gz.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-oXR8yBUgiA9BOfkZKBJneKWlpwHB71t/74b/5WpiKmw=
error: 1 dependencies of derivation '/nix/store/5x5aqb5hzjd02phv1jyrfl8lz0fpd1dx-python3.10-cryptography-41.0.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n21q8wy7a814hjbdzxz3w4j7hr3hdmnv-python3-3.10.12-env.drv' failed to build
```

**Comment by cdecker** [comment]
I wonder if we should rather build a flake rather than an env or a shell. That'd allow us to pull in other flakes from arbitrary sources, and more importantly pull CLN in as a flake themselves.

**Comment by vincenzopalazzo** [comment]
>I wonder if we should rather build a flake rather than an env or a shell. That'd allow us to pull in other flakes from arbitrary sources, and more importantly, pull CLN in as a flake themselves.

This is a good point, I can move to Nix Flake or maybe we can just adapt the nix-shell into a nix flake. However, I am having a hard time resolving the Python Nix bundle.

I will make some experiments, thanks for the suggestion

**Comment by cdecker** [comment]
Discussing somewhere else about the complexity of getting the python dependencies in, I was wondering if it'd make sense to have nix manage `poetry` as the only python dependency, and then we put the python dependency download as a pre-shell command. This way we'd stay in nix for everything except python dependencies and we can then slowly pull them in as more and more of our dependencies get nixified.

**Comment by vincenzopalazzo** [comment]
>Discussing somewhere else about the complexity of getting the python dependencies in, I was wondering if it'd make sense to have nix manage poetry as the only python dependency, and then we put the python dependency download as a pre-shell command. This way we'd stay in nix for everything except python dependencies and we can then slowly pull them in as more and more of our dependencies get nixified.

This is a good things to do IMHO, and I think also the only one because there is a bug on nix. I was testing it but I do not remember why I changed maybe due the nix env variable, but I can play with it after the release is over.

**Comment by nepet** [comment]
I am tempted to move this to the next release (or between releases as it does not touch core-lightning itself).

**Comment by vincenzopalazzo** [comment]
>I am tempted to move this to the next release (or between releases as it does not touch core-lightning itself).

Yeah currently there is no way to build a nix-shell with poetry2nix because there is a bug and we should wait for a fix.

Happy to move it

**Comment by cdecker** [comment]
Removed the milestone as this PR is not ready to be merged in its current state.

**Comment by vincenzopalazzo** [comment]
This nix to be reworked

**Pull request closed without merging**
