### PR TITLE
schemas: "description" field in "wait(any)invoice" is optional since BOLT12

### PR DESCRIPTION
**Pull request by laanwj**
# schemas: "description" field in "wait(any)invoice" is optional since BOLT12

## Description

For BOLT12 invoices, the "description" is field missing in the invoice responses. This causes a serde parse error when handling BOLT12 invoices in rust code. Update the schemas accordingly:

- `doc/schemas/lightning-waitanyinvoice.json`
- `doc/schemas/lightning-waitinvoice.json`

Also commit the generated msggen, cln-grpc, cln-rpc and pyln-grpc-proto files.

## Related Issues

Continues #7660.

## Changes Made

Changelog-Fixed: schemas: Make description in `Wait(any)invoiceResponse` optional to handle BOLT12

## Checklist
Ensure the following tasks are completed before submitting the PR:

- [x] Changelog has been added in relevant commit/s.
- N/A Tests have been added or updated to cover the changes.
- [x] Documentation has been updated as needed.
- [x] Any relevant comments or `TODOs` have been addressed or removed.

### CODE REVIEW

**Comment by laanwj** [comment]
It's complaining that the auto-generated files aren't updated, while i really did that. The python output looks way different though.
```
-# Protobuf Python Version: 5.26.1
+# Protobuf Python Version: 4.25.1
```
Seems the specific version is needed...

**Comment by daywalker90** [comment]
Are you using `poetry shell` -> `poetry install` before running make?

**Comment by laanwj** [comment]
Didn't even have that installed, i don't think i've ever used `poetry` in my life 😄  Will try that next time.

Did manually figure it out i think:
```
pip3 install protobuf==4.25.1
pip3 install grpcio-tools==1.62.2
```

**Comment by daywalker90** [comment]
I suggest this goes into 24.08.1 aswell @ShahanaFarooqui

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/7667/commits/dda7524a97e523a6e1dc1e63cbd17d6087401924

**Pull request merged**
