### PR TITLE
psbt: use DER encoded + sighash byte for PSBT_IN_PARTIAL_SIG items

### PR DESCRIPTION
**Pull request by jgriffiths**
This fixes the incorrect signature encoding as reported in https://github.com/ElementsProject/lightning/issues/5298.

I don't see that the old code could ever have worked: whether signing through wally or any other PSBT signer, the resulting signature in the witness would be of an incorrect form and thus should be rejected by core.

Its probably worth getting submission/validation of a tx produced from signing one of these PSBTs under test.

### CODE REVIEW

**Comment by cdecker** [comment]
That is likely because we were using the PSBT format as an internal transport format only, and didn't use `libwally` primitives to construct the final transaction. This was discovered when we made the previously internal `hsmd` protocol public to be consumed by VLS.

Thank you very much @jgriffiths, and sorry for causing a false alarm for `libwally`.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5307/commits/d8bde0aee436794b3eacc814c935a93c7ba0da9b

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5307/commits/d8bde0aee436794b3eacc814c935a93c7ba0da9b

**Comment by jgriffiths** [comment]
I've squashed the test commit into the actual change for git-bisectability, no further changes.

**Comment by cdecker** [comment]
Hurray, the bot actually did recognize that there were no content changes between the PR versions and reapplied the ACKs :-)

**Comment by devrandom** [comment]
confirmed compatible with rust-bitcoin 0.28.1

**Pull request merged**
