### PR TITLE
Closing weight fix

### PR DESCRIPTION
**Pull request by rustyrussell**
I was getting regular failures in the #4984 branch.  This was caused by the closing fee estimation being wrong in elements, however, AFAICT the flaky retester has been covering it up (prior to this it would sometimes pass).

In debugging this, I discovered that our non-elements closing weight was also wrong, though not enough to trigger an error.  New test, more debugging...

Can we remove the flaky stuff please after release?  It's just deferring pain, not removing it!

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
Good catch

ack https://github.com/ElementsProject/lightning/pull/5004/commits/4ac8e2383ad839ab457b4e3af7a774922d21c3fb

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5004/commits/5aaa03f99aafbec81e4d9429d7db588ae5b1b72f

**Comment by rustyrussell** [comment]
More elements fixes: @cdecker please review!

**Review by vincenzopalazzo — APPROVED** [review]
LGTM, but I'm a little bit out of context with elements

ack https://github.com/ElementsProject/lightning/pull/5004/commits/d6e603e733a5838bc6692ade6e9bc00c1b43f38f

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5004/commits/d6e603e733a5838bc6692ade6e9bc00c1b43f38f

**Pull request merged**
