### PR TITLE
dns: only allow one DNS announcement

### PR DESCRIPTION
**Pull request by m-schmoock**
Since upcoming https://github.com/lightning/bolts/pull/911 will likely contain `- MUST NOT announce more than one "type 5" DNS hostname.` we need to add this.

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4996/commits/6df2e9cf7834963965a6557235632b3dd9c45f91

**Comment by m-schmoock** [comment]
@cdecker 
Regardless of the RFC that does not restrict the number of announced IP and TOR addresses, should we (re)add such a restriction that limits it down to i.e. 3 IP addresses and 3 TOR address?

@TheBlueMatt and others mentioning that the network should really limit on gossip content, but currently nobody enforces anything so the limits were removed from the spec. So as a first step we can add a rule that at least our implementation can't be used to spam gossip by commandline.

**Comment by m-schmoock** [comment]
Also, currenlty RFC #911 does forsee to ignore and drop node_updates that contain more than one DNS name.

**Comment by m-schmoock** [comment]
Update: Rust-Lightning seems picking up on this :D
 https://github.com/lightningdevkit/rust-lightning/pull/1329

**Pull request merged**
