### PR TITLE
CI: give nicer names to Ci runners, disable DF tests due to chronic timeouts

### PR DESCRIPTION
**Pull request by rustyrussell**
Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4542/commits/416b6e9111737669d21a551a2710eb43d4d9ed17

**Comment by rustyrussell** [comment]
Oops, I had some tabs in that file so it skipped all the CI checks :)  Force pushed now.

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4542/commits/46ce1c1f497cb6924efc68c444a2b0222011d7fe

minus that whole um... DF failure.

**Comment by rustyrussell** [comment]
Trivial rebase.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4542/commits/ddd204b6189ad4a211345e8219817cbef409719c

**Pull request merged**
