### PR TITLE
Makefile: stumble along if git does not work.

### PR DESCRIPTION
**Pull request by rustyrussell**
In particular, it's started complaining about "sudo make install"
and the .git directory being owned by someone else :(

Fixes: #5221
Fixes: #5189
Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
LGTM, but I don't think this fixes https://github.com/ElementsProject/lightning/issues/5221 because the error is generated by libwally directory.

Git is working on a glob pattern with `path/*` but this is not supported yet, and we have two choice:

- Use the "*" magic path to allow skip the safety check as the docs say https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory
- or write a script in the tools directory that makes easy the inclusion of this directory.

Why do you think?

**Comment by cdecker** [comment]
I think this should very well fix #5221 as we always suggest first calling `make` as normal user, followed by calling `sudo make install` which then doesn't require compilation, and hence doesn't require updating submodules either.

ACK https://github.com/ElementsProject/lightning/pull/5225/commits/c43c635e90284dd259e5f850618801429c5c6799

**Comment by vincenzopalazzo** [comment]
>I think this should very well fix https://github.com/ElementsProject/lightning/issues/5221 as we always suggest first calling make as normal user, followed by calling sudo make install which then doesn't require compilation, and hence doesn't require updating submodules either.

Mh! @cdecker not sure, but maybe I'm missing something wrong, but in a clean machine, the error should happen also with a normal user, and git at the global level has no lib wally as a safe directory. BTW, I'm sure that I'm missing something!

**Comment by cdecker** [comment]
> > I think this should very well fix #5221 as we always suggest first calling make as normal user, followed by calling sudo make install which then doesn't require compilation, and hence doesn't require updating submodules either.
> 
> Mh! @cdecker not sure, but maybe I'm missing something wrong, but in a clean machine, the error should happen also with a normal user, and git at the global level has no lib wally as a safe directory. BTW, I'm sure that I'm missing something!

No, the `safe.directory` warning originates from a different user than the one executing `git` owning the directory, hence as long as the building user is the owner of the directories this warning will not be raised.

**Comment by vincenzopalazzo** [comment]
With the actual master code

```
(cln-meta-project-_Zy9CvTo-py3.8) gitpod /workspace/lightning (master) $ sudo make install
mkdir -p /usr/local/bin
mkdir -p /usr/local/libexec/c-lightning
mkdir -p /usr/local/libexec/c-lightning/plugins
mkdir -p /usr/local/share/man/man1
mkdir -p /usr/local/share/man/man5
mkdir -p /usr/local/share/man/man7
mkdir -p /usr/local/share/man/man8
mkdir -p /usr/local/share/doc/c-lightning
fatal: unsafe repository ('/workspace/lightning' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /workspace/lightning
Reinitializing submodules external/libsodium external/libwally-core external/gheap external/jsmn external/libbacktrace external/lnprototest ...
fatal: unsafe repository ('/workspace/lightning' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /workspace/lightning
fatal: unsafe repository ('/workspace/lightning' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /workspace/lightning
make: *** [external/Makefile:52: submodcheck] Error 128
(cln-meta-project-_Zy9CvTo-py3.8) gitpod /workspace/lightning (master) $ 
```

git log: 

```
(cln-meta-project-_Zy9CvTo-py3.8) gitpod /workspace/lightning (master) $ git log
commit 6ced5558fb7c817375112072d8f670b878356ddd (HEAD -> master, origin/master, origin/HEAD)
Author: Rusty Russell <rusty@rustcorp.com.au>
Date:   Tue Apr 26 13:25:47 2022 +0930

    Makefile: stumble along if git does not work.
    
    In particular, it's started complaining about "sudo make install"
    and the .git directory being owned by someone else :(
    
    Fixes: #5221
    Fixes: #5189
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

```

**Pull request merged**
