### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by cdecker**
Mainly  commit 0a855bb which adds the `$PYTEST_OPTS` to the `pytest` run, allowing the environment to finetune the test run (e.g., `--reruns=2` on Travis which got lost somewhere).

Changelog-None

### CODE REVIEW

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/4121/commits/b402e2bad9fc3f8d4512617c2595b4d6fca36b6e

But I've restarted the elements test twice, and it's still failing.  Not sure why...

**Comment by cdecker** [comment]
I'm looking into why the `pytest-rerunfailures` plugin isn't working, it just dies on the first flaky test again...

**Comment by cdecker** [comment]
Ok, found the issue: `pytest-rerunfailures==9.1.1` has a regression with `pytest==5.*` so I pinned it to version `9.1` which still worked. I'll have to revisit this later once we switch over to `pytest==6.*` but for now it works.

**Comment by cdecker** [comment]
Re-applying @rustyrussell's ACK so we can get Travis back to providing reasonable results again.

ACK https://github.com/ElementsProject/lightning/pull/4121/commits/8c38851a24abd4e05fc8f612f108db8a47369fd1

**Pull request merged**
