### PR TITLE
 Let canonicalize correctly handle a NULL pointer 

### PR DESCRIPTION
**Pull request by sumBTC**
This is my first pull request ever. Hope it makes sense and I'm doing this right.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Hi!  The patch itself seems fine, but I'm not sure what it solves?  If it can't open the bolt file, I guess it just ignores it now?

**Comment by sumBTC** [comment]
It doesn't really solve anything in how `canonicalize` is  being used, I just thought it's more complete as a function by itself, for example, if someone wants to copy-past the code and use it somewhere else.

**Comment by rustyrussell** [comment]
Right; by C convention though, string functions don't accept NULL, but instead give a nice diagnostic from the operating system by crashing :)

But if you're touching check-bolt, something which would be cool would be changing it so "..." refused to match across `#` which would stop it from matching a completely different section.  Might break too much stuff though!

**Comment by sumBTC** [comment]
I get it. I'll close the pull request.

**Pull request closed without merging**
