### PR TITLE
fix: getinfo showing unannounced discovered IPs

### PR DESCRIPTION
**Pull request by m-schmoock**
This fixes a visual bug in `getinfo` output, which contained unannounced
auto discovered IP addresses when announcement of discovered IPs
was actually turned off.

Addresses #5553

### CODE REVIEW

**Comment by m-schmoock** [comment]
... I still need to fix getinfo showing outbound ports on discovered addresses instead of `chainparams_get_ln_port(chainparams)`.

**Review by cdecker — APPROVED** [review]
ACK c4c89ab2a0ed761e2021b711260199d6b858059a

**Comment by m-schmoock** [comment]
@cdecker
Just to confirm, are we okay having indentation cleanup commits like c4c89ab ?

**Comment by cdecker** [comment]
I'm fine with them, as long as they are clearly marked as cleanup, to save on reviewer time (I sometimes spent several minutes on whitespace only commits trying to figure out what the changes are, only to realize there aren't any 😜)

**Pull request merged**
