### PR TITLE
UTXOs from remotes with csv, fixup

### PR DESCRIPTION
**Pull request by niftynei**
Couple of tiny changes to how the UTXOs are deep enough check, plus a test for it. Fixed in #4703, but this adds some tests and avoids the problem of having a `minheight` of 0 and getting a not-ready CSV utxo  yet (leased).

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4706/commits/7aadcafc9af6d4d9d30ac01a41fbaa77771e786b

**Review by darosior — APPROVED** [review]
utACK 7aadcafc9af6d4d9d30ac01a41fbaa77771e786b

**Review by rustyrussell — APPROVED** [review]
Ack c0069d8bcca1239124dadc5d9c6d3cd6a8e12b82

**Comment by rustyrussell** [comment]
Trivial rebase.

Ack https://github.com/ElementsProject/lightning/commit/3e77c25a151f5f69875925262cda495e78555860

**Comment by rustyrussell** [comment]
Trivial rebase now flakes covered...

**Pull request merged**
