### PR TITLE
make: always generate proto files sans rust

### PR DESCRIPTION
**Pull request by ddustin**
Generating the msggen proto files doesn’t require rust (even though it generates rust files).

Keep getting in this loop where my docs don't match CI and it's because the doc scripts were never running on my machine and I didn't enable rust.

Other's will probably run into this problem and it's quite hard to figure out.

Spotted by @niftynei and @chrisguida

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
```
#10 ERROR: process "/bin/sh -c git clone /source /repo --recursive &&     cd /repo &&     ./configure --enable-static --prefix=/usr &&     make -j $(nproc) &&     make install" did not complete successfully: exit code: 2
------
 > [builder 5/5] RUN git clone /source /repo --recursive &&     cd /repo &&     ./configure --enable-static --prefix=/usr &&     make -j $(nproc) &&     make install:
79.85 printgen wire/channel_type_printgen.h
79.94 wiregen wire/onion_wiregen.c
80.03 wiregen wire/peer_wiregen.c
80.23 wiregen gossipd/gossip_store_wiregen.c
80.35 xgettext wallet/statements_gettextgen.po
80.40 python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional
80.43 /usr/bin/python3: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
80.44 make: *** [Makefile:386: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Error 1
80.44 make: *** Waiting for unfinished jobs....
80.52 rm external/build-x86_64-alpine-linux-musl/libwally-core-build/src/secp256k1/libsecp256k1.la
------
Dockerfile.alpine:30
--------------------
  29 |     
  30 | >>> RUN git clone /source /repo --recursive && \
  31 | >>>     cd /repo && \
  32 | >>>     ./configure --enable-static --prefix=/usr && \
  33 | >>>     make -j $(nproc) && \
  34 | >>>     make install
  35 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone /source /repo --recursive &&     cd /repo &&     ./configure --enable-static --prefix=/usr &&     make -j $(nproc) &&     make install" did not complete successfully: exit code: 2
```

**Comment by ddustin** [comment]
This approach might not work, need to rethink it 🤔

**Comment by niftynei** [comment]
` Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')`

That's a python module import error.

**Comment by cdecker** [comment]
Not really all that surprising, since the Alpine compiler test does not have the grpc tooling.

**Comment by vincenzopalazzo** [comment]
Do we really want to require grpc tools just for a task that is not always required?

**Comment by cdecker** [comment]
I added an installation step for the python build dependencies.

**Comment by cdecker** [comment]
> To install the poetry dependencies we should add more dependencies inside the alpine, but I do not think it is worth due that we are just testing the compilation, maybe just `pip install mako <gpc tools>` should be enough?

So it just breaks again the next time we change the dependencies? Let's not hack things together, and actually install dependencies if we declare them as necessary to build.

**Comment by vincenzopalazzo** [comment]
>So it just breaks again the next time we change the dependencies? Let's not hack things together, and actually install dependencies if we declare them as necessary to build.

Not sure, I think that the `<gpc tools>` should be a developers tool, and do not required by install core lightning from source.

If some gen file are not generated when changed this is a `Makefile` problems and regenerate it also when it is not needed for me is just moving the problem somewhere-else, but I am fine ether way.

**Pull request merged**
