### PR TITLE
Split peer_control.c

### PR DESCRIPTION
**Pull request by rustyrussell**
There's no good time to make large changes like this, as it breaks every other PR.

So I split peer_control along (what I think are) fairly logical lines, then continued to fix two other
widespread API FIXMES we've had lurking around since I'm touching so much code anyway.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
The PR is a bit heavy and I am going through it, but it may take more than a day for me to review completely.  I will put up comments when I can find something.

**Comment by ZmnSCPxj** [comment]
lightningd/opening_control: routines to control openingd (move from peer_control.c) - looks OK

**Comment by cdecker** [comment]
utACK cf55a41

Thanks for the API fix for `fromwire_`. I consider the rest a move only but haven't verified it line by line, hence the utACK

**Comment by rustyrussell** [comment]
Yes, unf. I didn't resist the urge to do a cleanup (folding in opening_got_hsm_funding_sig() in opening_control.c), so it's not pure moveonly.  I apologize, and should have done that so review could be focussed.

I'm tempted to just merge it ASAP to avoid more conflicts, and avoid wasting reviewer cycles?

**Comment by cdecker** [comment]
I'd also suggest merging this as soon as possible, I would've tried a rebase, but I'm sure I'd have broken it :wink:

**Comment by cdecker** [comment]
ACK c0906f9

**Pull request merged**
