### PR TITLE
Call htlc accepted on startup after plugin init

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes: #2923

### CODE REVIEW

**Comment by cdecker** [comment]
While postponing the replay of HTLCs seems to address this, it leaves HTLCs temporarily in a weird state. I'd propose adding a new state for the HTLC (`hold`) and deferring the resolution until we the plugin has access to the RPC again (see https://github.com/ElementsProject/lightning/issues/2923#issuecomment-520164117 for rationale).

**Comment by cdecker** [comment]
I'll revisit this, adding the `hold` state, after the 0.7.2 release.

**Comment by rustyrussell** [comment]
Actually, should we just go back to failing these HTLCs on restart?

AFAICT we will anyway, since no peers can be connected at this point?

**Comment by cdecker** [comment]
> Actually, should we just go back to failing these HTLCs on restart?
> 
> AFAICT we will anyway, since no peers can be connected at this point?

No,  we can't since an incomplete hook call may have triggered an external event (if we are the recipient me might have marked a shopping cart as paid), and the triggering a failure would mean we end up in an inconsistent state (shopping cart will be shipped, but payment was returned).

The same scenario may happen if the hook short-circuits the payment or switches transport (cross-chain atomic swaps).

**Comment by cdecker** [comment]
I think your code does exactly what we'd like to do, sans the explicit `HOLD` state, i.e., defer resolution until startup is complete. I'd still like to add the `HOLD` state anyway, just to make it more explicit.

(I'm no longer sure we'd need the `HOLD` state for cross-chain atomic swaps since hooks are no longer always synchronous btw)

**Comment by ZmnSCPxj** [comment]
> (I'm no longer sure we'd need the `HOLD` state for cross-chain atomic swaps since hooks are no longer always synchronous btw)

Does that mean it would be unnecessary for this `HOLD` state also if we want to implement JIT-Routing?

@renepickhardt for interest.

**Comment by cdecker** [comment]
> > (I'm no longer sure we'd need the `HOLD` state for cross-chain atomic swaps since hooks are no longer always synchronous btw)
> 
> Does that mean it would be unnecessary for this `HOLD` state also if we want to implement JIT-Routing?
> 
> @renepickhardt for interest.

We would need to try, but it seems we could do without. Since the `htlc_accepted` hook is not called synchronously, we can do whatever intbetween getting the call and resolving it. The non-final state basically becomes an alias for `HOLD` so I think we can do without.

**Comment by cdecker** [comment]
Rebased, and I'm happy with the change as is :wink: 

Sorry for the delay @rustyrussell, you were right after all :-)

ACK https://github.com/ElementsProject/lightning/pull/2938/commits/10e3c7f210925e8afdf453f0ab5dc7099e8424c5

**Pull request merged**
