### PR TITLE
pyln: Add a dynamic configs and a callback for changes

### PR DESCRIPTION
**Pull request by cdecker**
This is an alternative to #7288, that uses a callback per config
option rather than hooking the `setconfig` function entirely. This
allows us to react to individual config options changing, while still
maintaining the default `setconfig` behavior.

### CODE REVIEW

**Comment by cdecker** [comment]
I'd love feedback from @rustyrussell and @cguida on this since it is an alternative to #7288

**Comment by rustyrussell** [comment]
What happened to the commit message in the first commit?

**Comment by rustyrussell** [comment]
Fo

**Comment by rustyrussell** [comment]
Fixed 'default: null' which cln doesn't like on flag values (if you specify a default, it must be false).

**Comment by rustyrussell** [comment]
Trivial rebase on master to re-run tests, and move one part of commit to make flake8 happy with each commit.

Ack 2b76ae3cfd64010166617a5608095dd8478d83eb

**Comment by rustyrussell** [comment]
Oh, we broke our own plugins which use plugin.option['optname']['value'] instead of get_value like I guess they're supposed to.  Fix that so we don't break other plugins!

**Pull request merged**
