### PR TITLE
Add some missing parsing checks

### PR DESCRIPTION
**Pull request by darosior**
This is part of the finds of #4526 PR'ed separately as i don't have a fix for all of them yet.

Changelog-None

### CODE REVIEW

**Comment by rustyrussell** [comment]
The first commit seems wrong?

Only some functions return success: some return void. Generally it's fine (by design!) to ignore fromwire() failures for a while as long as the top-level caller checks that cur is not NULL.  Presumably there are some places that check is missing?

**Comment by darosior** [comment]
Hmm, the first commit only adds this check to the `fromwire`s that return an allocated ([off the passed `ctx`](https://github.com/ElementsProject/lightning/pull/4527/commits/a6ba4d7a1a319a3942d255ed3cb7facd0adaf62f#diff-96140fbbf3b28243cf5822b043d9e46a703f1abd9cef6a5b292bed55c837e6e7R182-R184)) value. I just manually checked and it doesn't seem wrong (every place the check is implemented, if the result is NULL there was an error).

However it's probably misguided, i figured we should not continue to read if there was an error but i can replace this with adding the missing caller checks!

**Comment by rustyrussell** [comment]
> Hmm, the first commit only adds this check to the `fromwire`s that return an allocated ([off the passed `ctx`](https://github.com/ElementsProject/lightning/pull/4527/commits/a6ba4d7a1a319a3942d255ed3cb7facd0adaf62f#diff-96140fbbf3b28243cf5822b043d9e46a703f1abd9cef6a5b292bed55c837e6e7R182-R184)) value. I just manually checked and it doesn't seem wrong (every place the check is implemented, if the result is NULL there was an error).
> 

They mostly return bool though.  Because C, returning NULL "works", but should have no effect since each of these functions checks *cursor != NULL at the end.

> However it's probably misguided, i figured we should not continue to read if there was an error but i can replace this with adding the missing caller checks!

It's specifically designed that way, to simplify error checking, so ideally this commit should have no effect...

**Comment by darosior** [comment]
> They mostly return bool though. Because C, returning NULL "works", but should have no effect since each of these functions checks *cursor != NULL at the end.

Sorry, i just went through all of the places where the check is added in https://github.com/ElementsProject/lightning/pull/4527/commits/a6ba4d7a1a319a3942d255ed3cb7facd0adaf62f (again!), and none of the function it checks the result of returns `bool`. Anyways, will change to add check that cursor != NULL instead as soon as i can unstuck #4526 !

> ideally this commit should have no effect...

I'm pretty sure it had effect, but i can't reproduce anymore using the fuzz target as i'm stuck by https://github.com/ElementsProject/lightning/pull/4526#issuecomment-842256900 . Will modify to use a check further down the call stack as soon as i can test that it actually fixes the previously encountered issue..

**Comment by rustyrussell** [comment]
The first commit seems wrong, the second is redundant (new_psbt cannot fail), and the third is already merged.

**Pull request closed without merging**
