### PR TITLE
cln-rpc & cln-grpc: Backfill more methods

### PR DESCRIPTION
**Pull request by cdecker**
I now know how @rustyrussell felt filling in the JSON-Schemas for the JSON-RPC responses. This PR mostly consists of me backfilling the JSON-RPC request schemas, and then autogenerating the derived files, occasionally addressing a conversion issue or a missing type.

The PR is based on topp of #5013 and starts with the `msggen: Add meta file to keep the field numbers stable` commit (daa26ff27d7941aefdb709a9dab72b21f1d29c03 at the time of writing).

The following files where changed manually, all others were generated and are unlikely to hold any surprises:
 - `cln-grpc/proto/primitives.proto ` to add the `Feerate`, `Utxo` and `OutputDesc` primitives
 - `cln-grpc/src/pb.rs` to add a number of protobuf <-> JSON-RPC conversions
 - `cln-rpc/Cargo.toml` to add the `hex` dependency
 - `cln-rpc/src/primitives.rs`
 - `contrib/msggen/msggen/__main__.py` to allowlist more RPC methods and add method renaming for `connect` which is already used by grpc internally
 - `contrib/msggen/msggen/grpc.py` to add the fixed mapping from field path to field number required for grpc to work across versions (renumbering fields is not allowed by protobuf and grpc since that's how fields are identified).
 - `contrib/msggen/msggen/model.py` and `contrib/msggen/msggen/rust.py` to add mapped types
 - The following request schemas:
   - `doc/schemas/connect.request.json`
   - `doc/schemas/createinvoice.request.json`
   - `doc/schemas/createonion.request.json`
   - `doc/schemas/datastore.request.json`
   - `doc/schemas/deldatastore.request.json`
   - `doc/schemas/delexpiredinvoice.request.json`
   - `doc/schemas/delinvoice.request.json`
   - `doc/schemas/fundpsbt.request.json`
   - `doc/schemas/invoice.request.json`
   - `doc/schemas/keysend.request.json`
   - `doc/schemas/listdatastore.request.json`
   - `doc/schemas/listinvoices.request.json`
   - `doc/schemas/listnodes.request.json`
   - `doc/schemas/listsendpays.request.json`
   - `doc/schemas/listtransactions.request.json`
   - `doc/schemas/newaddr.request.json`
   - `doc/schemas/pay.request.json`
   - `doc/schemas/sendonion.request.json`
   - `doc/schemas/sendpay.request.json`
   - `doc/schemas/sendpsbt.request.json`
   - `doc/schemas/signpsbt.request.json`
   - `doc/schemas/utxopsbt.request.json`
   - `doc/schemas/waitanyinvoice.request.json`
   - `doc/schemas/waitinvoice.request.json`
   - `doc/schemas/waitsendpay.request.json`
   - `doc/schemas/withdraw.request.json`

It is likely easiest to review the final diff and not the individual commits, since I jumped around a bit between methods that are more or less related. As for completeness you can look at `contrib/msggen/msggen/__main__.py` as to which methods are mapped and which aren't yet. Please let me know if there are any methods that are needed for your use-cases and that should be mapped.

This has to be considered experimental code, since I couldn't test most of these commands, due to the sheer surface size. The code compiles, but we make liberal use of panics, which may lead to unexpected results. You have been warned, but feedback is very much welcome to stabilize this interface.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Yeah, we really need to add these request schemas to to python framework for testing!

OK, this isn't complete, but my proposal can be found (on top of this!) here: https://github.com/rustyrussell/lightning/tree/guilt/pr-5104

**Comment by rustyrussell** [comment]
OK, my tree now has all the schema fixes, and some others.  If you don't want to mess up your parsing, you can just cherry pick some of those changes (and not the part which actually validates it against the testsuite).

**Comment by cdecker** [comment]
I incorporated @rustyrussell's changes and fixes and got things working again. Currently backfilling some more types since they can be hard and might be considered braking changes if we do it later. Also added a couple of tests to gain some more certainty that the conversion code is working.

Will finish the changes by Monday, hoping to get these in asap

**Comment by rustyrussell** [comment]
Some commands have changed schemas maybe?  Needs rebasing I think...

**Comment by rustyrussell** [comment]
Didn't get time to fold these, but:

```diff
diff --git a/doc/schemas/signmessage.request.json b/doc/schemas/signmessage.request.json
index f5fd75727..163239e20 100644
--- a/doc/schemas/signmessage.request.json
+++ b/doc/schemas/signmessage.request.json
@@ -2,7 +2,7 @@
   "$schema": "http://json-schema.org/draft-07/schema#",
   "type": "object",
   "required": [
-    "id"
+    "message"
   ],
   "additionalProperties": false,
   "properties": {
diff --git a/tests/test_pay.py b/tests/test_pay.py
index bf8adf148..f4f5cc33b 100644
--- a/tests/test_pay.py
+++ b/tests/test_pay.py
@@ -2136,12 +2136,12 @@ def test_setchannel_routing(node_factory, bitcoind):
         l1.rpc.getroute(l3.info['id'], 4001793, 1, fuzzpercent=0)["route"]
 
     # We should consider this unroutable!  (MPP is disabled!)
-    inv = l3.rpc.call('invoice', {'msatoshi': 4001793,
-                                  'label': 'test_setchannel_1',
-                                  'description': 'desc',
-                                  'dev-routes': []})
+    inv = l3.dev_invoice(msatoshi=4001793,
+                         label='test_setchannel_1',
+                         description='desc',
+                         dev_routes=[])
     with pytest.raises(RpcError) as routefail:
-        l1.rpc.dev_pay(inv['bolt11'], use_shadow=False)
+        l1.dev_pay(inv['bolt11'], use_shadow=False)
     assert routefail.value.error['attempts'][0]['failreason'] == 'No path found'
 
     # 1337 + 4000000 * 137 / 1000000 = 1885
```

**Comment by rustyrussell** [comment]
Folded those simple fixes...

**Comment by rustyrussell** [comment]
Hmm, I put some cruft test changes in the rebase somehow.  Fixed and once it's tested locally I'll push again...

**Comment by rustyrussell** [comment]
I don't understand... I rebased it here fine, but GH claims conflicts?

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/9a76d840d2116966c63e983e299fe94d092cef85

Remaining memleak flake is known, on my workaround list soon.

**Pull request merged**
