### PR TITLE
lightningd: fix bogus channel iteration on setchannelfee

### PR DESCRIPTION
**Pull request by rustyrussell**
Setting channel to NULL then iterating doesn't work!

Fixes: #2733
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
That is not the behavior I would ecpect from `list_for_each`...

**Comment by m-schmoock** [comment]
@rustyrussell 
Hm, yes sorry for my broken code, in retrospect it does look wrong :D

I think the nullpointer was caused as we did set the iterator pointer
in the loop itself: (https://github.com/ElementsProject/lightning/pull/2736/files#diff-b34700033c5cd47ee522323329a7a789L1541) `channel = peer_active_channel(peer);`.

This also explains why it does work most of the times and also `tests/test_pay.py::test_setchannelfee_all` works, there is no test with a peer with more than one channel.

@ZmnSCPxj 
> That is not the behavior I would expect from list_for_each...

Correct. `list_for_each` should and does work with an initial `NULL` pointer, as noted above, I think rustys diagnose was not precise, the problem was cause by the fact that we set the pointer again in the (useless) loop.

**Comment by rustyrussell** [comment]
If you open code a single linked list it's clearer:

```C
for (p = head; p; p = p->next) {
    p = find_something();
}
```

You're messing with the iterator, of course it will crash!

**Comment by ZmnSCPxj** [comment]
Then I think the "correct" solution should have been:

    list_for_each (&peer->channels, channel, list) {
       if (channel->state != CHANNELD_NORMAL && channel->state != CHANNELD_AWAITING_LOCKIN)
           continue;
       set_channel_fees(cmd, channel, *base, *ppm, response);
    }

This is resilient against the possible future that we will have more than one normal channel per peer (assuming we plan to have such a future...).

Other parts of the code already use iteration over `&peer->channels`.

**Comment by m-schmoock** [comment]
@ZmnSCPxj yes, thats correct, but `peer_active_channel` will have to be removed then, so this and other occurrences will not be missed.

**Pull request merged**
