### PR TITLE
Disable backtrace on mac

### PR DESCRIPTION
**Pull request by conanoc**
fix https://github.com/ElementsProject/lightning/issues/840

backtrace module does not support mac. So, disable crash log if BACKTRACE_SUPPORTED is 0.

The reason why this patch fix https://github.com/ElementsProject/lightning/issues/840 is not fully identified. On mac, SIGSEGV and SIGBUS signal happens after jsonrpc only when signal handlers are registered with ``sigaction()``.

### CODE REVIEW

**Comment by isghe** [comment]
@lvaccaro @gabridome 
ACK 56ef03666135f78df04ab134d07361966b0cf76a

**Comment by Sjors** [comment]
Awesome, this works for me on macOS. I'm now able to connect to peers and fund channels (master  crashes on launch once I have some channels open).

**Comment by conanoc** [comment]
yeah. I saw the same issue with lldb. But, it's not related with this patch. You could file a new issue for that.

**Comment by arowser** [comment]
Yes, it seems not related, and the issue have been addressed in #1093

**Comment by laanwj** [comment]
> The reason why this patch fix #840 is not fully identified. On mac, SIGSEGV and SIGBUS signal happens after jsonrpc only when signal handlers are registered with sigaction().

What happens (see https://github.com/ElementsProject/lightning/issues/840#issuecomment-364400896) is that `autodata`  (the library used for constructing RPC and other tables) uses SIGSEGV/SIGBUS on MacOSX and other BSDs to probe memory maps (in a subprocess). It registers its own handler for this, but apparently backtrace's handler also still triggers. This results in a logged error.

So this fix, removing backtrace, is overkill but it works. Another option would have been to disable backtrace handling just for autodata's subprocesses.

**Pull request merged**
