### PR TITLE
Update onchain.c

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Round tx fees up.

Fixes https://github.com/ElementsProject/lightning/issues/1194#issuecomment-373333023 ... maybe.  I didn't even try compiling this.  I just directly edited it in github.

### CODE REVIEW

**Comment by ZmnSCPxj** [comment]
ACK 806bc022dcc8a0f69c929de9130a077174ca3071

**Comment by jb55** [comment]
this is begging for tests ;)

**Comment by ZmnSCPxj** [comment]
Looking more deeply, maybe it is incomplete? `wallet/wallet.c` also contains fee calculation code.https://github.com/ElementsProject/lightning/blob/044705a547f853cb89fba8a6711ac5420f658620/wallet/wallet.c#L289

**Comment by roconnor-blockstream** [comment]
Good catch in `wallet.c`

Sorry, this PR wasn't entirely serious.

**Comment by roconnor-blockstream** [comment]
Actually, while I think these are all errors, Perhaps they are not causing the problems in #1194.  Since feerate_per_kw should be exactly 4000, the division should be exact here.

**Comment by roconnor-blockstream** [comment]
Superseded  by https://github.com/ElementsProject/lightning/pull/1251

**Pull request closed without merging**
