### PR TITLE
Preparation for --developer configuration removal: generic parts.

### PR DESCRIPTION
**Pull request by rustyrussell**
I want to replace `./configure --developer` with a runtime developer flag, but there are some cleanups which make it easier.  These are those cleanups.

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/6306/commits/84b74d0662d36c4466a987c989826d8168388923

**Review by vincenzopalazzo — COMMENTED** [review]
Not sure why this code do not compile

```
cc wallet/wallet.c
cc wallet/walletrpc.c
wallet/wallet.c: In function 'wallet_has_funds':
wallet/wallet.c:636:34: error: passing argument 1 of 'db_fatal' from incompatible pointer type [-Werror=incompatible-pointer-types]
  636 |                         db_fatal("Invalid value for %s: %s",
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  char *
In file included from wallet/wallet.c:14:
./db/utils.h:123:32: note: expected 'const struct db *' but argument is of type 'char *'
  123 | void db_fatal(const struct db *db, const char *fmt, ...)
      |               ~~~~~~~~~~~~~~~~~^~
cc1: all warnings being treated as errors
make: *** [Makefile:299: wallet/wallet.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by rustyrussell** [comment]
> Not sure why this code do not compile
> 
> ```
> cc wallet/wallet.c
> cc wallet/walletrpc.c
> wallet/wallet.c: In function 'wallet_has_funds':
> wallet/wallet.c:636:34: error: passing argument 1 of 'db_fatal' from incompatible pointer type [-Werror=incompatible-pointer-types]
>   636 |                         db_fatal("Invalid value for %s: %s",
>       |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                  |
>       |                                  char *
> In file included from wallet/wallet.c:14:
> ./db/utils.h:123:32: note: expected 'const struct db *' but argument is of type 'char *'
>   123 | void db_fatal(const struct db *db, const char *fmt, ...)
>       |               ~~~~~~~~~~~~~~~~~^~
> cc1: all warnings being treated as errors
> make: *** [Makefile:299: wallet/wallet.o] Error 1
> make: *** Waiting for unfinished jobs....
> ```

That was from the rebase onto master: one more case I had to convert.  Done now!

**Comment by rustyrussell** [comment]
Flake fix, which is actually stopping other tests passing, so good to have.

Ack https://github.com/ElementsProject/lightning/commit/dd5b8a3f0898d23600ed593a2228078dd779c461

**Pull request merged**
