### PR TITLE
`onchaind` now scorches the earth when penalizing a revoked transaction

### PR DESCRIPTION
**Pull request by ZmnSCPxj**
Fixes: #3832

### CODE REVIEW

**Comment by cdecker** [comment]
This looks great, can't wait to dive in and review it, once the release is out the door 🙂

**Comment by ZmnSCPxj** [comment]
Rebased, also increased test coverage a little by also checking that an RBFed transaction is considered resolved by the `onchaind`.

**Comment by ZmnSCPxj** [comment]
An issue is that this changes the interface of `snedrawtransaction`. Older plugins which provide `sendrawtransaction` will not be compatible after this.  However, a possible change would be to check if `sendrawtransaction` with two arguments results in a `JSONRPC_INVALID_PARAMS` error, and if so, try again with just a single argument, and if this is an RBFed transaction, to print a warning in the log that the plugin is using the old interface and the RBFed transaction may not get forwarded due to too high fee.

**Comment by ZmnSCPxj** [comment]
Did what I suggested, which is, if `deprecated_apis`, try to use a single-arg `sendrawtransaction` if the two-arg `sendrawtransaction` errors complaining about parameters.

**Comment by ZmnSCPxj** [comment]
Rebased.  Also, changed the Changelog regarding two-argument `sendrawtransaction` to "deprecated" (it was "removed"), since we now continue to support the one-argument `sendrawtransaction` if `--deprecated-apis` is set.

**Comment by ZmnSCPxj** [comment]
Rebased on top of b934a92 from #3889

**Comment by ZmnSCPxj** [comment]
Rebased, especially with #3889 merged in.

**Comment by ZmnSCPxj** [comment]
***bump***

**Comment by ZmnSCPxj** [comment]
Rebased on master.  Also, ***bump***.

**Comment by ZmnSCPxj** [comment]
Rebased.  Also, fixed the capstone --- if we make a penalty transaction that donates the money to miners (because the locktime has been reached) then it previously would make a transaction smaller than the 82-byte limit. We now use a padded `OP_RETURN` with a pointless 20-byte random commitment to get over the 82-byte limit.

**Comment by cdecker** [comment]
Assigning @rustyrussell since `onchaind` is his brainchild :-)

**Comment by rustyrussell** [comment]
I am going to apply this, though the "real answer" is to have a general engine which makes these kind of "deadline" decisions.  That will require careful design, and meanwhile this fixes a real issue.

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/ee9d85eb8703ca35729eaef9eb3ff34a59ef7a6c

**Comment by rustyrussell** [comment]
(If @ZmnSCPxj doesn't get to it first, I'll rebase and apply...)

**Comment by rustyrussell** [comment]
Fairly trivial rebase.

**Comment by rustyrussell** [comment]
... another trivial rebase.

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/8d6442a5417df9e0ef4ff5886f9e538a5d3d9cdf

**Pull request merged**
