### PR TITLE
Compile on macOS High Sierra Version 10.13.3

### PR DESCRIPTION
**Pull request by isghe**

### CODE REVIEW

**Comment by Sjors** [comment]
I'm able to compile on macOS 10.13.3 with or without this change.

**Comment by isghe** [comment]
@Sjors and did you run it without crash using simple command: `lightning-cli help`?
thanks

**Comment by Sjors** [comment]
@isghe I can't get it work, see #840.

**Comment by cdecker** [comment]
@isghe and @Sjors is this PR still up to date or shall we close it? There have been quite a few changes in the meantime that supersede this PR IIRC.

**Comment by Sjors** [comment]
I'll defer to @isghe; build pipelines are mostly a black box to me; I have no idea what `-Lexternal` does.

**Comment by isghe** [comment]
yes the compilation on macOS now it's ok.

**Pull request closed without merging**
