### PR TITLE
Add and use support for pulling tx without PSBT wrappers

### LINKED ISSUE #6955: crash with --network=liquid
CLN v23.11-76-g56d42ea

When running CLN with `--network=liquid` it will crash soon after starting:

```
2023-12-19T18:30:19.946Z DEBUG   lightningd: Adding block 2643648: 105f1a22ffaaca7368f1b087f8639dc54968bbbca03919f77c960a1748f9a1f1
2023-12-19T18:30:19.967Z DEBUG   lightningd: Adding block 2643649: b0a98888e2daeb12ee638cff9bf7d5aef52f40faaee3d9b561546819673c9ba7
2023-12-19T18:30:20.029Z DEBUG   lightningd: Adding block 2643650: e52f425aa0c5f8b14a311ac4d955a1e0fda58aeef040a4992bad71856efe1405
2023-12-19T18:30:20.147Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v23.11-76-g56d42ea)
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: common/daemon.c:38 (send_backtrace) 0x100c0827
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: common/daemon.c:75 (crashdump) 0x100c089f
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac7e0463
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac0b410c
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac05070b
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac03073b
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac044797
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac044843
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: bitcoin/psbt.c:63 (new_psbt) 0x100e5073
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: bitcoin/tx.c:665 (pull_bitcoin_tx) 0x100ee373
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: bitcoin/block.c:213 (bitcoin_block_from_hex) 0x100e3ddb
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/bitcoind.c:486 (getrawblockbyheight_callback) 0x100140d3
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:660 (plugin_response_handle) 0x10078bc3
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:772 (plugin_read_json_one) 0x1007e1a3
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:823 (plugin_read_json) 0x1007e4eb
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x101f3107
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x101f39e3
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x101f3aeb
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:453 (io_loop) 0x101f65bf
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:22 (io_loop_with_timers) 0x100404bb
2023-12-19T18:30:20.147Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1334 (main) 0x100483db
2023-12-19T18:30:20.148Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac030f2b
2023-12-19T18:30:20.148Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7fffac03116b
2023-12-19T18:30:20.148Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

### PR DESCRIPTION
**Pull request by jgriffiths**
Includes https://github.com/ElementsProject/lightning/pull/6882 which is rebased and I reckon is ready to merge.

Supersedes https://github.com/ElementsProject/lightning/pull/6975, @vincenzopalazzo @grubles your review/testing would be appreciated.

Fixes #6975 
Fixes #6955

### CODE REVIEW

**Comment by cdecker** [comment]
Thanks @jgriffiths this looks great, and I'm glad to see some of the utilities we open-coded in CLN making their way back into libwally :+1:

I'll wait for @grubles to confirm that this works, and then merge it. In the meantime I think your script change in the last commit could give us a speed boost and so I'm benchmarking a blockchain sync with and without this change to quantify that.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6983/commits/fe96d3adf596aab33339808ae5d2361271ac5f3c

This looks good to me and my node is syncing with the liquid chain. It is not difficult to get a pegin transaction while syncing, so currently there is no crash.

Thanks for push this work on the final line

**Comment by grubles** [comment]
ACK fe96d3a 

Builds and syncs with `--network=liquid` successfully.

**Comment by jgriffiths** [comment]
> I'll wait for @grubles to confirm that this works, and then merge it.

Awesome, thanks @cdecker

> I'm glad to see some of the utilities we open-coded in CLN making their way back into libwally 👍

Worth noting that nothing has moved from cln to wally. The removed code was either added to wally for other purposes or was already in wally (but not exposed through its api,) and was exposed for 1.0.0.

I say this is worth mentioning because there is code in cln that should move to wally, I'm thinking particularly of the taproot code outside of the keypath spending support gsanders and I worked to merge last year. Also the previous iteration of the wally update PR removed a large amount of code relating to witness serialization but I had to pull it out as no-one helped me figure out how it was upsetting tal. Unfortunately I don't have time to work on this exclusively, but I would be happy to work with someone to get code into wally where it can help others who need e.g. taproot support.

> In the meantime I think your script change in the last commit could give us a speed boost and so I'm benchmarking a blockchain sync with and without this change to quantify that.

That change and your alloc removal will help, but note that your changes will be lost in the noise of the rest of that PR. In order of effect, the changes in this PR that will improve speed should be:

1. Building wally and libsecp in release mode, which enables asm hash impls amongst other optimizations
2. Not building PSBTs for every tx in each block and elsewhere (multiple dozens of allocations per tx)
3. Not re-serializing the tx to redundantly re-compute its txid (allocates, serializes and multi-hashes every tx redundantly)

If block processing in particular is a concern, one easy win I noticed but didn't make is to remove the top level `tal_count` calls from the block tx iteration for loops by computing the count outside the loop first, particularly in `topology.c`. I don't believe the compiler will optimize out these calls, and they perform redundant verification each time. The double nested loops for fees in particular are probably dominated by wasted tal overhead.

**Comment by cdecker** [comment]
> Worth noting that nothing has moved from cln to wally. The removed code was either added to wally for other purposes or was already in wally (but not exposed through its api,) and was exposed for 1.0.0.

Oh yeah, I meant more as in the use-cases we needed in CLN seem to be shared, rather than the code. Thanks for the detailed answer too, it'd certainly be useful to consolidate on `wally` for anything that accesses or manipulates TXs.

I also finally managed to get benchmarks working, which was strange since the bitcoind backend was slower than CLN  could process them :-)

Awesome find on that redundant `tal_count` and fee computation issue :+1:

**Comment by jgriffiths** [comment]
> bitcoind backend was slower than CLN could process them :-)

Probably no point optimising further for now then :)

I suspect the rpc overhead is what make this true. The absolute fastest way to do initial sync if the core block files are available would be to use an extremely cut-down block parser based on e.g. https://github.com/rustyrussell/bitcoin-iterate. With an interface that just returns each tx in the block as a pointer + length, the block txs could be constructed directly from the memmapped bytes without rpc overhead and without bin<>hex conversion. At the expense of having more code to maintain you could leave some of the parsing code intact and pass the filter criteria into the call so that filtered txs are skipped completely without even creating them.

**Pull request merged**
