### PR TITLE
Jon wally update

### PR DESCRIPTION
**Pull request by jgriffiths**
Update to latest wally candidate

This will require re-working of #3902 somewhat, since that code uses the old PSBT interfaces. I'll comment there on what needs updating.

Changelog-None

### CODE REVIEW

**Comment by rustyrussell** [comment]
Looks good, though I imagine it's not bisectable?  That's fine for review, but the last two commits need to be squashed into the first one to make it bisect.

**Comment by jgriffiths** [comment]
> Looks good, though I imagine it's not bisectable? That's fine for review, but the last two commits need to be squashed into the first one to make it bisect.

Yes this is just for review, once wally updates are merged this can be pointed at wally HEAD and the changes squashed.

**Comment by rustyrussell** [comment]
I'll ping @cdecker or @niftynei to do an elements test.. probably @niftynei since you touched it last :)

**Comment by jgriffiths** [comment]
@LeoComandini is finishing up review of the initial wally changes, once hes does that I'll merge them and update this branch to use master. There are more PSBT changes coming in wally before the next release, so I'd advise holding off on modifying your PSBT code too much until the second set of changes lands after this.

**Comment by jgriffiths** [comment]
last push is against the candidate PR if you'd like to quickly review again :)

**Comment by jgriffiths** [comment]
Updated and rebased, pointing at my current latest wally PR https://github.com/ElementsProject/libwally-core/pull/211.

This represents all of the interface changes I'm planning to make for wally PSBT support at this stage. I imagine there are further bugs in the finalizing, extracting and/or signing code that will be addressed as I can add tests. But assuming this passes your testing it should be good to merge once the wally merge is done.

If you have any requests for PSBT changes or fixes please raise wally bugs so I can track them, cheers.

**Comment by jgriffiths** [comment]
Previous CI fail was a flaky test it seems.

**Comment by jgriffiths** [comment]
Note that the wally changes are in master and this is rebased so I'm not expecting to update this PR any further at this point.

**Comment by niftynei** [comment]
`test_sign_and_send_psbt` is broken on liquid-regtest (here as well as on `master`) due to an unrelated change with how `fundpsbt` interacts with fee outputs.

I'm working on a fix, but shouldn't be a blocker for getting this merged. :+1:

**Pull request merged**
