### PR TITLE
Runes migration from commando to lightning

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
This moves the `runes` functionality of CLN from `commando` into the core (it does not yet redirect the commando plugin to use the core, but that's next!).  This allows runes to be use by far more infrastructure, such as the coming `clnrest` plugin!

Changelog-Added: JSON-RPC: `checkrune`: check rune validity for authorization; `createrune` to create/modify rune; `listrunes` to list existing runes; `blacklistrune` to revoke permission of rune

Changelog-Deprecated: JSON-RPC: `commando-rune`, `commando-listrunes` and `commando-blacklist`.

### CODE REVIEW

**Comment by rustyrussell** [comment]
> Changelog-Changed: JSON-RPC: `commando-rune` to `createrune`, `commando-listrunes` to `listrunes`, `commando-blacklist` to `blacklistrune` : rune functionality moved into core from commando plugin.
> 
> Changelog-Added: JSON-RPC: `checkrune`: check rune validity for authorization

These need to be in commit messages: we shouldn't count on getting them from GH.

Also, it's Changelog-Added: for the new ones, and Changelog-Deprecated: for the old ones!

**Comment by rustyrussell** [comment]
Oh, and don't merged inside PRs!  Always rebase, if you need to...

**Comment by MiWCryptAnalytics** [comment]
Any chance we could consider renaming the blacklistrune function? This is a user facing name, and I think we have an opportunity to be creative -- Its a rune, an ancient stone of great power and magical authorization, could it be: Destroyed, Shattered, Disintegrated, Obliterated, Pulverized, Smashed, Splintered, Unbound, Defaced, Demagicked, Disenchanted, Depowered ...

**Comment by rustyrussell** [comment]
"uncastrune"?

**Comment by rustyrussell** [comment]
Also needs rebase to fix db ops which have changed...

**Comment by rustyrussell** [comment]
> "uncastrune"?

"curserune".  But I'll let Shahana decide :)  (Note: we can have aliases to commands fairly trivially, by replicating the `struct json_command`)

**Comment by rustyrussell** [comment]
Weird!  postgres doesn't like "end" as a column name, so @ShahanaFarooqui suggested "start_index" and "end_index".

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/6403/commits/1b0a88c172ee37e5bbf58fcc96a82fbb27824dc4

**Comment by tonyaldon** [comment]
If `createrune`, `listrunes` and `blacklistrune` do the same thing as respectively `commando-rune`, `commando-listrunes` and `commando-blacklist`, why don't alias them in order not to break apps that depend on those names?

As mentioned above, it just requires replicating 3 `struct json_command`.

I think this has 2 benefits:

-   It doesn't break apps that rely on those names (for instance, those name changes break cln-application (<https://github.com/ElementsProject/cln-application/blob/main/entrypoint.sh#L22>) which uses `commando-rune` command),
-   In the long run programmers might prefer to use CLN over other LN nodes for building their apps because they know their apps won't break for API renaming.

Am I missing something about aliasing?  What do you think?

**Comment by ShahanaFarooqui** [comment]
> Any chance we could consider renaming the blacklistrune function? This is a user facing name, and I think we have an opportunity to be creative -- Its a rune, an ancient stone of great power and magical authorization, could it be: Destroyed, Shattered, Disintegrated, Obliterated, Pulverized, Smashed, Splintered, Unbound, Defaced, Demagicked, Disenchanted, Depowered ...

Thank you for the suggestion. 
- Added `invokerune` command alias for `createrune`
- Added `destroyrune` alias for command `blacklistrune`.

**Pull request merged**
