### PR TITLE
doc: update ubuntu install instructions

### PR DESCRIPTION
**Pull request by jules23**
I've followed the instructions in `doc/INSTALL.md` to install lightning on a Ubuntu `20.04.1 x86_64` machine, and I reliably get a crash on `poetry install` using the steps to reproduce below:
```
git clone https://github.com/ElementsProject/lightning.git
sudo apt-get update
sudo apt-get install -y \
  autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev \
  python3 python3-pip net-tools zlib1g-dev libsodium-dev gettext
cd lightning
virtualenv venv
source venv/bin/activate
pip install poetry
poetry install
```
The error is the following:
```
(venv) yellowcar@yellowcar:~/code/lightning$ poetry install
Installing dependencies from lock file

Package operations: 51 installs, 2 updates, 1 removal

  • Removing importlib-metadata (4.2.0)
  • Installing asn1crypto (1.4.0)
  • Installing base58 (2.1.1)
  • Installing bitstring (3.1.9)
  • Installing coincurve (17.0.0)
  • Updating cryptography (36.0.2 -> 36.0.1): Failed

  EnvCommandError

  Command ['/home/yellowcar/code/lightning/venv/bin/pip', 'install', '--no-deps', '-U', 'file:///home/yellowcar/.cache/pypoetry/artifacts/a3/bf/af/568b4f900b47050715c04cedf340b5de0373f806a090a59e03f49f8a4a/cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl'] errored with the following return code 1, and output: 
  ERROR: cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.
  

  at venv/lib/python3.8/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

  • Installing pysocks (1.7.1)
(venv) yellowcar@yellowcar:~/code/lightning$ 
```
This PR proposes a fix to this issue - move the `upgrade pip` instruction from `HACKING.md` to `INSTALL.md`. I also take the opportunity to delete the `requirements.txt` instruction in `HACKING.md`, among other minor fixes.

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5106/commits/7211330a258dbd0bcbdae5624fd3b5f4194e33d5

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
At this point, you can remove also the `requirements.lock`.

**Comment by jules23** [comment]
Rebase: remove `requirements.lock`

**Review by rustyrussell — APPROVED** [review]
Thanks!

Ack f0f730979f5b7543e558876c95c612c97ca19771

**Pull request merged**
