### PR TITLE
Clnrest testcases and removed `msat` suffix

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
Adds test suite for clnrest plugin

- cln-grpc certificate reuse
- new certificate generation
- `GET` and `POST` requests
- websocket server
- config options and HTTP headers

Link to #6436.

Also fixes a nasty bug, so I've changed milestone to the current release!

### CODE REVIEW

**Comment by tonyaldon** [comment]
Those tests were previously part of PR #6749.

Those tests need PR #6749 to be merged first to pass.

And there were failling anyway in #6749 (only in CI) with the following errors:

-   `requests.exceptions.ConnectionError` and,
-   `socketio.exceptions.ConnectionError`.

I've looked at it yesterday and I've been able to 'reproduce' similar errors locally (by tweaking `clnrest.py` code a little bit).

I think this is because waiting for `REST server running` in the log before doing http requests is not reliable as there may be a 'small' lag between that message in the log and the web server really available for incoming requests.

I think we can mitigate that by retrying the requests a few times using `Retry` class from `urllib3`.

@ShahanaFarooqui if you want you can try something like this:

In `test_clnrest.py` we can import those:

```python
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
```

Then we define a function that returns a `requests.Session()` with retry like this:

```python
def http_session_with_retry():
    # All requests are done after matching "REST server running" in the log,
    # but there may be a 'small' lag between that message in the log and the
    # web server really available for incoming requests.  So we use an http
    # session to retry several times the requests.
    http_session = requests.Session()
    retry = Retry(connect=10, backoff_factor=0.5)
    adapter = HTTPAdapter(max_retries=retry)
    http_session.mount('https://', adapter)
    return http_session
```

Then instead of doing requests like this

```python
response = requests.get(base_url + '/v1/list-methods', verify=ca_cert)
```

we generate a http session with retry and use it to do the requests
like this:

```python
http_session = http_session_with_retry()
response = http_session.get(base_url + '/v1/list-methods', verify=ca_cert)
```

Regarding the websockets, we do something similar.  Instead of doing this:

```python
# http session
http_session = requests.Session()
http_session.verify = ca_cert.as_posix()
```

we generate a http session with retry and use it like this:

```python
# http session
http_session = http_session_with_retry()
http_session.verify = ca_cert.as_posix()
```

I hope this fixes the CI errors of those tests.

**Comment by ShahanaFarooqui** [comment]
@tonyaldon Hey, thanks again for the suggestion, I will try this as soon as I am done with current task.

I tried to test the lag condition by adding 1 second sleep before sending any request the server. But tests still failed with `-n10`.

**Comment by endothermicdev** [comment]
Can we rebase this on #6749 to see the test status?
Should also probably swap the lines of clnrest.py even if it doesn't resolve all the timing issues:
```
        super().__init__()
        plugin.log(f"REST server running at {REST_PROTOCOL}://{REST_HOST}:{REST_PORT}", "info")
```
I haven't been able to recreate the test failures locally.

**Comment by ShahanaFarooqui** [comment]
> Can we rebase this on #6749 to see the test status? 

Done.

Should also probably swap the lines of clnrest.py even if it doesn't resolve all the timing issues:
> 
> ```
>         super().__init__()
>         plugin.log(f"REST server running at {REST_PROTOCOL}://{REST_HOST}:{REST_PORT}", "info")
> ```
> 

Makes sense. Done.

> I haven't been able to recreate the test failures locally.

After rebasing and using all your CPUs, you should be able to reproduce it.

**Comment by endothermicdev** [comment]
> After rebasing and using all your CPUs, you should be able to reproduce it.

I was able to replicate by limiting to 1 cpu and running 8 simultaneous tests.
`taskset -ca 0 pytest tests/test_clnrest.py -vv -n8 -x`

I was also able to complete the tests by adding a dumb delay before reporting the rest server running:

```
        super().__init__()
        time.sleep(1)
        plugin.log(f"REST server running at {REST_PROTOCOL}://{REST_HOST}:{REST_PORT}", "info")
```
Real feedback from the rest process would be better, but this was simple and sufficient to satisfy testing.  I ran through quite a few tests without failure.

**Comment by ShahanaFarooqui** [comment]
> disregard - I ran more tests and it was still slightly flaky. 

I also had the same result. After adding the delay, the tests success rate increases but they still fail sometimes.

> Some real feedback from the gunicorn worker would be nice.

Could you please elaborate on this?

**Comment by ShahanaFarooqui** [comment]
@tonyaldon I quickly tried the solution suggested above but I can still see the same behaviour. Tagging it for the next release for now.

**Comment by tonyaldon** [comment]
@ShahanaFarooqui, as you didn't push those changes, how do you know that this doesn't make the tests pass in CI? 

It could be interesting if you push those changes so that we could see if the tests pass in CI.

And if they don't pass we could have new informations (you, Alex, me and maybe other looking at that PR) from the CI environment.

**Comment by ShahanaFarooqui** [comment]
@tonyaldon Yay, CI ran successfully with clnrest tests but still failing on some other test. I tried to rerun the failed job but did not pass.

**Review by nepet — APPROVED** [review]
ACK 7579ab6a82022182afdf7205baa7a35d465a57e1

**Pull request merged**
