### PR TITLE
Feat: mbtc unit

### PR DESCRIPTION
**Pull request by m-schmoock**
As discussed in previous PRs and IRC, this PR adds the unit 'mbtc' in the RPC interface and pylightning. 

### Changes
- feat: mbtc in pylightning and amount.c
- tests: pylightning and amount.c
- doc: manpages and changelog

### Usage examples
```
lightning-cli fundchannel <node_id> 42mbtc
lightning-cli withdraw <address> 4.2mbtc
lightning-cli rebalance <out_scid> <in_scid> 1.234mbtc
...
```

### Rationale
Since fiat money turned out to be very inflationary, the Bitcoin's network token is nowadays denominated in the thousands. This makes it hard to calculate day-to-day amounts. Most wallets already support `mbtc` denomination, some of them even per default. If bitcoin is priced i.e. 5000$, anyone can quickly calculate in mbtc, which is 5$.

### CODE REVIEW

**Comment by m-schmoock** [comment]
Okay, so long I will rebase to solve conflicts...

**Comment by cdecker** [comment]
> Okay, so long I will rebase to solve conflicts...

There shouldn't be too many, hopefully :-)

**Comment by rustyrussell** [comment]
I have never seen mbtc used, so I disagree with this.  Perhaps one day we'll have a canonical unit other than btc and satoshis, but until then I think we should avoid adding another unit.

**Comment by m-schmoock** [comment]
Thanks anyway, lets wait then until a satoshi gets worth a dollar cent :D
After all its more of a frontend issue, which we don't really have.

**Comment by jb55** [comment]
My personal preference is bits, because when 1 BTC = 1 million fiat, then 1 bit = 1 dollar, and 1 sat = 1cent.

Luckily [bcalc](https://github.com/jb55/bcalc) makes it easy to do conversions in any format you want:

```
lightning-cli fundchannel <node_id> $(bcalc -n 42mbtc to sats)
lightning-cli withdraw <address> $(bcalc -n 4.2 finney to sats)
lightning-cli rebalance <out_scid> <in_scid> $(bcalc -n 1.23 bits)
```

**Pull request closed without merging**
