### PR TITLE
Signet update (stolen from PR #4068)

### PR DESCRIPTION
**Pull request by rustyrussell**

### CODE REVIEW

**Comment by kallewoof** [comment]
Code ACK. Testing now.

**Comment by dr-orlovsky** [comment]
Confirm exactly same error on Macbook Pro with macOS Catalina

**Comment by jsarenik** [comment]
@rustyrussell could you please cherry-pick (squeez-in) https://github.com/ElementsProject/lightning/pull/4073/commits/b5764fcdd8a05062b408befe71bf10b2dd49c698 from my tree?

**Comment by rustyrussell** [comment]
Oh, and I should add a Changelog-Fixed: `signet` is now compatible with the bitcoin-core version...

**Comment by jgriffiths** [comment]
@kallewoof can you post the config.log section after "checking for memset_s" from libwally built standalone and built under lightning? Use of that func is guarded by AC_CHECK_FUNC so it should work fine under both builds.

**Comment by kallewoof** [comment]
Hm..
```
$ lightning-cli newaddr
lightning-cli: WARNING: default network changing in 2020: please set network=testnet in config!
lightning-cli: Moving into '/Users/karljohan-alm/.lightning/testnet': No such file or directory
```

**Comment by jgriffiths** [comment]
> Compile errors (macbook on Catalina):
> ../../../libwally-core/src/internal.c:190:5: error: implicit declaration of function 'memset_s' is
>       invalid in C99 [-Werror,-Wimplicit-function-declaration]
>     memset_s(dest, len, 0, len);

This is fixed in wally master commit https://github.com/ElementsProject/libwally-core/commit/16fb5cc60dc38d7bc2ac5a3032dd8457c317e878 if you want to update, or alternately you can remove `CFLAGS=-std=c99 ` from `external/Makefile`.

**Review by dr-orlovsky — APPROVED** [review]
utACK https://github.com/ElementsProject/lightning/pull/4078/commits/5ac88cef90ef210fc9e12b3696a9f9507fe83fe6

**Comment by jsarenik** [comment]
ACK 5ac88cef90ef210fc9e12b3696a9f9507fe83fe6

**Comment by kallewoof** [comment]
I've tested what I could (funded a node), but don't know any peers I can connect to (jsarenik's node was gone by the time I tried it).

**Comment by jsarenik** [comment]
@kallewoof My node is up and I can leave it up as long as we agree. Otherwise it runs daily.

**Comment by kallewoof** [comment]
@jsarenik I got a 

> 2020-09-23T14:06:37.517Z DEBUG   03544abbc36ef2633fcfbc4ab3b038ca91b38fa475b760c2c76c1cb0425d15c890-connectd: Failed connected out: [2001:REDACTED:ccb6]:19737: Connection establishment: No route to host.

when I tried to do

> lightning-cli connect 03544abbc36ef2633fcfbc4ab3b038ca91b38fa475b760c2c76c1cb0425d15c890 2001:470:6f:200:ec29:2c49:5710:ccb6 19737

**Comment by kallewoof** [comment]
Tested ACK 5ac88cef90ef210fc9e12b3696a9f9507fe83fe6

(OK, apparently my home network doesn't support IPv6 right now. 

Anyway,) @jsarenik graciously gave me an IPv4 address, and that worked. I've funded a channel with his node, sent him several payments, and also used keysend a few times. He can't use it on me cause I'm behind a NAT atm.

**Comment by dr-orlovsky** [comment]
> I've tested what I could (funded a node), but don't know any peers I can connect to (jsarenik's node was gone by the time I tried it).

@kallewoof try mine: `03787bddbba4bbae8133a164fa6db5de0f267e9bffe96695bc1e1c47a7b8e3d4ff@pandora.network:39735`

I have also established channel with it + did funding and payments (from my notebook signet c-lightning). Everything working well (before the latest changes & bitcoin core update; with docker images I referenced above).

**Comment by kallewoof** [comment]
@dr-orlovsky I get

> 2020-09-23T15:18:50.248Z DEBUG   03787bddbba4bbae8133a164fa6db5de0f267e9bffe96695bc1e1c47a7b8e3d4ff-connectd: Failed connected out: 31.14.40.18:39735: Connection establishment: Bad file descriptor.

after about a minute of waiting.

**Comment by carnhofdaki** [comment]
Tested ACK

my node is at `02bcf115239d5c01b02d8f238bf736ffb23e0ef8ba73164b0fb3b82b83577190d4@dhouqtpq6sxrx4oopkawqp65ntpidwzgepv5g7azlbnl4m3owpwbriid.onion:1247`

**Comment by dr-orlovsky** [comment]
@kallewoof strange. I think I need to upgate docker container with a new build from this version.

@carnhofdaki I am getting
```console
orlovsky@pandora:~$ sightning-cli connect 02bcf115239d5c01b02d8f238bf736ffb23e0ef8ba73164b0fb3b82b83577190d4@dhouqtpq6sxrx4oopkawqp65ntpidwzgepv5g7azlbnl4m3owpwbriid.onion:1247
lightning-cli: Connecting to 'lightning-rpc': Connection refused
```

**Comment by kallewoof** [comment]
I should be available (sporadically) at 02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92@r5zmwuqr5kj7mufcyjtpgjggabw4fxwrj3ipd6i3f2afwddswnolx2yd.onion:9735 -- I think.

**Comment by jsarenik** [comment]
@kallewoof even though I can `ping` you, I can not `keysend` to you.

```
$ lightning-cli --signet ping 02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92
{
   "totlen": 132
}
$ lightning-cli --signet keysend 02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92 8304721sat
{
   "code": 210,
   "message": "Ran out of routes to try after 1 attempt: see `paystatus`",
   "attempts": [
      {
         "status": "failed",
         "failreason": "Error computing a route to 02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92: \"Could not find a route\" (205)",
         "partid": 0,
         "amount": "8304721000msat"
      }
   ]
}
$ lightning-cli --signet paystatus # nothing here
{
   "pay": []
}
```

All this running on node `03b9e6c1dec203f47efc95d003314d22cbb12a1324de4b091fe7d68f321a56322f` where I opened a maximum size channel to you and it is in active state. Full connection string to this node which should be running 24/7 on latest lightningd is 

 * IPv4: `03b9e6c1dec203f47efc95d003314d22cbb12a1324de4b091fe7d68f321a56322f@217.195.164.4:19738`
 * onion: `03b9e6c1dec203f47efc95d003314d22cbb12a1324de4b091fe7d68f321a56322f@4il7h45anzwjdkaguk7b7w5gzftjky6upov2wnlv7zuzfdp3rbv5ppyd.onion:9735`

And I will rather not mention this node's randomly generated alias here. Keeping it for some fun.

@kallewoof couldn't the problem with receiving be related to recent macOS issues? #3226

**Comment by kallewoof** [comment]
@jsarenik Could this be because I switched from IPv4 to Tor without closing our IPv4 channel first?

**Comment by jsarenik** [comment]
@kallewoof I think that should not be related. On the node where you opened a channel yesterday I see your node like this (trough `listpeers`):

```json
    {
      "id": "02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92",
      "connected": true,
      "netaddr": [
        "[2a0b:f4c2::1]:61893"
      ],
      "features": "02aaa2",
      "channels": [
        {
          "state": "CHANNELD_NORMAL",
          "scratch_txid": "69a8f7952efaa592eac8230b57f5c6f302c0291c17f61809bfb1b73e79a6c2e2",
          "owner": "channeld",
          "short_channel_id": "4498x1x0",
          "direction": 1,
          "channel_id": "66eaf9ab8efd313a4a589fa66ddc28223b82de34ca3b2607be623c2600ebe4fe",
          "funding_txid": "fee4eb00263c62be07263bca34de823b2228dc6da69f584a3a31fd8eabf9ea66",
          "close_to_addr": "tb1qm2rqg8fftkf862yl5rqh0td08v360540jz04uk",
          "close_to": "0014da86041d295d927d289fa0c177adaf3b23a7d2af",
          "private": false,
          "features": [
            "option_static_remotekey"
          ],
          "funding_allocation_msat": {
            "02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92": 16777215000,
            "03544abbc36ef2633fcfbc4ab3b038ca91b38fa475b760c2c76c1cb0425d15c890": 0
          },
          "funding_msat": {
            "02823458ef60b73cef29eb3071d8f8062a452342014e66cadf9a35750352e5fa92": "16777215000msat",
            "03544abbc36ef2633fcfbc4ab3b038ca91b38fa475b760c2c76c1cb0425d15c890": "0msat"
          },
          "msatoshi_to_us": 10000201,
          "to_us_msat": "10000201msat",
          "msatoshi_to_us_min": 0,
          "min_to_us_msat": "0msat",
          "msatoshi_to_us_max": 10000201,
          "max_to_us_msat": "10000201msat",
          "msatoshi_total": 16777215000,
          "total_msat": "16777215000msat",
          "dust_limit_satoshis": 546,
          "dust_limit_msat": "546000msat",
          "max_htlc_value_in_flight_msat": 18446744073709552000,
          "max_total_htlc_in_msat": "18446744073709551615msat",
          "their_channel_reserve_satoshis": 167772,
          "their_reserve_msat": "167772000msat",
          "our_channel_reserve_satoshis": 167772,
          "our_reserve_msat": "167772000msat",
          "spendable_msatoshi": 0,
          "spendable_msat": "0msat",
          "receivable_msatoshi": 4294967295,
          "receivable_msat": "4294967295msat",
          "htlc_minimum_msat": 0,
          "minimum_htlc_in_msat": "0msat",
          "their_to_self_delay": 6,
          "our_to_self_delay": 6,
          "max_accepted_htlcs": 483,
          "status": [
            "CHANNELD_NORMAL:Reconnected, and reestablished.",
            "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
          ],
          "in_payments_offered": 3,
          "in_msatoshi_offered": 10000201,
          "in_offered_msat": "10000201msat",
          "in_payments_fulfilled": 3,
          "in_msatoshi_fulfilled": 10000201,
          "in_fulfilled_msat": "10000201msat",
          "out_payments_offered": 0,
          "out_msatoshi_offered": 0,
          "out_offered_msat": "0msat",
          "out_payments_fulfilled": 0,
          "out_msatoshi_fulfilled": 0,
          "out_fulfilled_msat": "0msat",
          "htlcs": []
        }
      ]
    },
```

**Comment by dr-orlovsky** [comment]
@jsarenik channel funded.

So yes, prev build was just not working with the new one

And yes, c-lightning fails to estimate fees on signet (I assume that's ok?)

**Comment by kallewoof** [comment]
> And yes, c-lightning fails to estimate fees on signet (I assume that's ok?)

Yeah, this is the case for bitcoin core as well, and applies to regtest as well.

**Pull request merged**
