### PR TITLE
common: Check chain hash in gossip_timestamp_filter

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Fixes in code `FIXME` for checking chain hash in gossip_timestamp_filter messages. Updates tests to follow that as well.

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Thanks, this is a very nice cleanup and fix!

Ack 177d3f34bf29b480f61091564f190873bb27f3b5

**Comment by rustyrussell** [comment]
Pushed trivial rebase due to textual conflicts with updated master.

Ack https://github.com/ElementsProject/lightning/commit/fd2ea1bc3cfa77341945d74ef8a82236296b21a8

**Comment by nalinbhardwaj** [comment]
@rustyrussell thanks for the rebase. Seems like there's a few valgrind CI failures, but I'm assuming those are just flaky tests unrelated to my change. Let me know if not.

**Comment by rustyrussell** [comment]
Another rebase, hopefully fixes CI flakes.

Ack https://github.com/ElementsProject/lightning/commit/74a718b75548c525e07f2772e09de31c3ecb1d11

**Pull request merged**
