### PR TITLE
Remove Sensitive RPC Data from Logs

### LINKED ISSUE #2424: Security issue RPC passwords in the logs
### Issue and Steps to Reproduce

Security problem, rpc user and password is directly logged and visible in plain text:

`    {
      "type": "UNUSUAL", 
      "time": "36.846054011", 
      "source": "lightningd(6):", 
      "log": "bitcoin-cli: finished bitcoin-cli -rpcconnect=bitcoind -rpcuser=user -rpcpassword=XXXXXXXXXX getblock 00000000000000000026d73aa75d1731ac4340899fcec00091dd9e8e78aa53c3 false (15439 ms)"
    }, `

### `getinfo` output
`  "version": "v0.6.3rc1-118-g0da4054", `

Using Docker official image.

### PR DESCRIPTION
**Pull request by JeffVandrewJr**
This is a patch to fix #2424.

It modifies the `bcli_args` function to skip any arguments with sensitive RPC username/password data when printing `bitcoin-cli` data to logs.

This is my first code PR to the project; please accept my apologies ahead of time if I inadvertently violated any standards/procedures.

### CODE REVIEW

**Comment by JeffVandrewJr** [comment]
@rustyrussell Thanks! I have made the changes which you suggested.

**Comment by rustyrussell** [comment]
I can squash on merge. It's also 4 spaces vs tabs, but that's also a trivial fix :)

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/a88f39d04d9ffebf8150b5772433e4540c19b91c

**Comment by JeffVandrewJr** [comment]
@rustyrussell Thank you. I will make sure that the next time I have a PR I will squash any non-compiling commits as well as be more careful with my tabs/spaces. 🙏

**Pull request merged**
