### PR TITLE
Zombie channel patch

### PR DESCRIPTION
**Pull request by endothermicdev**
As reported by @m-schmoock, some nodes and channels went missing from the gossmap while running 23.02rc3.  This occurred after restarting the node, which possibly lost some state on the zombie channels.

Changelog-None

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Ack 530da53a05f0a2aef47c7af4aad20a7605f2a2e8

**Comment by rustyrussell** [comment]
Running this on my node now...

**Comment by m-schmoock** [comment]
Thanks Alex for digging into this! I'm also running it...

**Review by rustyrussell — APPROVED** [review]
ACK 0e229872bf7d62c22ee8ac53a99a96307cde5f91

**Comment by m-schmoock** [comment]
Updated my node again on this...

**Comment by endothermicdev** [comment]
I'm running as well.  I've modified the prune timer on my node to fire off every 10 minutes vs 3.5 days just so I can see some results. (divide the prune interval by 2016 rather than 4.)  This PR is keeping the store intact and resurrecting some channels afterward.  Node and channel counts are in line with what we now expect.  It only pruned about 24 nodes in the first cycle - and they all look like quite reasonable candidates.  Still in the 9K nodes 120K channel updates range.  Welcome to the new normal.

**Pull request merged**
