### PR TITLE
Only 3 question marks for 4 variables

### PR DESCRIPTION
**Pull request by hMsats**
I think this gave me a lot of problems while testing splicing. Don't ask me how I found it :-)

### CODE REVIEW

**Comment by ShahanaFarooqui** [comment]
@hMsats Rather than merging master into your fork, first rebase your master on elementsproject's master then add your change in a single commit please.

**Comment by hMsats** [comment]
@ShahanaFarooqui better? :smiley:

**Review by ddustin — APPROVED** [review]
Great find!

My only question is how this got past the testing... It looks like we may need to do lnprototest to recreate this instead of just the python test 🤔

**Comment by rustyrussell** [comment]
Yes.  This means this code has *never* been run.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6713/commits/465f173c98cd60697c3f04d965d3a668cb53cdfe

It is sad to see that it was not caught by the review process. Sorry about that

**Pull request merged**
