### PR TITLE
CPFP for mutual close

### PR DESCRIPTION
**Pull request by rustyrussell**

### CODE REVIEW

**Comment by wtogami** [comment]
Cool do any other implementations support this?

**Comment by rustyrussell** [comment]
> Cool do any other implementations support this?

I assume they all do: it's a weird CLN quirk that we didn't expose it in our wallet before confirmation.

**Review by vincenzopalazzo — COMMENTED** [review]
CI is failing

```
ld lightningd/test/run-jsonrpc
/usr/bin/ld: lightningd/test/run-invoice-select-inchan.o: in function `sign_and_send_last':
/home/runner/work/lightning/lightning/lightningd/test/../peer_control.c:302: undefined reference to `wallet_extract_owned_outputs'
collect2: error: ld returned 1 exit status
make: *** [Makefile:660: lightningd/test/run-invoice-select-inchan] Error 1
make: *** Waiting for unfinished jobs....
rm external/build-x86_64-linux-gnu/libwally-core-build/src/secp256k1/libsecp256k1.la
```

**Comment by rustyrussell** [comment]
> CI is failing
> 
> ```
> ld lightningd/test/run-jsonrpc
> /usr/bin/ld: lightningd/test/run-invoice-select-inchan.o: in function `sign_and_send_last':
> /home/runner/work/lightning/lightning/lightningd/test/../peer_control.c:302: undefined reference to `wallet_extract_owned_outputs'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:660: lightningd/test/run-invoice-select-inchan] Error 1
> make: *** Waiting for unfinished jobs....
> rm external/build-x86_64-linux-gnu/libwally-core-build/src/secp256k1/libsecp256k1.la
> ```

Yep, needed to update-mocks after rebase on master...

**Comment by vincenzopalazzo** [comment]
Ok now rerunning lnprototest because the following assertion looks really strange to me

```
2023-10-02T04:51:25.121Z DEBUG   gossipd: Shutting down
2023-10-02T04:51:25.121Z DEBUG   hsmd: Shutting down

ERROR:root:Traceback (most recent call last):
  File "/work/external/lnprototest/lnprototest/utils/utils.py", line 95, in run_runner
    runner.run(test)
  File "/work/external/lnprototest/lnprototest/runner.py", line 100, in run
    all_done = sequence.action(self)
  File "/work/external/lnprototest/lnprototest/structure.py", line 55, in action
    all_done &= e.action(runner)
  File "/work/external/lnprototest/lnprototest/event.py", line 340, in action
    raise EventError(
lnprototest.errors.EventError: `Did not receive a message msgtype-warning from runner` on event [{"event": "ExpectMsg", "file": "test_bolt2-01-open_channel.py", "pos": "335"},]

=========================== short test summary info ============================
FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side_wrong_announcement_signatures - AssertionError: `Did not receive a message msgtype-warning from runner` on ...
```

**Comment by rustyrussell** [comment]
> Ok now rerunning lnprototest because the following assertion looks really strange to me
> 
> ```
> 2023-10-02T04:51:25.121Z DEBUG   gossipd: Shutting down
> 2023-10-02T04:51:25.121Z DEBUG   hsmd: Shutting down
> 
> ERROR:root:Traceback (most recent call last):
>   File "/work/external/lnprototest/lnprototest/utils/utils.py", line 95, in run_runner
>     runner.run(test)
>   File "/work/external/lnprototest/lnprototest/runner.py", line 100, in run
>     all_done = sequence.action(self)
>   File "/work/external/lnprototest/lnprototest/structure.py", line 55, in action
>     all_done &= e.action(runner)
>   File "/work/external/lnprototest/lnprototest/event.py", line 340, in action
>     raise EventError(
> lnprototest.errors.EventError: `Did not receive a message msgtype-warning from runner` on event [{"event": "ExpectMsg", "file": "test_bolt2-01-open_channel.py", "pos": "335"},]
> 
> =========================== short test summary info ============================
> FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side_wrong_announcement_signatures - AssertionError: `Did not receive a message msgtype-warning from runner` on ...
> ```

Yes, timing changes in recent commits made this worse, but it's real: we never properly waited in many cases where we send a warning, and lightningd tells connectd to hang up.

Will fix

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6734/commits/284173edf6000e13ce12c02b14efa29144506dcc

It is missing just a rebase to see if the CI is happy again

**Comment by vincenzopalazzo** [comment]
Ah, I can do it :)

Trivial Rebase on master

**Pull request merged**
