### PR TITLE
Issue 4305 - Added in_channel,out_channel,state params to listforwards

### PR DESCRIPTION
**Pull request by hosiawak**
I've added in_channel,out_channel and state params to listforwards.

I also added an index to forwarded_payments.state to speed up lookups that use this column (eg. getinfo).

TODO:
* tests (struggling with a broken Python atm)
* docs

### CODE REVIEW

**Comment by rustyrussell** [comment]
Yep, this is great!  We generally dislike underscores in JSON parameters, *but* the JSON already outputs those names so consistency wins.

Tests would ofc be nice, so would docs ;)

**Comment by hosiawak** [comment]
Added `listforwards` test and updated the docs.

**Comment by rustyrussell** [comment]
Since we switch from failing Travis to GH actions, I will rebase this now...

**Comment by rustyrussell** [comment]
Source checks (make check-source) failed because:
1. wallet/wallet.c include files are not in alphabetical order for the first commit.
2. The third commit has extraneous whitespace in the python.

Trivial to fix up though!

**Comment by rustyrussell** [comment]
OK, due to lack of response, I rebased, fixed those check-source errors, and removed the accidental checkin of a binary.

**Comment by hosiawak** [comment]
_Trivial to fix up though!_

I read this and thought you were about to fix it up because it was trivial for you and then forgot about this issue. Sorry, guess I got lost in translation a little bit :)

I'll try to pay attention to such errors in my next PR. Navigating C and Python codebase is new water for me.

**Comment by rustyrussell** [comment]
Had to do a trivial rebase again, since db files changed under us.  This time for sure!

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/commit/3b9f5f5c123b00e714b40b22e609a1d200d65aa1

**Pull request merged**
