### PR TITLE
remove unnecessary software package from arm Dockerfile

### PR DESCRIPTION
**Pull request by arowser**

### CODE REVIEW

**Comment by cdecker** [comment]
Out of curiosity, @NicolasDorier what is `qemu` used for in the Docker images? You are in a far better position to give feedback on this PR :-)

**Comment by NicolasDorier** [comment]
@cdecker it is so you can build the image on a x64 machine.

**Comment by NicolasDorier** [comment]
tACK

**Comment by cdecker** [comment]
Thanks for the all-clear @NicolasDorier :-)

**Pull request merged**
