### PR TITLE
Connectd gossip timestamp filtering optimizations

### PR DESCRIPTION
**Pull request by rustyrussell**
This doesn't do the "optimize our own gossip" yet, as that is a bigger job.  But it does the normal gossip optimizations.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5342/commits/a3a670b786a9d9a317cfcd77597639d5046244b3

**Comment by rustyrussell** [comment]
Rebase on master (should fix flake)

**Comment by rustyrussell** [comment]
Rebased on top of #5375

**Comment by endothermicdev** [comment]
ACK bf3251d

**Review by endothermicdev — APPROVED** [review]
Nice optimization. This will save a lot of time traversing the gossip store.
ACK bf3251d

**Comment by rustyrussell** [comment]
Rebased on master to trivially resolve conflict.

Ack https://github.com/ElementsProject/lightning/pull/5342/commits/3c5012e097124ccef01a923af4e0c1108241c35b

**Pull request merged**
