### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by shuoer86**
fix typos in document.

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Thanks, could you squash these commits in a single one?

**Comment by shuoer86** [comment]
@vincenzopalazzo sure. thank you very much for your review.

**Review by vincenzopalazzo — COMMENTED** [review]
wondering if you ran `make doc-all`?

**Comment by shuoer86** [comment]
@vincenzopalazzo I already ran `make doc-all`, and everything is up to date.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/6965/commits/ac6b7245a2480c67eac5a90d76a2632edfcb131c

**Comment by shuoer86** [comment]
@vincenzopalazzo could you help to merge it? thank you very much.

**Pull request merged**
