### PR TITLE
Gossip announce problems

### PR DESCRIPTION
**Pull request by rustyrussell**
This tickles two separate bugs.  I'll look at actually fixing them in about 4 hours.

See: #2968

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Cool, let me know when done I can test again easily.

**Comment by cdecker** [comment]
Cleaned up the two tests (`pytest.mark.xfail` and removed redundant initialization), added fixes for both issues, and optimized the way `filteredblock_call`s get allocated (allocate result only once we get executed, saving all allocations for coalesced calls to `getfilteredblock`).

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/2973/commits/cc93b992de9ad0b35cada0f1dac6d1fcebc6cbac

**Comment by rustyrussell** [comment]
Autosquash

Ack https://github.com/ElementsProject/lightning/pull/2973/commits/c722739aff0442a117699d7315cd492ff2558463

**Pull request merged**
