### PR TITLE
channeld: Reduce the feerate security margin in high fee environments

### LINKED ISSUE #6974: Tweaking the feerate security margin
When forwarding an HTLC the funder needs to ensure that it can at
least add one more HTLC. This is the result of [LN#728], which aims to
protect a channel to get into a mode where no new HTLC can be added,
not even by the fundee to rebalance the channel (due to feerate
spiking causing the commitment TX fee to no longer be payable by the
funder).

CLN is trying to be secure even against larger feerate spikes, by
being very pessimistic and assuming up to a 100% feerate spike (using
200% current feerate to determine whether adding an HTLC is safe or
not).

I would argue that for low-fee environments the 100% security margin
is justified, since the likelihood of `2 * 1sat/vbyte` is much more
likely than `2 * fee ATH`, but I would linearize this buffer to reduce
it relative to the absolute fee as the feerate grows.

My proposal would be to:

 1. Take today's fee ATH: `maxfeerate`
 2. Use `1sat/vbyte` as `minfeerate`
 3. Compute the current feerate margin to use as the following: `1 -
    min(x - minfeerate, maxfeerate)/(maxfeerate * 1.1)`. This results
    in a 2x current feerate close to the minfeerate, smoothly
    discounted until we get to `maxfeerate` at which point we just
    take a 10% margin.
	
The idea here is that close to the lower end where feerates are likely
to increase from, the multiplier is still the current 2x. Closer to
the historical maximum feerate we only apply a 10% margin, as the fees
are much less likely to increase further. The place to apply this
would be the [code] line, where we replace the `2` constant with the
margin computation.

I'm currently trying to reproduce this in a test to verify the fix
works as expected, and some historical analysis on max feerates to use
could further inform the 3 variables in play here:

 - Starting slope (`2`)
 - Final slope (`1.1`)
 - Historical max feerate (`41234perkw`, taken from the original issue) 
 
## Additional information

In case somebody may be wondering what running into this issue looks
like, here are the relevant log lines:

``` text
2024-01-01T11:33:18.422Z DEBUG   03d6f117b93d0eb1c440de5549cc4f48253f94dfdcab5f92a3199167323ac05016-channeld-chan#1672: Adding HTLC would leave us only 51840000msat: we need 60531sat for another HTLC if fees increase by 100% to 41234perkw
2024-01-01T11:33:18.423Z DEBUG   03d6f117b93d0eb1c440de5549cc4f48253f94dfdcab5f92a3199167323ac05016-channeld-chan#1672: Adding HTLC 0 amount=2500000msat cltv=824005 gave CHANNEL_ERR_CHANNEL_CAPACITY_EXCEEDED
2024-01-01T11:33:18.423Z DEBUG   03d6f117b93d0eb1c440de5549cc4f48253f94dfdcab5f92a3199167323ac05016-channeld-chan#1672: REPLY WIRE_CHANNELD_OFFER_HTLC_REPLY with 0 fds
```

[LN#728]: https://github.com/lightning/bolts/issues/728
[code]: https://github.com/cdecker/lightning/blob/20240102-coverage/channeld/full_channel.c#L565

### PR DESCRIPTION
**Pull request by cdecker**
The feerate security margin is a multiplicative factor applied to the
feerate of some transactions in order to guarantee that the
transaction remains publishable and has a sufficient chance of being
confirmed, that we can base some of our decisions on that.

The multiplicative factor is >=1 and was so far a constant 2. This
might have been sensible in the low-fee environment, where the fees
are expected to oscillate, and almost guaranteeing that we will
eventually have rising feerates but in high-fee environments that is
no longer the case, and the 100% margin that the multiplicator 2
brings is excessive. We therefore opt to start out with 100%, then
linearly interpolate up to a given maxfeerate (which does not have to
be a real feerate ever reached, it just indicates the feerate after
which we apply the constant 10% margin.

Fixes #6974
Closes #6976

### CODE REVIEW

**Review by JssDWt — APPROVED** [review]

**Comment by cdecker** [comment]
Since the feerates changed, the thresholds for a couple of tests changed as well. Removing from milestone as we adjust the magic values in the tests.

**Comment by rustyrussell** [comment]
Trivial rebase to kick CI...

**Comment by rustyrussell** [comment]
This needed quite a bit more work.  Fortunately I'd already started that: including recalculating constants for tests, and changing our "spendable" calc to match this logic.

**Comment by endothermicdev** [comment]
Thank Rusty!  Was looking at this one yesterday and my machine was intimidated by "v. v. slow!"
Pushed a whitespace fixup.

**Comment by endothermicdev** [comment]
I like the minimal solution to allow the BOLT3 test vector.  Is there a good reason the test vector has a feerate of 0 versus the minimum to relay?  Should it be updated?
ACK 264a266eaea113d63a60a6949ae9f61f292fb0fc

**Pull request merged**
