### PR TITLE
Renepay: add channel filters

### PR DESCRIPTION
**Pull request by Lagrang3**
We add a channel filtering paymod that disables channels that have very
low max_htlc. It can be expanded to consider other properties as well,
for instance high base fee, low capacity or high latency.

This PR depends on #7337 and #7357.

### CODE REVIEW

**Comment by Lagrang3** [comment]
Rebased on top of `Lagrang3:renepay-simpler-routetracker` aka PR #7357.

**Comment by Lagrang3** [comment]
Rebased to fix conflicts 2b35ec8.

**Comment by rustyrussell** [comment]
Rebased to fix conflicts, but I had to merge many of the commits together to make it compile at each point!

**Comment by rustyrussell** [comment]
Ack 25a154101

**Comment by Lagrang3** [comment]
> Rebased to fix conflicts, but I had to merge many of the commits together to make it compile at each point!

Is this a conventional requirement?

**Pull request merged**
