### PR TITLE
plugins: rust clnrest plugin

### PR DESCRIPTION
**Pull request by JosephGoulden**
I'm running clightning on Nixos and make use of the REST API. The python build of the clnrest plugin keeps breaking because of incorrect dependency versions in nixpkgs (from what I understand python on nix is a bit of a pain, and its not a language I use so I don't care to dig into it).

So I wrote a replacement plugin in rust that utilises the cln-rpc and cln-plugin crates and it is working well.

I'm not aware of the architecture/language strategy for clightning and I don't mean to tread on any toes so I'm just opening this draft PR to see if this is something that would be of interest, or perhaps it should be in a different repo?

### CODE REVIEW

**Comment by daywalker90** [comment]
Duplicate of https://github.com/ElementsProject/lightning/pull/7509

**Comment by JosephGoulden** [comment]
Nice one @daywalker90 !

**Comment by chrisguida** [comment]
Wow, great minds think alike!

**Comment by chrisguida** [comment]
@JosephGoulden does this plugin have any features missing from @daywalker90's plugin?

Anyway it would be amazing if you could help test/maintain the other plugin! :)

**Comment by JosephGoulden** [comment]
@chrisguida No the other PR was already further down the line with features and integration into this project.

It would be a lot easier for me to work on this project if we could get #6650 merged. Even just a very basic flake that we can iterate on would be good. Happy to help with any rust plugins I can make use of (currently trying a few out).

**Comment by chrisguida** [comment]
Awesome! Yeah #6650 is just a draft, not sure if I ever got it working... did you try it yet?

**Pull request closed without merging**
