### PR TITLE
cleanup: Use the most common abbreviation of 'ctx' in `json_tok_address_scriptpubkey`

### PR DESCRIPTION
**Pull request by trueptolemy**
Though I don't know the meaning of name `ctx`, it's a most common abbreviation.
We'd better use `ctx` other than `cxt`.

...BTW, could you tell me what's the full name of `ctx`?

### CODE REVIEW

**Comment by niftynei** [comment]
`ctx` is short for 'context'. `tmpctx` is 'temporary context'. It's the 'context' that you want to associate a memory allocation to.

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2963/commits/55fa050f8df629098e6e3275b8c964aa193ebb84

**Comment by cdecker** [comment]
Waiting for the 0.7.2 feature freeze to finish before merging this :-)

**Comment by trueptolemy** [comment]
Rebased and wait Travis-CI to pass.

**Pull request merged**
