### PR TITLE
msggen: add delpay method

### PR DESCRIPTION
**Pull request by daywalker90**
Based on the fixes from #7215 + #7217 + #7218 and #7230

### CODE REVIEW

**Comment by cdecker** [comment]
Merging this one as soon as #7230 is merged :+1:

**Review by cdecker — APPROVED** [review]
ACK 7e1b82ee668138c223b2829b4e68d61effea9320

**Comment by cdecker** [comment]
This needs a rebase on top of `master` and we should be good to merge :+1:

**Comment by daywalker90** [comment]
rebased on master

**Comment by cdecker** [comment]
ACK 474ffe142d9e5d9fde034eb507311e8b5879aa24

**Pull request merged**
