### PR TITLE
pay: Use the networkheight as current height

### PR DESCRIPTION
**Pull request by cdecker**
We used to use the sync height, i.e., the height of the last block that
we processed as the offset for all calculations. This can result in CLTVs
that are too close to the current height while still synchronizing with
the blockchain.

This PR adds the `networkheight` to `waitblockheight` so we can retrieve
the current height of the block that our bitcoin backend has seen.

This means that CLTV calculations are correct as long as a) the backend
is in sync and b) the peer is in sync.

Sending the payment without sync is safe, because if the peer accepts the
HTLC they ensured the channel is still open and active.

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Needs fixup folding, but code looks great!

**Comment by cdecker** [comment]
I had to rework this patch a bit, since the `waitblockheight` call with `blockheight: 0` would not actually return the bitcoin backend's blockheight, but rather the `max(start blockheight, current sync height)` which may be ok in most cases, but in the case of a long catch up would not (new blocks coming in while we are syncing would not be taken into consideration).

This calls both `waitblockheight` and `getchaininfo` to compute a `chainlag` which is then used as the offset.

**Comment by cdecker** [comment]
Addressing a bunch of test failures that were reliant on the old behavior now.

**Review by endothermicdev — APPROVED** [review]
Looks great! nits only.

**Review by rustyrussell — APPROVED** [review]

**Pull request merged**
