### PR TITLE
add failing test for rpc_command calling another rpc method.

### PR DESCRIPTION
**Pull request by fiatjaf**
Actually this doesn't fail, it hangs forever.

Related to https://github.com/ElementsProject/lightning/issues/3578.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Erk, this is reentrant of course.  Not sure the best way to handle this!

**Comment by cdecker** [comment]
Yeah, this is not something we should or will ever support. `rpc_command` is a synchronous call blocking incoming RPC processing, if we then call anything on the RPC the expected behavior is to block indefinitely. Don't do this.

**Comment by fiatjaf** [comment]
Yes, it makes sense, better not do this. I'll find another way.

But please add a note to the documentation because I was misled by this thinking it would work multiple times.

**Comment by gijswijs** [comment]
I think it's actually worse than described in this issue and there *is* something wrong: Just using the `rpc_command` hook in your pkugin makes any rpc call from that plugin impossible, regardless of whether the call comes from inside that hook. That seems unwanted behavior.

Steps to reproduce:

Run this plugin:

```python
#!/usr/bin/env python3
from pyln.client import Plugin

plugin = Plugin()
plugin.our_node_id = None

@plugin.init()
def init(options, configuration, plugin):
    plugin.log("Plugin dpchannels.py initialized")
    plugin.our_node_id = plugin.rpc.getinfo()["id"]
    plugin.log("Our node id {}".format(plugin.our_node_id))

@plugin.hook("rpc_command")
def on_rpc_command(plugin, rpc_command, **kwargs):
    return {"result": "continue"}

plugin.run()
```

This plugin will hang upon initialization, because the `plugin.rpc.getinfo()` will never return a result. If you remove the 'rpc_command' hook, it does work.

It seems to me this should not have to be blocking, but somehow it is. 

@fiatjaf could you reopen this issue, or should I submit a new one?

**Comment by fiatjaf** [comment]
I can't reopen, the button is inactive.

And I think it's better to open a new one anyway, as this is a different and more serious issue.

**Comment by cdecker** [comment]
You can run the `getinfo` in a separate thread to avoid the mutual deadlock, it is an issue with pyln since that is singlethreaded. A fix to this could be to have a ThreadPoolExecutor that handles incoming method and hook calls.

**Comment by gijswijs** [comment]
Can confirm @cdecker 's solution works:

Same plugin, now with threading

```
#!/usr/bin/env python3
from pyln.client import Plugin
import threading

plugin = Plugin()
plugin.our_node_id = None

def get_node_id():
    plugin.log("Thread started")
    plugin.our_node_id = plugin.rpc.getinfo()["id"]
    plugin.log("Our node id from thread{}".format(plugin.our_node_id))

@plugin.init()
def init(options, configuration, plugin):
    plugin.log("Plugin dpchannels.py initialized")
    thread = threading.Thread(target=get_node_id, args=())
    thread.start()
    plugin.log("Our node id from init {}".format(plugin.our_node_id))

@plugin.hook("rpc_command")
def on_rpc_command(plugin, rpc_command, **kwargs):
    return {"result": "continue"}

plugin.run()
```

**Pull request closed without merging**
