### PR TITLE
Do not overflow the u16 num_channels field in the gossip_getchannels_reply message

### LINKED ISSUE #2504: Node not seeing recent channels
### Issue and Steps to Reproduce

Running b17b05b8ae271d097d39ff24840d17f1f47e88be, after a long uptime, the most recent channel is from block 552,214 (Dec 2018). Recent channels are not showing up.

However, logs have lines about more recent channels:

```
 Received channel_update for 559295x969x0 with old time 1550692137
```

### `getinfo` output

```json
{
  "id": "023d280ae29f84dcfd289eb66b57227fea3a7bde97ec2869923d3c4d5c6a426028", 
  "alias": "p2sh.info", 
  "color": "023d28", 
  "num_peers": 16, 
  "num_pending_channels": 0, 
  "num_active_channels": 15, 
  "num_inactive_channels": 0, 
  "address": [
    {
      "type": "ipv4", 
      "address": "195.201.84.23", 
      "port": 9735
    }, 
    {
      "type": "ipv6", 
      "address": "2a01:4f8:13b:3da8::2", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.7.0-48-gb17b05b", 
  "blockheight": 568888, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 3267, 
  "fees_collected_msat": "3267msat"
}
```

### PR DESCRIPTION
**Pull request by cdecker**
Turns out we now have more than `UINT16_MAX` channels to return, and we were just overflowing that field.

Fixes #2504

### CODE REVIEW

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2505/commits/22dc67f70bc3d7e4fb1c6317feef37d55d0a9d14

**Comment by rustyrussell** [comment]
Note there's an almost identical fix in my gossip_store optimization PR, for the million channels project...

**Comment by niftynei** [comment]
@rustyrussell yeah i just saw it. that PR is a monster btw, i'm about halfway through it :page_with_curl:

**Comment by cdecker** [comment]
I merged this one, since it addresses a small issue on its own. I really don't like keeping these standalone fixes pending forever as part of a huge pile of commits.

**Pull request merged**
