### PR TITLE
diff -R to diff -r

### PR DESCRIPTION
**Pull request by LightningHelper**
diff does not have -R, it has -r

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Mh, my diff command doesn't contain the option `-r` or `-R`. I think this depends on the version?

My version is: diff (GNU diffutils) 3.7

**Comment by LightningHelper** [comment]
```bash
3:~$ diff -R
diff: invalid option -- 'R'
diff: Try 'diff --help' for more information.
3:~$ diff -r
diff: missing operand after '-r'
diff: Try 'diff --help' for more information.
:~$ diff -v
diff (GNU diffutils) 3.7
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.


```

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4671/commits/9fa6b01a2ea7cba6ffebcf1f65e673e626afbad0

Sorry, I read the error in the wrong way.

**Review by rustyrussell — APPROVED** [review]
Ack 9fa6b01a2ea7cba6ffebcf1f65e673e626afbad0

**Pull request merged**
