### PR TITLE
contrib: add init file for systemd

### PR DESCRIPTION
**Pull request by dougsland**
Similar to init/bitcoind.service, this patch
includes an initial lightningd.service.

### CODE REVIEW

**Comment by dougsland** [comment]
This init will be useful for packaging schema. Tested against Fedora 28.

Reference: https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service
Related: https://github.com/ElementsProject/lightning/issues/1606#issuecomment-412167373
              https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md#to-build-on-fedora

Additional information for testing (On Fedora 28):

0. Create user bitcoin
1. Make sure bitcoind and lightningd are available in /usr/bin
2. Copy https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service to /usr/lib/systemd/system
3. Set bitcoin.conf
     cat /etc/bitcoin/bitcoin.conf 
     testnet=1
4.Copy the lightningd.service from this PR to /usr/lib/systemd/system
5. systemctl daemon-reload
6. systemctl start bitcoind
7. systemctl start lightningd
8 . systemctl status lightningd (should be all green)
9. Reboot the system and see if the service is started automatically.

**Comment by dougsland** [comment]
Before the reboot: 
6.1
systemctl enable bitcoind.service
systemctl enable lightningd.service

Otherwise, won't start the services automatically.

**Comment by dougsland** [comment]
Additionally:
# cat /etc/lightningd/lightningd.conf 
network=testnet

**Comment by rustyrussell** [comment]
Thanks!  Since it works for one user, I'll apply it and if others improve it, that's all good.

Great work!

**Pull request merged**
