### PR TITLE
emacs: add .dir-locals.el for linux style C

### PR DESCRIPTION
**Pull request by jb55**
This will automatically configure proper indent settings for new contributors using emacs.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Very nice!

**Comment by cdecker** [comment]
Interesting, we seem to have quite a few emacs users working on c-lightning now :-)

I might have a clash here, since I also have flycheck and company-clang configurations in this file. But I can probably move them somewhere else.

**Comment by cdecker** [comment]
At some point it gets pretty specific to ones personal setup, and I would hate to pollute a clean file shared by everybody with my hacks, happy to move my stuff out of the way :-)

**Comment by jb55** [comment]
Alternatively we can document these settings in HACKING so that we don't
force everyone to use workarounds when customizing their dir-locals

**Comment by rustyrussell** [comment]
I think I prefer this.  Generally it's nice to make things easier for new hackers, even at expense of experienced hands.

**Pull request merged**
