### PR TITLE
dual-fund: no feestep

### PR DESCRIPTION
**Pull request by niftynei**
The `fee_step` portion of the spec was cute but not really servicable, especially given that there's no guarantee that bumping the fee by 25% will put you over the required min_relay fee bump.

Instead, we just let the opener specify a new feerate, and require that it's at least 1/64th more than the last "successful" one (that means we've swapped tx_sigs for it successfully, it might still fail to broadcast).

Includes a fix for estimating the additional fee that a change output adds to the tx; we weren't considering the total weight which means it was possible to get off-by-one errors on the rounding.

This is a breaking change with prior dual-funding implementations.

### CODE REVIEW

**Review by rustyrussell — APPROVED** [review]
Ack 2263a7c724eff4c76b4285629bacc6d00907be81

**Comment by niftynei** [comment]
blocked on merge of https://github.com/rustyrussell/lnprototest/pull/16 (updates to rbf tests in protocol tests)

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4648/commits/2263a7c724eff4c76b4285629bacc6d00907be81

**Comment by vincenzopalazzo** [comment]
@niftynei this PR https://github.com/ElementsProject/lightning/pull/4652 can help to easily fix the GitHub actions :)

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4648/commits/808492654fda650364e4301aafd2ac889843af2c

> ERROR tests/test_db.py::test_backfill_scriptpubkeys - OSError: [Errno 39] Dir...

The github action look a like a unluck run

**Comment by niftynei** [comment]
reapplying ACK https://github.com/ElementsProject/lightning/pull/4648/commits/808492654fda650364e4301aafd2ac889843af2c

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4648/commits/26f969297515d115189ae9159410ef9dc2acf237

**Pull request merged**
