### PR TITLE
Release 0.11.2

### PR DESCRIPTION
**Pull request by rustyrussell**
This is based on v0.11.1 (first three commits), and consists entirely of commits cherry-picked from master (and pending PRs), and will be committed to its own branch after review and testing.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5327/commits/3a763bef51e7b8d3b79b1eeef00a64bbaa2a5b25

**Comment by cdecker** [comment]
Excellent changes :+1: However opening a PR for a hotfix release is a bit strange :smiley: 

This is not a PR against the master branch. Maybe we should start creating branches for each release, that then act as merge targets for these hotfix releases?

**Comment by devastgh** [comment]
We might? have a regression.
I'm running 0.11.2-rc1 3a763be . I just had a force close with another cln peer, with bad reestablish revocation, that is supposed to be fixed in #5327.
My listpeers says:
`"message": "channeld: received ERROR error channel 2927d41a493bd4948de06b1b65b7295624811e9708e2f3d3b310eae22923281e: bad reestablish revocation_number: 3354 vs 3359"`

**Comment by rustyrussell** [comment]
> We might? have a regression. I'm running 0.11.2-rc1 [3a763be](https://github.com/ElementsProject/lightning/commit/3a763bef51e7b8d3b79b1eeef00a64bbaa2a5b25) . I just had a force close with another cln peer, with bad reestablish revocation, that is supposed to be fixed in #5327. My listpeers says: `"message": "channeld: received ERROR error channel 2927d41a493bd4948de06b1b65b7295624811e9708e2f3d3b310eae22923281e: bad reestablish revocation_number: 3354 vs 3359"`

Any idea what your peer is running?

**Comment by devastgh** [comment]
> > We might? have a regression. I'm running 0.11.2-rc1 [3a763be](https://github.com/ElementsProject/lightning/commit/3a763bef51e7b8d3b79b1eeef00a64bbaa2a5b25) . I just had a force close with another cln peer, with bad reestablish revocation, that is supposed to be fixed in #5327. My listpeers says: `"message": "channeld: received ERROR error channel 2927d41a493bd4948de06b1b65b7295624811e9708e2f3d3b310eae22923281e: bad reestablish revocation_number: 3354 vs 3359"`
> 
> Any idea what your peer is running? This would be their end with the bug...

No clue unfortunately, he's not replying.
But this is the 2nd time with him, and the first happened before 0.11.1 while i was running 0.11.0.
The question is, if the bug bug is present on their end (it's possible), then is it expected a patched node would still receive this error.

**Comment by rustyrussell** [comment]
> > > We might? have a regression. I'm running 0.11.2-rc1 [3a763be](https://github.com/ElementsProject/lightning/commit/3a763bef51e7b8d3b79b1eeef00a64bbaa2a5b25) . I just had a force close with another cln peer, with bad reestablish revocation, that is supposed to be fixed in #5327. My listpeers says: `"message": "channeld: received ERROR error channel 2927d41a493bd4948de06b1b65b7295624811e9708e2f3d3b310eae22923281e: bad reestablish revocation_number: 3354 vs 3359"`
> > 
> > 
> > Any idea what your peer is running? This would be their end with the bug...
> 
> No clue unfortunately, he's not replying. But this is the 2nd time with him, and the first happened before 0.11.1 while i was running 0.11.0. The question is, if the bug is present on their end (it's possible), then is it expected a patched node would still receive this error and fc.

Yes... they get confused and send an error and fc :(

**Comment by rustyrussell** [comment]
I'm going to create a proper branch for this: release-0.11.2.  Not sure I can change the merge target for this PR though...

**Comment by wtogami** [comment]
The base branch changed in this way means the commits since 0.11.1 do not appear as reviewable commits in this pull request.

May I suggest something like this for the future.
* Make an ongoing stable branch `0.11.x`.
* Use pull requests to review and merge cherry-picks or backports against that branch.
* Releases use signed tags named like  `v0.11.1` and `0.11.2` and are visible to those who had checked out `0.11.x`.
* The branch accumulates backports and some people prefer to run this branch because it is more conservative than running the bleeding edge `master`. This means backports are better tested prior to release.
* When folks think a backport is important enough to release we ask the power users to test the stable branch. Some already would have been. This makes it easier to follow, easier to receive feedback. This as a proc

**Comment by rustyrussell** [comment]
Ok, just to confuse everyone: the branch is called release-0.11.2. Sorry, such point releases are unusual for us, still getting the method right.

 https://github.com/ElementsProject/lightning/compare/master...release-0.11.2

**Pull request merged**
