### PR TITLE
Reflow README.md with no changes to text

### PR DESCRIPTION
**Pull request by jsarenik**
Can be tested by calling a following script

    #!/bin/sh
    FILE=${1:-"CONTRIBUTING.md"}
    CUR_BRANCH=$(git rev-parse --abbrev-ref HEAD)

    {
    git checkout $CUR_BRANCH
    commonmarker $FILE | tidy > /tmp/aoeui.html
    git checkout master >/dev/null
    commonmarker $FILE | tidy | diff -u - /tmp/aoeui.html
    git checkout $CUR_BRANCH
    } 2>/dev/null

### CODE REVIEW

**Comment by jsarenik** [comment]
This is just to make README more readable for terminal plain-text folks (like me).

**Comment by jsarenik** [comment]
The patch-making was not totally automated, but `fmt` was used in general.

**Comment by ZmnSCPxj** [comment]
I think it would be better if there were newlines after each sentence.  They would not flow as well, but the problem is that something like the below example.

    This is an example of a paragraph containing multiple sentences, of which
    the first spans multiple lines.  The second sentence follows the first
    over multiple lines also.  It is possible to infect the entire paragraph
    when the first sentence is modified.

When we make a single-word change in the first sentence:

    This is an egregious example of a paragraph containing multiple sentences,
    of which the first spans multiple lines.  The second sentence follows the
    first over multiple lines also.  It is possible to infect the entire
    paragraph when the first sentence is modified.

-----

Now consider instead the below:

    This is an example of a paragraph containing multiple sentences, of which
    the first spans multiple lines.
    The second sentence follows the first over multiple lines also.
    It is possible to infect the entire paragraph when the first sentence is
    modified.

And then:

    This is an egregious example of a paragraph containing multiple sentences,
    of which the first spans multiple lines.
    The second sentence follows the first over multiple lines also.
    It is possible to infect the entire paragraph when the first sentence is
    modified.

**Comment by jsarenik** [comment]
@ZmnSCPxj I totally see your point. On the other hand I think that markdown's main advantage and the reason why it was preferred by 80-width folks (compared to any markup) was that it allowed plain-text formatted readable documents.

Otherwise a `groff`-like format would be used for `README.man` on GitHub which would generally lead to the same thing as current way of using markdown - nice rendered documentation, though poorly readable on text terminals.

Somwhere-in-between would be to have `md` files as you suggest, written with long lines, and then have a postprocessor to make them readable. That would mean some of the changes (mainly separating the links from the text they link to) would need to be done, but long lines would stay long.

Thanks for good point.

**Comment by ZmnSCPxj** [comment]
I am not suggesting `md` files with long lines; I am suggesting to break sentences at 80-width, but not follow the end of one sentence with the beginning of the next (start the next sentence on the next line).  I have found this to be a happy compromise: sentences early in the paragraph do not cause cascades in the entire paragraph when reworded, it can be read on a 80-width terminal, no postprocessing needed.

**Comment by Saibato** [comment]
@ZmnSCPxj  sure u are human and not a robot? \^^/  ;-)

**Comment by jsarenik** [comment]
@ZmnSCPxj ah, I misunderstood and really appreciate your patience in explaining this. Yes. Let me change the patch... I'll be back.

**Comment by jsarenik** [comment]
@ZmnSCPxj Check now please. Is this what you meant?

**Comment by jsarenik** [comment]
@ZmnSCPxj Please accept my sincere apology for not properly reading what you wrote already in your first comment.

**Comment by ZmnSCPxj** [comment]
ACK 189b30514fa40c8b6bd2e4a42d5798a8f33b08ed

**Comment by ZmnSCPxj** [comment]
@Saibato my description says "human", therefore, I must be human. Some humans do not sleep, right?

**Comment by Saibato** [comment]
@ZmnSCPxj  yes HAL i am happy,  its so funny i could not resist. <3

**Comment by jsarenik** [comment]
@ZmnSCPxj just a note that I found another reference of the text format described in https://github.com/ElementsProject/lightning/pull/1137#issuecomment-369273626 at AsciiDoctor recommended practices: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

**Pull request merged**
