### PR TITLE
Replace head -n with sort -R for better random peer selection

### PR DESCRIPTION
**Pull request by ekzyis**
I have noticed that `contrib/bootstrap-node.sh` uses `head -n $(($(date +%s) % (NUM - 3) ))` to get a random selection of peers.

It's a neat trick but... why not just use `sort -R`? That also works with `/bin/sh` and gives a better random selection.

Additionally, using `sort -R` doesn't break if the current seconds is a multiple of the amount of listed peers:

```
Timestamp: 1672214119
Trying to connect to random peer 02f40890af885da4673f0ee9725ee74bb2c66d6491cc4334056a2701057993e61d@88.198.91.250...
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Timestamp: 1672214120
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Timestamp: 1672214121
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Timestamp: 1672214122
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Timestamp: 1672214123
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Timestamp: 1672214124
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Trying to connect to random peer 038bcc6471941c7d6c14a8ce5b7159d8f73a3a0bb9a93e8896bcb892e14552658a@83.162.155.18...
Timestamp: 1672214125
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Trying to connect to random peer 038bcc6471941c7d6c14a8ce5b7159d8f73a3a0bb9a93e8896bcb892e14552658a@83.162.155.18...
Trying to connect to random peer 039437e5ba3cd7168394d08fd1e423a613084e3d30d31d8069a6ded0921bc5b6b6@37.8.237.243...
Timestamp: 1672214126
Timestamp: 1672214127
Trying to connect to random peer 024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605@128.199.202.168...
Timestamp: 1672214128
Trying to connect to random peer 024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605@128.199.202.168...
Trying to connect to random peer 0204a2b95b4c208383d7f02e741a8bfd5b5b7e8bea8d1543b1255da8342d9f2c6b@172.81.178.189...
Timestamp: 1672214129
Trying to connect to random peer 024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605@128.199.202.168...
Trying to connect to random peer 0204a2b95b4c208383d7f02e741a8bfd5b5b7e8bea8d1543b1255da8342d9f2c6b@172.81.178.189...
Trying to connect to random peer 020ca546d600037181b7cbcd094818100d780d32fd9f210e14390e0d10b7ec71fb@187.65.218.133...
Timestamp: 1672214130
Trying to connect to random peer 0204a2b95b4c208383d7f02e741a8bfd5b5b7e8bea8d1543b1255da8342d9f2c6b@172.81.178.189...
Trying to connect to random peer 020ca546d600037181b7cbcd094818100d780d32fd9f210e14390e0d10b7ec71fb@187.65.218.133...
Trying to connect to random peer 0216006237022044d9bdb73ca51af267c5f67cf76095b4c6275f1162eb422fed68@108.7.50.215...
Timestamp: 1672214131
Trying to connect to random peer 020ca546d600037181b7cbcd094818100d780d32fd9f210e14390e0d10b7ec71fb@187.65.218.133...
Trying to connect to random peer 0216006237022044d9bdb73ca51af267c5f67cf76095b4c6275f1162eb422fed68@108.7.50.215...
Trying to connect to random peer 0219fc8bad855d3c861166a89d637950242230fd3d475bb4a2d1da8c89b97beb0a@78.94.255.174...
Timestamp: 1672214132
Trying to connect to random peer 0216006237022044d9bdb73ca51af267c5f67cf76095b4c6275f1162eb422fed68@108.7.50.215...
Trying to connect to random peer 0219fc8bad855d3c861166a89d637950242230fd3d475bb4a2d1da8c89b97beb0a@78.94.255.174...
Trying to connect to random peer 024b00cf3368dbff39daa6de5638cd877b96227066e1e0d31b10183daa63ac325d@94.156.174.22...
Timestamp: 1672214133
Trying to connect to random peer 0219fc8bad855d3c861166a89d637950242230fd3d475bb4a2d1da8c89b97beb0a@78.94.255.174...
Trying to connect to random peer 024b00cf3368dbff39daa6de5638cd877b96227066e1e0d31b10183daa63ac325d@94.156.174.22...
Trying to connect to random peer 0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877@54.245.57.153...
Timestamp: 1672214134
Trying to connect to random peer 024b00cf3368dbff39daa6de5638cd877b96227066e1e0d31b10183daa63ac325d@94.156.174.22...
Trying to connect to random peer 0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877@54.245.57.153...
Trying to connect to random peer 027cb5b394c5330467081901dba14d48a4ac0f10012e5791e725a65d326405a82e@82.40.164.125...
Timestamp: 1672214135
Trying to connect to random peer 0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877@54.245.57.153...
Trying to connect to random peer 027cb5b394c5330467081901dba14d48a4ac0f10012e5791e725a65d326405a82e@82.40.164.125...
Trying to connect to random peer 02827a7ba367d10a29f0a178be878f737292889d1926b40301780d7e1402a90a72@18.223.138.245...
Timestamp: 1672214136
Trying to connect to random peer 027cb5b394c5330467081901dba14d48a4ac0f10012e5791e725a65d326405a82e@82.40.164.125...
Trying to connect to random peer 02827a7ba367d10a29f0a178be878f737292889d1926b40301780d7e1402a90a72@18.223.138.245...
Trying to connect to random peer 02866bd9513e4e82f250c9b8a0b83cabc9be3c4824f7016bd160859d0fad3d8920@153.126.136.98...
Timestamp: 1672214137
Trying to connect to random peer 02827a7ba367d10a29f0a178be878f737292889d1926b40301780d7e1402a90a72@18.223.138.245...
Trying to connect to random peer 02866bd9513e4e82f250c9b8a0b83cabc9be3c4824f7016bd160859d0fad3d8920@153.126.136.98...
Trying to connect to random peer 029d50d59c78b81a39f4ca40b6bc9b89710542a31429b69aa075b91b587979205d@185.228.137.238...
Timestamp: 1672214138
Trying to connect to random peer 02866bd9513e4e82f250c9b8a0b83cabc9be3c4824f7016bd160859d0fad3d8920@153.126.136.98...
Trying to connect to random peer 029d50d59c78b81a39f4ca40b6bc9b89710542a31429b69aa075b91b587979205d@185.228.137.238...
Trying to connect to random peer 02a5d937fd2328e1a48fd56769ab6ea810fa9c67bfac233f0ac864494b5442d483@82.94.35.199...
Timestamp: 1672214139
Trying to connect to random peer 029d50d59c78b81a39f4ca40b6bc9b89710542a31429b69aa075b91b587979205d@185.228.137.238...
Trying to connect to random peer 02a5d937fd2328e1a48fd56769ab6ea810fa9c67bfac233f0ac864494b5442d483@82.94.35.199...
Trying to connect to random peer 02ae3c06f6db6a87ea874ef7ba86c87ab0041eabf6d8be0594582505b1fd5d7ee8@76.103.92.123...
Timestamp: 1672214140
Trying to connect to random peer 02a5d937fd2328e1a48fd56769ab6ea810fa9c67bfac233f0ac864494b5442d483@82.94.35.199...
Trying to connect to random peer 02ae3c06f6db6a87ea874ef7ba86c87ab0041eabf6d8be0594582505b1fd5d7ee8@76.103.92.123...
Trying to connect to random peer 02f40890af885da4673f0ee9725ee74bb2c66d6491cc4334056a2701057993e61d@88.198.91.250...
Timestamp: 1672214141
Trying to connect to random peer 02ae3c06f6db6a87ea874ef7ba86c87ab0041eabf6d8be0594582505b1fd5d7ee8@76.103.92.123...
Trying to connect to random peer 02f40890af885da4673f0ee9725ee74bb2c66d6491cc4334056a2701057993e61d@88.198.91.250...
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Timestamp: 1672214142
Trying to connect to random peer 02f40890af885da4673f0ee9725ee74bb2c66d6491cc4334056a2701057993e61d@88.198.91.250...
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Timestamp: 1672214143
Trying to connect to random peer 02fd98ebd4cbedd1317d629d62d192cf943f0134c61464de48f1e232d861de4ef9@52.55.248.131...
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Timestamp: 1672214144
Trying to connect to random peer 0307a3fb98c026148e69f51f1851b41db6dc2abf58e77e588636a60ce85c82f091@46.4.79.166...
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Timestamp: 1672214145
Trying to connect to random peer 03144fcc73cea41a002b2865f98190ab90e4ff58a2ce24d3870f5079081e42922d@5.9.83.143...
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Timestamp: 1672214146
Trying to connect to random peer 034cfb8dcb453372e8f13915cc770bcd7bb0f0809dd1b47c0c3b43b969ff9ff3b7@206.189.62.95...
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Timestamp: 1672214147
Trying to connect to random peer 035287f7d8e7301660ed7e660a7baabb4c344326951c1739f9d930937adc82030e@18.195.199.190...
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Trying to connect to random peer 038bcc6471941c7d6c14a8ce5b7159d8f73a3a0bb9a93e8896bcb892e14552658a@83.162.155.18...
Timestamp: 1672214148
Trying to connect to random peer 0376a33371c17cd4fab6c1202f8031b4c899a53cc89739dd411d5b924afcd6cc7f@82.64.60.174...
Trying to connect to random peer 038bcc6471941c7d6c14a8ce5b7159d8f73a3a0bb9a93e8896bcb892e14552658a@83.162.155.18...
Trying to connect to random peer 039437e5ba3cd7168394d08fd1e423a613084e3d30d31d8069a6ded0921bc5b6b6@37.8.237.243...
```

### CODE REVIEW

**Comment by m-schmoock** [comment]
@ekzyis 
CI throws an error as `$NUM` is now unused:

```
contrib/bootstrap-node.sh:50:1: warning: NUM appears unused. Verify use (or export if used externally). [SC2034]
```

**Comment by ekzyis** [comment]
Ah, impressive that the CI caught that. Fixed in acd42c1c339e7903639ff6451366c4a78ac9d4cc

**Comment by vincenzopalazzo** [comment]
OK lgtm, the only think missed is squash the commit in a single one

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5857/commits/ed3335a31ba3a368bf9d87ebbae724c80d2a5a15

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5857/commits/ed3335a31ba3a368bf9d87ebbae724c80d2a5a15

**Comment by rustyrussell** [comment]
Hmm, -R (TIL!) is non-POSIX, but FreeBSD seems to have it too.

**Pull request merged**
