### PR TITLE
pyln-bolt7: fix requirements.txt

### PR DESCRIPTION
**Pull request by jonasnick**
The correct package name is [pyln-proto](https://github.com/ElementsProject/lightning/blob/12689674c7546a6b6ee70839e3867e04dcd33a2f/contrib/pyln-proto/setup.py#L22). H/T @erikarvstedt

### CODE REVIEW

**Review by erikarvstedt — APPROVED** [review]

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4910/commits/6db6a1248bac991f9f2f28e5a9f08d9168c394bd

**Comment by rustyrussell** [comment]
The other ones have the same issue, so I fixed them too!

Thanks!

Ack https://github.com/ElementsProject/lightning/pull/4910/commits/032c0485258b5cd5b03ab8c45a8e001b5c2fcff3

**Review by vincenzopalazzo — APPROVED** [review]
ack https://github.com/ElementsProject/lightning/pull/4910/commits/032c0485258b5cd5b03ab8c45a8e001b5c2fcff3

**Comment by cdecker** [comment]
ack 032c048

**Pull request merged**
