### PR TITLE
nit: use msat_or_all for fundpsbt request amount

### PR DESCRIPTION
**Pull request by joemphilips**
The type was not correct according to the man page.
https://github.com/ElementsProject/lightning/blob/master/doc/lightning-fundpsbt.7.md#description

Changelog-None

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
The CI failure is too exaggerated, to make it happen, you need just need to `make` a run with the rust to enable it to regenerate the type!

**Comment by cdecker** [comment]
Amended the commit to include derived files.

**Comment by cdecker** [comment]
And rebased to avoid merge conflict.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5555/commits/ab0a1792134a6fd6e363fa3d92416ffa580f7bbe

**Comment by cdecker** [comment]
Rebased again on top #5607 to get CI to pass

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/5555/commits/2bc365f54eb926b218e097c659e0b7020fc82d09

**Pull request merged**
