### PR TITLE
getinfo: make address field optional

### PR DESCRIPTION
**Pull request by RCasatta**
according to required fields in the getinfo schema address is not required, with this address array field is not returned if empty

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
mh I think in this case our doc is laying? I like the solution that id there is no address the array is empty, otherwise this can cause confusion for new people that are not able to find the address field

What do you think?

**Comment by RCasatta** [comment]
I would have gone that way initially (adding address field to required in the schema) but IIUC a private comment from @cdecker he preferred this way.

I've no strong preference so let me know

**Comment by vincenzopalazzo** [comment]
>IIUC a private comment from @cdecker he preferred this way.

Ah did not know it, so I'm not blocking anything here :) I was just thinking that this PR was just relaying on the docs!

I will review in a bit

**Comment by rustyrussell** [comment]
I think we won't have an address if the peer connected to us and we are not currently connected?  I'll have to test...

**Comment by cdecker** [comment]
#5904 seems to be less invasive, and generally backwards compatible, except for the `cln-grpc` crate and the generated proto file, which is broken with this.

**Pull request closed without merging**
