### PR TITLE
v0.12.0rc3 - Release Candidate numero tres

### PR DESCRIPTION
**Pull request by niftynei**
Release Candidate 3 for v0.12.0.

Now with more bugfixes!
Changelog-None: it's already done! --RR

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5528/commits/2f3f69a0428fc839ed6cece33845f0bc4fa59ee3

**Review by endothermicdev — APPROVED** [review]
ACK 2f3f69a

**Review by rustyrussell — APPROVED** [review]
Ack 2f3f69a0428fc839ed6cece33845f0bc4fa59ee3

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/commit/2f3f69a0428fc839ed6cece33845f0bc4fa59ee3

```
aa30bf7aa27b19c0088d7fb1e6c481b85986c8f577cbad0e70abce347f9664df  clightning-v0.12.0rc3-Ubuntu-18.04.tar.xz
25b7a4b0a67fc98bf791a2b01f41514bac9f62e074a29db8c1f215ecaeda58c5  clightning-v0.12.0rc3-Ubuntu-20.04.tar.xz
359ca86794b47df5528b8b1264c8fc81825cd8642c00f6732d742d54a6151c63  clightning-v0.12.0rc3-Ubuntu-22.04.tar.xz
62a0bc3813696c2ed89518eb103a1655b09826c4ec401b94efea95835ab06f3b  clightning-v0.12.0rc3.zip
```

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5528/commits/11a4205cdcf8b32e37b08a6dbba828cf2e9b4412

**Review by endothermicdev — APPROVED** [review]
ACK 11a4205
```
77b08f9ffb42529db2e7684981ab5e3e38763d9fb8cb40a992fd7f62f746673e  clightning-v0.12.0rc3-Ubuntu-18.04.tar.xz
d3b0f5abaf20e2f556300563649f4b8989004257dd2c2a2adbafdd6094d80a62  clightning-v0.12.0rc3-Ubuntu-20.04.tar.xz
54db84591be79fe06048fc50ac9ab1c478d318953084f44e17429bf1f6967d94  clightning-v0.12.0rc3-Ubuntu-22.04.tar.xz
003a05312f371b01e7fd0d365e3c10af95759a8c7af6f030ce184d67a2564fdc  clightning-v0.12.0rc3.zip
```

**Comment by cdecker** [comment]
Whoops, none of those hashes match. Need to backtrack that before tagging the release, otherwise this is going to get messy.

**Comment by vincenzopalazzo** [comment]
>Whoops, none of those hashes match. Need to backtrack that before tagging the release, otherwise this is going to get messy.

ok I will restart my cloud machine :D

**Comment by vincenzopalazzo** [comment]
However, if you do not recalculate the hash on https://github.com/ElementsProject/lightning/commit/11a4205cdcf8b32e37b08a6dbba828cf2e9b4412 yours should be old based on https://github.com/ElementsProject/lightning/commit/2f3f69a0428fc839ed6cece33845f0bc4fa59ee3 not sure if this is the cause

**Comment by niftynei** [comment]
> release

I ended up tagging the commit after rebasing this onto master, i suspect that you're using the tag and not the last commit in this PR (which these were built using.)

Let me re-post the hashes from my machine at the v0.12.0rc3 tag.

**Comment by cdecker** [comment]
Ok, will pull the tag and rebuild ^^

**Comment by niftynei** [comment]
Hmm ok 3/4 match @endothermicdev's SHAs. 

```
77b08f9ffb42529db2e7684981ab5e3e38763d9fb8cb40a992fd7f62f746673e  clightning-v0.12.0rc3-Ubuntu-18.04.tar.xz
d3b0f5abaf20e2f556300563649f4b8989004257dd2c2a2adbafdd6094d80a62  clightning-v0.12.0rc3-Ubuntu-20.04.tar.xz
fc685fe83a49fdb3b233602c13f9f704c651ae0bd391377ddd7bdcc9365072e5  clightning-v0.12.0rc3-Ubuntu-22.04.tar.xz
003a05312f371b01e7fd0d365e3c10af95759a8c7af6f030ce184d67a2564fdc  clightning-v0.12.0rc3.zip
```

**Comment by cdecker** [comment]
Yep, my bad for compiling before the rebase:

```
77b08f9ffb42529db2e7684981ab5e3e38763d9fb8cb40a992fd7f62f746673e  clightning-v0.12.0rc3-Ubuntu-18.04.tar.xz
d3b0f5abaf20e2f556300563649f4b8989004257dd2c2a2adbafdd6094d80a62  clightning-v0.12.0rc3-Ubuntu-20.04.tar.xz
54db84591be79fe06048fc50ac9ab1c478d318953084f44e17429bf1f6967d94  clightning-v0.12.0rc3-Ubuntu-22.04.tar.xz
003a05312f371b01e7fd0d365e3c10af95759a8c7af6f030ce184d67a2564fdc  clightning-v0.12.0rc3.zip
```
22.04 is a bit off, will try again.

**Comment by vincenzopalazzo** [comment]
Ship it 🚀

**Pull request merged**
