### PR TITLE
Do not call strlen for every character in the log entry

### PR DESCRIPTION
**Pull request by NicolasDorier**
Low hanging fruit taking quite of CPU.

image

(was log level debug)

### CODE REVIEW

**Comment by cdecker** [comment]
Shouldn't the compiler have optimized that away?

**Comment by NicolasDorier** [comment]
Should be, but we are not currently compiling with the best optimized gcc settings I think.  Like `-g` for the symbol/stack traces might disable some optimizations I guess.

**Comment by NicolasDorier** [comment]
will run a flamegraph before after.

**Comment by NicolasDorier** [comment]
It does not optimize... After:

image

**Comment by ZmnSCPxj** [comment]
ACK 5601a9ffbcb7fa93c892467dbc70d9c8250b30aa

Compiler "should" optimize it away but the code cost is reasonably low.

**Comment by NicolasDorier** [comment]
@ZmnSCPxj well here it is clear it does not optimize it. (I guess there is not proper compiler flags for it yet)

**Pull request merged**
