### PR TITLE
added a test to fix the enum wallet_payment_status 

### PR DESCRIPTION
**Pull request by renepickhardt**
according to the comment at: 
https://github.com/ElementsProject/lightning/blob/master/wallet/wallet.h#L83

I understand that the values for the constants of this enum are critical in the communication with the data storage and should thus be fixed by a unit test.

### CODE REVIEW

**Comment by rustyrussell** [comment]
We should probably make these BUILD_ASSERT() statements where they're used, in db/wallet.c.

There should be matching ones for the others, too.

**Comment by renepickhardt** [comment]
not sure if I get your right: 
1. matching ones for others means that you suggest to also fix the api of other constants / enums via test cases? 
2. I just read about BUILD_ASSERT() in the ccan package. What is the advantage of using them and move the asssertion the wallet.c where the enum is being used? I imagin a scenario in which a coder uses the enums at another position and later (for what ever reason) the original use of the API gets deleted together with those BUILD_ASSERT statments. Then the API would become unstable again. What I am trying to say: isn't the entire idea of using seperate test cases to prevent situations like the one described above?

**Comment by rustyrussell** [comment]
Good point, and it turns out that's far from the only enum we put into the db.

I had to do some test fixups, but I think this covers almost all the bases:

https://github.com/rustyrussell/lightning/tree/db-enum-asserts

Thoughts?

**Comment by renepickhardt** [comment]
As mentioned I am new to the codebase and would need more time to study your patch in order to give more meaningful feedback. I am pretty busy this week so I might not be able to do this quickly. 

On a high level I think I see what you did there and where you are going. I don't think there is a problem with having a test case like I did and your tests (since as far as I currently understand you test on the database side that it interprets the values correctly). If you wish I can merge your changes to my PR and we can merge this PR and close it for now and I would try to provide more feedback at a later point in time.

**Comment by rustyrussell** [comment]
Sure, this is one case where I'm happy for duplication.  Ideally we'd simply annotate these enums and have a magic tool ensure they don't change across commits...

**Comment by renepickhardt** [comment]
Done with merging both patches. You can merge to master and close if you wish.

**Comment by renepickhardt** [comment]
I was looking closer at wallet.h and wallet.c to recover my funds from #1738 what I don't get: how do you (@rustyrussell ) make sure coders will use `static inline enum output_status output_status_in_db(enum output_status s)` instead of addressing the constants from the enum right away?

**Comment by rustyrussell** [comment]
You can't *make* people use it, unless we wrap these in a struct type (which is a lot of overhead for marginal gain).  But even if they don't use it for runtime checking, its mere existence means those BUILD_ASSERT()s are making sure they don't change the enum values.

**Comment by rustyrussell** [comment]
Hmm, you should have probably just cherry-picked my two changes: github is fairly confused right now :)

I don't think there were any significant changes, so I just rebased the 4 commits onto master.

**Comment by rustyrussell** [comment]
Travis got stuck somehow, doing trivial rebase to try to unstick it...

**Comment by cdecker** [comment]
Nope, travis is complaining about "Abuse detected", I reached out to their support to get more details about this.

**Comment by rustyrussell** [comment]
OK, testing locally, will override and merge if all OK.

@renepickhardt BTW, I fixed this, too:

```C
static bool test_wallet_payment_status_enum()
{
```

Needs to be `(void)` otherwise it's considered a pre-ANSI C prototype...

**Comment by rustyrussell** [comment]
Sorry, my commits were completely broken (valgrind noticed that test/run-wallet no longer cleaned up).

I've fixed it a different way, and will open a new PR to fix travis.

**Comment by cdecker** [comment]
Duplicate of #1814

**Pull request closed without merging**
