### PR TITLE
Add pip requirements install to Mac instructions

### PR DESCRIPTION
**Pull request by ddustin**
@cdecker

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
nit: We have this line in the previous section called `For development or running tests, get additional dependencies:`

Or I'm missing some things that you and @cdecker discussed?

**Comment by cdecker** [comment]
I think `mrkd` (and `mistune` due to the broken dependency) might be enough, `requirements.txt` contains quite a few developer dependencies which are not needed for users (doesn't hurt though as long as there is no package conflict in the python installation).

**Comment by ddustin** [comment]
It was just a step I missed when setting up a new environment from scratch
to test and running make check. Took me a while to figure it out ><. Maybe
the ideal solution is having an extra “contributing” or “developer” section
that comes later.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/4983/commits/4c094e91127b5ded2635a221c045ce12293ab937

**Pull request merged**
