### PR TITLE
6996 Fix Unable to generate P2TR address via gRPC

### PR DESCRIPTION
**Pull request by rox1338**
See #6996 for more info on the bug.

Disclaimer:
I did this change directly in github and didn't run any tests. 
So see this as a suggestion only.
Someone with knowledge of the code needs to have a thorough look.

### CODE REVIEW

**Comment by ErikDeSmedt** [comment]
I think you're on the right track to diagnose this bug.

The issue is a little bit deeper though. The `cln-rpc/src/model.rs`-file is auto-generated by `msggen`.
To fix the bug we need to ensure `msggen` generates the correct code.

Otherwise, next time `msggen` is run it will override your changes.

**Comment by rox1338** [comment]
@ErikDeSmedt You are right.
Would appreciate if someone who knows what he is doing fixes this.

**Comment by s373nZ** [comment]
@rox1338 It looks like this was addressed in PR #7217 by @daywalker90. Have you managed to re-test against a more recent release? Can this PR could be closed?

**Comment by rox1338** [comment]
Yep, works now!
Thank you!

**Pull request closed without merging**
