### PR TITLE
runes: listrunes, createrune and blacklistrune commands update

### PR DESCRIPTION
**Pull request by ShahanaFarooqui**
- runes: Renamed `listrunes` to `showrunes`
- runes: Added `invokerune` alias for `createrune`
- runes: Added `destroyrune` alias for `blacklistrune`

### CODE REVIEW

**Comment by rustyrussell** [comment]
Final commit is not needed: we only allow methods which *start* with list in read-only runes ..

**Review by rustyrussell — CHANGES_REQUESTED** [review]
Last commit unnecessary (and awkward: we've shipped with this previously!).

And your commits seem a bit mixed: the first one renamed the command as well as add adding the aliases?

**Comment by ShahanaFarooqui** [comment]
> Final commit is not needed: we only allow methods which _start_ with list in read-only runes ..

Oh, didn't know that. So commando-listrunes is fine but listrunes is not. Removed the last commit to change `commando-listrunes`.

**Review by rustyrussell — APPROVED** [review]

**Comment by rustyrussell** [comment]
Ack 1a2b9446e

(Same commits, just separated cleanly into "add aliases" and "rename command").

**Pull request merged**
