### PR TITLE
docs: Switch to mkdocs + material theme

### PR DESCRIPTION
**Pull request by cdecker**
This is an attempt to make the docs less linear and more of a reference.

I have rendered this PR [here](https://cdecker-lightning.readthedocs.io/) and I think it looks much nicer.

This is not meant as a sure thing, but I'd like to see if we can agree that this is nicer, and if not, what we could do to maximize the use we get out of the docs.

Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
If not accepted we should likely port some of the new docs over to the existing system:

 - https://cdecker-lightning.readthedocs.io/dev/contributors/codegen.html
 - https://cdecker-lightning.readthedocs.io/LICENSE.html

And of course the minor fixes I applied along the way.

**Review by vincenzopalazzo — APPROVED** [review]
I like this, it is much nicer than mdbook from rust ecosystem.

ACK https://github.com/ElementsProject/lightning/pull/6057/commits/a543b566177442b49e1ed6f33819a307a33133b7

**Comment by cdecker** [comment]
I'd even be happy with `mdbook`, as long as it doesn't get as crammed as the default RTD theme we have currently.

**Comment by vincenzopalazzo** [comment]
> I'd even be happy with mdbook, as long as it doesn't get as crammed as the default RTD theme we have currently.

I see :) your proposal looks like real docs, instead `mdbook` is more of a hacking guide perfect for learning languages IMHO!

**Pull request merged**
