### PR TITLE
release 0.7.3

### PR DESCRIPTION
**Pull request by niftynei**

### CODE REVIEW

**Comment by niftynei** [comment]
> I think #3172 and #3174 should be merged before we release, as the first fixes a bug in hsm_secret encryption and the second fixes the build on some OS.

ACK. I've asked @rustyrussell to take a look at #3174.

**Comment by cdecker** [comment]
#3178 would be nice to have in this release.

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/3175/commits/c764624908d29635e81eb0d230e88c1b600e4fe6

**Comment by NicolasDorier** [comment]
My unit tests does not pass because I have no way to specify https://github.com/ElementsProject/lightning/issues/3160 in the configuration file. Must I add my own commit on top of your release to make it possible?

**Comment by NicolasDorier** [comment]
My unit tests pass for on 0.7.3 rc2

**Pull request merged**
