### PR TITLE
docs: try to fix up readthedocs.io, so it has the latest man pages, but points to docs.corelighting.org for the rest

### PR DESCRIPTION
**Pull request by rustyrussell**
Changelog-None

### CODE REVIEW

**Review by nepet — APPROVED** [review]
Checked that `make doc/index.rst` does not accidentally override the changes.
ack 4080c2f221d31847c42695d64e56f6664072fb88

**Comment by ShahanaFarooqui** [comment]
@rustyrussell Pushing updates to docs branch did not update the content to the server yet.

**Comment by adi-shankara** [comment]
@ShahanaFarooqui it will start syncing once #6480 is merged.

**Comment by rustyrussell** [comment]
I'm going to merge this as it can't make things *worse*...

**Pull request merged**
