### PR TITLE
plugins/pay.c: add curly braces arround JSON data field

### LINKED ISSUE #2698: Invalid JSON produced by lightning-cli pay <bolt11>
### Issue and Steps to Reproduce

(Via https://github.com/shesek/spark-wallet/issues/80#issuecomment-497916258.)

When attempting to pay a specific invoice using v0.7.0, `lightning-cli pay <bolt11>` seems to have output invalid JSON:

```
$ lightning-cli pay lnbc10u1pw0yr3wpp5uk6fmlldqxw4kqtvvjjl3ezmd3j4u3zng69dnqvpeul2venqvw4sdqlxycrqvpqwdshgueqvfjhggr0dcsry7qcqzpgr20fw6lwlarvcsatdrg797ktt52kpfcd7szw7jfgdv9rl6ne3xl42c8jl3mj0f7kjqnhwrqwsn6dqh4csp8n963yvr2psh54mrxmxmgqq7779k
{ "code" : 210, "message" : "Gave up after 10 attempts", "data": "attempts": [  { "route": [
[...]
```

(Note `"data": "attempts": [ ... ]`.)

### `getinfo` output

```
{
  "id": "03a9c46ddacd373f78b6679f9dec6adb10b3dc78ca1602a685e09b2ce6101bc18c", 
  "alias": "SLEEPYBAGEL", 
  "color": "03a9c4", 
  "num_peers": 6, 
  "num_pending_channels": 1, 
  "num_active_channels": 4, 
  "num_inactive_channels": 1, 
  "address": [
    {
      "type": "torv3", 
      "address": "3a6jfzt7rbxudbwyx4iajmxhn3xqoonh6vjtfbgggyqdxy7fzoquckyd.onion", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "127.0.0.1", 
      "port": 9735
    }
  ], 
  "version": "v0.7.0", 
  "blockheight": 578820, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0, 
  "fees_collected_msat": "0msat"
}
```

### c-lightning version
```
$ lightningd --version
v0.7.0
```

<details>
 <summary>full lightning-cli pay output</summary>

```
$ lightning-cli pay lnbc10u1pw0yr3wpp5uk6fmlldqxw4kqtvvjjl3ezmd3j4u3zng69dnqvpeul2venqvw4sdqlxycrqvpqwdshgueqvfjhggr0dcsry7qcqzpgr20fw6lwlarvcsatdrg797ktt52kpfcd7szw7jfgdv9rl6ne3xl42c8jl3mj0f7kjqnhwrqwsn6dqh4csp8n963yvr2psh54mrxmxmgqq7779k
{ "code" : 210, "message" : "Gave up after 10 attempts", "data": "attempts": [  { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001002,
      "amount_msat": "1001002msat",
      "delay": 433
    },
    {
      "id": "02a04446caa81636d60d63b066f2814cbd3a6b5c258e3172cbdded7a16e2cfff4c",
      "channel": "576947x600x0",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 393
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "576482x747x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "576947x600x0",
  "erring_direction": 1
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001002,
      "amount_msat": "1001002msat",
      "delay": 548
    },
    {
      "id": "02809e936f0e82dfce13bcc47c77112db068f569e1db29e7bf98bcdd68b838ee84",
      "channel": "566088x1073x0",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 404
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572343x972x0",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "566088x1073x0",
  "erring_direction": 1
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "035f5236d7e6c6d16107c1f86e4514e6ccdd6b2c13c2abc1d7a83cd26ecb4c1d0e",
      "channel": "574740x1519x1",
      "direction": 0,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "567217x2345x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "574740x1519x1",
  "erring_direction": 0
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "030995c0c0217d763c2274aa6ed69a0bb85fa2f7d118f93631550f3b6219a577f5",
      "channel": "574740x1532x1",
      "direction": 1,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "550338x1759x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "574740x1532x1",
  "erring_direction": 1
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "03fb822818be083e0a954db85257a2911a3d55458b8c1ea4124b157e865a836d12",
      "channel": "574740x1528x1",
      "direction": 0,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "550334x1794x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "574740x1528x1",
  "erring_direction": 0
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "039edc94987c8f3adc28dab455efc00dea876089a120f573bd0b03c40d9d3fb1e1",
      "channel": "574740x1523x1",
      "direction": 0,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "550696x565x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "574740x1523x1",
  "erring_direction": 0
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "022c260f9ad58196af280c80a96ec9eabf6404df59ff1a7553b0f381c875a29ba0",
      "channel": "574740x1521x1",
      "direction": 1,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "550343x865x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "574740x1521x1",
  "erring_direction": 1
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001254,
      "amount_msat": "1001254msat",
      "delay": 452
    },
    {
      "id": "03fce165537aea120bffe8505876b44d5119354f825b3eac329b761fc5636bf334",
      "channel": "573916x1728x1",
      "direction": 0,
      "msatoshi": 1000253,
      "amount_msat": "1000253msat",
      "delay": 412
    },
    {
      "id": "03e5ea100e6b1ef3959f79627cb575606b19071235c48b3e7f9808ebcd6d12e87d",
      "channel": "567233x1592x0",
      "direction": 1,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "033d485a2aa57e0b868da2e5c32471c3256f9114734b78abfa6ae55cbdacbd5c3d",
      "channel": "560837x2278x0",
      "direction": 1,
      "msatoshi": 1000002,
      "amount_msat": "1000002msat",
      "delay": 378
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "570301x1283x0",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "573916x1728x1",
  "erring_direction": 0
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001013,
      "amount_msat": "1001013msat",
      "delay": 562
    },
    {
      "id": "0395033b252c6f40e3756984162d68174e2bd8060a129c0d3462a9370471c6d28f",
      "channel": "564038x2202x0",
      "direction": 0,
      "msatoshi": 1000012,
      "amount_msat": "1000012msat",
      "delay": 418
    },
    {
      "id": "025d03912061771608cab55d84cefdecc3bba766085371cf63b454ce1f31fd441d",
      "channel": "574894x2097x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 378
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "574822x1704x0",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 2,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "0395033b252c6f40e3756984162d68174e2bd8060a129c0d3462a9370471c6d28f",
  "erring_channel": "574894x2097x1",
  "erring_direction": 1
} }
 }, { "route": [
    {
      "id": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
      "channel": "575171x2238x0",
      "direction": 1,
      "msatoshi": 1001253,
      "amount_msat": "1001253msat",
      "delay": 448
    },
    {
      "id": "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0",
      "channel": "573919x2176x0",
      "direction": 0,
      "msatoshi": 1000252,
      "amount_msat": "1000252msat",
      "delay": 408
    },
    {
      "id": "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
      "channel": "567225x2701x0",
      "direction": 1,
      "msatoshi": 1000251,
      "amount_msat": "1000251msat",
      "delay": 404
    },
    {
      "id": "020e56a13babec99abdc2c4afbe34e1e44230d79b234c059fd4ff1e367765fdb1b",
      "channel": "570037x2564x1",
      "direction": 1,
      "msatoshi": 1000001,
      "amount_msat": "1000001msat",
      "delay": 374
    },
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e",
      "channel": "572182x2995x1",
      "direction": 0,
      "msatoshi": 1000000,
      "amount_msat": "1000000msat",
      "delay": 364
    }
  ],
 "failure": { "code" : 204, "message" : "Call to waitsendpay:failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)", "data" :
{
  "erring_index": 1,
  "failcode": 4103,
  "failcodename": "WIRE_TEMPORARY_CHANNEL_FAILURE",
  "erring_node": "03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e",
  "erring_channel": "573919x2176x0",
  "erring_direction": 0
} }
 }] }
```
</details>

<details>
  <summary>logs from c-lightning during 'lightning-cli pay' attempt</summary>

```
2019-06-01T05:36:44.627Z lightningd(29293): Sending 1001002msat over 3 hops to deliver 1000000msat
2019-06-01T05:36:45.357Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 43 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:36:50.845Z lightningd(29293): Sending 1001002msat over 3 hops to deliver 1000000msat
2019-06-01T05:36:51.639Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 44 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:36:57.180Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:36:57.919Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 45 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:03.531Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:04.248Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 46 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:09.850Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:10.514Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 47 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:16.056Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:16.733Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 48 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:22.402Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:23.139Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 49 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:28.544Z lightningd(29293): Sending 1001254msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:29.298Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 50 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:34.785Z lightningd(29293): Sending 1001013msat over 4 hops to deliver 1000000msat
2019-06-01T05:37:36.077Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 51 failed from 1th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
2019-06-01T05:37:41.488Z lightningd(29293): Sending 1001253msat over 5 hops to deliver 1000000msat
2019-06-01T05:37:42.298Z lightningd(29293): 03584abd04d69168600340ad5d11723d324f2fc95ea36cbb84804580e344af235e chan #2: htlc 52 failed from 0th node with code 0x1007 (WIRE_TEMPORARY_CHANNEL_FAILURE)
```
</details>

### PR DESCRIPTION
**Pull request by SimonVrouwe**
fixes #2698

### CODE REVIEW

**Comment by rustyrussell** [comment]
Ouch!  This seems to be in 0.7.0, too, so please add a CHANGELOG.md entry?

**Comment by SimonVrouwe** [comment]
Added entry to CHANGELOG.md

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2708/commits/12d3d39a17e0b0d838289a65117be5015c7d9593

**Comment by rustyrussell** [comment]
CHANGELOG.md was malformed due to stray `_` but I'll just fix it up now...

**Pull request merged**
