### PR TITLE
CI: fix schema diff check.

### PR DESCRIPTION
**Pull request by rustyrussell**
GitHub's master branch is called "main" apparently.

Changelog-None

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
Mh I do not understand why this is necessary, github move the name of the default branch to main but it did not affect the previous repo like us. We should stay on master.

I'm missing something? the schema fetch is not done on the default branch?

**Comment by michaelfolkson** [comment]
Oh Rusty. Have we lost you to the culture wars too? :) Does this pose a problem for the CI having a different default branch name to GitHub? GitHub can waste their time and resources on culture war stuff but ideally it wouldn't impact us.

**Comment by rustyrussell** [comment]
I noticed in a CI run:

```
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5893/commits/180dd44caed49ff1082f4c4a34a45f71b582bfcb

Ok seems that GitHub is changing something, maybe related to some problem that some devs noted in its availability of it? BTW lets move on and see what happens

**Comment by cdecker** [comment]
Are we sure the error you mentioned is related to this repo, and not one of the submodules? I find it weird that we'd end up with a new target branch, despite us not renaming it. Would be surprised if Github just went ahead and did something as breaking as just rename everything.

**Comment by rustyrussell** [comment]
> Are we sure the error you mentioned is related to this repo, and not one of the submodules? I find it weird that we'd end up with a new target branch, despite us not renaming it. Would be surprised if Github just went ahead and did something as breaking as just rename everything.

It's political and I don't really want to go there?

But yes, that message is consistent with their previously started intention, and this fixes it without breaking anyone who has a "master" branch.

**Pull request merged**
