### PR TITLE
Minor pyln and pytest cleanups

### PR DESCRIPTION
**Pull request by cdecker**
Changelog-None

### CODE REVIEW

**Comment by cdecker** [comment]
> The Travis CI bot is failing on every PR!

We seem to have a couple of flaky tests, which are being tackled here: https://github.com/ElementsProject/lightning/pull/4254

**Comment by PapauloGamerOfc** [comment]
> > The Travis CI bot is failing on every PR!
> 
> We seem to have a couple of flaky tests, which are being tackled here: #4254
OK, thanks, hope that PR get approved.

**Comment by PapauloGamerOfc** [comment]
> > The Travis CI bot is failing on every PR!
> 
> We seem to have a couple of flaky tests, which are being tackled here: #4254

What did you do to your PR get approved by Travis?

**Review by niftynei — APPROVED** [review]
ACK 091f7ec9db50aa4cbe345da72ba34de52d999125

**Pull request merged**
