### PR TITLE
Submodulize and update libwally-core for LTO removal.

### LINKED ISSUE #738: Pull upstream libwally to include LTO removal
The `libwally-core` team have been busy making it compatible with BSDs and other OSs, let's pull in those changes and see if it fixes the compilation woes some people are reporting (#695, #653, #645, #533, #432).

### PR DESCRIPTION
**Pull request by dongcarl**
This PR fixes #738
- Made `libwally-core` a submodule.
- The submodule is on ElementsProject/libwally-core@8e6d990b5e62ff4d1c9bc68af29423cc98a232fa which removes LTO

This has been `gmake test-protocol`'ed with the following compilers on FreeBSD:
- gcc 6.4.0 with `gmake CC=gcc6 CPP=cpp6 CXX=g++6`
- gcc 5.5.0 with `gmake CC=gcc5 CPP=cpp5 CXX=g++5`
- clang 4.0.0 with `gmake CC=clang CPP=clang-cpp CXX=clang++`
- clang 3.8.1 with `gmake CC=clang38 CPP=clang-cpp38 CXX=clang++38` 

On Ubuntu 16.04.3 LTS:
- gcc 5.4.0 20160609 with `make CC=gcc CPP=cpp CXX=g++`
- clang 3.8.0-2ubuntu4 with `make`
- clang 4.0.0-1ubuntu1~16.04.2 with `make CC=clang-4.0 CPP=clang-cpp-4.0 CXX=clang++-4.0`
- clang 5.0.0-3~16.04.1 with `make CC=clang-5.0 CPP=clang-cpp-5.0 CXX=clang++-5.0`

### CODE REVIEW

**Comment by cdecker** [comment]
I remember @rustyrussell having an aversion against submodules, I'll let him decide :wink:

**Comment by dongcarl** [comment]
@rustyrussell I'm happy to just copy over the tree as well if you want 😄

**Comment by rustyrussell** [comment]
This is great.  We submodularize other things already in external/ but we originally needed a hacky patch to libwally so we didn't there.

**Comment by rustyrussell** [comment]
But this breaks my build.  I'm not surprised, submodules are unusable :(

Might work on a clean directory, but what good is that?  People are trying to actually do development.  I'll see if I can fix it.

**Comment by dongcarl** [comment]
@rustyrussell Huh... I had problems with it but the lines I added in `external/Makefile` fixed it for me on an Ubuntu 16.04 LTS VPS... Let me know if I can help!

**Comment by rustyrussell** [comment]
"This time for sure!"

**Comment by dongcarl** [comment]
Awesome! Thanks for helping get it across the finish line 😄

**Pull request merged**
