### PR TITLE
Minor "Reaching the Ground With Lightning" fixes.

### PR DESCRIPTION
**Pull request by droark**
- Added a reference to BIP112 and to the deployment of BIP68.
- Minor typo, grammar and formatting fixes.

### CODE REVIEW

**Comment by rustyrussell** [comment]
Douglas Roark <notifications@github.com> writes:
> - Added a reference to BIP112 and to the deployment of BIP68.
> - Minor typo, grammar and formatting fixes.

Thanks, applied!

Cheers,
Rusty.

**Comment by droark** [comment]
Thanks! I'll close this one out.

**Comment by droark** [comment]
Hmmm. I'm having a slight problem. I realized that I forgot to include a PDF. I have one ready to go and have committed it to my repo. Unfortunately, whenever I try to create a PR for it, Github seems to think that I want to make a PR for this (lyx/bib) commit and the PDF commit. I'm pretty sure I've fetched & pulled from the parent. It doesn't seem to matter. Am I doing something wrong? Should I go ahead and make the PR anyway? Google doesn't seem to be much help on this one.

Thanks.

**Comment by rustyrussell** [comment]
Douglas Roark <notifications@github.com> writes:
> Hmmm. I'm having a slight problem. I realized that I forgot to include a PDF. I have one ready to go and have committed it to my repo. Unfortunately, whenever I try to create a PR for it, Github seems to think that I want to make a PR for this (lyx/bib) commit and the PDF commit. I'm pretty sure I've fetched & pulled from the parent. It doesn't seem to matter. Am I doing something wrong? Should I go ahead and make the PR anyway? Google doesn't seem to be much help on this one.

No problems, I updated it and pushed.

Thanks,
Rusty.

**Pull request closed without merging**
